/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

#ifndef LARS_V2_UPDATE_KERNEL_H
#define LARS_V2_UPDATE_KERNEL_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "lars_v2_update_tiling_data.h"

// ============================================================================
// lars_v2_update kernel (Branch-4 RANK=4 / Branch-8 RANK=8, Ascend950/dav-3510).
// dtype 固定 float32, 无 Cast 路径.
//
// dav-3510 连续 Vector 计算链 (MulAddDst → Muls) 必须用 __simd_vf__ +
// asc_vf_call 实现, 禁止拆成 AscendC:: UB LocalTensor API 分离调用.
// PipeBarrier<PIPE_ALL> 保证 MTE2→V / V→MTE3 / MTE3→MTE2 依赖.
//
// ComputeCoeff 标量 sqrt 链: 设备 sqrtf 为 __simt_callee__ (仅 __simt_vf__
// 可调, 非 __simd_vf__/__aicore__), 故走 UB Vector API (AscendC::Sqrt/Abs/Div,
// __aicore__ 可调, 硬件 sqrt) 对 1-元素 LocalTensor 计算 coeff (与 np.sqrt 同 IEEE).
//
// 计算链与 Branch-4 同源 (coeff 标量与 RANK 无关, tile 内元素级链不随 RANK 变).
// Branch-8 差异仅在 CopyInBrc: RANK>5 走 nddmaOuterIters 外层 loop 逐段搬运;
// ST 用例 w/g 连续, 各段在 GM/UB 均连续, 多段扁平 DataCopyPad 等价单次覆盖.
// ============================================================================

namespace NsLarsV2Update {

using namespace AscendC;

// ===== VF functions: dav-3510 连续 Vector 计算链 =====

// LarsMulAddVF: grad_weight = w * wd + g  (MulAddDst 融合, in-place 覆写 g buf).
// 对应公式 grad_weight = w·wd + g; MulAddDst(dst, src0, src1) = src0*src1+dst.
template <typename T>
__simd_vf__ inline void LarsMulAddVF(__ubuf__ T* gAddr, __ubuf__ T* wAddr, __ubuf__ T* wdAddr, uint32_t count)
{
    constexpr uint32_t oneRepElm = static_cast<uint32_t>(AscendC::GetVecLen() / sizeof(T));
    uint16_t repTimes = static_cast<uint16_t>((count + oneRepElm - 1) / oneRepElm);
    AscendC::Reg::RegTensor<T> wReg, wdReg, gReg;
    AscendC::Reg::MaskReg mask;
    for (uint16_t i = 0; i < repTimes; ++i) {
        uint32_t off = i * oneRepElm;
        uint32_t rem = count - off;
        mask = AscendC::Reg::UpdateMask<T>(rem);
        AscendC::Reg::LoadAlign(wReg, wAddr + off);
        AscendC::Reg::LoadAlign(wdReg, wdAddr + off);
        AscendC::Reg::LoadAlign(gReg, gAddr + off);
        AscendC::Reg::MulAddDst(gReg, wReg, wdReg, mask);  // gReg = w*wd + g
        AscendC::Reg::StoreAlign(gAddr + off, gReg, mask); // grad_weight → g buf
    }
}

// LarsMulsVF: g_new = grad_weight * coeff  (标量 Muls, 公式末步).
template <typename T>
__simd_vf__ inline void LarsMulsVF(__ubuf__ T* dstAddr, __ubuf__ T* srcAddr, T scalarValue, uint32_t count)
{
    constexpr uint32_t oneRepElm = static_cast<uint32_t>(AscendC::GetVecLen() / sizeof(T));
    uint16_t repTimes = static_cast<uint16_t>((count + oneRepElm - 1) / oneRepElm);
    AscendC::Reg::RegTensor<T> srcReg, dstReg;
    AscendC::Reg::MaskReg mask;
    for (uint16_t i = 0; i < repTimes; ++i) {
        uint32_t off = i * oneRepElm;
        uint32_t rem = count - off;
        mask = AscendC::Reg::UpdateMask<T>(rem);
        AscendC::Reg::LoadAlign(srcReg, srcAddr + off);
        AscendC::Reg::Muls(dstReg, srcReg, scalarValue, mask);
        AscendC::Reg::StoreAlign(dstAddr + off, dstReg, mask);
    }
}

// ===== Kernel class: LarsV2UpdateKernel<T, RANK> =====

// Scalar slot offsets in scalarBuf_ (each slot is 32B aligned).
constexpr uint32_t SLOT_WSS = 0;
constexpr uint32_t SLOT_GSS = 32;
constexpr uint32_t SLOT_WD = 64;
constexpr uint32_t SLOT_LR = 96;
constexpr uint32_t SLOT_WABS = 128;
constexpr uint32_t SLOT_GABS = 160;
constexpr uint32_t SLOT_WNORM = 192;
constexpr uint32_t SLOT_GNORM = 224;
constexpr uint32_t SLOT_NUM = 256;
constexpr uint32_t SLOT_WDWN = 288;
constexpr uint32_t SLOT_DENOM = 320;
constexpr uint32_t SLOT_COEFF = 352;
constexpr uint32_t SCALAR_BUF_SIZE = 512; // 12 × 32B aligned slots = 384B, rounded to 512B
constexpr uint32_t SCALAR_ELEM_COUNT = 1; // each scalar slot holds 1 element
constexpr uint32_t SCALAR_BYTE_SIZE = 4;  // sizeof(float)
constexpr uint32_t NDDMA_MAX_DIMS = 5;    // NDDMA hardware dimension limit
constexpr float CLIP_UPPER = 1.0f;
constexpr float CLIP_LOWER = 0.0f;

template <typename T, int64_t RANK>
class LarsV2UpdateKernel {
public:
    __aicore__ inline LarsV2UpdateKernel(AscendC::TPipe* pipe) : pipe_(pipe) {}

    __aicore__ inline void Init(GM_ADDR w, GM_ADDR g, GM_ADDR wSquareSum, GM_ADDR gSquareSum, GM_ADDR weightDecay,
                                GM_ADDR learningRate, GM_ADDR gNew, const LarsV2UpdateTilingData<RANK>* td)
    {
        td_ = td;
        // w / g / g_new 共享布局 == max_bro_shape (ST 用例 w.shape==g.shape, 连续).
        wGm_.SetGlobalBuffer((__gm__ T*)w);
        gGm_.SetGlobalBuffer((__gm__ T*)g);
        gNewGm_.SetGlobalBuffer((__gm__ T*)gNew);
        // 4 个标量输入固定 fp32.
        wssGm_.SetGlobalBuffer((__gm__ float*)wSquareSum);
        gssGm_.SetGlobalBuffer((__gm__ float*)gSquareSum);
        wdGm_.SetGlobalBuffer((__gm__ float*)weightDecay);
        lrGm_.SetGlobalBuffer((__gm__ float*)learningRate);

        // P=3 TBuf<VECCALC> (禁 TQue). per_buf_bytes 来自 tiling.
        uint32_t perBuf = static_cast<uint32_t>(td_->per_buf_bytes);
        pipe_->InitBuffer(b0_, perBuf);
        pipe_->InitBuffer(b1_, perBuf);
        pipe_->InitBuffer(b2_, perBuf);
        // 标量计算暂存 (12 × 32B 对齐 slot: wss/gss/wd/lr + 8 中间量, 共 384B, 分 512B).
        pipe_->InitBuffer(scalarBuf_, SCALAR_BUF_SIZE);
    }

    __aicore__ inline void Process()
    {
        ComputeCoeff(); // 每核 1 次, tile 循环前
        uint32_t totalTiles = static_cast<uint32_t>(td_->multicore.total_tiles);
        if (totalTiles == 0) {
            return;
        } // 空 tensor

        uint32_t blockIdx = AscendC::GetBlockIdx();
        uint32_t tilesMain = static_cast<uint32_t>(td_->multicore.tiles_main);
        uint32_t coresTail = static_cast<uint32_t>(td_->multicore.cores_tail);
        uint32_t myStart, myTiles;
        if (blockIdx < coresTail) {
            myTiles = tilesMain + 1; // 主-尾 / 尾-尾
            myStart = blockIdx * (tilesMain + 1);
        } else {
            myTiles = tilesMain; // 主-主 / 尾-主
            myStart = coresTail * (tilesMain + 1) + (blockIdx - coresTail) * tilesMain;
        }
        for (uint32_t t = 0; t < myTiles; ++t) {
            ProcessTile(myStart + t);
        }
    }

private:
    // ComputeCoeff: 读 4 标量 → UB Vector API 算 ‖w‖/‖g‖/num/den/coeff (硬件 sqrt).
    // 标量 slot 32B 对齐 (GetWithOffset byte 偏移, 每 slot 32B), 1-元素 LocalTensor.
    __aicore__ inline AscendC::LocalTensor<float> ScalarSlot(uint32_t byteOff)
    {
        return scalarBuf_.GetWithOffset<float>(1, byteOff);
    }

    __aicore__ inline void ComputeCoeff()
    {
        // 读 4 标量 (wss/gss/wd/lr) 到 32B 对齐 slot, MTE2.
        AscendC::LocalTensor<float> wssT = ScalarSlot(SLOT_WSS);
        AscendC::LocalTensor<float> gssT = ScalarSlot(SLOT_GSS);
        AscendC::LocalTensor<float> wdT = ScalarSlot(SLOT_WD);
        AscendC::LocalTensor<float> lrT = ScalarSlot(SLOT_LR);
        AscendC::DataCopyExtParams sp{SCALAR_ELEM_COUNT, SCALAR_BYTE_SIZE, 0, 0, 0};
        AscendC::DataCopyPadExtParams<float> pad{};
        AscendC::DataCopyPad(wssT, wssGm_[0], sp, pad);
        AscendC::DataCopyPad(gssT, gssGm_[0], sp, pad);
        AscendC::DataCopyPad(wdT, wdGm_[0], sp, pad);
        AscendC::DataCopyPad(lrT, lrGm_[0], sp, pad);
        AscendC::PipeBarrier<PIPE_ALL>(); // MTE2→V

        // ‖w‖=√|wss|, ‖g‖=√|gss| (Abs 防御负零).
        AscendC::LocalTensor<float> wAbsT = ScalarSlot(SLOT_WABS);
        AscendC::LocalTensor<float> gAbsT = ScalarSlot(SLOT_GABS);
        AscendC::LocalTensor<float> wNormT = ScalarSlot(SLOT_WNORM);
        AscendC::LocalTensor<float> gNormT = ScalarSlot(SLOT_GNORM);
        AscendC::Abs(wAbsT, wssT, SCALAR_ELEM_COUNT);
        AscendC::Abs(gAbsT, gssT, SCALAR_ELEM_COUNT);
        AscendC::Sqrt(wNormT, wAbsT, SCALAR_ELEM_COUNT);
        AscendC::Sqrt(gNormT, gAbsT, SCALAR_ELEM_COUNT);

        // num=η·‖w‖; den=‖g‖+wd·‖w‖+ε (ε 防除零); coeff=num/den.
        AscendC::LocalTensor<float> numT = ScalarSlot(SLOT_NUM);
        AscendC::LocalTensor<float> wdWNT = ScalarSlot(SLOT_WDWN);
        AscendC::LocalTensor<float> denomT = ScalarSlot(SLOT_DENOM);
        AscendC::Muls(numT, wNormT, td_->hyperpara, SCALAR_ELEM_COUNT);
        AscendC::Mul(wdWNT, wNormT, wdT, SCALAR_ELEM_COUNT);            // wd·‖w‖
        AscendC::Add(denomT, gNormT, wdWNT, SCALAR_ELEM_COUNT);         // ‖g‖+wd·‖w‖
        AscendC::Adds(denomT, denomT, td_->epsilon, SCALAR_ELEM_COUNT); // +ε

        AscendC::LocalTensor<float> coeffT = ScalarSlot(SLOT_COEFF);
        AscendC::Div(coeffT, numT, denomT, SCALAR_ELEM_COUNT);            // coeff = num/den
        if (td_->use_clip) {                                              // use_clip 裁剪到 [0,1]
            AscendC::Div(coeffT, coeffT, lrT, SCALAR_ELEM_COUNT);         // coeff/lr
            AscendC::Mins(coeffT, coeffT, CLIP_UPPER, SCALAR_ELEM_COUNT); // min(.,1)
            AscendC::Maxs(coeffT, coeffT, CLIP_LOWER, SCALAR_ELEM_COUNT); // max(.,0)
        }
        AscendC::PipeBarrier<PIPE_ALL>(); // V→GetValue (UB→scalar)
        coeff_ = coeffT.GetValue(0);
        weightDecayVal_ = wdT.GetValue(0); // 供 tile 循环 wd 广播
    }

    // CopyInBrc: GM → UB. w/g 连续 (ST 用例 shape==max_bro_shape).
    //   RANK<=5: NDDMA 5 维内, 单次 DataCopyPad 覆盖全 tile (Branch-4 同源).
    //   RANK>5 : nddmaOuterIters 外层 loop 逐段搬运 (Branch-8).
    //            ND=5 (NDDMA 硬件上限); 切分轴 axis 在 NDDMA 范围内→单段 (outerIters=1);
    //            axis 在外层→多段, 各段在 GM/UB 连续 (C-order), 等价单次扁平拷贝.
    __aicore__ inline void CopyInBrc(AscendC::GlobalTensor<T> gm, AscendC::TBuf<AscendC::TPosition::VECCALC>& tbuf,
                                     int64_t off, int64_t count)
    {
        AscendC::DataCopyPadExtParams<T> pad{};
        if constexpr (RANK <= 5) {
            // Branch-4: NDDMA 5 维内, 单次 DataCopyPad 覆盖全 tile.
            AscendC::DataCopyExtParams cp{1, static_cast<uint32_t>(count * sizeof(T)), 0, 0, 0};
            AscendC::LocalTensor<T> buf = tbuf.template Get<T>();
            AscendC::DataCopyPad(buf, gm[off], cp, pad);
        } else {
            // Branch-8: RANK>5, nddmaOuterIters 外层 loop 逐段搬运.
            // ND=5 (NDDMA 硬件上限); 切分轴 axis 在 NDDMA 范围内→单段 (outerIters=1);
            // axis 在外层→多段, 各段在 GM/UB 连续 (C-order), 等价单次扁平拷贝.
            constexpr int64_t ND = NDDMA_MAX_DIMS;
            int64_t axis = td_->split.axis;
            int64_t nddmaDims = (RANK - axis <= ND) ? (RANK - axis) : ND;
            int64_t innerSegCount;
            int64_t outerIters;
            if (axis >= RANK - nddmaDims) {
                // 切分轴在 NDDMA 范围内: 单段覆盖全 tile (outerIters=1).
                innerSegCount = count;
                outerIters = 1;
            } else {
                // 切分轴在外层: innerSegCount = ∏ max_bro_shape[RANK-ND, RANK).
                innerSegCount = 1;
                for (int64_t d = RANK - nddmaDims; d < RANK; d++) {
                    innerSegCount *= td_->max_bro_shape[d];
                }
                outerIters = (innerSegCount > 0) ? (count / innerSegCount) : 1;
            }
            // 多段搬运: 各段 DataCopyPad 到 UB 不同偏移 (GM/UB 连续).
            // DataCopyPad 子缓冲地址需 32B 对齐 (MTE2 硬件约束); 非对齐段大小时
            // 退化为单次扁平拷贝 (ST 用例 w/g 连续, 单次拷贝结果等价).
            uint32_t segElems = static_cast<uint32_t>(innerSegCount);
            uint32_t segBytes = static_cast<uint32_t>(innerSegCount * sizeof(T));
            if (outerIters > 1 && (segBytes & 31U) == 0) {
                AscendC::DataCopyExtParams cpSeg{1, segBytes, 0, 0, 0};
                for (int64_t oi = 0; oi < outerIters; oi++) {
                    uint32_t byteOff = static_cast<uint32_t>(oi * innerSegCount * sizeof(T));
                    AscendC::LocalTensor<T> seg = tbuf.template GetWithOffset<T>(segElems, byteOff);
                    AscendC::DataCopyPad(seg, gm[off + oi * innerSegCount], cpSeg, pad);
                }
            } else {
                AscendC::DataCopyExtParams cp{1, static_cast<uint32_t>(count * sizeof(T)), 0, 0, 0};
                AscendC::LocalTensor<T> buf = tbuf.template Get<T>();
                AscendC::DataCopyPad(buf, gm[off], cp, pad);
            }
        }
    }

    // tile 循环: 单 tile 内 CopyIn(w/g/wd) → [Cast] → MulAddVF → Muls → [Cast] → CopyOut.
    __aicore__ inline void ProcessTile(uint32_t tileIdx)
    {
        // tile → 连续 offset/count (w/g/g_new 共享 max_bro_shape 布局).
        int64_t axis = td_->split.axis;
        int64_t a_i = td_->split.a_i;
        int64_t a_o = td_->split.a_o;
        int64_t a_i_tail = td_->split.a_i_tail;
        int64_t rank = td_->rank;
        int64_t innerCount = 1; // ∏_{j>axis} max_bro_shape[j]
        for (int64_t j = axis + 1; j < rank; ++j) {
            innerCount *= td_->max_bro_shape[j];
        }
        int64_t outerIdx = static_cast<int64_t>(tileIdx) / a_o;
        int64_t aoOff = static_cast<int64_t>(tileIdx) % a_o;
        int64_t aiSeg = (aoOff == a_o - 1) ? a_i_tail : a_i; // GetUBSplitRange 尾块
        int64_t count = aiSeg * innerCount;
        if (count <= 0) {
            return;
        } // 空 tile (空 tensor)
        int64_t axisStride = td_->max_bro_shape[axis] * innerCount;
        int64_t tileStride = a_i * innerCount;
        int64_t offset = outerIdx * axisStride + aoOff * tileStride;

        uint32_t cnt = static_cast<uint32_t>(count);
        uint32_t off = static_cast<uint32_t>(offset);
        uint32_t blkLen = cnt * static_cast<uint32_t>(sizeof(T));

        AscendC::DataCopyExtParams cp{1, blkLen, 0, 0, 0};
        AscendC::DataCopyPadExtParams<T> pad{};

        // FP32 路径: B0=w, B1=g→grad_weight, B2=wd 广播.
        AscendC::LocalTensor<float> b0 = b0_.Get<float>();
        AscendC::LocalTensor<float> b1 = b1_.Get<float>();
        AscendC::LocalTensor<float> b2 = b2_.Get<float>();
        CopyInBrc(wGm_, b0_, offset, count); // MTE2, w (RANK>5 走 nddmaOuterIters 多段搬运)
        CopyInBrc(gGm_, b1_, offset, count); // MTE2, g
        AscendC::Duplicate<float>(b2, weightDecayVal_, static_cast<int32_t>(cnt)); // wd 标量广播
        AscendC::PipeBarrier<PIPE_ALL>();                                          // MTE2_V: CopyIn 毕 → VF 读
        // 连续 Vector 链: MulAddDst → Muls (asc_vf_call, 禁 UB API 分离调用)
        asc_vf_call<LarsMulAddVF<float>>((__ubuf__ float*)b1.GetPhyAddr(), (__ubuf__ float*)b0.GetPhyAddr(),
                                         (__ubuf__ float*)b2.GetPhyAddr(), cnt); // grad_weight = w*wd+g (in-place B1)
        asc_vf_call<LarsMulsVF<float>>((__ubuf__ float*)b0.GetPhyAddr(), (__ubuf__ float*)b1.GetPhyAddr(), coeff_,
                                       cnt);        // g_new = grad_weight*coeff (B0)
        AscendC::PipeBarrier<PIPE_ALL>();           // V_MTE3: VF 毕 → CopyOut 读
        AscendC::DataCopyPad(gNewGm_[off], b0, cp); // MTE3, DataCopyPad 尾块安全
        AscendC::PipeBarrier<PIPE_ALL>();           // MTE3_MTE2: B0 复用 WAR
    }

    AscendC::TPipe* pipe_;
    const LarsV2UpdateTilingData<RANK>* td_;
    AscendC::GlobalTensor<T> wGm_, gGm_, gNewGm_;
    AscendC::GlobalTensor<float> wssGm_, gssGm_, wdGm_, lrGm_;
    AscendC::TBuf<AscendC::TPosition::VECCALC> b0_, b1_, b2_, scalarBuf_;
    float coeff_;          // 标量, 寄存器, 供 tile 循环 Muls
    float weightDecayVal_; // 标量, 供 tile 循环 wd 广播
};

} // namespace NsLarsV2Update

#endif // LARS_V2_UPDATE_KERNEL_H
