/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file act_ulq_clamp_max_grad_util.h
 * \brief ActULQClampMaxGrad 轴/索引工具成员定义（arch35 / RegBase）：
 *        LastAAxis / LastRAxis / FindNearestPower2 / CalLog2 / GetCacheID / RLenOfChunk / UnravelOuterR。
 *
 * 本文件是 ActULQClampMaxGradKernel<DType, MaskType> 的成员函数外联定义，
 *   由 act_ulq_clamp_max_grad.h 在类声明后 #include（模板实例化前可见）。
 */
#ifndef OPS_ACT_ULQ_CLAMP_MAX_GRAD_UTIL_H_
#define OPS_ACT_ULQ_CLAMP_MAX_GRAD_UTIL_H_

#include "act_ulq_clamp_max_grad.h"

namespace NsActULQClampMaxGrad {

using namespace AscendC;

// ════════════════════════════════════════════════════════════════════════════
// 工具函数
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline int32_t ActULQClampMaxGradKernel<DType, MaskType>::LastAAxis() const
{
    for (int32_t i = axisNum_ - 1; i >= 0; --i) {
        if (i % 2 == 0) {
            return i;
        }
    }
    return 0;
}

template <typename DType, typename MaskType>
__aicore__ inline int32_t ActULQClampMaxGradKernel<DType, MaskType>::LastRAxis() const
{
    for (int32_t i = axisNum_ - 1; i >= 0; --i) {
        if (i % 2 == 1) {
            return i;
        }
    }
    return 1;
}

template <typename DType, typename MaskType>
__aicore__ inline uint64_t ActULQClampMaxGradKernel<DType, MaskType>::FindNearestPower2(uint64_t v) const
{
    if (v == 0) {
        return 0;
    }
    // 直接对 v 求 clz，得到 floor(log2(v))，再取 2^p 即为 ≤v 的最大 2 的幂。
    // 原实现对 v-1 求 clz（仅对非精确幂正确），导致 v=2/4/8/16/32...
    // 等精确 2 的幂时结果减半，进而错误计算 bisectionPos_/bisectionTail_/cacheCount_。
    const uint64_t p = 63 - AscendC::ScalarCountLeadingZero(v);
    return static_cast<uint64_t>(1) << p;
}

template <typename DType, typename MaskType>
__aicore__ inline uint64_t ActULQClampMaxGradKernel<DType, MaskType>::CalLog2(uint64_t v) const
{
    uint64_t res = 0;
    while (v > 1) {
        v >>= 1;
        ++res;
    }
    return res;
}

template <typename DType, typename MaskType>
__aicore__ inline uint16_t ActULQClampMaxGradKernel<DType, MaskType>::GetCacheID(int64_t idx) const
{
    const uint64_t v = static_cast<uint64_t>(idx);
    return static_cast<uint16_t>(AscendC::ScalarGetCountOfValue<1>(v ^ (v + 1)) - 1);
}

template <typename DType, typename MaskType>
__aicore__ inline int64_t ActULQClampMaxGradKernel<DType, MaskType>::RLenOfChunk(int64_t rChunkIdx) const
{
    const int64_t rAxisSize = axisShape_[rSplit_];
    const int64_t start = rChunkIdx * rUbFactor_;
    return (start + rUbFactor_ > rAxisSize) ? (rAxisSize - start) : rUbFactor_;
}

// rIdx → (外层 R chunk idx, rLen)；返回外层 R 贡献的 GM 偏移
template <typename DType, typename MaskType>
__aicore__ inline int64_t ActULQClampMaxGradKernel<DType, MaskType>::UnravelOuterR(int64_t rIdx, int64_t& rChunkIdxOut,
                                                                                   int64_t& rLenOut) const
{
    const int64_t rChunksOnSplit = (axisShape_[rSplit_] + rUbFactor_ - 1) / rUbFactor_;
    rChunkIdxOut = rIdx % rChunksOnSplit;
    int64_t cur = rIdx / rChunksOnSplit;
    int64_t gmOff = 0;
    for (int32_t i = rSplit_ - 1; i >= 0; --i) {
        if (i % 2 == 1) {
            const int64_t sz = axisShape_[i];
            const int64_t ix = cur % sz;
            cur /= sz;
            gmOff += ix * axisStride_[i];
        }
    }
    rLenOut = RLenOfChunk(rChunkIdxOut);
    return gmOff + rChunkIdxOut * rUbFactor_ * axisStride_[rSplit_];
}
} // namespace NsActULQClampMaxGrad

#endif // OPS_ACT_ULQ_CLAMP_MAX_GRAD_UTIL_H_
