/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file act_ulq_clamp_max_grad_vf.h
 * \brief ActULQClampMaxGrad 计算段成员定义（arch35 / RegBase）：融合 pre-elewise、
 *        chunk 清尾、tmpBuf 合并、ReduceSum、缓存树清零/写入、PostElewise、CopyOut。
 *
 * 本文件是 ActULQClampMaxGradKernel<DType, MaskType> 的成员函数外联定义，
 *   由 act_ulq_clamp_max_grad.h 在类声明后 #include（模板实例化前可见）。
 */
#ifndef OPS_ACT_ULQ_CLAMP_MAX_GRAD_VF_H_
#define OPS_ACT_ULQ_CLAMP_MAX_GRAD_VF_H_

#include "act_ulq_clamp_max_grad.h"

namespace NsActULQClampMaxGrad {

using namespace AscendC;

// ════════════════════════════════════════════════════════════════════════════
// FusePreElewiseVf：Load 3 输入 → Cast→fp32 → signal=|mask| → x_max=xLoss+signal
//   → prod=yGrad×x_max → Store(tmpBuf[slot])。全程 fp32 视图。
//
// mask 两路径（编译期 if constexpr；bool 走 FusePreElewiseVfF32Mask，不进本函数）：
//   fp32：LoadAlign 直通
//   fp16/bf16：LoadAlign DIST_UNPACK_B16 + Cast→fp32
// ⚠ bool(uint8) mask 因 UB 自然 lane 宽（8/16bit）与 fp32 y/x（32bit）不一致，无法在同一 VF 内
//   按 UpdateMask<float> 逐 lane 混读（UNPACK4_B8 为稀疏 2/8 lane 布局，UNPACK_B8 需 16bit mask），
//   已在 ProcessOneRChunk 用 MemBase Cast 预转 fp32 → 走 FusePreElewiseVfF32Mask。
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::FusePreElewiseVf(AscendC::LocalTensor<D_T>& yGradIn,
                                                                                   AscendC::LocalTensor<M_T>& maskIn,
                                                                                   AscendC::LocalTensor<D_T>& xLossIn,
                                                                                   uint32_t slot)
{
    auto tmpAll = tmpBuf_.Get<float>();
    auto tmpSlot = tmpAll[static_cast<int32_t>(slot) * static_cast<int32_t>(tmpSlotElems_)];

    __ubuf__ D_T* yPtr = reinterpret_cast<__ubuf__ D_T*>(yGradIn.GetPhyAddr());
    __ubuf__ M_T* mPtr = reinterpret_cast<__ubuf__ M_T*>(maskIn.GetPhyAddr());
    __ubuf__ D_T* xPtr = reinterpret_cast<__ubuf__ D_T*>(xLossIn.GetPhyAddr());
    __ubuf__ float* dstPtr = reinterpret_cast<__ubuf__ float*>(tmpSlot.GetPhyAddr());

    const uint32_t totalElems = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_ * rUbFactorAlign_ *
                                                      innerRProdAlign_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> yReg, mReg, xReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;

        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            // ── y_grad / x_clamped_loss → fp32（D_T：fp32 直载 / b16 扩位）──
            LoadCastToF32<D_T>(yReg, yPtr, off, mask);
            LoadCastToF32<D_T>(xReg, xPtr, off, mask);

            // ── clamp_max_mask → fp32（M_T：fp32 直载 / b16 扩位；bool 不进本函数）──
            LoadCastToF32<M_T>(mReg, mPtr, off, mask);

            // ── signal = |mask| ；x_max = x_clamped_loss + signal ；prod = y_grad × x_max ──
            AscendC::Reg::Abs(mReg, mReg, mask);
            AscendC::Reg::Add(xReg, xReg, mReg, mask);
            AscendC::Reg::Mul(yReg, yReg, xReg, mask);

            AscendC::Reg::StoreAlign(dstPtr + off, yReg, mask);
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// FusePreElewiseVfF32Mask：bool mask 专用。mask 已由 MemBase Cast 预转为 fp32（maskF32In），
//   VF 内 mask 以 fp32 直载（与 y/x 同 32bit lane），其余与 FusePreElewiseVf 完全一致。
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::FusePreElewiseVfF32Mask(
    AscendC::LocalTensor<D_T>& yGradIn, AscendC::LocalTensor<float>& maskF32In, AscendC::LocalTensor<D_T>& xLossIn,
    uint32_t slot)
{
    auto tmpAll = tmpBuf_.Get<float>();
    auto tmpSlot = tmpAll[static_cast<int32_t>(slot) * static_cast<int32_t>(tmpSlotElems_)];

    __ubuf__ D_T* yPtr = reinterpret_cast<__ubuf__ D_T*>(yGradIn.GetPhyAddr());
    __ubuf__ float* mPtr = reinterpret_cast<__ubuf__ float*>(maskF32In.GetPhyAddr());
    __ubuf__ D_T* xPtr = reinterpret_cast<__ubuf__ D_T*>(xLossIn.GetPhyAddr());
    __ubuf__ float* dstPtr = reinterpret_cast<__ubuf__ float*>(tmpSlot.GetPhyAddr());

    const uint32_t totalElems = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_ * rUbFactorAlign_ *
                                                      innerRProdAlign_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> yReg, mReg, xReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;

        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            // ── y_grad / x_clamped_loss → fp32（D_T：fp32 直载 / b16 扩位）──
            LoadCastToF32<D_T>(yReg, yPtr, off, mask);
            LoadCastToF32<D_T>(xReg, xPtr, off, mask);

            // ── clamp_max_mask（已由 MemBase Cast 预转 fp32）直载 ──
            AscendC::Reg::LoadAlign(mReg, mPtr + off);

            // ── signal = |mask| ；x_max = x_clamped_loss + signal ；prod = y_grad × x_max ──
            AscendC::Reg::Abs(mReg, mReg, mask);
            AscendC::Reg::Add(xReg, xReg, mReg, mask);
            AscendC::Reg::Mul(yReg, yReg, xReg, mask);

            AscendC::Reg::StoreAlign(dstPtr + off, yReg, mask);
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// ClearChunkExtensionVf：tail-R；清 CeilAlign(rLen×innerRPA, bs) 之后的 tail（identity=0）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::ClearChunkExtensionVf(uint32_t slot, int64_t rLen)
{
    if (rLen >= rUbFactor_) {
        return;
    }
    auto tmpAll = tmpBuf_.Get<float>();
    auto tmpSlot = tmpAll[static_cast<int32_t>(slot) * static_cast<int32_t>(tmpSlotElems_)];
    __ubuf__ float* base = reinterpret_cast<__ubuf__ float*>(tmpSlot.GetPhyAddr());

    const uint32_t aBundleEntries = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t innerRPA = static_cast<uint32_t>(innerRProdAlign_);
    const uint32_t rLenInner = static_cast<uint32_t>(rLen) * innerRPA;
    const uint32_t extStart = (rLenInner + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    const uint32_t aStride = static_cast<uint32_t>(rUbFactorAlign_) * innerRPA;
    if (extStart >= aStride) {
        return;
    }
    const uint32_t extLanes = aStride - extStart;
    const uint32_t repPerA = (extLanes + kRepF32 - 1) / kRepF32;
    const uint16_t aU16 = static_cast<uint16_t>(aBundleEntries);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> idReg;
        AscendC::Reg::Duplicate(idReg, 0.0f);

        for (uint16_t a = 0; a < aU16; ++a) {
            int32_t aOff = static_cast<int32_t>(a) * static_cast<int32_t>(aStride);
            uint32_t remaining = extLanes;
            for (uint16_t r = 0; r < static_cast<uint16_t>(repPerA); ++r) {
                int32_t off = aOff + static_cast<int32_t>(extStart) +
                              static_cast<int32_t>(r) * static_cast<int32_t>(kRepF32);
                auto mask = AscendC::Reg::UpdateMask<float>(remaining);
                AscendC::Reg::StoreAlign(base + off, idReg, mask);
            }
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// MergeTmpBufVf：tmpBuf[0] += tmpBuf[1]
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::MergeTmpBufVf()
{
    auto tmpAll = tmpBuf_.Get<float>();
    __ubuf__ float* p0 = reinterpret_cast<__ubuf__ float*>(tmpAll.GetPhyAddr());
    __ubuf__ float* p1 = p0 + tmpSlotElems_;

    const uint32_t totalElems = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_ * rUbFactorAlign_ *
                                                      innerRProdAlign_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> aReg, bReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);
            AscendC::Reg::LoadAlign(aReg, p0 + off);
            AscendC::Reg::LoadAlign(bReg, p1 + off);
            AscendC::Reg::Add(aReg, aReg, bReg, mask);
            AscendC::Reg::StoreAlign(p0 + off, aReg, mask);
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// ReduceRPattern：ReduceSum<fp32, AR>（All Reduce 恒 tail-R）
//   src = tmpBuf[0]，dst = tmpBuf[1]（src/dst 不可重叠）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::ReduceRPattern()
{
    auto tmpAll = tmpBuf_.Get<float>();
    auto src = tmpAll;
    auto dst = tmpAll[static_cast<int32_t>(tmpSlotElems_)];

    const uint32_t aBundle = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t rBundle = static_cast<uint32_t>(rUbFactorAlign_ * innerRProdAlign_);

    uint32_t srcShape[2] = {aBundle, rBundle};
    AscendC::ReduceSum<float, AscendC::Pattern::Reduce::AR, /*isReuseSource=*/true>(dst, src, srcShape,
                                                                                    /*srcInnerPad=*/true);
}

// ════════════════════════════════════════════════════════════════════════════
// ClearCacheTreeVf：整个 cacheBuf 清 0（identity）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::ClearCacheTreeVf()
{
    __ubuf__ float* base = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr());
    const uint32_t totalElems = static_cast<uint32_t>(cacheBufElems_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> zReg;
        AscendC::Reg::Duplicate(zReg, 0.0f);
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);
            AscendC::Reg::StoreAlign(base + off, zReg, mask);
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// DoCachingVf：ReduceSum 结果（tmpBuf[1] 前 laneN 个 fp32）→ 缓存树 level cacheID
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::DoCachingVf(uint16_t cacheID)
{
    auto tmpAll = tmpBuf_.Get<float>();
    __ubuf__ float* srcPtr = reinterpret_cast<__ubuf__ float*>(
        tmpAll[static_cast<int32_t>(tmpSlotElems_)].GetPhyAddr());
    __ubuf__ float* cachePtr = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr());

    const uint32_t laneN = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t levelStride = (laneN + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    const int32_t levelOff = static_cast<int32_t>(cacheID) * static_cast<int32_t>(levelStride);
    const uint16_t repeatTime = static_cast<uint16_t>((laneN + kRepF32U - 1) / kRepF32U);
    const uint16_t cacheLvlU16 = cacheID;

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> aReg, bReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = laneN;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            AscendC::Reg::LoadAlign(aReg, srcPtr + off);

            for (uint16_t j = 0; j < cacheLvlU16; ++j) {
                int32_t jOff = static_cast<int32_t>(j) * static_cast<int32_t>(levelStride) + off;
                AscendC::Reg::LoadAlign(bReg, cachePtr + jOff);
                AscendC::Reg::Add(aReg, aReg, bReg, mask);
            }
            AscendC::Reg::StoreAlign(cachePtr + levelOff + off, aReg, mask);
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// PostElewise：读树根 fp32 → post_op(identity，sum 无后处理) → Cast→D_T → outBuf → EnQue
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::PostElewise(int64_t aLen)
{
    const uint32_t laneN = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t levelStride = (laneN + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    const int32_t rootOff = static_cast<int32_t>(cacheCount_ - 1) * static_cast<int32_t>(levelStride);

    __ubuf__ float* rootPtr = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr()) + rootOff;

    auto outLocal = outQue_.template AllocTensor<D_T>();
    __ubuf__ D_T* outPtr = reinterpret_cast<__ubuf__ D_T*>(outLocal.GetPhyAddr());

    const uint16_t repeatTime = static_cast<uint16_t>((laneN + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> f32Reg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = laneN;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            AscendC::Reg::LoadAlign(f32Reg, rootPtr + off);
            // post_op = identity（sum 无后处理）；fp32 直存 / fp16(bf16) 缩位 Cast 存
            StoreF32OrCastB16<D_T>(outPtr, off, f32Reg, mask);
        }
    }
    outQue_.EnQue(outLocal);
}

// ════════════════════════════════════════════════════════════════════════════
// CopyOut：All Reduce 恒 tail-R 路径 1（单 burst）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, typename MaskType>
__aicore__ inline void ActULQClampMaxGradKernel<DType, MaskType>::CopyOut(int64_t outerOutOff, int64_t aLen)
{
    auto outDeq = outQue_.template DeQue<D_T>();
    DataCopyExtParams outParams;
    outParams.blockLen = static_cast<uint32_t>(aLen * innerAProd_ * static_cast<int64_t>(sizeof(D_T)));
    outParams.blockCount = 1;
    outParams.srcStride = 0;
    outParams.dstStride = 0;
    DataCopyPad(outGm_[outerOutOff], outDeq, outParams);
    outQue_.FreeTensor(outDeq);
}
} // namespace NsActULQClampMaxGrad

#endif // OPS_ACT_ULQ_CLAMP_MAX_GRAD_VF_H_
