/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * ApplyCamePart2 static GE IR verification example.
 *
 * Builds a Data(...) -> ApplyCamePart2 graph, runs it on Ascend950, and verifies
 * the four outputs (r, c, u, sum_square_u) against a CPU golden computed in
 * double precision. r / c are in-place updates of the corresponding inputs.
 *
 * Formula (aligned with kernel arch35/apply_came_part2.cpp):
 *   r_out[i] = beta2 * r[i] + (1 - beta2) * sum_grad_r[i] / m
 *   c_out[j] = beta2 * c[j] + (1 - beta2) * sum_grad_c[j] / n
 *   denom   = beta2 * sum_r / n + (1 - beta2) * sum_grad_rc / (m * n)
 *   u[i,j]  = grad[i,j] / sqrt(r_out[i] * c_out[j] / denom)
 *   sum_square_u = sum(u * u)
 * where n = grad rows, m = grad cols; sum_r is provided as input (= sum(r)).
 */

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <map>
#include <new>
#include <string>
#include <vector>

#include "array_ops.h"
#include "ge_api.h"
#include "ge_api_types.h"
#include "ge_error_codes.h"
#include "ge_ir_build.h"
#include "graph.h"
#include "tensor.h"
#include "types.h"

#include "../../op_graph/apply_came_part2_proto.h"

namespace {

constexpr int kSuccess = 0;
constexpr int kFailed = -1;
constexpr float kAtol = 1.0e-4F;
constexpr float kRtol = 1.0e-4F;

using ShapeVector = std::vector<int64_t>;

int64_t ElementCount(const ShapeVector& shape)
{
    int64_t count = 1;
    for (int64_t dim : shape) {
        count *= dim;
    }
    return count;
}

std::string ShapeToString(const ShapeVector& shape)
{
    std::string result = "[";
    for (size_t index = 0; index < shape.size(); ++index) {
        if (index != 0U) {
            result += ",";
        }
        result += std::to_string(shape[index]);
    }
    result += "]";
    return result;
}

ge::TensorDesc MakeTensorDesc(const ShapeVector& shape, ge::DataType dtype)
{
    ge::TensorDesc desc(ge::Shape(shape), ge::FORMAT_ND, dtype);
    desc.SetPlacement(ge::kPlacementHost);
    desc.SetFormat(ge::FORMAT_ND);
    desc.SetRealDimCnt(shape.size());
    return desc;
}

struct InputFeeds {
    std::vector<float> grad;
    std::vector<float> sum_grad_r;
    std::vector<float> sum_grad_c;
    std::vector<float> sum_grad_rc;
    std::vector<float> r;
    std::vector<float> c;
    std::vector<float> beta2;
    std::vector<float> sum_r;
    std::vector<int64_t> global_shape;
    std::vector<ge::Tensor> tensors;
};

void FillPattern(std::vector<float>& buf, int64_t count, const std::vector<float>& pattern)
{
    buf.resize(static_cast<size_t>(count));
    for (int64_t i = 0; i < count; ++i) {
        buf[static_cast<size_t>(i)] = pattern[static_cast<size_t>(i) % pattern.size()];
    }
}

InputFeeds MakeFeeds(const ShapeVector& gradShape, const ShapeVector& rShape, const ShapeVector& cShape)
{
    InputFeeds feeds;
    const int64_t gradCount = ElementCount(gradShape);
    const int64_t rCount = ElementCount(rShape);
    const int64_t cCount = ElementCount(cShape);

    const std::vector<float> gradPattern = {0.5F, -0.3F, 0.8F, 0.2F, -0.6F, 0.4F, -0.1F, 0.7F};
    const std::vector<float> sgrPattern = {0.4F, 0.2F, -0.5F, 0.3F};
    const std::vector<float> sgcPattern = {0.3F, -0.2F, 0.6F, 0.1F, -0.4F, 0.5F, 0.2F, -0.3F};
    const std::vector<float> rPattern = {0.6F, 0.1F, -0.4F, 0.5F};
    const std::vector<float> cPattern = {0.5F, -0.3F, 0.7F, 0.2F, -0.5F, 0.4F, 0.1F, -0.2F};

    FillPattern(feeds.grad, gradCount, gradPattern);
    FillPattern(feeds.sum_grad_r, rCount, sgrPattern);
    FillPattern(feeds.sum_grad_c, cCount, sgcPattern);
    feeds.sum_grad_rc = {1.0F};
    FillPattern(feeds.r, rCount, rPattern);
    FillPattern(feeds.c, cCount, cPattern);
    feeds.beta2 = {0.9F};

    double sumR = 0.0;
    for (float v : feeds.r) {
        sumR += static_cast<double>(v);
    }
    feeds.sum_r = {static_cast<float>(sumR)};
    feeds.global_shape = {static_cast<int64_t>(gradShape[0]), static_cast<int64_t>(gradShape[1])};

    const ge::TensorDesc gradDesc = MakeTensorDesc(gradShape, ge::DT_FLOAT);
    const ge::TensorDesc rDesc = MakeTensorDesc(rShape, ge::DT_FLOAT);
    const ge::TensorDesc cDesc = MakeTensorDesc(cShape, ge::DT_FLOAT);
    const ge::TensorDesc scalarDesc = MakeTensorDesc({1}, ge::DT_FLOAT);
    const ge::TensorDesc globalDesc = MakeTensorDesc({2}, ge::DT_INT64);

    feeds.tensors.reserve(9U);
    feeds.tensors.emplace_back(gradDesc, reinterpret_cast<uint8_t*>(feeds.grad.data()),
                               static_cast<uint32_t>(feeds.grad.size() * sizeof(float)));
    feeds.tensors.emplace_back(rDesc, reinterpret_cast<uint8_t*>(feeds.sum_grad_r.data()),
                               static_cast<uint32_t>(feeds.sum_grad_r.size() * sizeof(float)));
    feeds.tensors.emplace_back(cDesc, reinterpret_cast<uint8_t*>(feeds.sum_grad_c.data()),
                               static_cast<uint32_t>(feeds.sum_grad_c.size() * sizeof(float)));
    feeds.tensors.emplace_back(scalarDesc, reinterpret_cast<uint8_t*>(feeds.sum_grad_rc.data()),
                               static_cast<uint32_t>(feeds.sum_grad_rc.size() * sizeof(float)));
    feeds.tensors.emplace_back(rDesc, reinterpret_cast<uint8_t*>(feeds.r.data()),
                               static_cast<uint32_t>(feeds.r.size() * sizeof(float)));
    feeds.tensors.emplace_back(cDesc, reinterpret_cast<uint8_t*>(feeds.c.data()),
                               static_cast<uint32_t>(feeds.c.size() * sizeof(float)));
    feeds.tensors.emplace_back(scalarDesc, reinterpret_cast<uint8_t*>(feeds.beta2.data()),
                               static_cast<uint32_t>(feeds.beta2.size() * sizeof(float)));
    feeds.tensors.emplace_back(scalarDesc, reinterpret_cast<uint8_t*>(feeds.sum_r.data()),
                               static_cast<uint32_t>(feeds.sum_r.size() * sizeof(float)));
    feeds.tensors.emplace_back(globalDesc, reinterpret_cast<uint8_t*>(feeds.global_shape.data()),
                               static_cast<uint32_t>(feeds.global_shape.size() * sizeof(int64_t)));
    return feeds;
}

struct GoldenOutputs {
    std::vector<float> r;
    std::vector<float> c;
    std::vector<float> u;
    float sum_square_u;
};

GoldenOutputs ComputeGolden(const InputFeeds& feeds, const ShapeVector& gradShape)
{
    const int64_t n = gradShape[0];
    const int64_t m = gradShape[1];
    const double beta2 = static_cast<double>(feeds.beta2[0]);
    const double sumR = static_cast<double>(feeds.sum_r[0]);
    const double sumGradRc = static_cast<double>(feeds.sum_grad_rc[0]);
    const double denom = beta2 * sumR / static_cast<double>(n) +
                         (1.0 - beta2) * sumGradRc / (static_cast<double>(m) * static_cast<double>(n));

    GoldenOutputs out;
    out.r.resize(static_cast<size_t>(n));
    out.c.resize(static_cast<size_t>(m));
    out.u.resize(static_cast<size_t>(n * m));

    for (int64_t i = 0; i < n; ++i) {
        out.r[static_cast<size_t>(i)] = static_cast<float>(
            beta2 * static_cast<double>(feeds.r[static_cast<size_t>(i)]) +
            (1.0 - beta2) * static_cast<double>(feeds.sum_grad_r[static_cast<size_t>(i)]) / static_cast<double>(m));
    }
    for (int64_t j = 0; j < m; ++j) {
        out.c[static_cast<size_t>(j)] = static_cast<float>(
            beta2 * static_cast<double>(feeds.c[static_cast<size_t>(j)]) +
            (1.0 - beta2) * static_cast<double>(feeds.sum_grad_c[static_cast<size_t>(j)]) / static_cast<double>(n));
    }

    double sumSquareU = 0.0;
    for (int64_t i = 0; i < n; ++i) {
        const double rOut = static_cast<double>(out.r[static_cast<size_t>(i)]);
        for (int64_t j = 0; j < m; ++j) {
            const double cOut = static_cast<double>(out.c[static_cast<size_t>(j)]);
            const double denom2 = rOut * cOut / denom;
            const double sqrtDenom = std::sqrt(denom2);
            const double gradVal = static_cast<double>(feeds.grad[static_cast<size_t>(i * m + j)]);
            const double uVal = gradVal / sqrtDenom;
            out.u[static_cast<size_t>(i * m + j)] = static_cast<float>(uVal);
            sumSquareU += uVal * uVal;
        }
    }
    out.sum_square_u = static_cast<float>(sumSquareU);
    return out;
}

bool CompareFloat(const float* actual, const std::vector<float>& golden, const std::string& name)
{
    for (size_t i = 0; i < golden.size(); ++i) {
        const float error = std::fabs(actual[i] - golden[i]);
        const float tolerance = kAtol + kRtol * std::fabs(golden[i]);
        if (!std::isfinite(actual[i]) || error > tolerance) {
            std::cerr << name << " value mismatch at index " << i << ": actual=" << actual[i]
                      << ", expected=" << golden[i] << ", tolerance=" << tolerance << std::endl;
            return false;
        }
    }
    return true;
}

bool VerifyOutput(const std::vector<ge::Tensor>& output, const ShapeVector& gradShape, const ShapeVector& rShape,
                  const ShapeVector& cShape, const GoldenOutputs& golden)
{
    if (output.size() != 4U) {
        std::cerr << "Expected exactly 4 outputs, got " << output.size() << std::endl;
        return false;
    }
    // output[0] = r (float, shape rShape)
    const ge::Tensor& rOut = output[0];
    if (rOut.GetTensorDesc().GetDataType() != ge::DT_FLOAT) {
        std::cerr << "r output dtype mismatch" << std::endl;
        return false;
    }
    if (!CompareFloat(reinterpret_cast<const float*>(rOut.GetData()), golden.r, "r")) {
        return false;
    }
    // output[1] = c (float, shape cShape)
    const ge::Tensor& cOut = output[1];
    if (!CompareFloat(reinterpret_cast<const float*>(cOut.GetData()), golden.c, "c")) {
        return false;
    }
    // output[2] = u (float, shape gradShape)
    const ge::Tensor& uOut = output[2];
    if (!CompareFloat(reinterpret_cast<const float*>(uOut.GetData()), golden.u, "u")) {
        return false;
    }
    // output[3] = sum_square_u (float scalar)
    const ge::Tensor& ssuOut = output[3];
    const float ssuActual = *reinterpret_cast<const float*>(ssuOut.GetData());
    const float tol = kAtol + kRtol * std::fabs(golden.sum_square_u);
    if (!std::isfinite(ssuActual) || std::fabs(ssuActual - golden.sum_square_u) > tol) {
        std::cerr << "sum_square_u mismatch: actual=" << ssuActual << ", expected=" << golden.sum_square_u << std::endl;
        return false;
    }
    return true;
}

int BuildGraph(const ShapeVector& gradShape, const ShapeVector& rShape, const ShapeVector& cShape, ge::Graph& graph)
{
    const ge::TensorDesc gradDesc = MakeTensorDesc(gradShape, ge::DT_FLOAT);
    const ge::TensorDesc rDesc = MakeTensorDesc(rShape, ge::DT_FLOAT);
    const ge::TensorDesc cDesc = MakeTensorDesc(cShape, ge::DT_FLOAT);
    const ge::TensorDesc scalarDesc = MakeTensorDesc({1}, ge::DT_FLOAT);
    const ge::TensorDesc globalDesc = MakeTensorDesc({2}, ge::DT_INT64);

    auto grad = ge::op::Data("grad").set_attr_index(0);
    grad.update_input_desc_x(gradDesc);
    grad.update_output_desc_y(gradDesc);
    graph.AddOp(grad);

    auto sumGradR = ge::op::Data("sum_grad_r").set_attr_index(1);
    sumGradR.update_input_desc_x(rDesc);
    sumGradR.update_output_desc_y(rDesc);
    graph.AddOp(sumGradR);

    auto sumGradC = ge::op::Data("sum_grad_c").set_attr_index(2);
    sumGradC.update_input_desc_x(cDesc);
    sumGradC.update_output_desc_y(cDesc);
    graph.AddOp(sumGradC);

    auto sumGradRc = ge::op::Data("sum_grad_rc").set_attr_index(3);
    sumGradRc.update_input_desc_x(scalarDesc);
    sumGradRc.update_output_desc_y(scalarDesc);
    graph.AddOp(sumGradRc);

    auto r = ge::op::Data("r").set_attr_index(4);
    r.update_input_desc_x(rDesc);
    r.update_output_desc_y(rDesc);
    graph.AddOp(r);

    auto c = ge::op::Data("c").set_attr_index(5);
    c.update_input_desc_x(cDesc);
    c.update_output_desc_y(cDesc);
    graph.AddOp(c);

    auto beta2 = ge::op::Data("beta2").set_attr_index(6);
    beta2.update_input_desc_x(scalarDesc);
    beta2.update_output_desc_y(scalarDesc);
    graph.AddOp(beta2);

    auto sumR = ge::op::Data("sum_r").set_attr_index(7);
    sumR.update_input_desc_x(scalarDesc);
    sumR.update_output_desc_y(scalarDesc);
    graph.AddOp(sumR);

    auto globalShape = ge::op::Data("global_shape").set_attr_index(8);
    globalShape.update_input_desc_x(globalDesc);
    globalShape.update_output_desc_y(globalDesc);
    graph.AddOp(globalShape);

    auto op = ge::op::ApplyCamePart2("apply_came_part2_0");
    op.set_input_grad(grad);
    op.set_input_sum_grad_r(sumGradR);
    op.set_input_sum_grad_c(sumGradC);
    op.set_input_sum_grad_rc(sumGradRc);
    op.set_input_r(r);
    op.set_input_c(c);
    op.set_input_beta2(beta2);
    op.set_input_sum_r(sumR);
    op.set_input_global_shape(globalShape);
    op.update_input_desc_grad(gradDesc);
    op.update_input_desc_sum_grad_r(rDesc);
    op.update_input_desc_sum_grad_c(cDesc);
    op.update_input_desc_sum_grad_rc(scalarDesc);
    op.update_input_desc_r(rDesc);
    op.update_input_desc_c(cDesc);
    op.update_input_desc_beta2(scalarDesc);
    op.update_input_desc_sum_r(scalarDesc);
    op.update_input_desc_global_shape(globalDesc);

    op.update_output_desc_r(rDesc);
    op.update_output_desc_c(cDesc);
    op.update_output_desc_u(gradDesc);
    op.update_output_desc_sum_square_u(scalarDesc);
    graph.AddOp(op);

    std::vector<ge::Operator> inputs = {grad, sumGradR, sumGradC, sumGradRc, r, c, beta2, sumR, globalShape};
    std::vector<ge::Operator> outputs = {op};
    graph.SetInputs(inputs).SetOutputs(outputs);
    return kSuccess;
}

} // namespace

int main()
{
    const ShapeVector gradShape = {4, 8};
    const ShapeVector rShape = {4};
    const ShapeVector cShape = {8};

    std::map<ge::AscendString, ge::AscendString> globalOptions = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    ge::Status status = ge::GEInitialize(globalOptions);
    if (status != kSuccess) {
        std::cerr << "ERROR: GEInitialize failed: " << ge::GEGetErrorMsgV2().GetString() << std::endl;
        return kFailed;
    }

    ge::Graph graph("apply_came_part2_static_graph");
    if (BuildGraph(gradShape, rShape, cShape, graph) != kSuccess) {
        std::cerr << "ERROR: BuildGraph failed" << std::endl;
        (void)ge::GEFinalize();
        return kFailed;
    }

    std::map<ge::AscendString, ge::AscendString> buildOptions;
    ge::Session* session = new (std::nothrow) ge::Session(buildOptions);
    if (session == nullptr) {
        std::cerr << "ERROR: unable to create GE Session" << std::endl;
        (void)ge::GEFinalize();
        return kFailed;
    }

    std::map<ge::AscendString, ge::AscendString> graphOptions;
    status = session->AddGraph(0U, graph, graphOptions);
    if (status != kSuccess) {
        std::cerr << "ERROR: AddGraph failed: " << ge::GEGetErrorMsgV2().GetString() << std::endl;
        delete session;
        (void)ge::GEFinalize();
        return kFailed;
    }

    InputFeeds feeds = MakeFeeds(gradShape, rShape, cShape);
    std::vector<ge::Tensor> output;
    status = session->RunGraph(0U, feeds.tensors, output);
    if (status != kSuccess) {
        std::cerr << "ERROR: RunGraph failed: " << ge::GEGetErrorMsgV2().GetString() << std::endl;
        delete session;
        (void)ge::GEFinalize();
        return kFailed;
    }

    GoldenOutputs golden = ComputeGolden(feeds, gradShape);
    bool passed = VerifyOutput(output, gradShape, rShape, cShape, golden);

    delete session;
    (void)ge::GEFinalize();

    if (passed) {
        std::cout << "Shape, dtype and values PASSED for " << ShapeToString(gradShape) << std::endl;
        std::cout << "ApplyCamePart2 static GEIR verification PASSED" << std::endl;
        return kSuccess;
    }
    std::cerr << "ApplyCamePart2 static GEIR verification FAILED" << std::endl;
    return kFailed;
}
