/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/* !
 * \file inplace_apply_add_sign_proto.h
 * \brief inplace_apply_add_sign proto head file
 */
#ifndef OPS_OP_PROTO_INC_INPLACE_APPLY_ADD_SIGN_H_
#define OPS_OP_PROTO_INC_INPLACE_APPLY_ADD_SIGN_H_

// operator_reg.h: provides REG_OP, TensorType, INPUT, OUTPUT, ATTR, OP_END_FACTORY_REG.
// types.h: provides DT_BF16 / DT_FLOAT16 / DT_FLOAT dtype enumerators.
#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

#ifndef OPS_PROTO_DEF_INPLACEAPPLYADDSIGN
#define OPS_PROTO_DEF_INPLACEAPPLYADDSIGN

/**
 * @brief Updates var and m in-place with the AddSign optimization algorithm.
 * Adaptive step size scales the update by the sign consistency between grad and m.
 *
 * @par Inputs:
 * @li var: An ND tensor of shape [d_0, d_1, ..., d_n]. Model weights to be updated.
 *     Must be one of the following types: bfloat16, float16, float32.
 * @li m: An ND tensor. Same type and shape as var. First moment buffer.
 * @li lr: An ND tensor of shape [1]. Same type as var. Learning rate scalar.
 * @li alpha: An ND tensor of shape [1]. Same type as var. Step size increment base.
 * @li sign_decay: An ND tensor of shape [1]. Same type as var. Sign consistency decay factor.
 * @li beta: An ND tensor of shape [1]. Same type as var. Momentum decay factor.
 * @li grad: An ND tensor. Same type and shape as var. Gradient of the loss with respect to var.
 *
 * @par Attributes:
 * @li use_locking: An optional bool. If true, locks var and m during update. Defaults to false.
 *
 * @par Outputs:
 * @li var: An ND tensor. Same type and shape as input var. Updated model weights (in-place write-back).
 * @li m: An ND tensor. Same type and shape as input m. Updated first moment (in-place write-back).
 *
 * @par Third-party framework compatibility
 * @li Compatible with TensorFlow's ResourceApplyAddSign optimizer
 */
REG_OP(InplaceApplyAddSign)
    .INPUT(var, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .INPUT(m, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .INPUT(lr, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .INPUT(alpha, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .INPUT(sign_decay, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .INPUT(beta, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .INPUT(grad, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .OUTPUT(var, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .OUTPUT(m, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT}))
    .ATTR(use_locking, Bool, false)
    .OP_END_FACTORY_REG(InplaceApplyAddSign)

#endif // OPS_PROTO_DEF_INPLACEAPPLYADDSIGN

} // namespace ge

#endif // OPS_OP_PROTO_INC_INPLACE_APPLY_ADD_SIGN_H_
