/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <gtest/gtest.h>

#include <limits>
#include <vector>

#include "any_value.h"
#include "infershape_case_executor.h"
#include "infer_shape_context_faker.h"

namespace {

using TensorDesc = gert::InfershapeContextPara::TensorDescription;
using OpAttr = gert::InfershapeContextPara::OpAttr;

gert::StorageShape MakeStorageShape(const std::vector<int64_t>& dims)
{
    gert::StorageShape shape;
    shape.MutableOriginShape().SetDimNum(dims.size());
    shape.MutableStorageShape().SetDimNum(dims.size());
    for (size_t i = 0; i < dims.size(); ++i) {
        shape.MutableOriginShape().SetDim(i, dims[i]);
        shape.MutableStorageShape().SetDim(i, dims[i]);
    }
    return shape;
}

std::vector<OpAttr> MakeAttrs(float spatialScale = 0.25F, int64_t outputDim = 2, int64_t groupSize = 3)
{
    return {
        OpAttr("spatial_scale", Ops::NN::AnyValue::CreateFrom<float>(spatialScale)),
        OpAttr("output_dim", Ops::NN::AnyValue::CreateFrom<int64_t>(outputDim)),
        OpAttr("group_size", Ops::NN::AnyValue::CreateFrom<int64_t>(groupSize)),
    };
}

gert::InfershapeContextPara MakeContext(const std::vector<int64_t>& xShape, const std::vector<int64_t>& roisShape,
                                        ge::DataType dtype = ge::DT_FLOAT,
                                        const std::vector<OpAttr>& attrs = MakeAttrs())
{
    const auto x = MakeStorageShape(xShape);
    const auto rois = MakeStorageShape(roisShape);
    const auto output = MakeStorageShape({});
    return gert::InfershapeContextPara("PSROIPoolingV2",
                                       {TensorDesc(x, dtype, ge::FORMAT_ND), TensorDesc(rois, dtype, ge::FORMAT_ND)},
                                       {TensorDesc(output, dtype, ge::FORMAT_ND)}, attrs);
}

void ExpectShape(gert::InfershapeContextPara para, const std::vector<int64_t>& expected)
{
    ExecuteTestCase(para, ge::GRAPH_SUCCESS, {expected});
}

void ExpectFailure(gert::InfershapeContextPara para) { ExecuteTestCase(para, ge::GRAPH_FAILED); }

class PSROIPoolingV2Infershape : public testing::Test {};

TEST_F(PSROIPoolingV2Infershape, StaticFloat32) { ExpectShape(MakeContext({2, 18, 8, 8}, {2, 5, 4}), {8, 2, 3, 3}); }

TEST_F(PSROIPoolingV2Infershape, StaticFloat16)
{
    ExpectShape(MakeContext({1, 32, 16, 12}, {1, 5, 3}, ge::DT_FLOAT16, MakeAttrs(0.5F, 2, 4)), {3, 2, 4, 4});
}

TEST_F(PSROIPoolingV2Infershape, ZeroBatch) { ExpectShape(MakeContext({0, 18, 8, 8}, {0, 5, 7}), {0, 2, 3, 3}); }

TEST_F(PSROIPoolingV2Infershape, ZeroRois) { ExpectShape(MakeContext({2, 18, 8, 8}, {2, 5, 0}), {0, 2, 3, 3}); }

TEST_F(PSROIPoolingV2Infershape, UnknownDimensions)
{
    ExpectShape(MakeContext({-1, 18, -1, -1}, {-1, 5, -1}), {-1, 2, 3, 3});
}

TEST_F(PSROIPoolingV2Infershape, UnknownXRankUsesKnownRois) { ExpectShape(MakeContext({-2}, {2, 5, 4}), {8, 2, 3, 3}); }

TEST_F(PSROIPoolingV2Infershape, UnknownRoisRankProducesUnknownLeadingDim)
{
    ExpectShape(MakeContext({2, 18, 8, 8}, {-2}), {-1, 2, 3, 3});
}

TEST_F(PSROIPoolingV2Infershape, RejectsInvalidInputRanks)
{
    ExpectFailure(MakeContext({2, 18, 8}, {2, 5, 4}));
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 5}));
}

TEST_F(PSROIPoolingV2Infershape, RejectsInvalidRoiFieldsAndBatchMismatch)
{
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 4, 4}));
    ExpectFailure(MakeContext({2, 18, 8, 8}, {1, 5, 4}));
}

TEST_F(PSROIPoolingV2Infershape, RejectsChannelMismatchAndInvalidKnownDimensions)
{
    ExpectFailure(MakeContext({2, 17, 8, 8}, {2, 5, 4}));
    ExpectFailure(MakeContext({2, 18, 0, 8}, {2, 5, 4}));
    ExpectFailure(MakeContext({2, 18, 8, 0}, {2, 5, 4}));
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 5, -3}));
}

TEST_F(PSROIPoolingV2Infershape, RejectsAttributeBoundaries)
{
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 5, 4}, ge::DT_FLOAT, MakeAttrs(0.0F, 2, 3)));
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 5, 4}, ge::DT_FLOAT, MakeAttrs(0.25F, 0, 3)));
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 5, 4}, ge::DT_FLOAT, MakeAttrs(0.25F, 2, 0)));
    ExpectFailure(MakeContext({2, 18, 8, 8}, {2, 5, 4}, ge::DT_FLOAT, MakeAttrs(0.25F, 2, 128)));
    ExpectFailure(
        MakeContext({2, 18, 8, 8}, {2, 5, 4}, ge::DT_FLOAT, MakeAttrs(std::numeric_limits<float>::infinity(), 2, 3)));
}

} // namespace
