/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software; you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file block_lstm_grad_graph_infer.cpp
 * \brief InferDataType for BlockLstmGrad (graph-side registration).
 *
 * Split from op_host/block_lstm_grad_infershape.cpp to match the forward's
 * layout: InferShape stays in op_host, InferDataType lives here (IMPL_OP).
 */
#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

static ge::graphStatus InferDataTypeBlockLstmGrad(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeBlockLstmGrad");

    /* Strict dtype uniformity (interface contract): every float operand
     * (inputs 1..17; index 0 is the int64 seq_len_max) must share x's dtype.
     * GE would otherwise silently insert an implicit Cast. */
    const ge::DataType xdt = context->GetInputDataType(1);
    for (size_t k = 2; k <= 17; ++k) {
        if (context->GetInputDataType(k) != xdt) {
            OP_LOGE(context->GetNodeName(),
                    "[BlockLstmGrad] input %zu dtype(%d) differs from x's dtype(%d); "
                    "all float operands must share one dtype.",
                    k, static_cast<int>(context->GetInputDataType(k)), static_cast<int>(xdt));
            return ge::GRAPH_FAILED;
        }
    }
    for (size_t k = 0; k < 8; ++k) {
        context->SetOutputDataType(k, xdt);
    }

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeBlockLstmGrad");
    return ge::GRAPH_SUCCESS;
}

IMPL_OP(BlockLstmGrad).InferDataType(InferDataTypeBlockLstmGrad);

} // namespace ops
