/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file tensor_scatter_sub_tiling_key.h
 * \brief Tiling key declaration for tensor_scatter_sub operator
 *
 * Single scene key: TENSOR_SCATTER_SUB_SCENE_DEFAULT = 0
 * dtype handled by DTYPE_X and DTYPE_INDICES macros (auto-instantiation)
 */

#ifndef TENSOR_SCATTER_SUB_TILING_KEY_H_
#define TENSOR_SCATTER_SUB_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define TENSOR_SCATTER_SUB_SCENE_DEFAULT 0

ASCENDC_TPL_ARGS_DECL(TensorScatterSub,
                      ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, TENSOR_SCATTER_SUB_SCENE_DEFAULT));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                                     ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
                                                          TENSOR_SCATTER_SUB_SCENE_DEFAULT),
                                     ASCENDC_TPL_TILING_STRUCT_SEL(TensorScatterSubTilingData)));

#endif // TENSOR_SCATTER_SUB_TILING_KEY_H_
