/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file in_training_reduce_grad_graph_infer.cpp
 * \brief INTrainingReduceGrad 算子图层数据类型推导
 *
 * 对齐 canndev reduce_ops.cc INTrainingReduceGradInferShape：
 *   pd_x.dtype = x.dtype（input index 1）
 */

#include "register/op_impl_registry.h"

using namespace ge;

namespace ops {

// ---------------------------------------------------------------------------
// InferDataTypeForINTrainingReduceGrad(context) — data type inference callback
//
// Aligned with canndev reduce_ops.cc INTrainingReduceGradInferShape:
//   pd_x.dtype = x.dtype (input index 1).
//
// ---------------------------------------------------------------------------
// [REF_SAMPLE]
static ge::graphStatus InferDataTypeForINTrainingReduceGrad(gert::InferDataTypeContext* context)
{
    const ge::DataType xDataType = context->GetInputDataType(1);
    context->SetOutputDataType(0, xDataType);
    return ge::GRAPH_SUCCESS;
}

// IMPL_OP(INTrainingReduceGrad).InferDataType(func):
//   Registers InferDataTypeForINTrainingReduceGrad as the type inference function
//   for the INTrainingReduceGrad operator type.
//   To create FooBar: change INTrainingReduceGrad → FooBar.
// [REF_SAMPLE]
IMPL_OP(INTrainingReduceGrad).InferDataType(InferDataTypeForINTrainingReduceGrad);
} // namespace ops
