/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <gtest/gtest.h> // NOLINT
#include <iostream>
#include "infershape_test_util.h" // NOLINT
#include "ut_op_common.h"
#include "../../../op_graph/inplace_apply_centered_rms_prop_proto.h"

class InplaceApplyCenteredRMSProp : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "InplaceApplyCenteredRMSProp SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "InplaceApplyCenteredRMSProp TearDown" << std::endl; }
};

TEST_F(InplaceApplyCenteredRMSProp, infershape_3d_fp32)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyCenteredRMSProp"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyCenteredRMSProp")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);
    gert::StorageShape varShape = {{4, 3, 4}, {4, 3, 4}};
    gert::StorageShape mgShape = {{4, 3, 4}, {4, 3, 4}};
    gert::StorageShape msShape = {{4, 3, 4}, {4, 3, 4}};
    gert::StorageShape momShape = {{4, 3, 4}, {4, 3, 4}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape rhoShape = {{1}, {1}};
    gert::StorageShape momentumShape = {{1}, {1}};
    gert::StorageShape epsilonShape = {{1}, {1}};
    gert::StorageShape gradShape = {{4, 3, 4}, {4, 3, 4}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(9, 4)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1, 1, 1})
                      .InputShapes({&varShape, &mgShape, &msShape, &momShape, &lrShape, &rhoShape, &momentumShape,
                                    &epsilonShape, &gradShape})
                      .OutputShapes({&varShape, &mgShape, &msShape, &momShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);
}

TEST_F(InplaceApplyCenteredRMSProp, infershape_2d_fp16)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyCenteredRMSProp"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyCenteredRMSProp")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);
    gert::StorageShape varShape = {{8, 16}, {8, 16}};
    gert::StorageShape mgShape = {{8, 16}, {8, 16}};
    gert::StorageShape msShape = {{8, 16}, {8, 16}};
    gert::StorageShape momShape = {{8, 16}, {8, 16}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape rhoShape = {{1}, {1}};
    gert::StorageShape momentumShape = {{1}, {1}};
    gert::StorageShape epsilonShape = {{1}, {1}};
    gert::StorageShape gradShape = {{8, 16}, {8, 16}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(9, 4)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1, 1, 1})
                      .InputShapes({&varShape, &mgShape, &msShape, &momShape, &lrShape, &rhoShape, &momentumShape,
                                    &epsilonShape, &gradShape})
                      .OutputShapes({&varShape, &mgShape, &msShape, &momShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);
}

TEST_F(InplaceApplyCenteredRMSProp, infershape_1d_fp32)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyCenteredRMSProp"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyCenteredRMSProp")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);
    gert::StorageShape varShape = {{128}, {128}};
    gert::StorageShape mgShape = {{128}, {128}};
    gert::StorageShape msShape = {{128}, {128}};
    gert::StorageShape momShape = {{128}, {128}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape rhoShape = {{1}, {1}};
    gert::StorageShape momentumShape = {{1}, {1}};
    gert::StorageShape epsilonShape = {{1}, {1}};
    gert::StorageShape gradShape = {{128}, {128}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(9, 4)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1, 1, 1})
                      .InputShapes({&varShape, &mgShape, &msShape, &momShape, &lrShape, &rhoShape, &momentumShape,
                                    &epsilonShape, &gradShape})
                      .OutputShapes({&varShape, &mgShape, &msShape, &momShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);
}
