/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file dua_quantize_add_layer_norm_tiling_data.h
 * \brief Tiling data structure shared by host and kernel
 */
#ifndef DUA_QUANTIZE_ADD_LAYER_NORM_TILING_DATA_H_
#define DUA_QUANTIZE_ADD_LAYER_NORM_TILING_DATA_H_

#include <cstdint>

constexpr int32_t MAX_PATTERN_RANK = 3; // AR=2 轴 / ARA=3 轴

// base/group 共用（isMulMode 由 TilingKey 承载，不入 struct）
struct DuaQuantizeAddLayerNormTilingData {
    // pattern 描述（轴类型由位置奇偶隐含：i 偶→A，i 奇→R）
    int32_t axisNum;                      // 合轴补轴后轴数：2（AR）或 3（ARA）
    int64_t axisShape[MAX_PATTERN_RANK];  // 各轴 size
    int64_t axisStride[MAX_PATTERN_RANK]; // 各轴 GM stride（element）
    int64_t aDim;                         // 行数 = ∏非 R 轴 size
    int64_t rDim;                         // R 轴 size（=W）

    // 多核切分（fused aLoop 大小核均衡）
    int64_t aLoopCntTotal;     // ∏(外层 A 整根) × aSplitChunkCnt
    int64_t aSplitChunkCnt;    // CeilDiv(axisShape[aSplitIdx], aUbFactor)
    int64_t aBigCoreLoopCnt;   // 大核块数（=aSmallCoreLoopCnt+1）
    int64_t aSmallCoreLoopCnt; // 小核块数（floor(aLoopCntTotal/coreNum)）
    int32_t aBigCoreCnt;       // 大核个数（aLoopCntTotal % coreNum）
    int32_t usedCoreNum;       // 实际使用核数（kernel 早退判据）

    // UB 切分
    int32_t aSplitIdx;       // A 切分轴下标
    int32_t rSplitIdx;       // R 切分轴下标
    int64_t aUbFactor;       // A 切分因子（valid 行数）
    int64_t rUbFactor;       // R 切分因子（valid 列数）
    int64_t rUbFactorAlign;  // padded 列数（UF 行距）
    int64_t innerAProdAlign; // aSplitIdx 右侧 A 轴连乘（padded）
    int64_t innerRProdAlign; // rSplitIdx 右侧 R 轴连乘（padded）
    int64_t rLoopCntTotal;   // ∏(外层 R) × CeilDiv(axisShape[rSplitIdx], rUbFactor)

    // UB buffer 字节数（14 槽布局尺寸来源）
    int64_t preBufSize;     // pre 侧单份：aUnit×rPadded×maxDtypeSize
    int64_t postBufSize;    // post 池单份
    int64_t redBufSize;     // ub_mu/ub_rstd 单份：CeilAlign(aUnit×4, blockSize)
    int64_t cacheBufUbSize; // 固定 16×1024（常量）

    // group 共用字段（base 恒 0 不读）
    int64_t rGroupCnt; // group Phase1 分组数 = Phase2 workspace R 维

    // 算子自定义字段
    float invRTotal; // 1/rDim（mu/var epilogue；host 保证 rDim>0）
    float epsilon;   // attr，加到方差上
    uint8_t hasZp1;  // zero_points1 存在标志（1=搬入，0=缺省按 0）
    uint8_t hasZp2;  // zero_points2 存在标志
};

// empty 独立（最小字段集）
struct DuaQuantizeAddLayerNormEmptyTilingData {
    int32_t usedCoreNum; // 恒 0（EMPTY_A 形式统一 EMPTY_A/EMPTY_R）
};

#endif // DUA_QUANTIZE_ADD_LAYER_NORM_TILING_DATA_H_
