/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/**
 * =============================================================================
 * inplace_apply_ada_max_package/tests/ut/test_inplace_apply_ada_max_branch1_tiling.cpp
 * =============================================================================
 * Role: gtest unit test for Branch-1 (fp32-unalign, tilingKey=1) tiling of
 *       InplaceApplyAdaMax (Task 25, DESIGN-BRANCH-1.md §2, TDD red baseline).
 *
 * Coverage (DESIGN-BRANCH-1.md §2 切分公式 + §9 用例 B1-1..B1-6 tiling 侧):
 *   - 单 tile 非对齐 N=100       (k==0 path, aO=1, aI=12696, aITail=100)
 *   - 多 tile 非对齐 N=12700      (split path, aO=2, aI=12696, aITail=4)
 *   - 尾 tile 极小 N=12697        (split path, aO=2, aI=12696, aITail=1)
 *   - 尾 tile=7 N=12703           (split path, aO=2, aI=12696, aITail=7)
 *   - 多核非对齐 N=1048573        (split path, aO=83, multi-core, coresTail=19)
 *   - rank=8 非对齐 N=2187        (k==0 path, aO=1, aI=12696, aITail=3)
 *
 * Branch-1 key difference from Branch-0 (DESIGN-BRANCH-1.md §2, k==0 path):
 *   Branch-0: aI = maxBroShape[0]            (dim size, no align)
 *   Branch-1: aI = (perBufElems // 8) * 8    (= 12696, aligned buffer
 *                                                upper bound; aO=1,
 *                                                aITail = maxBroShape[0])
 *   The split path is identical (align aI down to 8), but aITail is
 *   non-aligned (N%8!=0) — kernel must pad the tail tile (DataCopyPad).
 *
 * Oracle independence (per tiling-developer skill §五.5):
 *   The Branch1TilingOracle function below hand-writes the §2 formulas directly.
 *   It does NOT call any optiling:: function — the oracle and the impl under
 *   test are two independent implementations of the same spec.
 *
 * TDD baseline (Task 25, stub):
 *   The impl (inplace_apply_ada_max_tiling_host.cpp ComputeBranch1Tiling) is a
 *   STUB that fills INT64_MIN sentinels. Oracle returns real values. Every test
 *   case has all assertions failing (INT64_MIN != oracle value) →
 *   0 passed / 6 failed (red baseline).
 *
 *   Task 26 replaces the stub with real §2 formulas → all pass (green).
 * =============================================================================
 */

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <vector>
#include <gtest/gtest.h>
#include "graph/types.h"                              // ge::DataType
#include "inplace_apply_ada_max_tiling_host_arch35.h" // optiling::ComputeBranch1Tiling
#include "inplace_apply_ada_max_tiling_data.h"        // SplitResult, MultiCoreResult

namespace {

// ===========================================================================
// §5.2 / DESIGN-BRANCH-1.md §2 常量 (手抄自 DESIGN, NOT from impl)
// ===========================================================================
constexpr int64_t UB_BYTES_DAV3510 = 253952; // 248 KiB (DAV_3510)
constexpr int64_t P_PHYS_NODES = 5;          // 4 inputs + 1 tmp (§5.3)
constexpr int64_t COMPUTE_DTYPE_SZ = 4;      // FP32 compute domain
constexpr int64_t ALIGN_ELEM_FP32 = 8;       // FP32: 32B / 4B

// perBufElems = ((ubBytes / P) & ~31) / 4 = (50784) / 4 = 12696
constexpr int64_t AlignDown32(int64_t v) { return v & ~static_cast<int64_t>(31); }
constexpr int64_t PER_BUF_ELEMS = AlignDown32(UB_BYTES_DAV3510 / P_PHYS_NODES) / COMPUTE_DTYPE_SZ; // 12696

// ===========================================================================
// Independent oracle — hand-written DESIGN-BRANCH-1.md §2 formulas.
// Does NOT call any optiling:: function (skill §五.5: oracle independence).
//
// §2 UB切分 (Branch-1: fp32-unalign, key difference in k==0 path):
//   inner = 1
//   for k = rank-1 downto 0:
//       if maxBroShape[k] * inner > perBufElems:    # split needed
//           aIRaw  = perBufElems / inner
//           aI      = (aIRaw // alignElem) * alignElem   # align down to 8
//           aO      = ceil(maxBroShape[k] / aI)
//           aITail = maxBroShape[k] - aI * (aO - 1)   # non-aligned (N%8!=0)
//           axis = k; break
//       if k == 0:                                       # whole tensor fits
//           axis = 0
//           aI = (perBufElems // alignElem) * alignElem # = 12696 (aligned buf upper bound)
//           aO = 1
//           aITail = maxBroShape[0]                   # non-aligned (N%8!=0)
//       inner *= maxBroShape[k]
//
// §2 多核切分 (MultiCoreSplit):
//   outerProd  = Π_{j=0}^{axis-1} maxBroShape[j]
//   totalTiles = outerProd * aO
//   numCores   = min(totalTiles, coreNumAiv); if <1 → 1
//   tilesMain  = totalTiles // numCores
//   coresTail  = totalTiles %  numCores
// ===========================================================================
struct OracleBranch1 {
    int64_t splitAxis;
    int64_t splitAI;
    int64_t splitAO;
    int64_t splitAITail;
    int64_t mcNumCores;
    int64_t mcTotalTiles;
    int64_t mcTilesMain;
    int64_t mcCoresTail;
};

// Note: function name intentionally avoids the 'OracleCompute' prefix to keep
// the skill's oracle-independence grep (gate 5) precise (same convention as
// Branch-0's Branch0TilingOracle).
OracleBranch1 Branch1TilingOracle(const int64_t* maxBroShape, int64_t rank, int64_t N, int64_t perBufElems,
                                  int64_t coreNumAiv, int64_t alignElem)
{
    OracleBranch1 t{}; // zero-init

    // Branch-1 covers N%8!=0 (N=0 is align → Branch-0); guard anyway.
    if (N == 0) {
        t.splitAxis = 0;
        return t;
    }

    // ---- §2 UB切分 (Branch-1: k==0 path differs from Branch-0) ----
    int64_t inner = 1;
    int64_t axis = 0, aI = 0, aO = 0, aITail = 0;
    for (int64_t k = rank - 1; k >= 0; --k) {
        if (maxBroShape[k] * inner > perBufElems) {
            // Split path: align aI down to alignElem (same as Branch-0 split).
            int64_t aIRaw = perBufElems / inner;
            aI = (aIRaw / alignElem) * alignElem; // align down to 8
            if (aI < 1)
                aI = alignElem;                  // guard against 0
            aO = (maxBroShape[k] + aI - 1) / aI; // ceil
            aITail = maxBroShape[k] - aI * (aO - 1);
            axis = k;
            break;
        }
        if (k == 0) {
            // Branch-1 KEY DIFFERENCE: aI = aligned buffer upper bound
            // (NOT maxBroShape[0] as in Branch-0). aO=1, single tile.
            axis = 0;
            aI = (perBufElems / alignElem) * alignElem; // = 12696
            aO = 1;
            aITail = maxBroShape[0]; // non-aligned (N%8!=0)
            break;
        }
        inner *= maxBroShape[k];
    }

    t.splitAxis = axis;
    t.splitAI = aI;
    t.splitAO = aO;
    t.splitAITail = aITail;

    // ---- §2 多核切分 (MultiCoreSplit) ----
    int64_t outerProd = 1;
    for (int64_t j = 0; j < axis; ++j) {
        outerProd *= maxBroShape[j];
    }
    int64_t totalTiles = outerProd * aO;
    int64_t numCores = std::min(totalTiles, coreNumAiv);
    if (numCores < 1)
        numCores = 1;
    int64_t tilesMain = totalTiles / numCores;
    int64_t coresTail = totalTiles % numCores;

    t.mcNumCores = numCores;
    t.mcTotalTiles = totalTiles;
    t.mcTilesMain = tilesMain;
    t.mcCoresTail = coresTail;

    return t;
}

} // namespace

// ===========================================================================
// Parameterized test: 被测 ComputeBranch1Tiling vs oracle, 逐字段比较.
// ===========================================================================
struct Branch1Case {
    const char* name;
    std::vector<int64_t> shape; // maxBroShape (actual, NOT padded)
    int64_t N;                  // numel = product of shape
    int64_t coreNumAiv;
};

class Branch1TilingTest : public testing::TestWithParam<Branch1Case> {};

TEST_P(Branch1TilingTest, Formula)
{
    const auto& p = GetParam();
    int64_t rank = static_cast<int64_t>(p.shape.size());

    OracleBranch1 exp = Branch1TilingOracle(p.shape.data(), rank, p.N, PER_BUF_ELEMS, p.coreNumAiv, ALIGN_ELEM_FP32);

    optiling::BranchInputs in{};
    in.maxBroShape = p.shape.data();
    in.rank = rank;
    in.N = p.N;
    in.perBufElems = PER_BUF_ELEMS;
    in.coreNumAiv = p.coreNumAiv;
    in.alignElem = ALIGN_ELEM_FP32;

    SplitResult split{};
    MultiCoreResult multicore{};
    std::memset(&split, 0, sizeof(split));
    std::memset(&multicore, 0, sizeof(multicore));
    optiling::ComputeBranchTiling(1, in, split, multicore);

    // §2 UB切分 (split) — 逐字段比较.
    EXPECT_EQ(split.axis, exp.splitAxis);
    EXPECT_EQ(split.aI, exp.splitAI);
    EXPECT_EQ(split.aO, exp.splitAO);
    EXPECT_EQ(split.aITail, exp.splitAITail);
    // §2 多核切分 (multicore) — 逐字段比较.
    EXPECT_EQ(multicore.numCores, exp.mcNumCores);
    EXPECT_EQ(multicore.totalTiles, exp.mcTotalTiles);
    EXPECT_EQ(multicore.tilesMain, exp.mcTilesMain);
    EXPECT_EQ(multicore.coresTail, exp.mcCoresTail);
}

INSTANTIATE_TEST_SUITE_P(Section2Branch1, Branch1TilingTest,
                         testing::Values(
                             // §2 / §9 用例 B1-1: 单 tile 非对齐 (N=100, k==0 path, aI=12696, aO=1, aITail=100)
                             Branch1Case{"single_tile_unalign_n100", {100}, 100, 32},
                             // §2 / §9 用例 B1-2: 多 tile 非对齐 (N=12700, split path, aO=2, aI=12696, aITail=4)
                             Branch1Case{"multi_tile_unalign_n12700", {12700}, 12700, 32},
                             // §2 / §9 用例 B1-3: 尾 tile 极小 (N=12697, split path, aO=2, aITail=1)
                             Branch1Case{"tail_tile_min_n12697", {12697}, 12697, 32},
                             // §2 / §9 用例 B1-6: 尾 tile=7 (N=12703, split path, aO=2, aITail=7, max padding)
                             Branch1Case{"tail_tile_7_n12703", {12703}, 12703, 32},
                             // §2 / §9 用例 B1-4: 多核非对齐 (N=1048573, aO=83, numCores=32, tilesMain=2, coresTail=19)
                             Branch1Case{"multi_core_unalign_n1048573", {1048573}, 1048573, 32},
                             // §2 / §9 用例 B1-5: rank=8 非对齐 (N=2187, k==0 path, aO=1, aITail=3)
                             //   shape=[3,3,3,3,3,3,3,1] → product=3^7=2187, rank=8, 2187%8=3≠0
                             //   (DESIGN §9 B1-5 lists [3,3,3,3,3,3,3,3]=6561 elem but task says N=2187;
                             //    use [3,3,3,3,3,3,3,1] to match N=2187 while keeping rank=8 non-aligned.)
                             Branch1Case{"rank8_unalign_n2187", {3, 3, 3, 3, 3, 3, 3, 1}, 2187, 32}));

// Note: main() is provided by test_inplace_apply_ada_max_tiling.cpp (the common
// TilingUT in the same executable). gtest discovers all TEST_P/TEST instances
// linked into the executable, so Branch-1 tests run alongside common + Branch-0.
