/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software; you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License).
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED on an "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file gru_block_cell_proto.h
 * \brief GruBlockCell 算子 GE IR 原型定义（图模式）。
 *
 * GRU（门控循环单元）单步前向全融合算子，对标 TensorFlow tf.raw_ops.GRUBlockCell
 * （reset_before 语义）。给定当前步输入 x、上一步隐状态 hPrev、合并权重与偏置，
 * 单次调用融合完成门控 GEMM、候选 GEMM、sigmoid/tanh 门控激活与隐状态更新，
 * 输出 r/u/c/h 四个 [B, H] 张量。仅支持 fp32、ND 格式，无属性。
 */
#ifndef OPS_OP_PROTO_INC_GRU_BLOCK_CELL_H_
#define OPS_OP_PROTO_INC_GRU_BLOCK_CELL_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief GRU single-step forward cell (reset_before variant).
 * ru_bar = [x, h_prev]·w_ru + b_ru; r = sigmoid(ru_bar[:, :H]); u = sigmoid(ru_bar[:, H:])
 * c = tanh([x, h_prev⊙r]·w_c + b_c); h = u⊙(h_prev − c) + c
 *
 *@attention Constraints:
 * *All six inputs and four outputs must be DT_FLOAT and FORMAT_ND.*
 * *x/hPrev/wRu/wC are rank-2; bRu/bC must be rank-1 (rank-2 [1,N] size-1 broadcast view
 * is rejected at the tiling stage -- see README constraints).*
 * *wRu is the merged gate weight [I+H, 2H] with column order r|u; wC is [I+H, H].*
 *
 *@par Inputs:
 *@li x: A Tensor of type DT_FLOAT. Current step input, shape [B, I].
 *@li hPrev: A Tensor of type DT_FLOAT. Previous hidden state, shape [B, H], dim0 must match x.
 *@li wRu: A Tensor of type DT_FLOAT. Merged reset/update gate weight, shape [I+H, 2H] (rows: x block then h block;
 *columns: r block then u block).
 *@li wC: A Tensor of type DT_FLOAT. Merged candidate weight, shape [I+H, H].
 *@li bRu: A Tensor of type DT_FLOAT. Merged gate bias, shape [2H], rank-1 ([1, 2H] broadcast view rejected).
 *@li bC: A Tensor of type DT_FLOAT. Candidate bias, shape [H], rank-1 ([1, H] broadcast view rejected).
 *
 *@par Outputs:
 *@li r: A Tensor of type DT_FLOAT. Reset gate activation, shape [B, H].
 *@li u: A Tensor of type DT_FLOAT. Update gate activation, shape [B, H].
 *@li c: A Tensor of type DT_FLOAT. Candidate state, shape [B, H].
 *@li h: A Tensor of type DT_FLOAT. New hidden state, shape [B, H].
 *
 *@par Third-party framework compatibility
 *Compatible with the TensorFlow operator GRUBlockCell.
 */
#ifndef OPS_PROTO_DEF_GRUBLOCKCELL
#define OPS_PROTO_DEF_GRUBLOCKCELL
REG_OP(GruBlockCell)
    .INPUT(x, TensorType({DT_FLOAT}))
    .INPUT(hPrev, TensorType({DT_FLOAT}))
    .INPUT(wRu, TensorType({DT_FLOAT}))
    .INPUT(wC, TensorType({DT_FLOAT}))
    .INPUT(bRu, TensorType({DT_FLOAT}))
    .INPUT(bC, TensorType({DT_FLOAT}))
    .OUTPUT(r, TensorType({DT_FLOAT}))
    .OUTPUT(u, TensorType({DT_FLOAT}))
    .OUTPUT(c, TensorType({DT_FLOAT}))
    .OUTPUT(h, TensorType({DT_FLOAT}))
    .OP_END_FACTORY_REG(GruBlockCell)
#endif

} // namespace ge

#endif // OPS_OP_PROTO_INC_GRU_BLOCK_CELL_H_
