/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_apply_centered_rms_prop_infershape.cpp
 * \brief InplaceApplyCenteredRMSProp 算子形状推导实现
 *
 * 4 个输出 shape = 对应输入 shape（element-wise，无归约，shape 完全一致）
 *   var_out.shape = var.shape
 *   mg_out.shape  = mg.shape
 *   ms_out.shape  = ms.shape
 *   mom_out.shape = mom.shape
 *
 * 输出 dtype = 对应输入 dtype（same_as_input，由 def 文件 DataType 列表保证）
 */

#include "util/shape_util.h"
#include "register/op_impl_registry.h"
#include "exe_graph/runtime/infer_shape_context.h"
#include "op_common/log/log.h"

using namespace ge;

namespace ops {

static graphStatus InferShape4InplaceApplyCenteredRmsProp(gert::InferShapeContext* context)
{
    for (size_t i = 0; i < 4; i++) {
        const gert::Shape* inputShape = context->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
        gert::Shape* outputShape = context->GetOutputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, outputShape);
        *outputShape = *inputShape;
    }

    OP_LOGI(context->GetNodeName(), "[InferShape] output0 shape=%s",
            Ops::Base::ToString(*context->GetOutputShape(0)).c_str());

    return ge::GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(InplaceApplyCenteredRMSProp).InferShape(InferShape4InplaceApplyCenteredRmsProp);

} // namespace ops
