/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file apply_came_part2_proto.h
 * \brief ApplyCamePart2 GE IR 算子注册
 *
 * 对齐 canndev nn_optimizer.h REG_OP(ApplyCamePart2)：输入 r/c 与输出 r/c 同名，即原地输出。
 */
#ifndef OPS_OP_PROTO_INC_APPLY_CAME_PART2_H_
#define OPS_OP_PROTO_INC_APPLY_CAME_PART2_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 * @brief Computes the ApplyCamePart2.
 *
 * @par Inputs:
 * including:
 * @li grad: A mutable Tensor with rank 2, shape is [n, m], support dtypes:
 * float16, float32, bfloat16.
 * @li sum_grad_r: A 1-dimensional float32 Tensor, shape is [n].
 * @li sum_grad_c: A 1-dimensional float32 Tensor, shape is [m].
 * @li sum_grad_rc: A 1-dimensional float32 Tensor, shape must be [1].
 * @li r: A 1-dimensional Tensor, shape is [n], support dtypes:
 * float16, float32, bfloat16.
 * @li c: A 1-dimensional Tensor, shape is [m], support dtypes:
 * float16, float32, bfloat16.
 * @li beta2: A 1-dimensional float32 Tensor, shape must be [1].
 * @li sum_r: A optional 1-dimensional float32 Tensor, shape must be [1].
 * Default equals to sum(r).
 * @li global_shape: A optional 1-dimensional int64 Tensor, shape must be [2],
 * value specifies the original shape (n, m). Default equals to grad's shape. \n
 *
 * @par Outputs:
 * @li r: A mutable tensor. Must have the same shape as input "r", shape is [n].
 * Same dtype as "grad". \n
 * r = beta2 * r + (1 - beta2) * sum_grad_r / m.
 * @li c: A mutable tensor. Must have the same shape as input "c", shape is [m].
 * Same dtype as "grad". \n
 * c = beta2 * c + (1 - beta2) * sum_grad_c / n.
 * @li u: A mutable float32 tensor. Must have the same shape as input "grad",
 * shape is [n, m]. \n
 * u = grad / (sqrt (r * c / (beta2 * sum_r / n + (1 - beta2) * sum_grad_rc / (m * n)))).
 * @li sum_square_u: A float32 mutable tensor. Shape must be [1]. \n
 * sum_square_u = sum(u * u). \n
 *
 * @par Restrictions:
 * Warning: THIS FUNCTION IS EXPERIMENTAL. Please do not use.
 */
#ifndef OPS_PROTO_DEF_APPLYCAMEPART2
#define OPS_PROTO_DEF_APPLYCAMEPART2
REG_OP(ApplyCamePart2)
    .INPUT(grad, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .INPUT(sum_grad_r, TensorType({DT_FLOAT}))
    .INPUT(sum_grad_c, TensorType({DT_FLOAT}))
    .INPUT(sum_grad_rc, TensorType({DT_FLOAT}))
    .INPUT(r, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .INPUT(c, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .INPUT(beta2, TensorType({DT_FLOAT}))
    .OPTIONAL_INPUT(sum_r, TensorType({DT_FLOAT}))
    .OPTIONAL_INPUT(global_shape, TensorType({DT_INT64}))
    .OUTPUT(r, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .OUTPUT(c, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .OUTPUT(u, TensorType({DT_FLOAT}))
    .OUTPUT(sum_square_u, TensorType({DT_FLOAT}))
    .OP_END_FACTORY_REG(ApplyCamePart2)
#endif

} // namespace ge

#endif // OPS_OP_PROTO_INC_APPLY_CAME_PART2_H_
