/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file inplace_apply_power_sign.h
 * \brief InplaceApplyPowerSign kernel class definition (arch35 / DAV_3510: Ascend950PR/950DT)
 *
 * Iteration 2: Multi-dtype support (FP32 + FP16 + BF16).
 *
 * Formula:
 *   m_new = beta * m + (1 - beta) * grad
 *   sign_gm = Sign(m_new) * Sign(grad)
 *   var_new = var - lr * Exp(logbase * sign_decay * sign_gm) * grad
 *   m = m_new (in-place writeback)
 *
 * Memory Strategy:
 *   FP32 path:     5 FP32 Queues + 2 FP32 Buf
 *   FP16/BF16 path: 5 T-type Queues + 5 FP32 Buf
 *
 * Probe findings integrated:
 *   - Sign API: 3-param version Sign(dst, src, count) — no sharedTmp needed
 *   - Exp API: basic version Exp(dst, src, count) — no sharedTmp needed
 *   - Allocate output queue tensors early, compute directly into them
 *   - DataCopyExtParams for GM<->UB transport (uint32_t blockLen)
 *
 * Generated By CANNBot
 */

#ifndef INPLACE_APPLY_POWER_SIGN_H
#define INPLACE_APPLY_POWER_SIGN_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "inplace_apply_power_sign_tiling_data.h"
#include "inplace_apply_power_sign_tiling_key.h"

namespace NsInplaceApplyPowerSign {

using namespace AscendC;

// Type trait: check if T is float (FP32 direct path)
template <typename T>
struct IsFloat32 {
    static constexpr bool value = false;
};
template <>
struct IsFloat32<float> {
    static constexpr bool value = true;
};

// Type trait: check if T is bfloat16_t (needs manual Cast on arch35)
// Note: bfloat16_t is a compiler built-in type, not in AscendC namespace
template <typename T>
struct IsBFloat16 {
    static constexpr bool value = false;
};
template <>
struct IsBFloat16<bfloat16_t> {
    static constexpr bool value = true;
};

template <typename T>
class InplaceApplyPowerSign {
public:
    __aicore__ inline InplaceApplyPowerSign() {}

    __aicore__ inline void Init(GM_ADDR var, GM_ADDR m, GM_ADDR lr, GM_ADDR logbase, GM_ADDR signDecay, GM_ADDR beta,
                                GM_ADDR grad, GM_ADDR varOut, GM_ADDR mOut,
                                const InplaceApplyPowerSignTilingData* tilingData);
    __aicore__ inline void Process();

private:
    // Read 4 scalar inputs (lr/logbase/sign_decay/beta) from GM into a UB
    // scratch buffer via DataCopyPad, then materialize them as fp32 scalars.
    // Reading GM tensors through GetValue() directly triggers an MTE
    // out-of-range fault on real hardware (arch35), so scalars must be
    // staged in UB first.
    __aicore__ inline void LoadScalarsFromGm(GM_ADDR lrAddr, GM_ADDR logbaseAddr, GM_ADDR signDecayAddr,
                                             GM_ADDR betaAddr);
    // fp32 path: DataCopyPad each scalar into its fp32 slot, read directly.
    __aicore__ inline void LoadScalarsFp32(const AscendC::GlobalTensor<T>& lrGM,
                                           const AscendC::GlobalTensor<T>& logbaseGM,
                                           const AscendC::GlobalTensor<T>& signDecayGM,
                                           const AscendC::GlobalTensor<T>& betaGM,
                                           const AscendC::DataCopyExtParams& cpScalar,
                                           const AscendC::DataCopyPadExtParams<T>& padParams);
    // fp16/bf16 path: stage dtype-T payloads, tensor Cast to fp32, then read.
    __aicore__ inline void LoadScalarsCasted(const AscendC::GlobalTensor<T>& lrGM,
                                             const AscendC::GlobalTensor<T>& logbaseGM,
                                             const AscendC::GlobalTensor<T>& signDecayGM,
                                             const AscendC::GlobalTensor<T>& betaGM,
                                             const AscendC::DataCopyExtParams& cpScalar,
                                             const AscendC::DataCopyPadExtParams<T>& padParams);

    __aicore__ inline void ProcessTile(int64_t offset, int64_t count);
    __aicore__ inline void CopyIn(int64_t offset, int64_t count);
    __aicore__ inline void Compute(int64_t count);
    __aicore__ inline void CopyOut(int64_t offset, int64_t count);

    __aicore__ inline void ComputeFp32(AscendC::LocalTensor<float>& varFp32, AscendC::LocalTensor<float>& mFp32,
                                       AscendC::LocalTensor<float>& gradFp32, AscendC::LocalTensor<T>& varOutLocal,
                                       AscendC::LocalTensor<T>& mOutLocal, int64_t count);

    __aicore__ inline void ComputeUpdateFp32(AscendC::LocalTensor<float>& tempBuf, AscendC::LocalTensor<float>& varFp32,
                                             AscendC::LocalTensor<float>& mFp32, AscendC::LocalTensor<float>& gradFp32,
                                             AscendC::LocalTensor<float>& varOrigFp32, int64_t count);

    __aicore__ inline void ComputeCasted(AscendC::LocalTensor<T>& varLocal, AscendC::LocalTensor<T>& mLocal,
                                         AscendC::LocalTensor<T>& gradLocal, AscendC::LocalTensor<T>& varOutLocal,
                                         AscendC::LocalTensor<T>& mOutLocal, int64_t count);

private:
    TPipe pipe;

    // VECIN Queues: 3 input tensors (stored in original dtype T)
    TQue<QuePosition::VECIN, 1> varQueue;
    TQue<QuePosition::VECIN, 1> mQueue;
    TQue<QuePosition::VECIN, 1> gradQueue;

    // VECOUT Queues: 2 output tensors (stored in original dtype T)
    TQue<QuePosition::VECOUT, 1> varOutQueue;
    TQue<QuePosition::VECOUT, 1> mOutQueue;

    // FP32 intermediate buffers
    // FP32 path (2 buffers):
    //   fp32Buf0: tmp/signM/expVal/update (reused sequentially)
    //   fp32Buf1: signG (Sign(grad) output)
    // FP16/BF16 path (5 buffers):
    //   fp32Buf0: varFp32 (cast from var input)
    //   fp32Buf1: mFp32 (cast from m, holds m_new for output)
    //   fp32Buf2: gradFp32 (cast from grad)
    //   fp32Buf3: tempBuf (reusable temp for Sign/Exp/Mul results)
    //   fp32Buf4: varOrigFp32 (saved copy of original var for Step 7)
    TBuf<QuePosition::VECCALC> fp32Buf0;
    TBuf<QuePosition::VECCALC> fp32Buf1;
    TBuf<QuePosition::VECCALC> fp32Buf2;
    TBuf<QuePosition::VECCALC> fp32Buf3;
    TBuf<QuePosition::VECCALC> fp32Buf4;

    // Dedicated 32B-aligned UB scratch for the 4 scalar-tensor reads
    // (lr / logbase / sign_decay / beta). Each scalar lands in its own
    // 8-fp32-element slot so the four DataCopyPad reads do not collide.
    // SCALAR_ALIGN_ELEMS = 8 keeps every slot 32B-aligned.
    static constexpr int32_t SCALAR_ALIGN_ELEMS = 8;
    static constexpr int32_t SCALAR_COUNT = 4;
    TBuf<QuePosition::VECCALC> scalarBuf;

    // Global memory tensors
    GlobalTensor<T> varGM;
    GlobalTensor<T> mGM;
    GlobalTensor<T> gradGM;
    GlobalTensor<T> varOutGM; // in-place with varGM
    GlobalTensor<T> mOutGM;   // in-place with mGM

    int64_t blockFormer_ = 0;
    int64_t blockNum_ = 0;
    int32_t ubFormer_ = 0;
    int64_t ubLoopOfFormerBlock_ = 0;
    int64_t ubTailOfFormerBlock_ = 0;
    int64_t ubLoopOfTailBlock_ = 0;
    int64_t ubTailOfTailBlock_ = 0;

    // Scalar values
    float lr_ = 0.0f;
    float logbase_ = 0.0f;
    float signDecay_ = 0.0f;
    float beta_ = 0.0f;
};

// Stage the 4 scalar inputs from GM into UB via DataCopyPad, then convert to
// fp32 scalars. Reading a 1-element GM tensor via GetValue() directly faults
// on real hardware (MTE out-of-range), so scalars must be staged in UB first.
// dtype-T -> fp32 conversion:
//   fp32: read the fp32 slot directly.
//   fp16/bf16: tensor Cast<float, T> (both supported on arch35).
// scalarBuf layout (2*SCALAR_COUNT slots): fp32 result slots occupy the first
// SCALAR_COUNT 32B-aligned slots; the dtype-T payloads land in the second half.
template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::LoadScalarsFromGm(GM_ADDR lrAddr, GM_ADDR logbaseAddr,
                                                                   GM_ADDR signDecayAddr, GM_ADDR betaAddr)
{
    AscendC::GlobalTensor<T> lrGM;
    AscendC::GlobalTensor<T> logbaseGM;
    AscendC::GlobalTensor<T> signDecayGM;
    AscendC::GlobalTensor<T> betaGM;
    lrGM.SetGlobalBuffer((__gm__ T*)lrAddr, 1);
    logbaseGM.SetGlobalBuffer((__gm__ T*)logbaseAddr, 1);
    signDecayGM.SetGlobalBuffer((__gm__ T*)signDecayAddr, 1);
    betaGM.SetGlobalBuffer((__gm__ T*)betaAddr, 1);

    AscendC::DataCopyExtParams cpScalar;
    cpScalar.blockCount = 1;
    cpScalar.blockLen = sizeof(T); // 1 element in bytes
    cpScalar.srcStride = 0;
    cpScalar.dstStride = 0;
    AscendC::DataCopyPadExtParams<T> padParams{false, 0, 0, 0};

    if constexpr (IsFloat32<T>::value) {
        LoadScalarsFp32(lrGM, logbaseGM, signDecayGM, betaGM, cpScalar, padParams);
    } else {
        LoadScalarsCasted(lrGM, logbaseGM, signDecayGM, betaGM, cpScalar, padParams);
    }
}

// fp32 path: DataCopyPad each scalar into its own 32B slot and read directly.
template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::LoadScalarsFp32(const AscendC::GlobalTensor<T>& lrGM,
                                                                 const AscendC::GlobalTensor<T>& logbaseGM,
                                                                 const AscendC::GlobalTensor<T>& signDecayGM,
                                                                 const AscendC::GlobalTensor<T>& betaGM,
                                                                 const AscendC::DataCopyExtParams& cpScalar,
                                                                 const AscendC::DataCopyPadExtParams<T>& padParams)
{
    // fp32 result slots (first half of scalarBuf), one 32B slot per scalar.
    AscendC::LocalTensor<float> scratchF = scalarBuf.template Get<float>();
    AscendC::LocalTensor<float> s0 = scratchF[0 * SCALAR_ALIGN_ELEMS];
    AscendC::LocalTensor<float> s1 = scratchF[1 * SCALAR_ALIGN_ELEMS];
    AscendC::LocalTensor<float> s2 = scratchF[2 * SCALAR_ALIGN_ELEMS];
    AscendC::LocalTensor<float> s3 = scratchF[3 * SCALAR_ALIGN_ELEMS];
    AscendC::DataCopyPad(s0, lrGM, cpScalar, padParams);
    AscendC::DataCopyPad(s1, logbaseGM, cpScalar, padParams);
    AscendC::DataCopyPad(s2, signDecayGM, cpScalar, padParams);
    AscendC::DataCopyPad(s3, betaGM, cpScalar, padParams);
    AscendC::PipeBarrier<PIPE_ALL>();
    lr_ = s0.GetValue(0);
    logbase_ = s1.GetValue(0);
    signDecay_ = s2.GetValue(0);
    beta_ = s3.GetValue(0);
}

// fp16/bf16 path: stage each 1-element T payload, tensor Cast to fp32, then read.
template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::LoadScalarsCasted(const AscendC::GlobalTensor<T>& lrGM,
                                                                   const AscendC::GlobalTensor<T>& logbaseGM,
                                                                   const AscendC::GlobalTensor<T>& signDecayGM,
                                                                   const AscendC::GlobalTensor<T>& betaGM,
                                                                   const AscendC::DataCopyExtParams& cpScalar,
                                                                   const AscendC::DataCopyPadExtParams<T>& padParams)
{
    // Non-fp32: DataCopyPad each 1-element T payload into the second-half slots.
    AscendC::LocalTensor<T> scratchT = scalarBuf.template Get<T>();
    constexpr int32_t tPerFp32 = static_cast<int32_t>(sizeof(float) / sizeof(T));
    constexpr int32_t payloadBase = SCALAR_COUNT * SCALAR_ALIGN_ELEMS * tPerFp32;
    constexpr int32_t strideT = SCALAR_ALIGN_ELEMS * tPerFp32;
    AscendC::LocalTensor<T> tLr = scratchT[payloadBase + 0 * strideT];
    AscendC::LocalTensor<T> tLog = scratchT[payloadBase + 1 * strideT];
    AscendC::LocalTensor<T> tSign = scratchT[payloadBase + 2 * strideT];
    AscendC::LocalTensor<T> tBeta = scratchT[payloadBase + 3 * strideT];

    AscendC::DataCopyPad(tLr, lrGM, cpScalar, padParams);
    AscendC::DataCopyPad(tLog, logbaseGM, cpScalar, padParams);
    AscendC::DataCopyPad(tSign, signDecayGM, cpScalar, padParams);
    AscendC::DataCopyPad(tBeta, betaGM, cpScalar, padParams);
    AscendC::PipeBarrier<PIPE_ALL>();

    // fp32 result slots (first half of scalarBuf), one 32B slot per scalar.
    AscendC::LocalTensor<float> scratchF = scalarBuf.template Get<float>();
    AscendC::LocalTensor<float> s0 = scratchF[0 * SCALAR_ALIGN_ELEMS];
    AscendC::LocalTensor<float> s1 = scratchF[1 * SCALAR_ALIGN_ELEMS];
    AscendC::LocalTensor<float> s2 = scratchF[2 * SCALAR_ALIGN_ELEMS];
    AscendC::LocalTensor<float> s3 = scratchF[3 * SCALAR_ALIGN_ELEMS];

    // fp16/bf16 -> fp32 via tensor Cast (both supported on arch35).
    AscendC::Cast<float, T>(s0, tLr, AscendC::RoundMode::CAST_NONE, 1);
    AscendC::Cast<float, T>(s1, tLog, AscendC::RoundMode::CAST_NONE, 1);
    AscendC::Cast<float, T>(s2, tSign, AscendC::RoundMode::CAST_NONE, 1);
    AscendC::Cast<float, T>(s3, tBeta, AscendC::RoundMode::CAST_NONE, 1);
    AscendC::PipeBarrier<PIPE_ALL>();

    lr_ = s0.GetValue(0);
    logbase_ = s1.GetValue(0);
    signDecay_ = s2.GetValue(0);
    beta_ = s3.GetValue(0);
}

template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::Init(GM_ADDR var, GM_ADDR m, GM_ADDR lrAddr, GM_ADDR logbaseAddr,
                                                      GM_ADDR signDecayAddr, GM_ADDR betaAddr, GM_ADDR grad,
                                                      GM_ADDR varOut, GM_ADDR mOut,
                                                      const InplaceApplyPowerSignTilingData* tilingData)
{
    // Cache tiling params
    blockFormer_ = tilingData->blockFormer;
    blockNum_ = tilingData->blockNum;
    ubFormer_ = tilingData->ubFormer;
    ubLoopOfFormerBlock_ = tilingData->ubLoopOfFormerBlock;
    ubTailOfFormerBlock_ = tilingData->ubTailOfFormerBlock;
    ubLoopOfTailBlock_ = tilingData->ubLoopOfTailBlock;
    ubTailOfTailBlock_ = tilingData->ubTailOfTailBlock;

    if (tilingData->dim0 == 0) {
        return;
    }

    // Scalars must be staged in UB (DataCopyPad) before reading — reading
    // a 1-element GM tensor via GetValue() directly faults on real hardware.
    // Buffer holds both the dtype-T payload slots and the fp32 result slots
    // in disjoint 32B-aligned regions (2x SCALAR_COUNT slots total).
    pipe.InitBuffer(scalarBuf, 2 * SCALAR_COUNT * SCALAR_ALIGN_ELEMS * sizeof(float));
    LoadScalarsFromGm(lrAddr, logbaseAddr, signDecayAddr, betaAddr);

    // Calculate this core's offset and length
    int64_t blockIdx = AscendC::GetBlockIdx();
    int64_t offset = blockFormer_ * blockIdx;
    int64_t remainderLength = tilingData->dim0 - offset;
    int64_t blockLength = (remainderLength > blockFormer_) ? blockFormer_ : remainderLength;

    // Set global buffers
    varGM.SetGlobalBuffer((__gm__ T*)var + offset, blockLength);
    mGM.SetGlobalBuffer((__gm__ T*)m + offset, blockLength);
    gradGM.SetGlobalBuffer((__gm__ T*)grad + offset, blockLength);
    varOutGM.SetGlobalBuffer((__gm__ T*)varOut + offset, blockLength);
    mOutGM.SetGlobalBuffer((__gm__ T*)mOut + offset, blockLength);

    // Initialize Queues (original dtype T)
    pipe.InitBuffer(varQueue, 1, ubFormer_ * sizeof(T));
    pipe.InitBuffer(mQueue, 1, ubFormer_ * sizeof(T));
    pipe.InitBuffer(gradQueue, 1, ubFormer_ * sizeof(T));
    pipe.InitBuffer(varOutQueue, 1, ubFormer_ * sizeof(T));
    pipe.InitBuffer(mOutQueue, 1, ubFormer_ * sizeof(T));

    // Initialize FP32 buffers
    // All paths need at least 2 FP32 buffers
    pipe.InitBuffer(fp32Buf0, ubFormer_ * sizeof(float));
    pipe.InitBuffer(fp32Buf1, ubFormer_ * sizeof(float));

    // FP16/BF16 path needs 3 additional FP32 buffers (total 5)
    if constexpr (!IsFloat32<T>::value) {
        pipe.InitBuffer(fp32Buf2, ubFormer_ * sizeof(float));
        pipe.InitBuffer(fp32Buf3, ubFormer_ * sizeof(float));
        pipe.InitBuffer(fp32Buf4, ubFormer_ * sizeof(float));
    }
}

template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::Process()
{
    // Early return for empty tensor (integrated from probe_empty_tensor)
    if (blockNum_ == 0) {
        return;
    }

    int64_t blockIdx = AscendC::GetBlockIdx();
    bool isLastBlock = (blockIdx == blockNum_ - 1);

    int64_t loopNum = isLastBlock ? ubLoopOfTailBlock_ : ubLoopOfFormerBlock_;
    int64_t tailNum = isLastBlock ? ubTailOfTailBlock_ : ubTailOfFormerBlock_;

    int64_t offset = 0;
    for (int64_t i = 0; i < loopNum - 1; i++) {
        ProcessTile(offset, ubFormer_);
        offset += ubFormer_;
    }
    if (loopNum > 0) {
        ProcessTile(offset, tailNum);
    }
}

template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::ProcessTile(int64_t offset, int64_t count)
{
    CopyIn(offset, count);
    constexpr int64_t vecAlign = (sizeof(T) == 4) ? 8 : 16;
    int64_t alignedCount = (count + vecAlign - 1) / vecAlign * vecAlign;
    Compute(alignedCount);
    CopyOut(offset, count);
}

template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::CopyIn(int64_t offset, int64_t count)
{
    AscendC::LocalTensor<T> varLocal = varQueue.template AllocTensor<T>();
    AscendC::LocalTensor<T> mLocal = mQueue.template AllocTensor<T>();
    AscendC::LocalTensor<T> gradLocal = gradQueue.template AllocTensor<T>();

    // DataCopyExtParams: uint32_t blockLen supports large tiles (>65535 bytes)
    AscendC::DataCopyExtParams copyParams(1, static_cast<uint32_t>(count * sizeof(T)), 0, 0, 0);
    AscendC::DataCopyPadExtParams<T> padParams(false, 0, 0, 0);

    AscendC::DataCopyPad(varLocal, varGM[offset], copyParams, padParams);
    AscendC::DataCopyPad(mLocal, mGM[offset], copyParams, padParams);
    AscendC::DataCopyPad(gradLocal, gradGM[offset], copyParams, padParams);

    varQueue.EnQue(varLocal);
    mQueue.EnQue(mLocal);
    gradQueue.EnQue(gradLocal);
}

template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::Compute(int64_t count)
{
    AscendC::LocalTensor<T> varLocal = varQueue.template DeQue<T>();
    AscendC::LocalTensor<T> mLocal = mQueue.template DeQue<T>();
    AscendC::LocalTensor<T> gradLocal = gradQueue.template DeQue<T>();

    AscendC::LocalTensor<T> varOutLocal = varOutQueue.template AllocTensor<T>();
    AscendC::LocalTensor<T> mOutLocal = mOutQueue.template AllocTensor<T>();

    if constexpr (IsFloat32<T>::value) {
        AscendC::LocalTensor<float> varFp32 = varLocal;
        AscendC::LocalTensor<float> mFp32 = mLocal;
        AscendC::LocalTensor<float> gradFp32 = gradLocal;
        ComputeFp32(varFp32, mFp32, gradFp32, varOutLocal, mOutLocal, count);
    } else {
        // FP16 and BF16 both use the standard Cast path. On arch35 the tensor
        // Cast API supports fp16/bf16 <-> fp32 directly (CAST_NONE for widening,
        // CAST_RINT / round-to-nearest-ties-to-even for narrowing) — matching
        // numpy/TF semantics. No manual bit-manipulation is required.
        ComputeCasted(varLocal, mLocal, gradLocal, varOutLocal, mOutLocal, count);
    }

    varOutQueue.template EnQue<T>(varOutLocal);
    mOutQueue.template EnQue<T>(mOutLocal);

    varQueue.FreeTensor(varLocal);
    mQueue.FreeTensor(mLocal);
    gradQueue.FreeTensor(gradLocal);
}

// FP32 direct computation: 3-param Sign + basic Exp (no sharedTmpBuf needed)
template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::ComputeFp32(AscendC::LocalTensor<float>& varFp32,
                                                             AscendC::LocalTensor<float>& mFp32,
                                                             AscendC::LocalTensor<float>& gradFp32,
                                                             AscendC::LocalTensor<T>& varOutLocal,
                                                             AscendC::LocalTensor<T>& mOutLocal, int64_t count)
{
    AscendC::LocalTensor<float> tmpBuf = fp32Buf0.template AllocTensor<float>();
    AscendC::LocalTensor<float> signGBuf = fp32Buf1.template AllocTensor<float>();

    // Step 3: m_new = beta * m + (1 - beta) * grad
    AscendC::Muls(tmpBuf, mFp32, beta_, count);
    float oneMinusBeta = 1.0f - beta_;
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Muls(mFp32, gradFp32, oneMinusBeta, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Add(mFp32, tmpBuf, mFp32, count);

    // Save m_new to output BEFORE Sign overwrites mFp32's dependencies
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::DataCopy(mOutLocal, mFp32, count);

    // Step 4: sign_gm = Sign(m_new) * Sign(grad)
    AscendC::Sign(tmpBuf, mFp32, count);
    AscendC::Sign(signGBuf, gradFp32, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Mul(tmpBuf, tmpBuf, signGBuf, count);

    // Step 5: exp_val = Exp(logbase * sign_decay * sign_gm)
    float coeff = logbase_ * signDecay_;
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Muls(tmpBuf, tmpBuf, coeff, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Exp(signGBuf, tmpBuf, static_cast<int32_t>(count));

    // Step 6-7: var_new = var - lr * exp_val * grad
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Mul(tmpBuf, signGBuf, gradFp32, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Muls(tmpBuf, tmpBuf, lr_, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Sub(varOutLocal, varFp32, tmpBuf, count);
}

// Shared Steps 3-7 core for non-FP32 paths (3-param Sign + basic Exp)
// Results left in varFp32 (var_new) and mFp32 (m_new)
template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::ComputeUpdateFp32(
    AscendC::LocalTensor<float>& tempBuf, AscendC::LocalTensor<float>& varFp32, AscendC::LocalTensor<float>& mFp32,
    AscendC::LocalTensor<float>& gradFp32, AscendC::LocalTensor<float>& varOrigFp32, int64_t count)
{
    // Step 3: m_new = beta * m + (1 - beta) * grad
    AscendC::Muls(tempBuf, mFp32, beta_, count);
    float oneMinusBeta = 1.0f - beta_;
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Muls(mFp32, gradFp32, oneMinusBeta, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Add(mFp32, tempBuf, mFp32, count);

    // Step 4: sign_gm = Sign(m_new) * Sign(grad)
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Sign(tempBuf, mFp32, count);
    AscendC::Sign(varFp32, gradFp32, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Mul(tempBuf, tempBuf, varFp32, count);

    // Step 5: exp_val = Exp(logbase * sign_decay * sign_gm)
    float coeff = logbase_ * signDecay_;
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Muls(tempBuf, tempBuf, coeff, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Exp(varFp32, tempBuf, static_cast<int32_t>(count));

    // Step 6-7: var_new = var_orig - lr * exp_val * grad
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Mul(tempBuf, varFp32, gradFp32, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Muls(tempBuf, tempBuf, lr_, count);
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Sub(varFp32, varOrigFp32, tempBuf, count);
}

// Standard Cast path for FP16 and BF16 (arch35 tensor Cast supports both)
template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::ComputeCasted(AscendC::LocalTensor<T>& varLocal,
                                                               AscendC::LocalTensor<T>& mLocal,
                                                               AscendC::LocalTensor<T>& gradLocal,
                                                               AscendC::LocalTensor<T>& varOutLocal,
                                                               AscendC::LocalTensor<T>& mOutLocal, int64_t count)
{
    AscendC::LocalTensor<float> varFp32 = fp32Buf0.template AllocTensor<float>();
    AscendC::LocalTensor<float> mFp32 = fp32Buf1.template AllocTensor<float>();
    AscendC::LocalTensor<float> gradFp32 = fp32Buf2.template AllocTensor<float>();
    AscendC::LocalTensor<float> tempBuf = fp32Buf3.template AllocTensor<float>();
    AscendC::LocalTensor<float> varOrigFp32 = fp32Buf4.template AllocTensor<float>();

    AscendC::Cast<float, T>(varFp32, varLocal, AscendC::RoundMode::CAST_NONE, count);
    AscendC::Cast<float, T>(mFp32, mLocal, AscendC::RoundMode::CAST_NONE, count);
    AscendC::Cast<float, T>(gradFp32, gradLocal, AscendC::RoundMode::CAST_NONE, count);

    AscendC::PipeBarrier<PIPE_V>();
    AscendC::DataCopy(varOrigFp32, varFp32, count);

    ComputeUpdateFp32(tempBuf, varFp32, mFp32, gradFp32, varOrigFp32, count);

    // CAST_RINT = round-to-nearest-ties-to-even, matching numpy/TF bf16/fp16 cast.
    AscendC::PipeBarrier<PIPE_V>();
    AscendC::Cast<T, float>(varOutLocal, varFp32, AscendC::RoundMode::CAST_RINT, count);
    AscendC::Cast<T, float>(mOutLocal, mFp32, AscendC::RoundMode::CAST_RINT, count);
}

template <typename T>
__aicore__ inline void InplaceApplyPowerSign<T>::CopyOut(int64_t offset, int64_t count)
{
    AscendC::LocalTensor<T> varOutLocal = varOutQueue.template DeQue<T>();
    AscendC::LocalTensor<T> mOutLocal = mOutQueue.template DeQue<T>();

    AscendC::DataCopyExtParams copyParams(1, static_cast<uint32_t>(count * sizeof(T)), 0, 0, 0);

    AscendC::DataCopyPad(varOutGM[offset], varOutLocal, copyParams);
    AscendC::DataCopyPad(mOutGM[offset], mOutLocal, copyParams);

    varOutQueue.FreeTensor(varOutLocal);
    mOutQueue.FreeTensor(mOutLocal);
}

} // namespace NsInplaceApplyPowerSign

#endif // INPLACE_APPLY_POWER_SIGN_H
