/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef THNN_FUSED_GRU_CELL_GRAD_STRUCT_H
#define THNN_FUSED_GRU_CELL_GRAD_STRUCT_H

#include "ascendc/host_api/tiling/template_argument.h" // ASCENDC_TPL macros

// GRU 单步融合反向 TilingKey 模板参数 — 按 reduction 范式双 bool 轴声明
ASCENDC_TPL_ARGS_DECL(ThnnFusedGruCellGrad,
                      ASCENDC_TPL_BOOL_DECL(isGroup, 0, 1),        // 0=base/empty, 1=group（A×R 2D 分核）
                      ASCENDC_TPL_BOOL_DECL(isEmptyTensor, 0, 1)); // 空 tensor 模板（EMPTY_A / EMPTY_R 共用）

ASCENDC_TPL_SEL(
    // base 模板：isGroup=0, isEmptyTensor=0 → GET_TPL_TILING_KEY(0, 0) = 0
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isGroup, 0), ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 0)),
    // 空 tensor 模板：isGroup=0, isEmptyTensor=1 → GET_TPL_TILING_KEY(0, 1) = 2
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isGroup, 0), ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 1)),
    // group 模板（isEmptyTensor 固定 0，与 empty 互斥）：GET_TPL_TILING_KEY(1, 0) = 1
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isGroup, 1), ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 0)));

#endif // THNN_FUSED_GRU_CELL_GRAD_STRUCT_H
