/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "gtest/gtest.h"
#include "infershape_test_util.h"
#include "kernel_run_context_facker.h"
#include "register/op_impl_registry.h"

using ge::FORMAT_ND;

struct AvgPoolUpdateInfershapeParam {
    string case_name;
    std::initializer_list<int64_t> x1Shape;
    std::initializer_list<int64_t> x2Shape;
    ge::DataType x1Dtype;
};

class AvgPoolUpdateRuntimeInferShape : public testing::TestWithParam<AvgPoolUpdateInfershapeParam> {};

TEST_P(AvgPoolUpdateRuntimeInferShape, general_cases)
{
    AvgPoolUpdateInfershapeParam param = GetParam();
    std::cout << "run case " << param.case_name << std::endl;
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("AvgPoolUpdate")->infer_shape;

    gert::StorageShape x1Shape = {param.x1Shape, {}};
    gert::StorageShape x2Shape = {param.x2Shape, {}};
    gert::StorageShape yShape = {{}, {}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(2, 1)
                      .IrInstanceNum({1, 1})
                      .NodeInputTd(0, param.x1Dtype, FORMAT_ND, ge::Format::FORMAT_RESERVED)
                      .NodeInputTd(1, param.x1Dtype, FORMAT_ND, ge::Format::FORMAT_RESERVED)
                      .NodeOutputTd(0, param.x1Dtype, FORMAT_ND, ge::Format::FORMAT_RESERVED)
                      .InputShapes({&x1Shape, &x2Shape})
                      .OutputShapes({&yShape})
                      .Build();

    // infershape: y.shape = x1.shape, verify return success and output shape dims match x1
    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);
    ASSERT_EQ(yShape.GetStorageShape().GetDimNum(), x1Shape.GetStorageShape().GetDimNum());
    for (size_t i = 0; i < x1Shape.GetStorageShape().GetDimNum(); i++) {
        EXPECT_EQ(yShape.GetStorageShape().GetDim(i), x1Shape.GetStorageShape().GetDim(i));
    }
}

INSTANTIATE_TEST_CASE_P(
    AvgPoolUpdateInfershapeTests, AvgPoolUpdateRuntimeInferShape,
    testing::Values(AvgPoolUpdateInfershapeParam{"fp32_static_4d_nhwc", {1, 4, 4, 3}, {1, 8, 8, 3}, ge::DT_FLOAT},
                    AvgPoolUpdateInfershapeParam{"fp16_dynamic_4d", {1, -1, -1, 64}, {1, -1, -1, 64}, ge::DT_FLOAT16},
                    AvgPoolUpdateInfershapeParam{"fp32_nchw", {2, 3, 5, 5}, {2, 3, 10, 10}, ge::DT_FLOAT}));
