/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file in_training_reduce_grad.h
 * \brief INTrainingReduceGrad 算子 kernel 类定义（arch35 架构）
 *
 * 模板参数说明：
 *   - T: 数据类型（half / float），由 DTYPE_DY 编译宏注入
 *   - RANK: 编译时维度（4 或 8），由 ASCENDC_TPL_UINT_DECL 定义
 *
 * 计算公式（对齐 TBE canndev in_training_reduce_grad.py）：
 *   data_sqrt = sqrt(variance + eps)
 *   multiplier = -res_gamma / (num * data_sqrt)
 *   diff = x - mean
 *   neg_res_beta_num = -res_beta / num
 *   coef = dy + multiplier * diff + neg_res_beta_num
 *   pd_x = (coef * gamma) / data_sqrt
 *
 * dtype 升精度策略：
 *   - FP32: 原生计算，无需 Cast
 *   - FP16: FP16→FP32→FP16，输入 CAST_NONE，输出 CAST_RINT
 */

#pragma once
#include "kernel_operator.h"
#include "in_training_reduce_grad_tiling_data.h"
#include "in_training_reduce_grad_tiling_key.h"

// ---------------------------------------------------------------------------
// CoefVF: coef = dy + multiplier * diff + negResBetaNum
//   where diff = x - mean, negResBetaNum = -res_beta / num
//   Mathematically equivalent to dy + multiplier*x + addend but avoids
//   catastrophic cancellation when x ≈ mean (multiplier*x and addend cancel).
// VF chain length 3 <= 7, non-Cast, fusible
// ---------------------------------------------------------------------------
template <typename T>
__simd_vf__ inline void CoefVF(__ubuf__ T* dstAddr, __ubuf__ T* mulAddr, __ubuf__ T* xAddr, __ubuf__ T* dyAddr,
                               __ubuf__ T* addendAddr, uint32_t count, uint32_t oneRepeatSize, uint16_t repeatTimes)
{
    AscendC::Reg::RegTensor<T> mulReg, xReg, dyReg, addReg, tmpReg, dstReg;
    AscendC::Reg::MaskReg mask;
    AscendC::Reg::AddrReg aReg;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        aReg = AscendC::Reg::CreateAddrReg<T>(i, oneRepeatSize);
        uint32_t remain = count - (uint32_t)i * oneRepeatSize;
        mask = AscendC::Reg::UpdateMask<T>(remain);
        AscendC::Reg::LoadAlign(mulReg, mulAddr, aReg);
        AscendC::Reg::LoadAlign(xReg, xAddr, aReg);
        AscendC::Reg::LoadAlign(dyReg, dyAddr, aReg);
        AscendC::Reg::LoadAlign(addReg, addendAddr, aReg);
        AscendC::Reg::Mul(tmpReg, mulReg, xReg, mask);
        AscendC::Reg::Add(tmpReg, tmpReg, dyReg, mask);
        AscendC::Reg::Add(dstReg, tmpReg, addReg, mask);
        AscendC::Reg::StoreAlign(dstAddr, dstReg, aReg, mask);
    }
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------
__aicore__ inline void GetCoreRange(int64_t coreId, int64_t tilesMain, int64_t coresTail, int64_t& start, int64_t& end)
{
    if (coreId < coresTail) {
        start = coreId * (tilesMain + 1);
        end = start + tilesMain + 1;
    } else {
        start = coresTail * (tilesMain + 1) + (coreId - coresTail) * tilesMain;
        end = start + tilesMain;
    }
}

__aicore__ inline int64_t GetUBSplitRange(int64_t aOOff, int64_t aO, int64_t aI, int64_t aITail)
{
    return (aOOff == aO - 1) ? aITail : aI;
}

__aicore__ inline bool FlatToEffectiveCoord(int64_t flat, const int64_t* maxBroShape, int64_t rank, int64_t splitAxis,
                                            int64_t aI, int64_t aO, int64_t* effCoord)
{
    for (int64_t d = 0; d < rank; d++)
        effCoord[d] = 0;
    if (aO <= 0)
        return false;
    int64_t aOOff = flat % aO;
    int64_t outer = flat / aO;
    for (int64_t d = splitAxis - 1; d >= 0; d--) {
        effCoord[d] = outer % maxBroShape[d];
        outer /= maxBroShape[d];
    }
    effCoord[splitAxis] = aOOff * aI;
    return true;
}

__aicore__ inline int64_t CalcOffset(const int64_t* effCoord, const int64_t* strides, int64_t rank)
{
    int64_t offset = 0;
    for (int64_t d = 0; d < rank; d++)
        offset += effCoord[d] * strides[d];
    return offset;
}

// ===========================================================================
// class INTrainingReduceGradKernel<T, RANK>
// ===========================================================================
template <typename T, int64_t RANK>
class INTrainingReduceGradKernel {
    static constexpr int64_t ND = (RANK <= 5) ? RANK : 5;
    static constexpr bool NEED_CAST = !std::is_same_v<T, float>;
    static constexpr uint32_t VL_F32 = AscendC::GetVecLen() / sizeof(float);

    static constexpr int B0 = 0, B1 = 1, B2 = 2, B3 = 3, B4 = 4, B5 = 5;
    static constexpr int IN_DY = 0, IN_X = 1, IN_VAR = 2, IN_MEAN = 3;
    static constexpr int IN_RES_GAMMA = 4, IN_RES_BETA = 5, IN_GAMMA = 6;

    AscendC::TPipe pipe_;
    const INTrainingReduceGradTilingData<RANK>* td_;

    AscendC::GlobalTensor<T> gmDy_;
    AscendC::GlobalTensor<T> gmX_;
    AscendC::GlobalTensor<T> gmPdX_;
    AscendC::GlobalTensor<float> gmVar_;
    AscendC::GlobalTensor<float> gmMean_;
    AscendC::GlobalTensor<float> gmResGamma_;
    AscendC::GlobalTensor<float> gmResBeta_;
    AscendC::GlobalTensor<float> gmGamma_;

    AscendC::TBuf<AscendC::TPosition::VECCALC> buf_[PHYS_NODES];

    // Two NDDMA param sets: one for T-typed (dy/x), one for float-typed (aux inputs)
    AscendC::MultiCopyParams<T, ND> nddmaParamsT_[2];     // dy, x
    AscendC::MultiCopyParams<float, ND> nddmaParamsF_[5]; // variance, mean, res_gamma, res_beta, gamma
    int64_t nddmaOuterIters_[MAX_INPUT_SLOTS];
    int64_t nddmaDims_;

public:
    __aicore__ inline void Init(GM_ADDR inputs[MAX_INPUT_SLOTS], GM_ADDR outputs[MAX_OUTPUT_SLOTS],
                                const INTrainingReduceGradTilingData<RANK>* td)
    {
        td_ = td;

        gmDy_.SetGlobalBuffer((__gm__ T*)inputs[IN_DY]);
        gmX_.SetGlobalBuffer((__gm__ T*)inputs[IN_X]);
        gmVar_.SetGlobalBuffer((__gm__ float*)inputs[IN_VAR]);
        gmMean_.SetGlobalBuffer((__gm__ float*)inputs[IN_MEAN]);
        gmResGamma_.SetGlobalBuffer((__gm__ float*)inputs[IN_RES_GAMMA]);
        gmResBeta_.SetGlobalBuffer((__gm__ float*)inputs[IN_RES_BETA]);
        gmGamma_.SetGlobalBuffer((__gm__ float*)inputs[IN_GAMMA]);
        gmPdX_.SetGlobalBuffer((__gm__ T*)outputs[0]);

        for (int i = 0; i < PHYS_NODES; i++)
            pipe_.InitBuffer(buf_[i], td_->perBufBytes);

        const int64_t* dstShape = td_->maxBroShape;
        int64_t k = td_->split.axis;
        nddmaDims_ = (RANK - k <= ND) ? (RANK - k) : ND;

        // Precompute NDDMA params for T-typed inputs (dy=0, x=1)
        for (int inp = 0; inp < 2; inp++) {
            int64_t inner = 1;
            int64_t nd = 0;
            for (int64_t d = RANK - 1; d >= k && nd < ND; d--) {
                nddmaParamsT_[inp].loopInfo.loopSize[nd] = (d == k) ? 0 : dstShape[d];
                nddmaParamsT_[inp].loopInfo.loopSrcStride[nd] = td_->inputStrides[inp][d];
                nddmaParamsT_[inp].loopInfo.loopDstStride[nd] = inner;
                nddmaParamsT_[inp].loopInfo.loopLpSize[nd] = 0;
                nddmaParamsT_[inp].loopInfo.loopRpSize[nd] = 0;
                inner *= (d == k) ? td_->split.aI : dstShape[d];
                nd++;
            }
            for (; nd < ND; nd++) {
                nddmaParamsT_[inp].loopInfo.loopSize[nd] = 1;
                nddmaParamsT_[inp].loopInfo.loopSrcStride[nd] = 0;
                nddmaParamsT_[inp].loopInfo.loopDstStride[nd] = inner;
                nddmaParamsT_[inp].loopInfo.loopLpSize[nd] = 0;
                nddmaParamsT_[inp].loopInfo.loopRpSize[nd] = 0;
            }
            nddmaOuterIters_[inp] = 1;
            for (int64_t d = k; d < RANK - nddmaDims_; d++)
                nddmaOuterIters_[inp] *= (d == k) ? td_->split.aI : dstShape[d];
        }

        // Precompute NDDMA params for float-typed inputs (variance=2..gamma=6)
        for (int inp = 2; inp < MAX_INPUT_SLOTS; inp++) {
            int64_t inner = 1;
            int64_t nd = 0;
            for (int64_t d = RANK - 1; d >= k && nd < ND; d--) {
                nddmaParamsF_[inp - 2].loopInfo.loopSize[nd] = (d == k) ? 0 : dstShape[d];
                nddmaParamsF_[inp - 2].loopInfo.loopSrcStride[nd] = td_->inputStrides[inp][d];
                nddmaParamsF_[inp - 2].loopInfo.loopDstStride[nd] = inner;
                nddmaParamsF_[inp - 2].loopInfo.loopLpSize[nd] = 0;
                nddmaParamsF_[inp - 2].loopInfo.loopRpSize[nd] = 0;
                inner *= (d == k) ? td_->split.aI : dstShape[d];
                nd++;
            }
            for (; nd < ND; nd++) {
                nddmaParamsF_[inp - 2].loopInfo.loopSize[nd] = 1;
                nddmaParamsF_[inp - 2].loopInfo.loopSrcStride[nd] = 0;
                nddmaParamsF_[inp - 2].loopInfo.loopDstStride[nd] = inner;
                nddmaParamsF_[inp - 2].loopInfo.loopLpSize[nd] = 0;
                nddmaParamsF_[inp - 2].loopInfo.loopRpSize[nd] = 0;
            }
            nddmaOuterIters_[inp] = 1;
            for (int64_t d = k; d < RANK - nddmaDims_; d++)
                nddmaOuterIters_[inp] *= (d == k) ? td_->split.aI : dstShape[d];
        }
    }

    __aicore__ inline void Process()
    {
        int32_t evMTE2toV = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::MTE2_V));
        int32_t evVtoMTE2 = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::V_MTE2));
        int32_t evVtoMTE3 = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::V_MTE3));
        int32_t evMTE3toMTE2 = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::MTE3_MTE2));

        int64_t start, end;
        GetCoreRange(AscendC::GetBlockIdx(), td_->multicore.tilesMain, td_->multicore.coresTail, start, end);

        int64_t innerCount = 1;
        for (int64_t d = td_->split.axis + 1; d < RANK; d++)
            innerCount *= td_->maxBroShape[d];

        int64_t coord[8] = {};
        float eps = 1e-6f;
        float negOne = -1.0f;
        float numRec = 1.0f / static_cast<float>(td_->numElements);
        float negNumRec = -1.0f / static_cast<float>(td_->numElements);

        for (int64_t flat = start; flat < end; flat++) {
            int64_t aISeg = GetUBSplitRange(flat % td_->split.aO, td_->split.aO, td_->split.aI, td_->split.aITail);
            int64_t count = aISeg * innerCount;
            FlatToEffectiveCoord(flat, td_->maxBroShape, RANK, td_->split.axis, td_->split.aI, td_->split.aO, coord);

            if (flat != start)
                AscendC::WaitFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);

            // ===== Phase A: Scalar computation per channel =====

            // S1: variance -> B0, data_sqrt = sqrt(variance + eps)
            CopyInBrc(coord, IN_VAR, B0, aISeg);
            AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::Adds(buf_[B0].Get<float>(), buf_[B0].Get<float>(), eps, count);
            AscendC::Sqrt(buf_[B0].Get<float>(), buf_[B0].Get<float>(), count);

            // S2: res_gamma -> B5 (temp), scale_inv = res_gamma / num -> B2
            CopyInBrc(coord, IN_RES_GAMMA, B5, aISeg);
            AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::Muls(buf_[B2].Get<float>(), buf_[B5].Get<float>(), numRec, count);

            // S3: multiplier = -scale_inv / data_sqrt -> B1
            AscendC::Div(buf_[B1].Get<float>(), buf_[B2].Get<float>(), buf_[B0].Get<float>(), count);
            AscendC::Muls(buf_[B1].Get<float>(), buf_[B1].Get<float>(), negOne, count);
            AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

            // S4: mean -> B3 (KEEP for coef: diff = x - mean)
            CopyInBrc(coord, IN_MEAN, B3, aISeg);
            AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);

            // S5: res_beta -> B5, neg_res_beta_num = -res_beta / num -> B4
            CopyInBrc(coord, IN_RES_BETA, B5, aISeg);
            AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::Muls(buf_[B4].Get<float>(), buf_[B5].Get<float>(), negNumRec, count);

            // S6: gamma -> B5 (reuse), save to B2 (overwrite scale_inv)
            AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            CopyInBrc(coord, IN_GAMMA, B5, aISeg);
            AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::Copy(buf_[B2].Get<float>(), buf_[B5].Get<float>(), count);
            AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

            // ===== Phase B: Full-size inputs + coef =====

            // S10: x -> B0 (fp32 direct or fp16 via B5 temp then Cast)
            if constexpr (NEED_CAST) {
                CopyInBrc(coord, IN_X, B5, aISeg);
                AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
                AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
                AscendC::Cast(buf_[B0].Get<float>(), buf_[B5].Get<T>(), AscendC::RoundMode::CAST_NONE, count);
            } else {
                CopyInBrc(coord, IN_X, B0, aISeg);
                AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
                AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            }

            // S10b: diff = x - mean -> B0 (B3=mean consumed, B3 now free)
            AscendC::Sub(buf_[B0].Get<float>(), buf_[B0].Get<float>(), buf_[B3].Get<float>(), count);

            // S11: dy -> B3 (fp32 direct or fp16 via B5 temp then Cast)
            AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            if constexpr (NEED_CAST) {
                CopyInBrc(coord, IN_DY, B5, aISeg);
                AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
                AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
                AscendC::Cast(buf_[B3].Get<float>(), buf_[B5].Get<T>(), AscendC::RoundMode::CAST_NONE, count);
            } else {
                CopyInBrc(coord, IN_DY, B3, aISeg);
                AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
                AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            }

            // S12: coef = dy + multiplier * diff + neg_res_beta_num -> B5 (VF)
            //     CoefVF computes: dst = dy + mul * diff + negResBetaNum
            //     diff = x - mean avoids catastrophic cancellation when x ≈ mean
            uint16_t rep12 = AscendC::CeilDivision(count, VL_F32);
            asc_vf_call<CoefVF<float>>((__ubuf__ float*)buf_[B5].Get<float>().GetPhyAddr(),
                                       (__ubuf__ float*)buf_[B1].Get<float>().GetPhyAddr(),
                                       (__ubuf__ float*)buf_[B0].Get<float>().GetPhyAddr(),
                                       (__ubuf__ float*)buf_[B3].Get<float>().GetPhyAddr(),
                                       (__ubuf__ float*)buf_[B4].Get<float>().GetPhyAddr(), count, VL_F32, rep12);

            // ===== Phase C: pd_x = coef * gamma / data_sqrt + CopyOut =====

            // S13a: pd_x = coef * gamma -> B0 (V: B0 = B5 * B2)
            AscendC::Mul(buf_[B0].Get<float>(), buf_[B5].Get<float>(), buf_[B2].Get<float>(), count);

            // S13b: Reload variance -> B3 (MTE2)
            AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
            CopyInBrc(coord, IN_VAR, B3, aISeg);
            AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);

            // S13c: data_sqrt = sqrt(variance + eps) -> B3
            AscendC::Adds(buf_[B3].Get<float>(), buf_[B3].Get<float>(), eps, count);
            AscendC::Sqrt(buf_[B3].Get<float>(), buf_[B3].Get<float>(), count);

            // S13d: pd_x = pd_x / data_sqrt -> B0
            AscendC::Div(buf_[B0].Get<float>(), buf_[B0].Get<float>(), buf_[B3].Get<float>(), count);

            if constexpr (NEED_CAST) {
                AscendC::Cast(buf_[B0].Get<T>(), buf_[B0].Get<float>(), AscendC::RoundMode::CAST_RINT, count);
            }

            // S14: CopyOut
            AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
            CopyOutFrom(buf_[B0].template Get<T>(), coord, aISeg);

            if (flat != end - 1)
                AscendC::SetFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);
        }
    }

private:
    __aicore__ inline void CopyInBrc(const int64_t* coord, int inputIdx, int slot, int64_t aISeg)
    {
        int64_t k = td_->split.axis;
        int64_t off = CalcOffset(coord, td_->inputStrides[inputIdx], RANK);

        static constexpr AscendC::NdDmaConfig cfg = {false, AscendC::NdDmaConfig::unsetPad,
                                                     AscendC::NdDmaConfig::unsetPad, false};

        if constexpr (RANK <= 5) {
            if (inputIdx <= 1) {
                // T-typed inputs (dy, x)
                auto params = nddmaParamsT_[inputIdx];
                int64_t kNd = RANK - 1 - k;
                int64_t inner = 1;
                for (int64_t nd = 0; nd < ND; nd++) {
                    if (nd == kNd)
                        params.loopInfo.loopSize[nd] = aISeg;
                    params.loopInfo.loopDstStride[nd] = inner;
                    inner *= params.loopInfo.loopSize[nd];
                }
                if (inputIdx == IN_DY) {
                    AscendC::DataCopy<T, ND, cfg>(buf_[slot].template Get<T>(), gmDy_[off], params);
                } else {
                    AscendC::DataCopy<T, ND, cfg>(buf_[slot].template Get<T>(), gmX_[off], params);
                }
            } else {
                // float-typed inputs (variance, mean, res_gamma, res_beta, gamma)
                auto params = nddmaParamsF_[inputIdx - 2];
                int64_t kNd = RANK - 1 - k;
                int64_t inner = 1;
                for (int64_t nd = 0; nd < ND; nd++) {
                    if (nd == kNd)
                        params.loopInfo.loopSize[nd] = aISeg;
                    params.loopInfo.loopDstStride[nd] = inner;
                    inner *= params.loopInfo.loopSize[nd];
                }
                switch (inputIdx) {
                    case IN_VAR:
                        AscendC::DataCopy<float, ND, cfg>(buf_[slot].template Get<float>(), gmVar_[off], params);
                        break;
                    case IN_MEAN:
                        AscendC::DataCopy<float, ND, cfg>(buf_[slot].template Get<float>(), gmMean_[off], params);
                        break;
                    case IN_RES_GAMMA:
                        AscendC::DataCopy<float, ND, cfg>(buf_[slot].template Get<float>(), gmResGamma_[off], params);
                        break;
                    case IN_RES_BETA:
                        AscendC::DataCopy<float, ND, cfg>(buf_[slot].template Get<float>(), gmResBeta_[off], params);
                        break;
                    case IN_GAMMA:
                        AscendC::DataCopy<float, ND, cfg>(buf_[slot].template Get<float>(), gmGamma_[off], params);
                        break;
                    default:
                        break;
                }
            }
        } else {
            // RANK > 5: outer loop for dimensions beyond NDDMA limit
            if (inputIdx <= 1) {
                auto params = nddmaParamsT_[inputIdx];
                int64_t kNd = RANK - 1 - k;
                int64_t inner = 1;
                for (int64_t nd = 0; nd < ND; nd++) {
                    if (nd == kNd)
                        params.loopInfo.loopSize[nd] = aISeg;
                    params.loopInfo.loopDstStride[nd] = inner;
                    inner *= params.loopInfo.loopSize[nd];
                }
                AscendC::LocalTensor<T> buf = buf_[slot].template Get<T>();
                int64_t elemBase = off;
                for (int64_t oi = 0; oi < nddmaOuterIters_[inputIdx]; oi++) {
                    int64_t elemAdj = 0, tmp = oi;
                    for (int64_t d = RANK - nddmaDims_ - 1; d >= k; d--) {
                        int64_t sz = (d == k) ? aISeg : td_->maxBroShape[d];
                        elemAdj += (tmp % sz) * td_->inputStrides[inputIdx][d];
                        tmp /= sz;
                    }
                    if (inputIdx == IN_DY) {
                        AscendC::DataCopy<T, ND, cfg>(buf[oi * inner], gmDy_[elemBase + elemAdj], params);
                    } else {
                        AscendC::DataCopy<T, ND, cfg>(buf[oi * inner], gmX_[elemBase + elemAdj], params);
                    }
                }
            } else {
                auto params = nddmaParamsF_[inputIdx - 2];
                int64_t kNd = RANK - 1 - k;
                int64_t inner = 1;
                for (int64_t nd = 0; nd < ND; nd++) {
                    if (nd == kNd)
                        params.loopInfo.loopSize[nd] = aISeg;
                    params.loopInfo.loopDstStride[nd] = inner;
                    inner *= params.loopInfo.loopSize[nd];
                }
                AscendC::LocalTensor<float> buf = buf_[slot].template Get<float>();
                int64_t elemBase = off;
                for (int64_t oi = 0; oi < nddmaOuterIters_[inputIdx]; oi++) {
                    int64_t elemAdj = 0, tmp = oi;
                    for (int64_t d = RANK - nddmaDims_ - 1; d >= k; d--) {
                        int64_t sz = (d == k) ? aISeg : td_->maxBroShape[d];
                        elemAdj += (tmp % sz) * td_->inputStrides[inputIdx][d];
                        tmp /= sz;
                    }
                    switch (inputIdx) {
                        case IN_VAR:
                            AscendC::DataCopy<float, ND, cfg>(buf[oi * inner], gmVar_[elemBase + elemAdj], params);
                            break;
                        case IN_MEAN:
                            AscendC::DataCopy<float, ND, cfg>(buf[oi * inner], gmMean_[elemBase + elemAdj], params);
                            break;
                        case IN_RES_GAMMA:
                            AscendC::DataCopy<float, ND, cfg>(buf[oi * inner], gmResGamma_[elemBase + elemAdj], params);
                            break;
                        case IN_RES_BETA:
                            AscendC::DataCopy<float, ND, cfg>(buf[oi * inner], gmResBeta_[elemBase + elemAdj], params);
                            break;
                        case IN_GAMMA:
                            AscendC::DataCopy<float, ND, cfg>(buf[oi * inner], gmGamma_[elemBase + elemAdj], params);
                            break;
                        default:
                            break;
                    }
                }
            }
        }
    }

    __aicore__ inline void CopyOutFrom(AscendC::LocalTensor<T> srcBuf, const int64_t* coord, int64_t aISeg)
    {
        int64_t off = CalcOffset(coord, td_->outputStrides[0], RANK);
        int64_t splitElems = aISeg;
        int64_t innerElems = 1;
        for (int64_t d = td_->split.axis + 1; d < RANK; d++)
            innerElems *= td_->outputShapes[0][d];
        int64_t cnt = splitElems * innerElems;

        AscendC::DataCopyExtParams extParams;
        extParams.blockCount = 1;
        extParams.blockLen = cnt * sizeof(T);
        extParams.srcStride = 0;
        extParams.dstStride = 0;
        AscendC::DataCopyPad(gmPdX_[off], srcBuf, extParams);
    }
};
