/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "arch35/npu_alloc_float_status.h"

enum class NPUAllocFloatStatusTilingKey : uint32_t {
    TILING_KEY_ALLOC = 0,
};

template <uint32_t schMode>
__global__ __aicore__ void npu_alloc_float_status(GM_ADDR data, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(NPUAllocFloatStatusTilingData);
    GET_TILING_DATA_WITH_STRUCT(NPUAllocFloatStatusTilingData, tilingData, tiling);
    (void)tilingData;
    if constexpr (schMode == static_cast<uint32_t>(NPUAllocFloatStatusTilingKey::TILING_KEY_ALLOC)) {
        NsNPUAllocFloatStatus::Process<DTYPE_DATA>(data);
    }
}
