/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file add_row_ranges_tiling_data.h
 * \brief Tiling data struct for add_row_ranges operator
 *
 * 字段定义：
 *   - totalElements: M×N，输出元素总数（Grid-Stride 遍历上限）
 *   - N: 矩阵列数（用于坐标分解 r = idx / N, c = idx % N）
 *   - K: src 矩阵行数（用于 kernel 中裁剪 indices 范围到 [0, K]，对齐 numpy 切片行为）
 * 不包含 threadNum/magic/shift（VF 线程数是编译期常量，快除参数在 kernel Process 中预计算）
 *
 * ⚠️ TTK 修复（v1）：新增 K 字段，用于 kernel 中裁剪 end = min(end, K)，
 *    修复 indices 越界导致 kernel 读取 src 缓冲区外内存的精度问题。
 *    MDE 文档 §3.1 已同步更新。
 */

#ifndef ADD_ROW_RANGES_TILING_DATA_H_
#define ADD_ROW_RANGES_TILING_DATA_H_

struct AddRowRangesTilingData {
    int64_t totalElements = 0; // M × N，输出元素总数
    int32_t N = 0;             // 矩阵列数（坐标分解用）
    int32_t K = 0;             // src 矩阵行数（indices 范围裁剪用）
};

#endif // ADD_ROW_RANGES_TILING_DATA_H_
