/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef BN_INFERENCE_TILING_KEY_H
#define BN_INFERENCE_TILING_KEY_H

#include <cstdint>

#define BN_INFERENCE_KEY_EMPTY 1000
#define BN_INFERENCE_KEY_CF_GENERIC_0 2000
#define BN_INFERENCE_KEY_CF_GENERIC_1 2001
#define BN_INFERENCE_KEY_CF_GENERIC_2 2002
#define BN_INFERENCE_KEY_CF_GENERIC_3 2003
#define BN_INFERENCE_KEY_CF_PACKED_0 2100
#define BN_INFERENCE_KEY_CF_PACKED_1 2101
#define BN_INFERENCE_KEY_CF_PACKED_2 2102
#define BN_INFERENCE_KEY_CF_PACKED_3 2103
#define BN_INFERENCE_KEY_CL_GENERIC_0 3000
#define BN_INFERENCE_KEY_CL_GENERIC_1 3001
#define BN_INFERENCE_KEY_CL_GENERIC_2 3002
#define BN_INFERENCE_KEY_CL_GENERIC_3 3003
#define BN_INFERENCE_KEY_CL_PACKED_0 3100
#define BN_INFERENCE_KEY_CL_PACKED_1 3101
#define BN_INFERENCE_KEY_CL_PACKED_2 3102
#define BN_INFERENCE_KEY_CL_PACKED_3 3103
#define BN_INFERENCE_KEY_CF_GENERIC_PRE_FOLDED_0 4000
#define BN_INFERENCE_KEY_CF_GENERIC_PRE_FOLDED_1 4001
#define BN_INFERENCE_KEY_CF_GENERIC_PRE_FOLDED_3 4003
#define BN_INFERENCE_KEY_CF_PACKED_PRE_FOLDED_0 4100
#define BN_INFERENCE_KEY_CF_PACKED_PRE_FOLDED_1 4101
#define BN_INFERENCE_KEY_CF_PACKED_PRE_FOLDED_3 4103
#define BN_INFERENCE_KEY_CL_GENERIC_PRE_FOLDED_0 5000
#define BN_INFERENCE_KEY_CL_GENERIC_PRE_FOLDED_1 5001
#define BN_INFERENCE_KEY_CL_GENERIC_PRE_FOLDED_3 5003
#define BN_INFERENCE_KEY_CL_PACKED_PRE_FOLDED_0 5100
#define BN_INFERENCE_KEY_CL_PACKED_PRE_FOLDED_1 5101
#define BN_INFERENCE_KEY_CL_PACKED_PRE_FOLDED_3 5103

namespace BNInferenceKey {
constexpr uint64_t EMPTY = BN_INFERENCE_KEY_EMPTY;
constexpr uint64_t CF_GENERIC_BASE = BN_INFERENCE_KEY_CF_GENERIC_0;
constexpr uint64_t CF_PACKED_BASE = BN_INFERENCE_KEY_CF_PACKED_0;
constexpr uint64_t CL_GENERIC_BASE = BN_INFERENCE_KEY_CL_GENERIC_0;
constexpr uint64_t CL_PACKED_BASE = BN_INFERENCE_KEY_CL_PACKED_0;
constexpr uint64_t CF_GENERIC_PRE_FOLDED_BASE = BN_INFERENCE_KEY_CF_GENERIC_PRE_FOLDED_0;
constexpr uint64_t CF_PACKED_PRE_FOLDED_BASE = BN_INFERENCE_KEY_CF_PACKED_PRE_FOLDED_0;
constexpr uint64_t CL_GENERIC_PRE_FOLDED_BASE = BN_INFERENCE_KEY_CL_GENERIC_PRE_FOLDED_0;
constexpr uint64_t CL_PACKED_PRE_FOLDED_BASE = BN_INFERENCE_KEY_CL_PACKED_PRE_FOLDED_0;

constexpr uint64_t OptionalMask(bool hasScale, bool hasOffset) { return (hasScale ? 1U : 0U) + (hasOffset ? 2U : 0U); }
} // namespace BNInferenceKey

#endif // BN_INFERENCE_TILING_KEY_H
