/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot - Iter1 */

/*!
 * \file bn_infer_grad_tiling_data.h
 * \brief BNInferGrad TilingData 结构体（arch35 架构，按 rank 模板化）
 *
 * 迭代一：TilingKey_RANK4 + float32 路径
 *
 * 结构对齐 Broadcast 范式参考算子 adam_apply_one_assign：
 *   - split/multicore 由 Host 侧 FindSplitAxis / MultiCoreSplit 填充
 *   - max_bro_shape / input_shapes / input_strides / output_* 为 NDDMA 坐标系
 *   - epsilon_value 为算子特有标量（来自 OpDef Attr）
 */

#ifndef BN_INFER_GRAD_TILING_DATA_H_
#define BN_INFER_GRAD_TILING_DATA_H_

#include <cstdint>

// === 算子特定常量 ===
// grads, scale, batch_variance 三个 GM 输入（epsilon 为 Attr 标量，不占 GM slot）
constexpr int64_t kMaxInputSlots = 3;  // 本算子最大输入张量数
constexpr int64_t kMaxOutputSlots = 1; // 本算子最大输出张量数
constexpr int64_t kPhysNodes = 5;      // 物理存活节点 P（= TBuf 槽位数，float32 路径）

struct SplitResult {
    int64_t axis;     // UB 切分轴
    int64_t a_i;      // 内轴 tile 大小（元素数）
    int64_t a_o;      // 外轴 tile 数
    int64_t a_i_tail; // 末块大小（元素数）
};

struct MultiCoreResult {
    int64_t num_cores;   // 参与计算的核数
    int64_t total_tiles; // tile 总数
    int64_t tiles_main;  // 每核主 tile 数
    int64_t cores_tail;  // 多处理一个 tile 的核数
};

template <int64_t kRank>
struct BNInferGradTilingData {
    SplitResult split;                              // UB 切分结果（来源：FindSplitAxis）
    MultiCoreResult multicore;                      // 多核切分结果（来源：MultiCoreSplit）
    int64_t rank;                                   // 实际有效 rank（去 1 补 1 后）
    int64_t per_buf_bytes;                          // 单 buffer 字节数 = (UB/P) & ~31
    int64_t max_bro_shape[kRank];                   // 广播后各维大小（坐标系）
    int64_t num_inputs;                             // 输入张量数（3）
    int64_t num_outputs;                            // 输出张量数（1）
    int64_t input_shapes[kMaxInputSlots][kRank];    // 各输入补 1 后的 shape
    int64_t input_strides[kMaxInputSlots][kRank];   // 各输入的 GM stride（broadcast 轴 = 0）
    int64_t output_shapes[kMaxOutputSlots][kRank];  // 各输出补 1 后的 shape
    int64_t output_strides[kMaxOutputSlots][kRank]; // 各输出的 GM stride
    float epsilon_value;                            // epsilon 标量值（来自 OpDef Attr）
};

#endif // BN_INFER_GRAD_TILING_DATA_H_
