/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#pragma once
#include <cstdint>
#include <vector>
#include <string>
#include "register/op_def_registry.h"
#include "tiling/tiling_api.h"
#include "optim/apply_adam_v2/op_kernel/arch35/apply_adam_v2_tiling_data.h"

namespace optiling {

struct ApplyAdamV2CompileInfo {
    uint64_t ubSize = 0;
    uint64_t coreNum = 0;
    int64_t adamModeFlag = 0;
};

class ApplyAdamV2Tiling {
public:
    explicit ApplyAdamV2Tiling(gert::TilingContext* ctx);
    ge::graphStatus RunTiling();
    void SetCompileInfo(uint64_t coreNum, uint64_t ubSize, int64_t adamModeFlag);

private:
    ge::graphStatus GetShapeInfo();
    template <int64_t R>
    ge::graphStatus DoTilingAndSet();

    gert::TilingContext* ctx_;
    std::vector<std::vector<int64_t>> raw_input_shapes_;
    std::vector<std::vector<int64_t>> raw_output_shapes_;
    std::vector<int64_t> max_bro_shape_;
    std::vector<std::vector<int64_t>> normal_input_shapes_;
    std::vector<std::vector<int64_t>> normal_output_shapes_;
    int64_t dtype_size_ = 0;
    int64_t rank_ = 0;
    int64_t adam_mode_flag_ = 0;     // 0=adam, 1=mbart_adam
    float clip_coeff_ = 1.0f;        // host-precomputed gradient clipping coefficient
    bool has_max_grad_norm_ = false; // whether max_grad_norm optional input is provided
    bool has_step_size_ = false;     // whether step_size optional input is provided
    uint64_t core_num_ = 0;
    uint64_t ub_size_ = 0;
};

} // namespace optiling
