/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#ifndef SIGMOID_FOCAL_LOSS_STRUCT_H_
#define SIGMOID_FOCAL_LOSS_STRUCT_H_

#include <cstdint>
#include "ascendc/host_api/tiling/template_argument.h"

#define SIGMOID_FOCAL_LOSS_REDUCE_NORMAL 0
#define SIGMOID_FOCAL_LOSS_REDUCE_GROUP 1
#define SIGMOID_FOCAL_LOSS_ELEWISE 2

ASCENDC_TPL_ARGS_DECL(SigmoidFocalLoss, ASCENDC_TPL_BOOL_DECL(isEmptyTensor, 0, 1),
                      ASCENDC_TPL_UINT_DECL(kernelMode, 2, ASCENDC_TPL_UI_LIST, SIGMOID_FOCAL_LOSS_ELEWISE,
                                            SIGMOID_FOCAL_LOSS_REDUCE_NORMAL, SIGMOID_FOCAL_LOSS_REDUCE_GROUP), );

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 0),
                         ASCENDC_TPL_UINT_SEL(kernelMode, ASCENDC_TPL_UI_LIST, SIGMOID_FOCAL_LOSS_ELEWISE)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 1),
                         ASCENDC_TPL_UINT_SEL(kernelMode, ASCENDC_TPL_UI_LIST, SIGMOID_FOCAL_LOSS_ELEWISE)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 0),
                         ASCENDC_TPL_UINT_SEL(kernelMode, ASCENDC_TPL_UI_LIST, SIGMOID_FOCAL_LOSS_REDUCE_NORMAL)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 1),
                         ASCENDC_TPL_UINT_SEL(kernelMode, ASCENDC_TPL_UI_LIST, SIGMOID_FOCAL_LOSS_REDUCE_NORMAL)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(isEmptyTensor, 0),
                         ASCENDC_TPL_UINT_SEL(kernelMode, ASCENDC_TPL_UI_LIST, SIGMOID_FOCAL_LOSS_REDUCE_GROUP)), );

#endif // SIGMOID_FOCAL_LOSS_STRUCT_H_
