/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef KTH_VALUE_TILING_KEY_H
#define KTH_VALUE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define KTH_VALUE_SCHID_MERGE_SORT 0
#define KTH_VALUE_SCHID_RADIX_ONE_CORE 1
#define KTH_VALUE_SCHID_RADIX_MORE_CORE 2
#define KTH_VALUE_SCHID_MERGE_MORE_CORE 3
#define KTH_VALUE_SCHID_MERGE_INTRA_CORE 4
#define KTH_VALUE_SCHID_SMALL_AXIS_INSERTION 5
#define KTH_VALUE_SCHID_SMALL_AXIS_TWO_STAGE 6
#define KTH_VALUE_SCHID_SORT32_SMALL_AXIS 8
#define KTH_VALUE_SCHID_AXIS_ONE_COPY 7
#define KTH_VALUE_SCHID_NON_LAST_SMALL_AXIS 9
#define KTH_VALUE_SCHID_NON_LAST_SMALL_AXIS_RADIX 10
#define KTH_VALUE_SCHID_RADIX_SELECT 11
#define KTH_VALUE_SCHID_SMALL_AXIS_SHORT_RANK_SELECT 12

#define KTH_VALUE_TPL_KEY_DECL()                                                                          \
    ASCENDC_TPL_UINT_DECL(schId, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_MERGE_SORT,       \
                          KTH_VALUE_SCHID_RADIX_ONE_CORE, KTH_VALUE_SCHID_RADIX_MORE_CORE,                \
                          KTH_VALUE_SCHID_MERGE_MORE_CORE, KTH_VALUE_SCHID_MERGE_INTRA_CORE,              \
                          KTH_VALUE_SCHID_SMALL_AXIS_INSERTION, KTH_VALUE_SCHID_SMALL_AXIS_TWO_STAGE,     \
                          KTH_VALUE_SCHID_AXIS_ONE_COPY, KTH_VALUE_SCHID_SORT32_SMALL_AXIS,               \
                          KTH_VALUE_SCHID_NON_LAST_SMALL_AXIS, KTH_VALUE_SCHID_NON_LAST_SMALL_AXIS_RADIX, \
                          KTH_VALUE_SCHID_RADIX_SELECT, KTH_VALUE_SCHID_SMALL_AXIS_SHORT_RANK_SELECT),    \
        ASCENDC_TPL_UINT_DECL(isInt32, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST, 0, 1)

#define KTH_VALUE_TPL_MERGE_SORT_KEY_SEL()                                                                           \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_MERGE_SORT, KTH_VALUE_SCHID_SORT32_SMALL_AXIS), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_RADIX_ONE_CORE_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_RADIX_ONE_CORE), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_RADIX_MORE_CORE_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_RADIX_MORE_CORE), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 0, 1)

#define KTH_VALUE_TPL_MERGE_MORE_CORE_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_MERGE_MORE_CORE), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_MERGE_INTRA_CORE_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_MERGE_INTRA_CORE), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_AXIS_ONE_COPY_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_AXIS_ONE_COPY), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_SMALL_AXIS_INSERTION_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_SMALL_AXIS_INSERTION), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_SMALL_AXIS_TWO_STAGE_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_SMALL_AXIS_TWO_STAGE), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_NON_LAST_SMALL_AXIS_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_NON_LAST_SMALL_AXIS), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_NON_LAST_SMALL_AXIS_RADIX_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_NON_LAST_SMALL_AXIS_RADIX), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_RADIX_SELECT_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_RADIX_SELECT), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_SMALL_AXIS_SHORT_RANK_SELECT_KEY_SEL()                                        \
    ASCENDC_TPL_UINT_SEL(schId, ASCENDC_TPL_UI_LIST, KTH_VALUE_SCHID_SMALL_AXIS_SHORT_RANK_SELECT), \
        ASCENDC_TPL_UINT_SEL(isInt32, ASCENDC_TPL_UI_LIST, 1)

#define KTH_VALUE_TPL_ALL_KEY_SEL()                                              \
    ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_MERGE_SORT_KEY_SEL()),                    \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_RADIX_ONE_CORE_KEY_SEL()),            \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_RADIX_MORE_CORE_KEY_SEL()),           \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_MERGE_MORE_CORE_KEY_SEL()),           \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_MERGE_INTRA_CORE_KEY_SEL()),          \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_SMALL_AXIS_INSERTION_KEY_SEL()),      \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_SMALL_AXIS_TWO_STAGE_KEY_SEL()),      \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_AXIS_ONE_COPY_KEY_SEL()),             \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_NON_LAST_SMALL_AXIS_KEY_SEL()),       \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_NON_LAST_SMALL_AXIS_RADIX_KEY_SEL()), \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_RADIX_SELECT_KEY_SEL()),              \
        ASCENDC_TPL_ARGS_SEL(KTH_VALUE_TPL_SMALL_AXIS_SHORT_RANK_SELECT_KEY_SEL())

ASCENDC_TPL_ARGS_DECL(KthValue, KTH_VALUE_TPL_KEY_DECL());

ASCENDC_TPL_SEL(KTH_VALUE_TPL_ALL_KEY_SEL());

#endif
