/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_apply_keras_momentum_graph_infer.cpp
 * \brief InplaceApplyKerasMomentum graph dtype inference
 */

#include "register/op_impl_registry.h"

namespace ops {
using namespace ge;

static constexpr size_t VAR_INDEX = 0;
static constexpr size_t ACCUM_INDEX = 1;

static graphStatus InferDataType4InplaceApplyKerasMomentum(gert::InferDataTypeContext* context)
{
    context->SetOutputDataType(VAR_INDEX, context->GetInputDataType(VAR_INDEX));
    context->SetOutputDataType(ACCUM_INDEX, context->GetInputDataType(ACCUM_INDEX));
    return GRAPH_SUCCESS;
}

IMPL_OP(InplaceApplyKerasMomentum).InferDataType(InferDataType4InplaceApplyKerasMomentum);

} // namespace ops
