/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_apply_ftrl_v2_graph_infer.cpp
 * \brief InplaceApplyFtrlV2 Graph InferDataType 实现
 */

#include "register/op_impl_registry.h"

using namespace ge;

namespace ops {

constexpr size_t INPUT_INDEX_VAR = 0;
constexpr size_t OUTPUT_INDEX_VAR = 0;
constexpr size_t OUTPUT_INDEX_ACCUM = 1;
constexpr size_t OUTPUT_INDEX_LINEAR = 2;

static ge::graphStatus InferDataTypeForInplaceApplyFtrlV2(gert::InferDataTypeContext* context)
{
    const ge::DataType inDtype = context->GetInputDataType(INPUT_INDEX_VAR);
    context->SetOutputDataType(OUTPUT_INDEX_VAR, inDtype);
    context->SetOutputDataType(OUTPUT_INDEX_ACCUM, inDtype);
    context->SetOutputDataType(OUTPUT_INDEX_LINEAR, inDtype);
    return ge::GRAPH_SUCCESS;
}

IMPL_OP(InplaceApplyFtrlV2).InferDataType(InferDataTypeForInplaceApplyFtrlV2);
} // namespace ops
