/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file npu_get_float_status_apt.cpp
 * \brief Kernel entry for npu_get_float_status operator
 *
 * Single template parameter schMode (always NPU_GET_FLOAT_STATUS_TPL_DEFAULT=0).
 * Dispatches to NsNPUGetFloatStatus::Process<float>() which zeroes the output.
 * Ascend 950 empty implementation: overflow detection is not yet supported,
 * so get_overflow_status() is not called and input addr is left untouched.
 */

#include "arch35/npu_get_float_status_simt.h"

template <uint32_t schMode>
__global__ __aicore__ void npu_get_float_status(GM_ADDR addr, GM_ADDR data, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(NPUGetFloatStatusTilingData);
    GET_TILING_DATA_WITH_STRUCT(NPUGetFloatStatusTilingData, tilingData, tiling);

    // TilingData is empty; directly call Process.
    // schMode is always NPU_GET_FLOAT_STATUS_TPL_DEFAULT (0) — no branching needed.
    // 950 空实现：不读取溢出状态寄存器，不修改输入 addr，输出固定全零。
    NsNPUGetFloatStatus::Process<float>(addr, data);
}
