/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file lp_norm_update.cpp
 * \brief LpNormUpdate level0 op_api implementation
 */

#include "lp_norm_update.h"
#include "opdev/aicpu/aicpu_task.h"
#include "opdev/data_type_utils.h"
#include "opdev/format_utils.h"
#include "opdev/make_op_executor.h"
#include "opdev/op_def.h"
#include "opdev/op_dfx.h"
#include "opdev/op_executor.h"
#include "opdev/op_log.h"
#include "opdev/shape_utils.h"

using namespace op;

namespace l0op {
OP_TYPE_REGISTER(LpNormUpdate);

static const std::initializer_list<op::DataType> AICORE_DTYPE_SUPPORT_LIST = {
    op::DataType::DT_FLOAT, op::DataType::DT_FLOAT16, op::DataType::DT_DOUBLE, op::DataType::DT_COMPLEX64,
    op::DataType::DT_COMPLEX128};

static bool IsAiCoreSupport(const aclTensor* self) { return CheckType(self->GetDataType(), AICORE_DTYPE_SUPPORT_LIST); }

static const aclTensor* LpNormUpdateAiCore(const aclTensor* self, int64_t p, float eps, const op::DataType relType,
                                           const aclTensor* updateOut, aclOpExecutor* executor)
{
    L0_DFX(LpNormUpdateAiCore, self, p, eps, relType, updateOut);
    auto ret = ADD_TO_LAUNCHER_LIST_AICORE(LpNormUpdate, OP_INPUT(self), OP_OUTPUT(updateOut), OP_ATTR(p, eps));
    OP_CHECK(ret == ACLNN_SUCCESS,
             OP_LOGE(ACLNN_ERR_INNER_NULLPTR, "LpNormUpdateAiCore ADD_TO_LAUNCHER_LIST_AICORE failed."),
             return nullptr);
    return updateOut;
}

static const aclTensor* LpNormUpdateAiCpu(const aclTensor* self, int64_t p, float eps, const op::DataType relType,
                                          const aclTensor* updateOut, aclOpExecutor* executor)
{
    L0_DFX(LpNormUpdateAiCpu, self, p, eps, relType);
    static internal::AicpuTaskSpace space("LpNormUpdate");
    auto ret = ADD_TO_LAUNCHER_LIST_AICPU(LpNormUpdate, OP_ATTR_NAMES({"p", "eps"}), OP_INPUT(self),
                                          OP_OUTPUT(updateOut), OP_ATTR(p, eps));
    OP_CHECK(ret == ACLNN_SUCCESS,
             OP_LOGE(ACLNN_ERR_INNER_NULLPTR, "LpNormUpdateAiCpu ADD_TO_LAUNCHER_LIST_AICPU failed."), return nullptr);
    return updateOut;
}

const aclTensor* LpNormUpdate(const aclTensor* self, int64_t p, float eps, const op::DataType relType,
                              aclOpExecutor* executor)
{
    if (self->GetDataType() != static_cast<op::DataType>(ACL_FLOAT)) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID, "LpNormUpdate selftype [%s] && current shape [%s].",
                op::ToString(self->GetDataType()).GetString(), op::ToString(self->GetViewShape()).GetString());
        return nullptr;
    }

    auto updateOut = executor->AllocTensor(self->GetViewShape(), self->GetDataType(), self->GetViewFormat());

    if (IsAiCoreSupport(self)) {
        return LpNormUpdateAiCore(self, p, eps, relType, updateOut, executor);
    }
    return LpNormUpdateAiCpu(self, p, eps, relType, updateOut, executor);
}
} // namespace l0op
