/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file selu_grad_tiling_data.h
 * \brief TilingData 结构体定义（arch35 架构）
 */

#ifndef _SELU_GRAD_TILING_DATA_H_
#define _SELU_GRAD_TILING_DATA_H_

struct SeluGradTilingData {
    int64_t totalElements = 0; // 总元素数
    int64_t blockFormer = 0;   // 每核元素数
    int64_t ubFormer = 0;      // 每次 UB 处理的元素数
};

#endif // _SELU_GRAD_TILING_DATA_H_
