/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// rnn/dynamic_gru/op_kernel/arch35/dynamic_gru_mask.h
//
// ROLE: MASK 分支 (tilingKey=1, 掩码吸收路径) kernel 类 — seq_length 传入
//   ⇒ 变长冻结式递推。
//
// NORMAL / MASK 两 kernel 类物理分文件，公共逻辑单源共享：三段骨架 / 12 平面
//   工作集 / AIC GEMM 链 / 门控 VF 链全部落在 dynamic_gru_normal.h 的
//   `DynamicGRUNormalKernel<T, kMask>` 模板（kMask=false 即 NORMAL 路径），
//   掩码语义经编译期 `if constexpr (kMask)` 织入同一骨架。本类继承 kMask=true
//   实例化（T = DTYPE_B: b/cb/init_h/输出 dtype; x/w/cw 恒 fp16）。
//
// 掩码计算链（实现均在 normal.h）:
//   - Init: gmSeq_ 绑定 + seq/maskRow 两行向量分配
//   - CopyInSeq: seq_length 本核行片拷入（int32 直读，字节精确）
//   - GenMaskRow: m[b] = 𝟙[t < s[b]]（⚠ Compare 极性: src0 = tVec 在前 +
//     CMPMODE::LT，写反即掩码整体取反），每步一次，hoist 出 h 块循环
//   - 冻结式施加 h_t = h_{t-1} + (h̃_t − h_{t-1})·m_t：maskRow 单元素经
//     DIST_BRC_B32 寄存器内广播直接参与 Mul，不物化掩码平面
//   - r/i/n 门输出不经掩码；y/output_h 双写源 = hNew（padding 步即冻结
//     边界值，output_h 末步自然取有效长度边界隐状态）
//   - padding 步 (m=0) 回灌轮照常执行（禁按值跳轮）
//   - NaN 不阻断（NaN·0=NaN 沿时间传播），±Inf 门激活饱和
//   - cube 侧 / 段 1 / Xproj / bias / init_h / 镜像 / 同步: 与 NORMAL 同构
//
// INSTANTIATION: dynamic_gru.cpp MODE==DYNAMIC_GRU_TPL_MODE_MASK 分支
//   `DynamicGRUMaskKernel<DTYPE_B>`。

#ifndef DYNAMIC_GRU_MASK_H_
#define DYNAMIC_GRU_MASK_H_

#include "dynamic_gru_normal.h" // DynamicGRUNormalKernel<T, kMask> 共享骨架

// DynamicGRUMaskKernel — 继承共享骨架的 kMask=true 实例化：掩码语义已在
// 基类编译期织入，本类不新增任何状态或方法（空壳即完整 MASK kernel）。
template <typename T>
class DynamicGRUMaskKernel : public DynamicGRUNormalKernel<T, true> {};

#endif // DYNAMIC_GRU_MASK_H_
