/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef __RENORM_TILING_KEY_H__
#define __RENORM_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

// 模板编号
// 0: Template A (SM-CT) - Slice-Major Continuous Single-Level  [已实现]
// 1: Template B (SM-TL) - Slice-Major Continuous Two-Level     [预留]
// 2: Template C (SM-CR) - Slice-Major Cross-Core Reduction     [预留]
// 3: Template D (SM-ST) - Slice-Major Stride                   [预留]
// 4: Template E (BM-VD) - Block-Major Vector Direct            [待实现]
// 5: Template F (BM-VG) - Block-Major Vector Grouped           [预留]

ASCENDC_TPL_ARGS_DECL(Renorm,
                      ASCENDC_TPL_DATATYPE_DECL(D_T_X, C_DT_FLOAT, C_DT_FLOAT16, C_DT_BF16, ASCENDC_TPL_INPUT(0)),
                      ASCENDC_TPL_UINT_DECL(TEMPLATE, 8, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                            13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32,
                                            33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
                                            52, 55, 58, 59));

ASCENDC_TPL_SEL(
    // TEMPLATE=0 (Template A: SM-CT, Slice-Major Continuous Single-Level)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 0)),
    // TEMPLATE=1 (Template B: SM-TL, Slice-Major Continuous Two-Level)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 1)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 1)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 1)),
    // TEMPLATE=2 (Template C: SM-CR, Slice-Major Cross-Core Reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 2)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 2)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 2)),
    // TEMPLATE=3 (Template D: SM-ST, Slice-Major Stride)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 3)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 3)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 3)),
    // TEMPLATE=4 (Template E: BM-VD, Block-Major Vector Direct)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 4)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 4)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 4)),
    // TEMPLATE=5 (Template F: BM-VG, Block-Major Vector Grouped)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 5)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 5)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 5)),
    // TEMPLATE=6 (Template G: Global Reduce, single-core)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 6)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 6)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 6)),
    // TEMPLATE=7 (Template B2: isolated stable two-level route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 7)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 7)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 7)),
    // TEMPLATE=8 (Template C2: isolated packed small-block route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 8)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 8)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 8)),
    // TEMPLATE=9 (Template G2: isolated global high-p route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 9)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 9)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 9)),
    // TEMPLATE=10 (Template G3: isolated long single-slice p route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 10)),
    // TEMPLATE=11 (Template C3: dense logical-block cross-core route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 11)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 11)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 11)),
    // TEMPLATE=12 (Template D2: isolated long-slice ping-pong route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 12)),
    // TEMPLATE=13 (Template H: isolated inner block split route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 13)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 13)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 13)),
    // TEMPLATE=14 (Template C4: isolated unaligned packed fp16 route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 14)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 14)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 14)),
    // TEMPLATE=15 (Template C5: isolated block-major tiled fp16 route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 15)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 15)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 15)),
    // TEMPLATE=16 (Template C6: isolated p=inf packed max route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 16)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 16)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 16)),
    // TEMPLATE=17 (Template C7: isolated high-p overflow early-exit route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 17)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 17)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 17)),
    // TEMPLATE=18 (Template C8: packed block-major p=inf RA reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 18)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 18)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 18)),
    // TEMPLATE=19 (Template C9: dense finite-p source-reuse AR reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 19)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 19)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 19)),
    // TEMPLATE=20 (Template C10: dense p=98 overflow precheck)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 20)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 20)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 20)),
    // TEMPLATE=21 (Template C11: packed block-major finite-p RA reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 21)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 21)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 21)),
    // TEMPLATE=22 (Template F2: packed-row BM-VG for long non-aligned FP16 rows)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 22)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 22)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 22)),
    // TEMPLATE=23 (Template F3: packed BM-VG p=96 overflow early exit)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 23)),
    // TEMPLATE=24 (Template C12: contiguous B=1 p=inf RA reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 24)),
    // TEMPLATE=25 (Template C13: B=1 p=inf RA reduction with 8-lane rows)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 25)),
    // TEMPLATE=26 (Template H2: Inner-Split p=inf copy-only scale)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 26)),
    // TEMPLATE=27 (Template F4: packed BM-VG with a two-row UB tile)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 27)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 27)),
    // TEMPLATE=28 (Template C14: isolated large-tile contiguous B=1 RA)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 28)),
    // TEMPLATE=30 (Template G4: isolated large-tile global p=inf)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 30)),
    // TEMPLATE=31 (Template G5: isolated optimized large global p=inf)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 31)),
    // TEMPLATE=32 (Template H3: isolated native p=inf inner reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 32)),
    // TEMPLATE=33 (Template C15: isolated native 16-bit p=inf RA)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 33)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 33)),
    // TEMPLATE=34 (Template F5: isolated native FP16 packed-row p=inf)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 34)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 34)),
    // TEMPLATE=35 (Template C16: dense BF16 finite-p batched AR reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 35)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 35)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 35)),
    // TEMPLATE=36 (Template C17: compact-UB dense positive AR)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 36)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 36)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 36)),
    // TEMPLATE=37 (Template B3: legacy two-level reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 37)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 37)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 37)),
    // TEMPLATE=38 (Template G6: isolated flat one-slice positive reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 38)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 38)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 38)),
    // TEMPLATE=39 (Template C18: direct-pow B=1 batched RA reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 39)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 39)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 39)),
    // TEMPLATE=40 (Template C19: direct-pow overflow probe)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 40)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 40)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 40)),
    // TEMPLATE=41 (Template C20: tiled generic positive reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 41)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 41)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 41)),
    // TEMPLATE=42 (Template H4: direct-pow overflow output shortcut)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 42)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 42)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 42)),
    // TEMPLATE=43 (Template H5: compact positive-p inner split)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 43)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 43)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 43)),
    // TEMPLATE=44 (Template C21: dense integer-p exponentiation)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 44)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 44)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 44)),
    // TEMPLATE=45 (Template C22: packed B=1 integer-p exponentiation)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 45)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 45)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 45)),
    // TEMPLATE=46 (Template C23: compact integer-power packed reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 46)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 46)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 46)),
    // TEMPLATE=47 (contiguous B=1 integer-power route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 47)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 47)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 47)),
    // TEMPLATE=48 (generic scalar reduction for reduction-risk geometry)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 48)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 48)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 48)),
    // TEMPLATE=49 (isolated direct-pow local sum-overflow route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 49)),
    // TEMPLATE=50 (isolated FP16 p=77 H4 overflow probe)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 50)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 51)),
    // TEMPLATE=52 (isolated large-GM flat global-p route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 52)),
    // TEMPLATE=55 (isolated H4 integer-power route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 55)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 55)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 55)),
    // TEMPLATE=58 (isolated FP32 p=inf scalar route)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 58)),
    // TEMPLATE=59 (max-normalized high-order positive-p scalar reduction)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 59)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 59)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE, ASCENDC_TPL_UI_LIST, 59)), );

#endif // __RENORM_TILING_KEY_H__
