#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# ----------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------
# Generated By CANNBot

import numpy as np


__golden__ = {
    "kernel": {
        "fused_mul_apply_momentum_extern": "fused_mul_apply_momentum_extern_golden"
    }
}


def fused_mul_apply_momentum_extern_golden(
    var,
    accum,
    lr,
    x1,
    momentum,
    x2,
    var_copy,  # inputs
    use_nesterov: bool = False,
    use_locking: bool = False,  # attributes
    **kwargs,
):
    """
    Golden function for fused_mul_apply_momentum_extern (ApplyMomentum 加号权威口径).

    参数名与顺序遵循 fused_mul_apply_momentum_extern_def.cpp（不含 outputs），
    所有输入 Tensor 均为 numpy.ndarray。计算全程升 float64 高精度，最后 Cast 回原 dtype。

    公式（锁定）：
        grad         = x1 * x2                                     # x2 = LossScale reciprocal（标量）
        accum'       = accum * momentum + grad                     # 加号动量
        var_delta    = accum' * lr                                 (use_nesterov=False)
        var_delta    = grad * lr + accum' * momentum * lr          (use_nesterov=True)
        var_out      = var - var_delta                             # 主权重恒 FP32
        var_copy_out = var_copy - Cast(var_delta)                  # 低精度副本独立同步更新（非 Cast(var_out)）
        accum_out    = Cast(accum')                                # 回原 accum dtype

    Args:
        **kwargs: {input,output}_{dtypes,ori_shapes,formats,ori_formats},
                  full_soc_version, short_soc_version, testcase_name

    Returns:
        (var_out, var_copy_out, accum_out)，各自 Cast 回对应输入 dtype。
    """
    var_dtype = var.dtype  # 恒 float32
    accum_dtype = accum.dtype  # float16 / bfloat16 / float32（计算通路驱动）
    var_copy_dtype = var_copy.dtype  # float16 / bfloat16

    # 升 float64 高精度计算
    var_f64 = var.astype(np.float64)
    accum_f64 = accum.astype(np.float64)
    x1_f64 = x1.astype(np.float64)
    var_copy_f64 = var_copy.astype(np.float64)

    def _scalar_f64(arr):
        a = np.asarray(arr).astype(np.float64)
        return float(a.flat[0])

    lr_val = _scalar_f64(lr)
    momentum_val = _scalar_f64(momentum)
    x2_val = _scalar_f64(x2)

    grad = x1_f64 * x2_val
    accum_t = accum_f64 * momentum_val + grad

    if use_nesterov:
        var_delta = grad * lr_val + accum_t * momentum_val * lr_val
    else:
        var_delta = accum_t * lr_val

    var_out_f64 = var_f64 - var_delta

    # var_copy 独立同步更新：减去 Cast(var_delta)（先降到 var_copy dtype 再回升），非 Cast(var_out)
    var_delta_cast = var_delta.astype(var_copy_dtype).astype(np.float64)
    var_copy_out_f64 = var_copy_f64 - var_delta_cast

    var_out = var_out_f64.astype(var_dtype, copy=False)
    var_copy_out = var_copy_out_f64.astype(var_copy_dtype, copy=False)
    accum_out = accum_t.astype(accum_dtype, copy=False)
    return var_out, var_copy_out, accum_out
