/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/*!
 * \file fused_mul_apply_keras_momentum_struct.h
 * \brief 数据结构定义
 * Generated By CANNBot
 */
// FusedMulApplyKerasMomentum TilingKey 模板参数
// Broadcast 范式：TilingKey 只与有效 RANK 相关（RANK_4 常态 / RANK_8 保底），与 dtype 无关。
// 参考源码：adam_struct.h
#ifndef FUSED_MUL_APPLY_KERAS_MOMENTUM_STRUCT_H_
#define FUSED_MUL_APPLY_KERAS_MOMENTUM_STRUCT_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define FUSED_MUL_APPLY_KERAS_MOMENTUM_RANK_4 4
#define FUSED_MUL_APPLY_KERAS_MOMENTUM_RANK_8 8

ASCENDC_TPL_ARGS_DECL(FusedMulApplyKerasMomentum,
                      ASCENDC_TPL_UINT_DECL(RANK, 8, ASCENDC_TPL_UI_LIST, FUSED_MUL_APPLY_KERAS_MOMENTUM_RANK_4,
                                            FUSED_MUL_APPLY_KERAS_MOMENTUM_RANK_8));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(RANK, ASCENDC_TPL_UI_LIST, FUSED_MUL_APPLY_KERAS_MOMENTUM_RANK_4)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(RANK, ASCENDC_TPL_UI_LIST, FUSED_MUL_APPLY_KERAS_MOMENTUM_RANK_8)));

#endif // FUSED_MUL_APPLY_KERAS_MOMENTUM_STRUCT_H_
