/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file smooth_l1_loss_grad_infershape.cpp
 * \brief SmoothL1LossGrad 形状 / 类型推导
 *
 * 逐元素运算，无广播：
 *   gradient.shape = predict.shape
 *   gradient.dtype = predict.dtype
 *
 * 显式注册 InferDataType 保证
 *   gradient.dtype=predict.dtype（多 dtype 入图场景下比仅依赖 def.cpp 输入输出列表
 *   按位对应更稳健，与同仓 relu6_d / cosh 范式一致）。
 */

#include "register/op_impl_registry.h"
#include "exe_graph/runtime/infer_shape_context.h"
#include "op_common/log/log.h"

using namespace ge;

namespace ops {

static ge::graphStatus InferShape4SmoothL1LossGrad(gert::InferShapeContext* context)
{
    // Format 校验：仅支持 ND
    const auto* predictTensor = context->GetInputTensor(0);
    if (predictTensor != nullptr) {
        auto format = predictTensor->GetStorageFormat();
        OP_CHECK_IF(format != ge::FORMAT_ND,
                    OP_LOGE(context, "SmoothL1LossGrad: unsupported format on input predict: %d, only ND is supported",
                            static_cast<int>(format)),
                    return ge::GRAPH_FAILED);
    }

    const gert::Shape* predictShape = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, predictShape);

    gert::Shape* gradientShape = context->GetOutputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, gradientShape);

    // gradient.shape = predict.shape（无广播，OneInOneOutDynamicInfer）
    *gradientShape = *predictShape;

    return ge::GRAPH_SUCCESS;
}

// 类型推导：gradient.dtype = predict.dtype（无类型提升）
static ge::graphStatus InferDataType4SmoothL1LossGrad(gert::InferDataTypeContext* context)
{
    const ge::DataType predictDtype = context->GetInputDataType(0);
    context->SetOutputDataType(0, predictDtype);
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(SmoothL1LossGrad)
    .InferShape(InferShape4SmoothL1LossGrad)
    .InferDataType(InferDataType4SmoothL1LossGrad);

} // namespace ops
