/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the License).
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_lstm_block_cell_tiling.cpp
 * \brief LstmBlockCell host TilingFunc UT.
 *
 * 正例矩阵：按 K=I+H 分档覆盖 W 策略全部分支（小 K 均分 / 160 / 64 / 大 K 160）、
 * 反饥饿 SK 收缩、空 strip 防护（B=1）、多轮模式（超大 B）、fp16 偶分、属性透传。
 * 负例参数化套件：dtype / 缺输入 / rank / shape 一致性 / 零维 / 越界 / 负维 /
 * GM 2^32 上界守卫 —— 覆盖 TilingFunc 的每一条 OP_LOGE 拒绝路径。
 */

#include <cstdint>
#include <iostream>
#include <map>
#include <numeric>
#include <string>
#include <vector>
#include <gtest/gtest.h>
#include "log/log.h"
#include "register/op_impl_registry.h"
#include "ut_op_util.h"
#include "kernel_run_context_facker.h"
#include "test_cube_util.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "platform/platform_infos_def.h"
#include "tiling/platform/platform_ascendc.h"
#include "../../../op_kernel/arch35/lstm_block_cell_tiling.h"

using namespace ut_util;
using namespace std;
using namespace ge;

namespace {

constexpr size_t kNumInputs = 8;  // x, cs_prev, h_prev, w, wci, wcf, wco, b
constexpr size_t kNumOutputs = 7; // i, cs, f, o, ci, co, h
constexpr uint32_t kMaxBlocks = 32;

struct LstmBlockCellCompileInfoStub {};

gert::StorageShape MakeShape(const std::vector<int64_t>& dims)
{
    gert::StorageShape shape;
    for (const int64_t dim : dims) {
        shape.MutableOriginShape().AppendDim(dim);
        shape.MutableStorageShape().AppendDim(dim);
    }
    return shape;
}

std::vector<std::vector<int64_t>> MakeInputDims(int64_t batch, int64_t inputSize, int64_t hiddenSize)
{
    const int64_t k = inputSize + hiddenSize;
    return {{batch, inputSize}, {batch, hiddenSize}, {batch, hiddenSize}, {k, 4 * hiddenSize},
            {hiddenSize},       {hiddenSize},        {hiddenSize},        {4 * hiddenSize}};
}

enum class Constraint {
    kXDtype,       // x dtype 不支持
    kMissingInput, // 某输入 shape 为 null
    kInputRank,    // 某输入 rank 错
    kInputShape,   // 某输入 shape 与 x/cs 不一致
    kDimZero,      // B/I/H 为 0
    kDimOverMax,   // 维度超 2^24
    kDimNegative,  // 维度为负
    kGmOverflow,   // 元素总数 >= 2^32
    kValid,
};

struct TilingCase {
    std::string name;
    int64_t batch = 16;
    int64_t inputSize = 64;
    int64_t hiddenSize = 173;
    ge::DataType dtype = ge::DT_FLOAT;
    Constraint constraint = Constraint::kValid;
    size_t tensor = 0;
    size_t dim = 0;
    bool greater = false;
};

uint32_t CeilDivU(uint32_t a, uint32_t b) { return (a + b - 1) / b; }

ge::graphStatus RunTilingCase(const TilingCase& testCase, LstmBlockCellTilingData* tilingOut = nullptr)
{
    int64_t batch = testCase.batch;
    int64_t inputSize = testCase.inputSize;
    int64_t hiddenSize = testCase.hiddenSize;
    if (testCase.constraint == Constraint::kDimZero) {
        // tensor: 0=B 1=I 2=H
        if (testCase.tensor == 0) {
            batch = 0;
        }
        if (testCase.tensor == 1) {
            inputSize = 0;
        }
        if (testCase.tensor == 2) {
            hiddenSize = 0;
        }
    }
    std::vector<std::vector<int64_t>> inputDims = MakeInputDims(batch, inputSize, hiddenSize);
    std::vector<std::vector<int64_t>> outputDims(kNumOutputs, {batch, hiddenSize});
    std::vector<ge::DataType> inputDtypes(kNumInputs, testCase.dtype);
    std::vector<ge::DataType> outputDtypes(kNumOutputs, testCase.dtype);

    if (testCase.constraint == Constraint::kXDtype) {
        inputDtypes[0] = testCase.dtype;
        outputDtypes.assign(kNumOutputs, testCase.dtype);
    } else if (testCase.constraint == Constraint::kInputRank) {
        auto& dims = inputDims[testCase.tensor];
        if (testCase.greater) {
            dims.push_back(1);
        } else {
            dims.clear();
        }
    } else if (testCase.constraint == Constraint::kInputShape) {
        inputDims[testCase.tensor][testCase.dim] += testCase.greater ? 1 : -1;
    }

    std::vector<gert::StorageShape> inputShapes;
    std::vector<gert::StorageShape> outputShapes;
    for (const auto& dims : inputDims) {
        inputShapes.emplace_back(MakeShape(dims));
    }
    for (const auto& dims : outputDims) {
        outputShapes.emplace_back(MakeShape(dims));
    }
    std::vector<gert::StorageShape*> inputPtr;
    std::vector<gert::StorageShape*> outputPtr;
    for (size_t i = 0; i < kNumInputs; ++i) {
        inputPtr.push_back(testCase.constraint == Constraint::kMissingInput && i == testCase.tensor ? nullptr :
                                                                                                      &inputShapes[i]);
    }
    for (size_t i = 0; i < kNumOutputs; ++i) {
        outputPtr.push_back(&outputShapes[i]);
    }

    map<string, string> socInfos;
    map<string, string> aicoreSpec;
    map<string, string> intrinsics;
    string PLATFORM_JSON = R"({
    "hardware_info": {"BT_SIZE": 0, "load3d_constraints": "1",
    "Intrinsic_fix_pipe_l0c2out": true, "Intrinsic_data_move_l12ub": true,
    "Intrinsic_data_move_l0c2ub": true, "Intrinsic_data_move_out2l1_nd2nz": false,
    "UB_SIZE": 253952, "L2_SIZE": 134217728, "L1_SIZE": 524288,
    "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 262144,
    "CORE_NUM": 32}})";
    GetPlatFormInfos(PLATFORM_JSON.c_str(), socInfos, aicoreSpec, intrinsics);

    fe::PlatFormInfos platformInfo;
    platformInfo.Init();
    LstmBlockCellCompileInfoStub compileInfo;

    auto tilingData = gert::TilingData::CreateCap(4096);
    auto workspaceHolder = gert::ContinuousVector::Create<size_t>(4);
    if (tilingData == nullptr || workspaceHolder == nullptr) {
        ADD_FAILURE() << "failed to build the TilingContext test infrastructure";
        return ge::GRAPH_FAILED;
    }
    const auto workspace = reinterpret_cast<gert::ContinuousVector*>(workspaceHolder.get());
    auto holder = gert::TilingContextFaker()
                      .SetOpType("LstmBlockCell")
                      .NodeIoNum(kNumInputs, kNumOutputs)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1, 1})
                      .InputShapes(inputPtr)
                      .OutputShapes(outputPtr)
                      .CompileInfo(&compileInfo)
                      .PlatformInfo(reinterpret_cast<char*>(&platformInfo))
                      .NodeInputTd(0, inputDtypes[0], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(1, inputDtypes[1], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(2, inputDtypes[2], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(3, inputDtypes[3], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(4, inputDtypes[4], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(5, inputDtypes[5], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(6, inputDtypes[6], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(7, inputDtypes[7], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(0, outputDtypes[0], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(1, outputDtypes[1], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(2, outputDtypes[2], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(3, outputDtypes[3], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(4, outputDtypes[4], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(5, outputDtypes[5], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(6, outputDtypes[6], ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeAttrs({
                          {"forget_bias", Ops::NN::AnyValue::CreateFrom<float>(1.0f)},
                          {"cell_clip", Ops::NN::AnyValue::CreateFrom<float>(3.0f)},
                          {"use_peephole", Ops::NN::AnyValue::CreateFrom<bool>(false)},
                      })
                      .TilingData(tilingData.get())
                      .Workspace(workspace)
                      .Build();

    const auto* opImpl = gert::OpImplRegistry::GetInstance().GetOpImpl("LstmBlockCell");
    if (opImpl == nullptr || opImpl->tiling == nullptr) {
        ADD_FAILURE() << "LstmBlockCell host Tiling was not registered";
        return ge::GRAPH_FAILED;
    }
    auto* context = holder.GetContext<gert::TilingContext>();
    if (context == nullptr || context->GetPlatformInfo() == nullptr) {
        ADD_FAILURE() << "failed to build the TilingContext test infrastructure";
        return ge::GRAPH_FAILED;
    }
    context->GetPlatformInfo()->SetPlatformRes("SoCInfo", socInfos);
    context->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicoreSpec);
    context->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    context->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intrinsics);

    const ge::graphStatus status = opImpl->tiling(context);
    if (tilingOut != nullptr && status == ge::GRAPH_SUCCESS) {
        // CreateCap 的 buffer 首部是 gert::TilingData POD 头（capacity/size/data 指针），
        // tiling 载荷从 GetData() 开始。按值拷出：cap buffer 随本函数局部 unique_ptr
        // 析构，外泄裸指针在调用方校验阶段是 heap-use-after-free（ASAN 实报）；
        // LstmBlockCellTilingData 为纯标量 POD，值拷贝零语义损失。
        const auto* tilingDataObj = reinterpret_cast<const gert::TilingData*>(tilingData.get());
        *tilingOut = *reinterpret_cast<const LstmBlockCellTilingData*>(tilingDataObj->GetData());
    }
    return status;
}

std::vector<TilingCase> BuildNegativeCases()
{
    std::vector<TilingCase> cases;
    // x dtype 不支持（dtype 派发分支）
    cases.push_back({"neg_x_dtype_int32", 16, 64, 173, ge::DT_INT32, Constraint::kXDtype});
    cases.push_back({"neg_x_dtype_bf16", 16, 64, 173, ge::DT_BF16, Constraint::kXDtype});
    cases.push_back({"neg_x_dtype_bool", 16, 64, 173, ge::DT_BOOL, Constraint::kXDtype});
    // 每个输入的空指针（逐个 OP_CHECK_NULL_WITH_CONTEXT 分支）
    for (size_t input = 0; input < kNumInputs; ++input) {
        TilingCase c{"", 16, 64, 173, ge::DT_FLOAT, Constraint::kMissingInput};
        c.tensor = input;
        c.name = "neg_missing_input_" + std::to_string(input);
        cases.push_back(c);
    }
    // 每个输入 rank 低/高（rank 校验分支）
    for (size_t input = 0; input < kNumInputs; ++input) {
        for (int greater = 0; greater < 2; ++greater) {
            TilingCase c{"", 16, 64, 173, ge::DT_FLOAT, Constraint::kInputRank};
            c.tensor = input;
            c.greater = greater != 0;
            c.name = std::string("neg_rank_input_") + std::to_string(input) + (greater ? "_high" : "_low");
            cases.push_back(c);
        }
    }
    // shape 一致性（h_prev[2]/cs_prev[0]/w[2]/b[0]/wci|wcf|wco[0] 的 ±1）
    const std::vector<std::pair<size_t, size_t>> shapeTargets = {{2, 0}, {2, 1}, {1, 0}, {3, 0}, {3, 1},
                                                                 {7, 0}, {4, 0}, {5, 0}, {6, 0}};
    int idx = 0;
    for (const auto& target : shapeTargets) {
        for (int greater = 0; greater < 2; ++greater) {
            TilingCase c{"", 16, 64, 173, ge::DT_FLOAT, Constraint::kInputShape};
            c.tensor = target.first;
            c.dim = target.second;
            c.greater = greater != 0;
            c.name = "neg_shape_" + std::to_string(idx++);
            cases.push_back(c);
        }
    }
    // 零维（dimB/I/H <= 0 分支）
    cases.push_back({"neg_dim_zero_b", 16, 64, 173, ge::DT_FLOAT, Constraint::kDimZero, 0});
    cases.push_back({"neg_dim_zero_i", 16, 64, 173, ge::DT_FLOAT, Constraint::kDimZero, 1});
    cases.push_back({"neg_dim_zero_h", 16, 64, 173, ge::DT_FLOAT, Constraint::kDimZero, 2});
    // 越上界（DIM_MAX = 2^24）
    {
        TilingCase c{"neg_dim_over_max_b", (1LL << 24) + 1, 64, 173, ge::DT_FLOAT, Constraint::kValid};
        cases.push_back(c);
    }
    {
        TilingCase c{"neg_dim_over_max_h", 16, 64, (1LL << 24) + 1, ge::DT_FLOAT, Constraint::kValid};
        cases.push_back(c);
    }
    // 负维（含未知维 -1/-2 漏到 tiling 的防线）
    {
        TilingCase c{"neg_dim_negative_b", -1, 64, 173, ge::DT_FLOAT, Constraint::kValid};
        cases.push_back(c);
    }
    {
        TilingCase c{"neg_dim_negative_h", 16, 64, -2, ge::DT_FLOAT, Constraint::kValid};
        cases.push_back(c);
    }
    // GM 偏移 2^32 守卫：B*I 与 (I+H)*4H 各一条（[2^31, 2^32) 区间合法，见
    // fp32_gm_overflow_border_succ 正例）
    {
        TilingCase c{"neg_gm_overflow_bi", 65536, 65536, 8, ge::DT_FLOAT, Constraint::kValid};
        cases.push_back(c);
    }
    {
        // (I+H)*4H = 46400*92800 = 4,305,920,000 >= 2^32
        TilingCase c{"neg_gm_overflow_k4h", 16, 23200, 23200, ge::DT_FLOAT, Constraint::kValid};
        cases.push_back(c);
    }
    return cases;
}

class LstmBlockCellTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "LstmBlockCellTiling SetUp" << std::endl; }
    static void TearDownTestCase() { std::cout << "LstmBlockCellTiling TearDown" << std::endl; }
};

// 通用正例校验：W/SK 策略 + 网格不变量
void CheckTilingInvariants(const LstmBlockCellTilingData* td, uint32_t batch, uint32_t expectedKey, uint32_t expectedW)
{
    EXPECT_EQ(td->tilingKey, expectedKey);
    EXPECT_EQ(td->batch, batch);
    // W 策略（K 分档定型值，与核数解耦）
    EXPECT_EQ(td->ksSegWidth, expectedW);
    // S 与 SK 反饥饿收缩
    const uint32_t k = td->inputSize + td->hiddenSize;
    const uint32_t s = CeilDivU(k, expectedW);
    const uint32_t skBudget = expectedKey == 0 ? kMaxBlocks / 2 : 2;
    const uint32_t expectedSk = skBudget < s ? skBudget : s;
    EXPECT_EQ(td->ksCores, expectedSk);
    // 网格不变量
    EXPECT_EQ(td->blockDim, td->ksStrips * td->ksCores);
    EXPECT_EQ(td->rowsPerClusterTotal, CeilDivU(batch, td->ksStrips));
    EXPECT_GE(td->rowsPerBlock, 1);
    EXPECT_LE(td->blockDim, kMaxBlocks);
}

TEST_F(LstmBlockCellTiling, fp32_small_k_even_split_succ)
{
    // K=237 < 1909：小 K 均分 —— W=ceil(237/12)=20, S=12, SK 收缩到 12
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_small_k", 16, 64, 173, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 16, 0, 20);
    EXPECT_EQ(td.ksCores, 12);
}

TEST_F(LstmBlockCellTiling, fp32_bucket160_succ)
{
    // K=2344：常规档 W=160，S=15，SK=min(16,15)=15；B=1 空 strip 防护 strips=1
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_bucket160", 1, 32, 2312, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 1, 0, 160);
    EXPECT_EQ(td.ksCores, 15);
    EXPECT_EQ(td.ksStrips, 1);
    EXPECT_EQ(td.blockDim, 15);
}

TEST_F(LstmBlockCellTiling, fp32_bucket64_succ)
{
    // 4096 < K=8192 <= 32768：中档 W=64，S=128，SK=16，满核 blockDim=32
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_bucket64", 16, 4096, 4096, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 16, 0, 64);
    EXPECT_EQ(td.ksCores, 16);
    EXPECT_EQ(td.blockDim, 32);
}

TEST_F(LstmBlockCellTiling, fp32_large_k_bucket160_succ)
{
    // K=40100 > 32768：大 K 档回到 W=160，S=251，SK=16（H 取小值避免触发 GM 2^32 守卫，
    // 守卫本身由 neg_gm_overflow_* 负例覆盖）
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_large_k", 16, 40000, 100, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 16, 0, 160);
    EXPECT_EQ(td.ksCores, 16);
    EXPECT_EQ(td.blockDim, 32);
}

TEST_F(LstmBlockCellTiling, fp32_huge_b_multi_round_succ)
{
    // B=100000：多轮模式（span >> rowsPerBlock），K=16 小 K 均分 W=2/S=8/SK=8
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_multi_round", 100000, 8, 8, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 100000, 0, 2);
    EXPECT_EQ(td.ksCores, 8);
    EXPECT_GT(td.rowsPerClusterTotal, td.rowsPerBlock);
    EXPECT_EQ(td.blockDim, 32);
}

TEST_F(LstmBlockCellTiling, fp32_gm_overflow_border_succ)
{
    // (I+H)*4H = 84814*35324 = 2,995,969,736 ∈ [2^31, 2^32)：uint32 元素偏移
    // 不回绕（真机实证精度 PASS），守卫放行
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_gm_border", 39, 75983, 8831, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    EXPECT_EQ(td.tilingKey, 0u);
    EXPECT_EQ(td.batch, 39u);
    EXPECT_EQ(td.blockDim, td.ksStrips * td.ksCores);
}

TEST_F(LstmBlockCellTiling, fp16_even_split_succ)
{
    // fp16：偶分 W=ceil(K/2)，S=2，SK=2
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_fp16", 16, 256, 244, ge::DT_FLOAT16}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 16, 1, 250);
    EXPECT_EQ(td.ksCores, 2);
}

TEST_F(LstmBlockCellTiling, fp16_b1_succ)
{
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_fp16_b1", 1, 32, 2312, ge::DT_FLOAT16}, &td), ge::GRAPH_SUCCESS);
    CheckTilingInvariants(&td, 1, 1, 1172);
    EXPECT_EQ(td.ksStrips, 1);
    EXPECT_EQ(td.blockDim, 2);
}

TEST(LstmBlockCellTilingAttr, attrs_propagate)
{
    LstmBlockCellTilingData td{};
    ASSERT_EQ(RunTilingCase({"pos_attrs", 16, 64, 173, ge::DT_FLOAT}, &td), ge::GRAPH_SUCCESS);
    EXPECT_EQ(td.tilingKey, 0);
    EXPECT_FLOAT_EQ(td.forgetBias, 1.0f); // faker 属性取值透传
    EXPECT_FLOAT_EQ(td.cellClip, 3.0f);
    EXPECT_EQ(td.usePeephole, 0u);
}

class LstmBlockCellNegativeTiling : public testing::TestWithParam<TilingCase> {};

TEST_P(LstmBlockCellNegativeTiling, rejected_by_host_tiling)
{
    const auto* opImpl = gert::OpImplRegistry::GetInstance().GetOpImpl("LstmBlockCell");
    ASSERT_NE(opImpl, nullptr);
    ASSERT_NE(opImpl->tiling, nullptr);
    EXPECT_EQ(RunTilingCase(GetParam()), ge::GRAPH_FAILED) << GetParam().name;
}

INSTANTIATE_TEST_SUITE_P(NegativeMatrix, LstmBlockCellNegativeTiling, testing::ValuesIn(BuildNegativeCases()),
                         [](const testing::TestParamInfo<TilingCase>& info) { return info.param.name; });

} // namespace
