/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef PSROI_POOLING_GRAD_V2_D_TILING_DATA_H_
#define PSROI_POOLING_GRAD_V2_D_TILING_DATA_H_

#include <cstdint>

struct PSROIPoolingGradV2DTilingData {
    uint64_t totalOutputElements = 0;
    uint64_t totalRois = 0;
    uint64_t batchSize = 0;
    uint64_t roiCount = 0;
    uint64_t outputDim = 0;
    uint64_t channels = 0;
    uint64_t height = 0;
    uint64_t width = 0;
    uint32_t groupSize = 0;
    uint32_t groupArea = 0;
    float spatialScale = 0.0f;
    uint32_t needCoreNum = 0;
    uint64_t roiBatchOffset = 0;
    uint64_t stableQOffset = 0;
    uint64_t batchOffsetsOffset = 0;
    uint64_t coreCursorOffset = 0;
    uint64_t boundsOffset = 0;
    uint64_t outputMetaOffset = 0;
    uint64_t contributionOffset = 0;
    uint64_t addMaskOffset = 0;
};

#endif // PSROI_POOLING_GRAD_V2_D_TILING_DATA_H_
