/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file psroi_pooling_grad_v2_d_graph_infer.cpp
 * \brief PSROIPoolingGradV2D operator graph infer datatype resource
 */

#include "register/op_impl_registry.h"
#include "log/log.h"
#include "op_common/op_host/util/shape_util.h"

namespace ops {
using namespace ge;

static constexpr size_t X_INDEX = 0;
static constexpr size_t ROIS_INDEX = 1;
static constexpr size_t Y_INDEX = 0;

static ge::graphStatus InferDataTypePSROIPoolingGradV2D(gert::InferDataTypeContext* context)
{
    const ge::DataType xType = context->GetInputDataType(X_INDEX);
    const ge::DataType roisType = context->GetInputDataType(ROIS_INDEX);
    OP_CHECK_IF(
        xType != ge::DT_FLOAT || roisType != ge::DT_FLOAT,
        OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "x, rois",
                                               Ops::Base::ToString(xType) + ", " + Ops::Base::ToString(roisType),
                                               "Both input dtypes must be float32"),
        return GRAPH_FAILED);
    context->SetOutputDataType(Y_INDEX, ge::DT_FLOAT);
    return GRAPH_SUCCESS;
}

IMPL_OP(PSROIPoolingGradV2D).InferDataType(InferDataTypePSROIPoolingGradV2D);

}; // namespace ops
