/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/*!
 * \file test_fused_mul_apply_keras_momentum_infershape.cpp
 * \brief InferShape
 * Generated By CANNBot
 */
/**
 * @file test_fused_mul_apply_keras_momentum_infershape.cpp
 * @brief FusedMulApplyKerasMomentum InferShape UT（主线仓级范式）
 *
 * 挂载：nn_op_infershape_ut 聚合体（add_modules_ut_sources HOSTNAME ${OP_INFERSHAPE_MODULE_NAME}）。
 * 框架：仓级 gert::InfershapeContextPara + ExecuteTestCase（tests/ut/common/infershape_case_executor.*）。
 *       Executor 通过 op 名从 OpImplSpaceRegistryV2 解析已注册 infer_shape 函数，无需 include proto。
 *
 * 语义：out_var.shape = var.shape，out_accum.shape = accum.shape（in-place）。
 * 6 输入（var, accum, lr, x1, momentum, x2）/ 2 输出（var, accum）。
 * 覆盖：fp16/fp32、rank0 标量、2D/4D、8D 最大 rank、空 tensor、动态 shape。
 */

#include <gtest/gtest.h>
#include <iostream>
#include <vector>
#include "infershape_case_executor.h"

namespace FmakmInferShapeUT {

static const std::string OP_NAME = "FusedMulApplyKerasMomentum";

class FmakmInfershape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "FmakmInfershape SetUp" << std::endl; }
    static void TearDownTestCase() { std::cout << "FmakmInfershape TearDown" << std::endl; }
};

// 由运行期 vector 构造 gert::StorageShape（rank=0 时为空 shape）
static gert::StorageShape MakeStorageShape(const std::vector<int64_t>& dims)
{
    gert::StorageShape ss;
    for (auto d : dims) {
        ss.MutableOriginShape().AppendDim(d);
        ss.MutableStorageShape().AppendDim(d);
    }
    return ss;
}

// 构造 6 输入 / 2 输出的 InferShape 上下文（var/accum/x1 同 shape，lr/momentum/x2 [1]）
static void RunCase(const std::vector<int64_t>& tShape, ge::DataType dtype,
                    const std::vector<std::vector<int64_t>>& expectOut)
{
    gert::StorageShape t = MakeStorageShape(tShape);
    gert::StorageShape s = MakeStorageShape({1});
    gert::InfershapeContextPara para(OP_NAME,
                                     {
                                         {t, dtype, ge::FORMAT_ND}, // var
                                         {t, dtype, ge::FORMAT_ND}, // accum
                                         {s, dtype, ge::FORMAT_ND}, // lr
                                         {t, dtype, ge::FORMAT_ND}, // x1
                                         {s, dtype, ge::FORMAT_ND}, // momentum
                                         {s, dtype, ge::FORMAT_ND}, // x2
                                     },
                                     {
                                         {t, dtype, ge::FORMAT_ND}, // out var
                                         {t, dtype, ge::FORMAT_ND}, // out accum
                                     });
    ExecuteTestCase(para, ge::GRAPH_SUCCESS, expectOut);
}

TEST_F(FmakmInfershape, Fp16_2D) { RunCase({16, 16}, ge::DT_FLOAT16, {{16, 16}, {16, 16}}); }

TEST_F(FmakmInfershape, Fp32_4D) { RunCase({2, 3, 4, 5}, ge::DT_FLOAT, {{2, 3, 4, 5}, {2, 3, 4, 5}}); }

TEST_F(FmakmInfershape, Rank0_Scalar) { RunCase({}, ge::DT_FLOAT, {{}, {}}); }

TEST_F(FmakmInfershape, Rank8_Max)
{
    RunCase({2, 2, 2, 2, 2, 2, 2, 2}, ge::DT_FLOAT16, {{2, 2, 2, 2, 2, 2, 2, 2}, {2, 2, 2, 2, 2, 2, 2, 2}});
}

TEST_F(FmakmInfershape, EmptyTensor) { RunCase({0, 4}, ge::DT_FLOAT, {{0, 4}, {0, 4}}); }

TEST_F(FmakmInfershape, DynamicShape) { RunCase({-1, -1, 64}, ge::DT_FLOAT16, {{-1, -1, 64}, {-1, -1, 64}}); }

} // namespace FmakmInferShapeUT
