/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file test_inplace_apply_power_sign_infershape.cpp
 * \brief InplaceApplyPowerSign infershape unit tests
 *
 * Generated By CANNBot
 */

#include <gtest/gtest.h>
#include <iostream>
#include "infershape_test_util.h"
#include "ut_op_common.h"
#include "../../../op_graph/inplace_apply_power_sign_proto.h"

class InplaceApplyPowerSignInferShape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "InplaceApplyPowerSignInferShape SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "InplaceApplyPowerSignInferShape TearDown" << std::endl; }
};

static std::vector<int64_t> ShapeToVec(const gert::Shape& shape)
{
    std::vector<int64_t> vec(shape.GetDimNum());
    for (size_t i = 0; i < shape.GetDimNum(); i++) {
        vec[i] = shape.GetDim(i);
    }
    return vec;
}

TEST_F(InplaceApplyPowerSignInferShape, infershape_case_0_2d)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyPowerSign"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyPowerSign")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);
    gert::StorageShape varShape = {{96, 256}, {96, 256}};
    gert::StorageShape mShape = {{96, 256}, {96, 256}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape logbaseShape = {{1}, {1}};
    gert::StorageShape signDecayShape = {{1}, {1}};
    gert::StorageShape betaShape = {{1}, {1}};
    gert::StorageShape gradShape = {{96, 256}, {96, 256}};

    gert::StorageShape varOutShape = {{96, 256}, {96, 256}};
    gert::StorageShape mOutShape = {{96, 256}, {96, 256}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(7, 2)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1})
                      .InputShapes(
                          {&varShape, &mShape, &lrShape, &logbaseShape, &signDecayShape, &betaShape, &gradShape})
                      .OutputShapes({&varOutShape, &mOutShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);

    auto* context = holder.GetContext<gert::InferShapeContext>();
    std::vector<int64_t> expectedVarOut = {96, 256};
    std::vector<int64_t> expectedMOut = {96, 256};
    EXPECT_EQ(ShapeToVec(*context->GetOutputShape(0)), expectedVarOut);
    EXPECT_EQ(ShapeToVec(*context->GetOutputShape(1)), expectedMOut);
}

TEST_F(InplaceApplyPowerSignInferShape, infershape_case_1_4d)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyPowerSign"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyPowerSign")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);
    gert::StorageShape varShape = {{2, 4, 8, 16}, {2, 4, 8, 16}};
    gert::StorageShape mShape = {{2, 4, 8, 16}, {2, 4, 8, 16}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape logbaseShape = {{1}, {1}};
    gert::StorageShape signDecayShape = {{1}, {1}};
    gert::StorageShape betaShape = {{1}, {1}};
    gert::StorageShape gradShape = {{2, 4, 8, 16}, {2, 4, 8, 16}};

    gert::StorageShape varOutShape = {{2, 4, 8, 16}, {2, 4, 8, 16}};
    gert::StorageShape mOutShape = {{2, 4, 8, 16}, {2, 4, 8, 16}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(7, 2)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1})
                      .InputShapes(
                          {&varShape, &mShape, &lrShape, &logbaseShape, &signDecayShape, &betaShape, &gradShape})
                      .OutputShapes({&varOutShape, &mOutShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);

    auto* context = holder.GetContext<gert::InferShapeContext>();
    std::vector<int64_t> expectedVarOut = {2, 4, 8, 16};
    std::vector<int64_t> expectedMOut = {2, 4, 8, 16};
    EXPECT_EQ(ShapeToVec(*context->GetOutputShape(0)), expectedVarOut);
    EXPECT_EQ(ShapeToVec(*context->GetOutputShape(1)), expectedMOut);
}

TEST_F(InplaceApplyPowerSignInferShape, infershape_case_2_1d)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyPowerSign"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("InplaceApplyPowerSign")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);
    gert::StorageShape varShape = {{16}, {16}};
    gert::StorageShape mShape = {{16}, {16}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape logbaseShape = {{1}, {1}};
    gert::StorageShape signDecayShape = {{1}, {1}};
    gert::StorageShape betaShape = {{1}, {1}};
    gert::StorageShape gradShape = {{16}, {16}};

    gert::StorageShape varOutShape = {{16}, {16}};
    gert::StorageShape mOutShape = {{16}, {16}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(7, 2)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1, 1})
                      .InputShapes(
                          {&varShape, &mShape, &lrShape, &logbaseShape, &signDecayShape, &betaShape, &gradShape})
                      .OutputShapes({&varOutShape, &mOutShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);

    auto* context = holder.GetContext<gert::InferShapeContext>();
    std::vector<int64_t> expectedVarOut = {16};
    std::vector<int64_t> expectedMOut = {16};
    EXPECT_EQ(ShapeToVec(*context->GetOutputShape(0)), expectedVarOut);
    EXPECT_EQ(ShapeToVec(*context->GetOutputShape(1)), expectedMOut);
}
