/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file npu_clear_float_status_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_NPUCLEARFLOATSTATUS_H_
#define OPS_OP_PROTO_INC_NPUCLEARFLOATSTATUS_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief Clears the float overflow status on NPU.
 *@par Inputs:
 *One input, including:
 * @li addr: A ND Tensor of type float32. Shape (8,). \n

 *@par Outputs:
 *data: A ND Tensor of type float32. Shape (8,).
 */
#ifndef OPS_PROTO_DEF_NPUCLEARFLOATSTATUS
#define OPS_PROTO_DEF_NPUCLEARFLOATSTATUS
REG_OP(NPUClearFloatStatus)
    .INPUT(addr, TensorType({DT_FLOAT}))
    .OUTPUT(data, TensorType({DT_FLOAT}))
    .OP_END_FACTORY_REG(NPUClearFloatStatus)
#endif

} // namespace ge

#endif // OPS_OP_PROTO_INC_NPUCLEARFLOATSTATUS_H_
