/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#pragma once

#include <cstdint>
#include <type_traits>

#include "kernel_operator.h"
#include "adv_api/math/power.h"
#include "sigmoid_focal_loss_grad_tiling_struct.h"

static constexpr AscendC::PowerConfig kHighPrecisionPowerConfig = {AscendC::PowerAlgo::DOUBLE_FLOAT_TECH};

static constexpr AscendC::Reg::CastTrait kB16ToF32 = {AscendC::Reg::RegLayout::ZERO, AscendC::Reg::SatMode::UNKNOWN,
                                                      AscendC::Reg::MaskMergeMode::ZEROING,
                                                      AscendC::RoundMode::CAST_NONE};
static constexpr AscendC::Reg::CastTrait kF32ToB16 = {AscendC::Reg::RegLayout::ZERO, AscendC::Reg::SatMode::NO_SAT,
                                                      AscendC::Reg::MaskMergeMode::ZEROING,
                                                      AscendC::RoundMode::CAST_RINT};
static constexpr AscendC::Reg::CastTrait kS32ToF32 = {AscendC::Reg::RegLayout::ZERO, AscendC::Reg::SatMode::UNKNOWN,
                                                      AscendC::Reg::MaskMergeMode::ZEROING,
                                                      AscendC::RoundMode::CAST_RINT};

template <typename PredT, typename DoutT, typename WeightT, bool HAS_WEIGHT>
__simd_vf__ inline void PrepareInputsVf(__ubuf__ float* predDst, __ubuf__ float* targetDst, __ubuf__ float* doutDst,
                                        __ubuf__ float* weightDst, __ubuf__ PredT* predSrc, __ubuf__ int32_t* targetSrc,
                                        __ubuf__ DoutT* doutSrc, __ubuf__ WeightT* weightSrc, uint32_t count,
                                        uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    AscendC::Reg::RegTensor<float> predF, targetF, doutF, weightF;
    AscendC::Reg::RegTensor<PredT> predRaw;
    AscendC::Reg::RegTensor<int32_t> targetRaw;
    AscendC::Reg::RegTensor<DoutT> doutRaw;
    AscendC::Reg::RegTensor<WeightT> weightRaw;
    AscendC::Reg::MaskReg mask;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        if constexpr (std::is_same_v<PredT, half>) {
            AscendC::Reg::LoadAlign<half, AscendC::Reg::LoadDist::DIST_UNPACK_B16>(predRaw, predSrc + off);
            AscendC::Reg::Cast<float, half, kB16ToF32>(predF, predRaw, mask);
        } else {
            AscendC::Reg::LoadAlign(predF, reinterpret_cast<__ubuf__ float*>(predSrc) + off);
        }
        AscendC::Reg::LoadAlign(targetRaw, targetSrc + off);
        AscendC::Reg::Cast<float, int32_t, kS32ToF32>(targetF, targetRaw, mask);
        if constexpr (std::is_same_v<DoutT, half>) {
            AscendC::Reg::LoadAlign<half, AscendC::Reg::LoadDist::DIST_UNPACK_B16>(doutRaw, doutSrc + off);
            AscendC::Reg::Cast<float, half, kB16ToF32>(doutF, doutRaw, mask);
        } else {
            AscendC::Reg::LoadAlign(doutF, reinterpret_cast<__ubuf__ float*>(doutSrc) + off);
        }
        if constexpr (HAS_WEIGHT) {
            if constexpr (std::is_same_v<WeightT, half>) {
                AscendC::Reg::LoadAlign<half, AscendC::Reg::LoadDist::DIST_UNPACK_B16>(weightRaw, weightSrc + off);
                AscendC::Reg::Cast<float, half, kB16ToF32>(weightF, weightRaw, mask);
            } else {
                AscendC::Reg::LoadAlign(weightF, reinterpret_cast<__ubuf__ float*>(weightSrc) + off);
            }
            AscendC::Reg::StoreAlign(weightDst + off, weightF, mask);
        }
        AscendC::Reg::StoreAlign(predDst + off, predF, mask);
        AscendC::Reg::StoreAlign(targetDst + off, targetF, mask);
        AscendC::Reg::StoreAlign(doutDst + off, doutF, mask);
    }
}

__simd_vf__ inline void StableSigmoidExpVf(__ubuf__ float* positiveDst, __ubuf__ float* expDst, __ubuf__ float* predSrc,
                                           uint32_t count, uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    static constexpr AscendC::Reg::ExpSpecificMode kExpMode = {AscendC::Reg::MaskMergeMode::ZEROING,
                                                               AscendC::ExpAlgo::PRECISION_1ULP_FTZ_FALSE};
    static constexpr AscendC::Reg::DivSpecificMode kDivMode = {AscendC::Reg::MaskMergeMode::ZEROING, false,
                                                               AscendC::DivAlgo::PRECISION_0ULP_FTZ_FALSE};
    AscendC::Reg::RegTensor<float> x, absX, negAbsX, e, denom;
    AscendC::Reg::RegTensor<float> one, positive;
    AscendC::Reg::MaskReg mask;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(x, predSrc + off);
        AscendC::Reg::Duplicate(one, 1.0f);
        AscendC::Reg::Abs(absX, x, mask);
        AscendC::Reg::Neg(negAbsX, absX, mask);
        AscendC::Reg::Exp<float, &kExpMode>(e, negAbsX, mask);
        AscendC::Reg::Adds(denom, e, 1.0f, mask);
        AscendC::Reg::Div<float, &kDivMode>(positive, one, denom, mask);
        AscendC::Reg::StoreAlign(positiveDst + off, positive, mask);
        AscendC::Reg::StoreAlign(expDst + off, e, mask);
    }
}

__simd_vf__ inline void StableSigmoidVf(__ubuf__ float* pDst, __ubuf__ float* pFloorDst, __ubuf__ float* qDst,
                                        __ubuf__ float* qFloorDst, __ubuf__ float* predSrc, uint32_t count,
                                        uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    constexpr float kLogEps = 1.17549435e-38f;
    static constexpr AscendC::Reg::ExpSpecificMode kExpMode = {AscendC::Reg::MaskMergeMode::ZEROING,
                                                               AscendC::ExpAlgo::PRECISION_1ULP_FTZ_FALSE};
    static constexpr AscendC::Reg::DivSpecificMode kDivMode = {AscendC::Reg::MaskMergeMode::ZEROING, false,
                                                               AscendC::DivAlgo::PRECISION_0ULP_FTZ_FALSE};
    AscendC::Reg::RegTensor<float> x, absX, one, positive, directExp, negativeDenom, negative;
    AscendC::Reg::RegTensor<float> p, q, pFloor, qFloor;
    AscendC::Reg::MaskReg mask, nonNegative;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(x, predSrc + off);
        AscendC::Reg::LoadAlign(positive, pDst + off);
        AscendC::Reg::Duplicate(one, 1.0f);
        AscendC::Reg::Abs(absX, x, mask);
        AscendC::Reg::Exp<float, &kExpMode>(directExp, absX, mask);
        AscendC::Reg::Adds(negativeDenom, directExp, 1.0f, mask);
        AscendC::Reg::Div<float, &kDivMode>(negative, one, negativeDenom, mask);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::GE>(nonNegative, x, 0.0f, mask);
        AscendC::Reg::Select<float>(p, positive, negative, nonNegative);
        AscendC::Reg::Neg(q, p, mask);
        AscendC::Reg::Adds(q, q, 1.0f, mask);
        AscendC::Reg::Maxs(pFloor, p, kLogEps, mask);
        AscendC::Reg::Maxs(qFloor, q, kLogEps, mask);
        AscendC::Reg::StoreAlign(pDst + off, p, mask);
        AscendC::Reg::StoreAlign(pFloorDst + off, pFloor, mask);
        AscendC::Reg::StoreAlign(qDst + off, q, mask);
        AscendC::Reg::StoreAlign(qFloorDst + off, qFloor, mask);
    }
}

__simd_vf__ inline void DetectClampedPowerBaseVf(__ubuf__ float* minBaseDst, __ubuf__ float* pBaseSrc,
                                                 __ubuf__ float* qBaseSrc, uint32_t count, uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    AscendC::Reg::RegTensor<float> pBase, qBase, currentMin, tileMin, reducedMin;
    AscendC::Reg::MaskReg mask;
    AscendC::Reg::MaskReg fullMask = AscendC::Reg::CreateMask<float>();
    AscendC::Reg::MaskReg firstMask = AscendC::Reg::CreateMask<float, AscendC::Reg::MaskPattern::VL1>();
    AscendC::Reg::Duplicate(tileMin, 3.402823466e+38f, fullMask);
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(pBase, pBaseSrc + off);
        AscendC::Reg::LoadAlign(qBase, qBaseSrc + off);
        AscendC::Reg::Min(currentMin, pBase, qBase, mask);
        AscendC::Reg::Min(tileMin, tileMin, currentMin, mask);
    }
    AscendC::Reg::Reduce<AscendC::Reg::ReduceType::MIN>(reducedMin, tileMin, fullMask);
    AscendC::Reg::StoreAlign(minBaseDst, reducedMin, firstMask);
}

__simd_vf__ inline void CorrectClampedPowerVf(__ubuf__ float* powGammaDst, __ubuf__ float* powGammaPlusOneDst,
                                              __ubuf__ float* baseSrc, float gamma, uint32_t count,
                                              uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    constexpr float kLogEps = 1.17549435e-38f;
    static constexpr AscendC::Reg::ExpSpecificMode kExpMode = {AscendC::Reg::MaskMergeMode::ZEROING,
                                                               AscendC::ExpAlgo::PRECISION_1ULP_FTZ_FALSE};
    AscendC::Reg::RegTensor<float> base, logBase, tmp, current, fallback;
    AscendC::Reg::MaskReg mask, clamped, subnormal, needsFallback;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(base, baseSrc + off);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::LE>(clamped, base, kLogEps, mask);
        AscendC::Reg::Ln(logBase, base, mask);

        AscendC::Reg::LoadAlign(current, powGammaDst + off);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::LE>(subnormal, current, kLogEps, mask);
        AscendC::Reg::MaskOr(needsFallback, clamped, subnormal, mask);
        AscendC::Reg::Muls(tmp, logBase, gamma, mask);
        AscendC::Reg::Exp<float, &kExpMode>(fallback, tmp, mask);
        AscendC::Reg::Select<float>(current, fallback, current, needsFallback);
        AscendC::Reg::StoreAlign(powGammaDst + off, current, mask);

        AscendC::Reg::LoadAlign(current, powGammaPlusOneDst + off);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::LE>(subnormal, current, kLogEps, mask);
        AscendC::Reg::MaskOr(needsFallback, clamped, subnormal, mask);
        AscendC::Reg::Muls(tmp, logBase, gamma + 1.0f, mask);
        AscendC::Reg::Exp<float, &kExpMode>(fallback, tmp, mask);
        AscendC::Reg::Select<float>(current, fallback, current, needsFallback);
        AscendC::Reg::StoreAlign(powGammaPlusOneDst + off, current, mask);
    }
}

__simd_vf__ inline void DPosVf(__ubuf__ float* dst, __ubuf__ float* pSrc, __ubuf__ float* pFloorSrc,
                               __ubuf__ float* qGammaSrc, __ubuf__ float* qGamma1Src, float alpha, float gamma,
                               uint32_t count, uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    constexpr float kMinNormal = 1.17549435e-38f;
    constexpr float kMaxFloat = 3.402823466e+38f;
    AscendC::Reg::RegTensor<float> p, q, pFloor, qGamma, qGamma1, logP, reconstructed, corrected, original, lhs, rhs;
    AscendC::Reg::RegTensor<float> absOriginal, absLhs, absRhs, maxTerm, cancellationLimit;
    AscendC::Reg::MaskReg mask, cancellation, nonzeroTerms, qNormal, qGamma1Normal, qGamma1Finite;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(p, pSrc + off);
        AscendC::Reg::LoadAlign(pFloor, pFloorSrc + off);
        AscendC::Reg::LoadAlign(qGamma, qGammaSrc + off);
        AscendC::Reg::LoadAlign(qGamma1, qGamma1Src + off);
        AscendC::Reg::Ln(logP, pFloor, mask);
        AscendC::Reg::Neg(q, p, mask);
        AscendC::Reg::Adds(q, q, 1.0f, mask);
        AscendC::Reg::Mul(lhs, qGamma, logP, mask);
        AscendC::Reg::Mul(lhs, lhs, p, mask);
        AscendC::Reg::Muls(lhs, lhs, gamma * alpha, mask);
        AscendC::Reg::Muls(rhs, qGamma1, alpha, mask);
        AscendC::Reg::Sub(original, lhs, rhs, mask);
        AscendC::Reg::Div(reconstructed, qGamma1, q, mask);
        AscendC::Reg::Mul(corrected, reconstructed, logP, mask);
        AscendC::Reg::Mul(corrected, corrected, p, mask);
        AscendC::Reg::Muls(corrected, corrected, gamma * alpha, mask);
        AscendC::Reg::Sub(corrected, corrected, rhs, mask);
        AscendC::Reg::Abs(absOriginal, original, mask);
        AscendC::Reg::Abs(absLhs, lhs, mask);
        AscendC::Reg::Abs(absRhs, rhs, mask);
        AscendC::Reg::Max(maxTerm, absLhs, absRhs, mask);
        AscendC::Reg::Muls(cancellationLimit, maxTerm, 0.015625f, mask);
        AscendC::Reg::Compare<float, AscendC::CMPMODE::LE>(cancellation, absOriginal, cancellationLimit, mask);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::GT>(nonzeroTerms, maxTerm, kMinNormal, mask);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::GT>(qNormal, q, kMinNormal, mask);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::GT>(qGamma1Normal, qGamma1, kMinNormal, mask);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::LE>(qGamma1Finite, qGamma1, kMaxFloat, mask);
        AscendC::Reg::Select<float>(corrected, corrected, original, cancellation);
        AscendC::Reg::Select<float>(corrected, corrected, original, nonzeroTerms);
        AscendC::Reg::Select<float>(corrected, corrected, original, qNormal);
        AscendC::Reg::Select<float>(corrected, corrected, original, qGamma1Normal);
        AscendC::Reg::Select<float>(corrected, corrected, original, qGamma1Finite);
        AscendC::Reg::StoreAlign(dst + off, corrected, mask);
    }
}

__simd_vf__ inline void DNegVf(__ubuf__ float* dst, __ubuf__ float* qSrc, __ubuf__ float* qFloorSrc,
                               __ubuf__ float* pGammaSrc, __ubuf__ float* pGamma1Src, float alpha, float gamma,
                               uint32_t count, uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    AscendC::Reg::RegTensor<float> q, qFloor, pGamma, pGamma1, logQ, lhs, rhs, oneMinusAlphaReg;
    AscendC::Reg::MaskReg mask, oneMinusAlphaIsOne;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(q, qSrc + off);
        AscendC::Reg::LoadAlign(qFloor, qFloorSrc + off);
        AscendC::Reg::LoadAlign(pGamma, pGammaSrc + off);
        AscendC::Reg::LoadAlign(pGamma1, pGamma1Src + off);
        AscendC::Reg::Ln(logQ, qFloor, mask);
        AscendC::Reg::Mul(lhs, pGamma, q, mask);
        AscendC::Reg::Mul(lhs, lhs, logQ, mask);
        AscendC::Reg::Muls(lhs, lhs, gamma * (alpha - 1.0f), mask);
        const float oneMinusAlpha = 1.0f - alpha;
        AscendC::Reg::Muls(rhs, pGamma1, oneMinusAlpha, mask);
        AscendC::Reg::Duplicate(oneMinusAlphaReg, oneMinusAlpha, mask);
        AscendC::Reg::Compares<float, AscendC::CMPMODE::EQ>(oneMinusAlphaIsOne, oneMinusAlphaReg, 1.0f, mask);
        AscendC::Reg::Select<float>(rhs, pGamma1, rhs, oneMinusAlphaIsOne);
        AscendC::Reg::Add(lhs, lhs, rhs, mask);
        AscendC::Reg::StoreAlign(dst + off, lhs, mask);
    }
}

__simd_vf__ inline void ComposeRawVf(__ubuf__ float* rawDst, __ubuf__ float* dposSrc, __ubuf__ float* dnegSrc,
                                     __ubuf__ float* targetSrc, uint32_t count, uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    AscendC::Reg::RegTensor<float> dpos, dneg, target;
    AscendC::Reg::RegTensor<float> oneMinusTarget, negTerm, work;
    AscendC::Reg::MaskReg mask;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(dpos, dposSrc + off);
        AscendC::Reg::LoadAlign(dneg, dnegSrc + off);
        AscendC::Reg::LoadAlign(target, targetSrc + off);
        AscendC::Reg::Neg(oneMinusTarget, target, mask);
        AscendC::Reg::Adds(oneMinusTarget, oneMinusTarget, 1.0f, mask);
        AscendC::Reg::Mul(work, dpos, oneMinusTarget, mask);
        AscendC::Reg::Mul(negTerm, dneg, target, mask);
        AscendC::Reg::Add(work, work, negTerm, mask);
        AscendC::Reg::StoreAlign(rawDst + off, work, mask);
    }
}

template <typename PredT, bool HAS_WEIGHT>
__simd_vf__ inline void ScaleStoreVf(__ubuf__ PredT* gradDst, __ubuf__ float* weightedDst, __ubuf__ float* scaledDst,
                                     __ubuf__ float* rawSrc, __ubuf__ float* weightSrc, __ubuf__ float* doutSrc,
                                     float reduceMeanCoef, uint32_t count, uint16_t repeatTimes)
{
    constexpr uint32_t kVl = 256 / sizeof(float);
    static constexpr AscendC::Reg::DivSpecificMode kDivMode = {AscendC::Reg::MaskMergeMode::ZEROING, false,
                                                               AscendC::DivAlgo::PRECISION_0ULP_FTZ_FALSE};
    AscendC::Reg::RegTensor<float> raw, weight, dout, weighted, scaled;
    AscendC::Reg::RegTensor<float> one, weightReciprocal, doutReciprocal, preciseWeighted, preciseScaled;
    AscendC::Reg::RegTensor<float> absRaw, absWeight, absWeighted;
    AscendC::Reg::RegTensor<PredT> grad;
    AscendC::Reg::MaskReg mask, weightedSubnormal, rawNonzero, weightNonzero, recoverSubnormal;
    uint32_t remaining = count;
    for (uint16_t i = 0; i < repeatTimes; ++i) {
        const int32_t off = static_cast<int32_t>(i) * kVl;
        mask = AscendC::Reg::UpdateMask<float>(remaining);
        AscendC::Reg::LoadAlign(raw, rawSrc + off);
        AscendC::Reg::LoadAlign(dout, doutSrc + off);
        if constexpr (HAS_WEIGHT) {
            AscendC::Reg::LoadAlign(weight, weightSrc + off);
            AscendC::Reg::Mul(weighted, raw, weight, mask);
        } else {
            AscendC::Reg::Muls(weighted, raw, 1.0f, mask);
        }
        AscendC::Reg::Mul(scaled, weighted, dout, mask);
        if constexpr (HAS_WEIGHT) {
            AscendC::Reg::Abs(absRaw, raw, mask);
            AscendC::Reg::Abs(absWeight, weight, mask);
            AscendC::Reg::Abs(absWeighted, weighted, mask);
            AscendC::Reg::Compares<float, AscendC::CMPMODE::LT>(weightedSubnormal, absWeighted, 1.17549435e-38f, mask);
            AscendC::Reg::Compares<float, AscendC::CMPMODE::GT>(rawNonzero, absRaw, 0.0f, mask);
            AscendC::Reg::Compares<float, AscendC::CMPMODE::GT>(weightNonzero, absWeight, 0.0f, mask);
            AscendC::Reg::MaskAnd(recoverSubnormal, weightedSubnormal, rawNonzero, mask);
            AscendC::Reg::MaskAnd(recoverSubnormal, recoverSubnormal, weightNonzero, mask);
            AscendC::Reg::Duplicate(one, 1.0f);
            AscendC::Reg::Div<float, &kDivMode>(weightReciprocal, one, weight, recoverSubnormal);
            AscendC::Reg::Div<float, &kDivMode>(preciseWeighted, raw, weightReciprocal, recoverSubnormal);
            AscendC::Reg::Div<float, &kDivMode>(doutReciprocal, one, dout, recoverSubnormal);
            AscendC::Reg::Div<float, &kDivMode>(preciseScaled, preciseWeighted, doutReciprocal, recoverSubnormal);
            AscendC::Reg::Select<float>(scaled, preciseScaled, scaled, recoverSubnormal);
        }
        AscendC::Reg::Muls(scaled, scaled, reduceMeanCoef, mask);
        AscendC::Reg::StoreAlign(weightedDst + off, weighted, mask);
        AscendC::Reg::StoreAlign(scaledDst + off, scaled, mask);
        if constexpr (std::is_same_v<PredT, float>) {
            AscendC::Reg::StoreAlign(reinterpret_cast<__ubuf__ float*>(gradDst) + off, scaled, mask);
        } else {
            AscendC::Reg::Cast<half, float, kF32ToB16>(grad, scaled, mask);
            AscendC::Reg::StoreAlign<half, AscendC::Reg::StoreDist::DIST_PACK_B32>(gradDst + off, grad, mask);
        }
    }
}

__aicore__ inline void GetBlockWork(const SigmoidFocalLossGradTilingData* td, uint64_t blockId, uint64_t& blockLength,
                                    uint64_t& loopNum, uint64_t& tailNum)
{
    const bool isTailBlock = blockId + 1 == static_cast<uint64_t>(td->blockNum);
    blockLength = isTailBlock ?
                      static_cast<uint64_t>(td->dim0) - (static_cast<uint64_t>(td->blockNum) - 1) * td->blockFormer :
                      static_cast<uint64_t>(td->blockFormer);
    loopNum = isTailBlock ? td->ubLoopOfTailBlock : td->ubLoopOfFormerBlock;
    tailNum = isTailBlock ? td->ubTailOfTailBlock : td->ubTailOfFormerBlock;
}

template <typename T>
__aicore__ inline __ubuf__ T* GetUbPtr(AscendC::TBuf<AscendC::TPosition::VECCALC>& buf)
{
    return (__ubuf__ T*)buf.template Get<T>().GetPhyAddr();
}

template <typename T>
__aicore__ inline void CopyDenseIn(AscendC::TBuf<AscendC::TPosition::VECCALC>& dst, AscendC::GlobalTensor<T>& src,
                                   uint64_t offset, uint64_t count)
{
    const uint32_t blockLen = static_cast<uint32_t>(count * sizeof(T));
    const uint32_t remainBytes = blockLen & 31U;
    const uint8_t rightPadding = remainBytes == 0 ? 0 : static_cast<uint8_t>((32U - remainBytes) / sizeof(T));
    const AscendC::DataCopyExtParams copyParams{1, blockLen, 0, 0, 0};
    const AscendC::DataCopyPadExtParams<T> padParams{rightPadding != 0, 0, rightPadding, static_cast<T>(0)};
    AscendC::DataCopyPad(dst.template Get<T>(), src[offset], copyParams, padParams);
}

#include "sigmoid_focal_loss_grad_kernel_impl.h"
