/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file in_training_reduce_grad.cpp
 * \brief INTrainingReduceGrad 算子 kernel 入口（arch35 架构）
 *
 * 模板参数 RANK 由 ASCENDC_TPL_UINT_DECL 定义（4=≤4D, 8=5-8D）
 * dtype 由 def 文件 DataType 列表驱动，构建系统注入 DTYPE_DY 编译宏
 *
 * 核函数签名契约：参数顺序须与 op_def I/O 一致（输入→输出→workspace→tiling）
 */

#include "kernel_operator.h"
#include "arch35/in_training_reduce_grad.h"

template <int RANK>
__global__ __aicore__ void in_training_reduce_grad(GM_ADDR dy, GM_ADDR x, GM_ADDR variance, GM_ADDR mean,
                                                   GM_ADDR res_gamma, GM_ADDR res_beta, GM_ADDR gamma, GM_ADDR pd_x,
                                                   GM_ADDR workspace, GM_ADDR tiling)
{
    AscendC::InitSocState();
    GM_ADDR ins[MAX_INPUT_SLOTS] = {dy, x, variance, mean, res_gamma, res_beta, gamma};
    GM_ADDR outs[MAX_OUTPUT_SLOTS] = {pd_x};
    REGISTER_NONE_TILING;
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);
    if constexpr (RANK == IN_TRAINING_REDUCE_GRAD_RANK_4) {
        GET_TILING_DATA_WITH_STRUCT(INTrainingReduceGradTilingData<IN_TRAINING_REDUCE_GRAD_RANK_4>, td, tiling);
        INTrainingReduceGradKernel<DTYPE_DY, IN_TRAINING_REDUCE_GRAD_RANK_4> kernel;
        kernel.Init(ins, outs, &td);
        kernel.Process();
    } else {
        GET_TILING_DATA_WITH_STRUCT(INTrainingReduceGradTilingData<IN_TRAINING_REDUCE_GRAD_RANK_8>, td, tiling);
        INTrainingReduceGradKernel<DTYPE_DY, IN_TRAINING_REDUCE_GRAD_RANK_8> kernel;
        kernel.Init(ins, outs, &td);
        kernel.Process();
    }
    AscendC::PipeBarrier<PIPE_ALL>();
}
