/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/* !
 * \file inplace_apply_add_sign_infershape.cpp
 * \brief inplace_apply_add_sign_infershape source file
 */
#include "register/op_impl_registry.h"

#include "graph/types.h"
#include "log/log.h"

using namespace ge;

namespace ops {

// InferShapeForInplaceApplyAddSign: GE shape inference callback.
//   Derivation: var_out.shape = var.shape, m_out.shape = m.shape (in-place
//   update keeps the output shapes identical to the inputs).
//   When either var or m is unknown rank, both outputs inherit unknown rank
//   because var.shape == m.shape (merge constraint).
//   Returns GRAPH_FAILED on null input/output shape pointers.
static ge::graphStatus InferShapeForInplaceApplyAddSign(gert::InferShapeContext* context)
{
    const gert::Shape* varShape = context->GetInputShape(0);
    const gert::Shape* mShape = context->GetInputShape(1);
    gert::Shape* varOutShape = context->GetOutputShape(0);
    gert::Shape* mOutShape = context->GetOutputShape(1);
    if (varShape == nullptr || mShape == nullptr || varOutShape == nullptr || mOutShape == nullptr) {
        OP_LOGE(context, "InplaceApplyAddSign: input/output shape ptr is null, var=%p, m=%p, var_out=%p, m_out=%p.",
                static_cast<const void*>(varShape), static_cast<const void*>(mShape), static_cast<void*>(varOutShape),
                static_cast<void*>(mOutShape));
        return GRAPH_FAILED;
    }

    // Unknown rank: a 1-D shape whose only dim is UNKNOWN_DIM_NUM.
    // If either var or m is unknown rank, both outputs inherit it
    // (var.shape == m.shape merge constraint).
    const auto isUnknownRank = [](const gert::Shape* s) -> bool {
        return s->GetDimNum() == 1U && s->GetDim(0) == ge::UNKNOWN_DIM_NUM;
    };
    if (isUnknownRank(varShape) || isUnknownRank(mShape)) {
        varOutShape->SetDimNum(1);
        varOutShape->SetDim(0, ge::UNKNOWN_DIM_NUM);
        mOutShape->SetDimNum(1);
        mOutShape->SetDim(0, ge::UNKNOWN_DIM_NUM);
        return GRAPH_SUCCESS;
    }

    // var_out.shape = var.shape (in-place update)
    varOutShape->SetDimNum(varShape->GetDimNum());
    for (size_t i = 0; i < varShape->GetDimNum(); ++i) {
        varOutShape->SetDim(i, varShape->GetDim(i));
    }

    // m_out.shape = m.shape (in-place update)
    mOutShape->SetDimNum(mShape->GetDimNum());
    for (size_t i = 0; i < mShape->GetDimNum(); ++i) {
        mOutShape->SetDim(i, mShape->GetDim(i));
    }

    return GRAPH_SUCCESS;
}

// IMPL_OP_INFERSHAPE(InplaceApplyAddSign).InferShape(...): registers the shape
// inference function for the operator named "InplaceApplyAddSign" at static init.
IMPL_OP_INFERSHAPE(InplaceApplyAddSign).InferShape(InferShapeForInplaceApplyAddSign);

} // namespace ops
