/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file lars_v2_update_tiling_arch35.cpp
 * \brief LarsV2Update 算子 Host 侧 Tiling 计算（arch35 / Ascend950）
 */

#include "register/op_def_registry.h"
#include "../lars_v2_update_tiling.h"
#include "tiling/platform/platform_ascendc.h"
#include "exe_graph/runtime/tiling_context.h"
#include "../../op_kernel/arch35/lars_v2_update_tiling_data.h"
#include "../../op_kernel/arch35/lars_v2_update_tiling_key.h"
#include "log/log.h"

using Ops::Base::ToString;

namespace optiling {
namespace {
constexpr size_t MAX_DIM_NUM = 8;
const std::set<ge::DataType> SUPPORTED_DTYPES = {ge::DT_FLOAT};
// TilingKey constants. The kernel binary uses these to select the
// RANK=4 / RANK=8 template instantiation.
// LARS_V2_UPDATE_RANK_4 / LARS_V2_UPDATE_RANK_8 defined in tiling_key.h

// Extract an origin-shape dim list from a StorageShape (GetShapeInfo).
std::vector<int64_t> ShapeToVector(const gert::StorageShape* shp)
{
    std::vector<int64_t> v;
    if (shp == nullptr)
        return v;
    const gert::Shape& s = shp->GetOriginShape();
    v.reserve(s.GetDimNum());
    for (size_t i = 0; i < s.GetDimNum(); i++)
        v.push_back(s.GetDim(i));
    return v;
}

// Precompute GM strides for a (squeezed) normal shape in the broadcast coord
// system (PrecomputeInputStrides/PrecomputeOutputStrides).
// stride[d] = 0 on broadcast axes (normal[d]==1 && bro[d]>1), else the row-major
// product of higher dims of the input's own shape.
std::vector<int64_t> ComputeStrides(const std::vector<int64_t>& normal, const std::vector<int64_t>& bro)
{
    int64_t rank = static_cast<int64_t>(normal.size());
    std::vector<int64_t> strides(rank, 0);
    int64_t acc = 1;
    for (int64_t d = rank - 1; d >= 0; d--) {
        if (normal[d] == 1 && bro[d] > 1) {
            strides[d] = 0; // broadcast axis: NDDMA stride=0 reuses the element
        } else {
            strides[d] = acc;
        }
        acc *= normal[d];
    }
    return strides;
}

// Fill a LarsV2UpdateTilingData<kRank> from the computed tiling quantities.
// Dims beyond effective_rank are padded (shape=1, stride=0) — the kernel reads
// only [0, rank) per the `rank` field.
template <int64_t kRank>
void FillTilingData(LarsV2UpdateTilingData<kRank>* td, const SplitResult& split, const MultiCoreResult& mc,
                    int64_t eff_rank, int64_t per_buf_bytes, const std::vector<int64_t>& max_bro,
                    const std::vector<std::vector<int64_t>>& normal_in,
                    const std::vector<std::vector<int64_t>>& normal_out, const LarsAttrs& attrs)
{
    td->split = split;
    td->multicore = mc;
    td->rank = eff_rank;
    td->per_buf_bytes = per_buf_bytes;
    td->num_inputs = MAX_INPUT_SLOTS;
    td->num_outputs = MAX_OUTPUT_SLOTS;
    td->hyperpara = attrs.hyperpara;
    td->epsilon = attrs.epsilon;
    td->use_clip = attrs.use_clip;

    for (int64_t d = 0; d < kRank; d++) {
        td->max_bro_shape[d] = (d < eff_rank) ? max_bro[d] : 1;
    }
    for (int64_t i = 0; i < MAX_INPUT_SLOTS; i++) {
        for (int64_t d = 0; d < kRank; d++) {
            td->input_shapes[i][d] = (d < eff_rank) ? normal_in[i][d] : 1;
            td->input_strides[i][d] = 0;
        }
        if (i < static_cast<int64_t>(normal_in.size()) && static_cast<int64_t>(normal_in[i].size()) == eff_rank) {
            std::vector<int64_t> st = ComputeStrides(normal_in[i], max_bro);
            for (int64_t d = 0; d < eff_rank && d < kRank; d++) {
                td->input_strides[i][d] = st[d];
            }
        }
    }
    for (int64_t o = 0; o < MAX_OUTPUT_SLOTS; o++) {
        for (int64_t d = 0; d < kRank; d++) {
            td->output_shapes[o][d] = (d < eff_rank) ? normal_out[o][d] : 1;
            td->output_strides[o][d] = 0;
        }
        if (o < static_cast<int64_t>(normal_out.size()) && static_cast<int64_t>(normal_out[o].size()) == eff_rank) {
            std::vector<int64_t> st = ComputeStrides(normal_out[o], max_bro);
            for (int64_t d = 0; d < eff_rank && d < kRank; d++) {
                td->output_strides[o][d] = st[d];
            }
        }
    }
}
} // namespace

// TilingFunc glue (Tiling 整体结构):
//   1. GetShapeInfo — 6 in / 1 out shape + dtype_size + attrs; PadAndSqueeze; CheckBroadcastShape
//   2. mapped = ChooseTilingKey(effective_rank)
//   3. FindSplitAxis / MultiCoreSplit / per_buf_bytes / PrecomputeStrides
//   4. SetTilingKey / SetBlockDim(multicore.num_cores) / workspaces[0]=sysWorkspace
//
// key=4 -> TilingData4 (RANK=4 template), key=8 -> TilingData8 (RANK=8 template).
static ge::graphStatus TilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter LarsV2UpdateTilingFunc");
    // --- step 0: platform info ---
    auto platformInfo = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfo);
    platform_ascendc::PlatformAscendC plat(platformInfo);
    uint32_t coreNum = plat.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    uint64_t ubSize = 0;
    plat.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);

    // --- step 1: collect 6 in / 1 out shapes + dtype_size + attrs ---
    // dtype check: all 6 inputs must be DT_FLOAT (def.cpp:26-31)
    for (int64_t i = 0; i < MAX_INPUT_SLOTS; i++) {
        auto inputDesc = context->GetInputDesc(static_cast<size_t>(i));
        OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
        auto dt = inputDesc->GetDataType();
        OP_CHECK_IF(SUPPORTED_DTYPES.count(dt) == 0,
                    OP_LOGE(context, "LarsV2Update: input%d has incorrect dtype %s. It should be DT_FLOAT.",
                            static_cast<int32_t>(i), ToString(dt).c_str()),
                    return ge::GRAPH_FAILED);
        // format check: all 6 inputs must be FORMAT_ND (def.cpp:26-31)
        OP_CHECK_IF(inputDesc->GetStorageFormat() != ge::FORMAT_ND,
                    OP_LOGE(context, "LarsV2Update: input%d format is not ND.", static_cast<int32_t>(i)),
                    return ge::GRAPH_FAILED);
    }

    std::vector<std::vector<int64_t>> in_shapes(MAX_INPUT_SLOTS);
    for (int64_t i = 0; i < MAX_INPUT_SLOTS; i++) {
        in_shapes[i] = ShapeToVector(context->GetInputShape(static_cast<size_t>(i)));
        OP_CHECK_IF(in_shapes[i].size() > MAX_DIM_NUM,
                    OP_LOGE(context, "LarsV2Update: input%d dim num %zu must be less than or equal to 8.",
                            static_cast<int32_t>(i), in_shapes[i].size()),
                    return ge::GRAPH_FAILED);
        for (size_t d = 0; d < in_shapes[i].size(); d++) {
            OP_CHECK_IF(in_shapes[i][d] < 0,
                        OP_LOGE(context, "LarsV2Update: input%d dim%zu is negative (%lld).", static_cast<int32_t>(i), d,
                                static_cast<long long>(in_shapes[i][d])),
                        return ge::GRAPH_FAILED);
        }
    }
    std::vector<std::vector<int64_t>> out_shapes(MAX_OUTPUT_SLOTS);
    out_shapes[0] = ShapeToVector(context->GetOutputShape(0));

    // --- step 1a: shape constraints (README 约束的代码实现) ---
    // 约束1: w 和 g 必须具有相同的形状 (kernel 按 max_bro 共享布局读写 w/g/g_new).
    OP_CHECK_IF(in_shapes[0] != in_shapes[1], OP_LOGE(context, "LarsV2Update: w and g must have the same shape."),
                return ge::GRAPH_FAILED);
    // 约束2: 输出 g_new 与 w 同形 (InferShape 为 broadcast(w, g), w==g 时等价; 此处兜底校验).
    if (!out_shapes[0].empty()) {
        OP_CHECK_IF(out_shapes[0] != in_shapes[0],
                    OP_LOGE(context, "LarsV2Update: output g_new must have the same shape as w."),
                    return ge::GRAPH_FAILED);
    }
    // 约束3: w_square_sum / g_square_sum / weight_decay / learning_rate 必须为标量 (元素数 1).
    for (int64_t i = 2; i < MAX_INPUT_SLOTS; i++) {
        int64_t numel = 1;
        for (size_t d = 0; d < in_shapes[i].size(); d++) {
            numel *= in_shapes[i][d];
        }
        OP_CHECK_IF(numel != 1,
                    OP_LOGE(context, "LarsV2Update: input%d must be a scalar (1 element), got %lld elements.",
                            static_cast<int32_t>(i), static_cast<long long>(numel)),
                    return ge::GRAPH_FAILED);
    }

    int64_t dtypeSize = FP32_BYTES; // 固定 FP32

    const gert::RuntimeAttrs* attrs = context->GetAttrs();
    const float* hpAttr = (attrs != nullptr) ? attrs->GetFloat(0) : nullptr;
    const float* epsAttr = (attrs != nullptr) ? attrs->GetFloat(1) : nullptr;
    const bool* ucAttr = (attrs != nullptr) ? attrs->GetBool(2) : nullptr;
    LarsAttrs larsAttrs;
    ResolveAttrs(hpAttr, epsAttr, ucAttr, larsAttrs);

    // --- step 1b: PadAndSqueeze + CheckBroadcastShape ---
    std::vector<int64_t> max_bro;
    std::vector<std::vector<int64_t>> normal_in, normal_out;
    if (!PadAndSqueeze(in_shapes, out_shapes, max_bro, normal_in, normal_out)) {
        return ge::GRAPH_FAILED;
    }
    int64_t eff_rank = static_cast<int64_t>(max_bro.size());
    int64_t bad_dim = -1;
    if (!CheckBroadcastShape(normal_in, normal_out, eff_rank, &bad_dim)) {
        return ge::GRAPH_FAILED;
    }

    // --- step 2: TilingKey dispatch ---
    int64_t tilingKey = ChooseTilingKey(eff_rank);
    if (tilingKey < 0) {
        return ge::GRAPH_FAILED; // effective rank > 8 unsupported
    }

    // --- step 3: UB split + multi-core split + per_buf ---
    SplitResult split{};
    if (!FindSplitAxis(max_bro, dtypeSize, static_cast<int64_t>(ubSize), PHYS_NODES, split)) {
        return ge::GRAPH_FAILED;
    }
    MultiCoreResult mc{};
    if (!MultiCoreSplit(max_bro, split, static_cast<int64_t>(coreNum), mc)) {
        return ge::GRAPH_FAILED;
    }
    int64_t perBufBytes = ComputePerBufBytes(static_cast<int64_t>(ubSize), PHYS_NODES);

    // --- step 4: fill TilingData + set key/block-dim/workspace ---
    // key=4 -> TilingData4 (RANK=4 template), key=8 -> TilingData8 (RANK=8 template).
    if (tilingKey == LARS_V2_UPDATE_RANK_8) {
        TilingData8* td = context->GetTilingData<TilingData8>();
        OP_CHECK_NULL_WITH_CONTEXT(context, td);
        FillTilingData<8>(td, split, mc, eff_rank, perBufBytes, max_bro, normal_in, normal_out, larsAttrs);
        context->SetTilingKey(GET_TPL_TILING_KEY(LARS_V2_UPDATE_RANK_8));
    } else {
        TilingData4* td = context->GetTilingData<TilingData4>();
        OP_CHECK_NULL_WITH_CONTEXT(context, td);
        FillTilingData<4>(td, split, mc, eff_rank, perBufBytes, max_bro, normal_in, normal_out, larsAttrs);
        context->SetTilingKey(GET_TPL_TILING_KEY(LARS_V2_UPDATE_RANK_4));
    }

    context->SetBlockDim(static_cast<uint32_t>(mc.num_cores > 0 ? mc.num_cores : 1));

    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(plat.GetLibApiWorkSpaceSize());
    return ge::GRAPH_SUCCESS;
}

struct LarsV2UpdateCompileInfo {};

IMPL_OP_OPTILING(LarsV2Update)
    .Tiling(TilingFunc)
    .TilingParse<LarsV2UpdateCompileInfo>([]([[maybe_unused]] gert::TilingParseContext* context) {
        return ge::GRAPH_SUCCESS;
    });

} // namespace optiling
