/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file block_lstm_infershape.cpp
 * \brief InferShape for BlockLstm (host-side registration).
 *
 * InferDataType moved to op_graph/block_lstm_graph_infer.cpp (IMPL_OP
 * registration) per the transfer-test infer layout rule.
 */
#include "log/log.h"
#include "register/op_impl_registry.h"
#include "exe_graph/runtime/infer_shape_context.h"

namespace ge {

/* The operator has seven outputs, all [T, B, H]: i, cs, f, o, ci, co, h. */
constexpr int NUM_OUTPUTS = 7;

static ge::graphStatus InferShape4BlockLstm(gert::InferShapeContext* context)
{
    const gert::Shape* x = context->GetInputShape(1);
    const gert::Shape* csPrev = context->GetInputShape(2);
    if (x == nullptr || csPrev == nullptr) {
        OP_LOGE(context->GetNodeName(), "[BlockLstm] x/cs_prev shape is missing from the context.");
        return GRAPH_FAILED;
    }
    const size_t xr = x->GetDimNum();
    const size_t cr = csPrev->GetDimNum();

    /* Scalar inputs are not part of the contract (x is [T,B,I] rank 3) -- reject
     * them rather than treat rank 0 as an unknown rank. */
    if (xr == 0U || cr == 0U) {
        OP_LOGE(context->GetNodeName(), "[BlockLstm] scalar input is not supported: x rank(%zu), cs_prev rank(%zu).",
                xr, cr);
        return GRAPH_FAILED;
    }

    /* Unknown-rank (-2) inputs: the output dims cannot be determined until the
     * runtime shape binding supplies concrete values. Propagate UNKNOWN RANK to
     * the outputs (not a fabricated concrete shape); GE re-invokes InferShape
     * after the binding. */
    const bool xUnknownRank = (xr == 1U && x->GetDim(0) == -2);
    const bool csUnknownRank = (cr == 1U && csPrev->GetDim(0) == -2);
    if (xUnknownRank || csUnknownRank) {
        for (int k = 0; k < NUM_OUTPUTS; ++k) {
            gert::Shape* out = context->GetOutputShape(k);
            if (out == nullptr) {
                OP_LOGE(context->GetNodeName(), "[BlockLstm] output %d shape is missing.", k);
                return GRAPH_FAILED;
            }
            out->SetDimNum(1);
            out->SetDim(0, -2);
        }
        return GRAPH_SUCCESS;
    }

    if (xr != 3U || cr != 2U) {
        OP_LOGE(context->GetNodeName(),
                "[BlockLstm] x must be 3-D [T,B,I] and cs_prev 2-D [B,H], got x rank(%zu), cs_prev rank(%zu).", xr, cr);
        return GRAPH_FAILED;
    }
    /* Zero extents are propagated here as zero-element output shapes, but they are
     * NOT a supported execution case for this op: the tiling rejects any zero dim
     * (block_lstm_tiling.cpp, "dims out of range"), so the kernel never runs and GE
     * hands back empty outputs. InferShape stays a pure shape propagator -- input
     * validity is the tiling's call. (block_lstm_grad differs: its tiling checks
     * `< 0`, so it does accept zero extents.) */
    for (int k = 0; k < NUM_OUTPUTS; ++k) {
        gert::Shape* out = context->GetOutputShape(k);
        if (out == nullptr) {
            OP_LOGE(context->GetNodeName(), "[BlockLstm] output %d shape is missing.", k);
            return GRAPH_FAILED;
        }
        out->SetDimNum(3);
        /* Unknown DIMs (-1) copy through unchanged; the runtime shape binding
         * re-invokes InferShape with concrete values. */
        out->SetDim(0, x->GetDim(0));      // T
        out->SetDim(1, x->GetDim(1));      // B
        out->SetDim(2, csPrev->GetDim(1)); // H
    }
    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(BlockLstm).InferShape(InferShape4BlockLstm);

} // namespace ge
