/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file inplace_apply_power_sign_def.cpp
 * \brief InplaceApplyPowerSign operator definition (OpDef registration)
 *
 * Generated By CANNBot
 */
#include "register/op_def_registry.h"

namespace ops {
static const std::vector<ge::DataType> dataType = {ge::DT_BF16, ge::DT_FLOAT16, ge::DT_FLOAT};

static const std::vector<ge::Format> dataFormat = {ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND};

static const std::vector<ge::Format> paraFormat = {ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND};

class InplaceApplyPowerSign : public OpDef {
public:
    explicit InplaceApplyPowerSign(const char* name) : OpDef(name)
    {
        this->Input("var")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(dataFormat)
            .UnknownShapeFormat(dataFormat)
            .AutoContiguous();
        this->Input("m")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(dataFormat)
            .UnknownShapeFormat(dataFormat)
            .AutoContiguous();
        this->Input("lr")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(paraFormat)
            .UnknownShapeFormat(paraFormat)
            .AutoContiguous();
        this->Input("logbase")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(paraFormat)
            .UnknownShapeFormat(paraFormat)
            .AutoContiguous();
        this->Input("sign_decay")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(paraFormat)
            .UnknownShapeFormat(paraFormat)
            .AutoContiguous();
        this->Input("beta")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(paraFormat)
            .UnknownShapeFormat(paraFormat)
            .AutoContiguous();
        this->Input("grad")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(dataFormat)
            .UnknownShapeFormat(dataFormat)
            .AutoContiguous();
        this->Output("var")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(dataFormat)
            .UnknownShapeFormat(dataFormat)
            .AutoContiguous();
        this->Output("m")
            .ParamType(REQUIRED)
            .DataType(dataType)
            .Format(dataFormat)
            .UnknownShapeFormat(dataFormat)
            .AutoContiguous();

        this->Attr("use_locking").AttrType(OPTIONAL).Bool(false);

        OpAICoreConfig aiCoreConfig;
        aiCoreConfig.DynamicCompileStaticFlag(true)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .PrecisionReduceFlag(true);
        this->AICore().AddConfig("ascend950", aiCoreConfig);
    }
};

OP_ADD(InplaceApplyPowerSign);
} // namespace ops
