/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * @file test_geir_bn_training_update.cpp
 * @brief BNTrainingUpdate 静态 GE IR（图模式）调用示例（Ascend950 真机）
 *
 * 构造一张仅含 BNTrainingUpdate 节点的静态 NCHW 计算图并在 Ascend950 上执行：
 *   x{2,3,2,2}、sum/square_sum/scale/offset/mean/variance{3}，factor=0.25、epsilon=1e-3。
 *
 * CPU Golden 语义（与 docs spec/golden 一致）：
 *   batch_mean     = sum / M                       （M = numel(x) / C）
 *   batch_variance = square_sum / M - batch_mean^2
 *   multiplier     = scale / sqrt(|batch_variance + epsilon|)
 *   addend         = offset - multiplier * batch_mean
 *   y              = multiplier * x + addend
 *   mean_out       = factor * batch_mean + (1 - factor) * mean_old
 *   variance_out   = factor * (M / (M - 1)) * batch_variance + (1 - factor) * variance_old
 *
 * 校验图模式全链路：proto 注册 / OpDef(ascend950) / infershape + inferDataType /
 * tiling / kernel，并对全部 5 个输出做 Shape、dtype 与逐元素数值校验。
 */

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <map>
#include <string>
#include <vector>

#include "array_ops.h"
#include "ge_api.h"
#include "graph.h"
#include "../../op_graph/bn_training_update_proto.h"
#include "tensor.h"
#include "types.h"

namespace {

constexpr float kAtol = 1.0e-4F;
constexpr float kRtol = 1.0e-4F;
constexpr int64_t kChannels = 3;
constexpr float kFactor = 0.25F;
constexpr float kEpsilon = 1.0e-3F;
const std::vector<int64_t> kXShape = {2, 3, 2, 2};

struct Inputs {
    std::vector<float> x;
    std::vector<float> sum;
    std::vector<float> squareSum;
    std::vector<float> scale;
    std::vector<float> offset;
    std::vector<float> meanRef;
    std::vector<float> varianceRef;
};

struct Expected {
    std::vector<float> y;
    std::vector<float> meanOut;
    std::vector<float> varianceOut;
    std::vector<float> batchMean;
    std::vector<float> batchVariance;
};

size_t ElementCount(const std::vector<int64_t>& shape)
{
    size_t count = 1U;
    for (int64_t dim : shape) {
        count *= static_cast<size_t>(dim);
    }
    return count;
}

Inputs MakeInputs()
{
    Inputs inputs;
    const size_t channels = static_cast<size_t>(kChannels);
    const size_t elements = ElementCount(kXShape);
    inputs.x.resize(elements);
    inputs.sum.assign(channels, 0.0F);
    inputs.squareSum.assign(channels, 0.0F);
    inputs.scale.resize(channels);
    inputs.offset.resize(channels);
    inputs.meanRef.resize(channels);
    inputs.varianceRef.resize(channels);

    for (size_t channel = 0; channel < channels; ++channel) {
        inputs.scale[channel] = 0.75F + 0.25F * static_cast<float>(channel);
        inputs.offset[channel] = -0.2F + 0.15F * static_cast<float>(channel);
        inputs.meanRef[channel] = 0.25F * static_cast<float>(channel + 1U);
        inputs.varianceRef[channel] = 1.0F + 0.5F * static_cast<float>(channel);
    }

    const size_t spatial = static_cast<size_t>(kXShape[2] * kXShape[3]);
    for (size_t i = 0; i < elements; ++i) {
        const size_t channel = (i / spatial) % channels;
        const int pattern = static_cast<int>((i * 7U + channel * 3U) % 17U) - 8;
        const float value = 0.125F * static_cast<float>(pattern) + 0.2F * static_cast<float>(channel);
        inputs.x[i] = value;
        inputs.sum[channel] += value;
        inputs.squareSum[channel] += value * value;
    }
    return inputs;
}

Expected ComputeExpected(const Inputs& inputs)
{
    Expected expected;
    const size_t channels = static_cast<size_t>(kChannels);
    const float sampleCount = static_cast<float>(inputs.x.size() / channels);
    const float bessel = sampleCount == 1.0F ? 0.0F : sampleCount / (sampleCount - 1.0F);
    const float oldWeight = 1.0F - kFactor;

    expected.y.resize(inputs.x.size());
    expected.meanOut.resize(channels);
    expected.varianceOut.resize(channels);
    expected.batchMean.resize(channels);
    expected.batchVariance.resize(channels);
    std::vector<float> multiplier(channels);
    std::vector<float> addend(channels);

    for (size_t channel = 0; channel < channels; ++channel) {
        const float batchMean = inputs.sum[channel] / sampleCount;
        const float rawVariance = inputs.squareSum[channel] / sampleCount - batchMean * batchMean;
        const float batchVariance = rawVariance;
        multiplier[channel] = inputs.scale[channel] / std::sqrt(std::abs(batchVariance + kEpsilon));
        addend[channel] = inputs.offset[channel] - multiplier[channel] * batchMean;
        expected.batchMean[channel] = batchMean;
        expected.batchVariance[channel] = batchVariance;
        expected.meanOut[channel] = kFactor * batchMean + oldWeight * inputs.meanRef[channel];
        expected.varianceOut[channel] = kFactor * batchVariance * bessel + oldWeight * inputs.varianceRef[channel];
    }

    const size_t spatial = static_cast<size_t>(kXShape[2] * kXShape[3]);
    for (size_t i = 0; i < inputs.x.size(); ++i) {
        const size_t channel = (i / spatial) % channels;
        expected.y[i] = multiplier[channel] * inputs.x[i] + addend[channel];
    }
    return expected;
}

ge::Tensor MakeTensor(const std::vector<int64_t>& shape, ge::Format format, const std::vector<float>& values)
{
    ge::TensorDesc desc(ge::Shape(shape), format, ge::DT_FLOAT);
    desc.SetOriginShape(ge::Shape(shape));
    desc.SetOriginFormat(format);
    desc.SetPlacement(ge::kPlacementHost);
    desc.SetRealDimCnt(static_cast<int64_t>(shape.size()));
    std::vector<uint8_t> bytes(values.size() * sizeof(float));
    if (!bytes.empty()) {
        std::memcpy(bytes.data(), values.data(), bytes.size());
    }
    return ge::Tensor(desc, bytes);
}

bool Close(float actual, float expected)
{
    return std::isfinite(actual) && std::fabs(actual - expected) <= kAtol + kRtol * std::fabs(expected);
}

bool ValidateTensor(const ge::Tensor& actual, const std::vector<float>& expected,
                    const std::vector<int64_t>& expectedShape, const char* outputName)
{
    const ge::TensorDesc desc = actual.GetTensorDesc();
    const bool shapePass = desc.GetShape().GetDims() == expectedShape;
    const bool dtypePass = desc.GetDataType() == ge::DT_FLOAT;
    const bool sizePass = actual.GetSize() == expected.size() * sizeof(float);
    if (!shapePass || !dtypePass || !sizePass) {
        std::printf("  output %s metadata check not passed: shape_ok=%d dtype_ok=%d size_ok=%d\n", outputName,
                    shapePass ? 1 : 0, dtypePass ? 1 : 0, sizePass ? 1 : 0);
        return false;
    }
    const float* values = reinterpret_cast<const float*>(actual.GetData());
    for (size_t i = 0; i < expected.size(); ++i) {
        if (!Close(values[i], expected[i])) {
            std::printf("  output %s[%zu] got %.8g, expected %.8g\n", outputName, i, values[i], expected[i]);
            return false;
        }
    }
    return true;
}

std::string CurrentError()
{
    const ge::AscendString message = ge::GEGetErrorMsgV2();
    return message.GetString() == nullptr ? "" : message.GetString();
}

} // namespace

int main()
{
    const std::map<ge::AscendString, ge::AscendString> options = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    const ge::Status initStatus = ge::GEInitialize(options);
    if (initStatus != ge::SUCCESS) {
        std::fprintf(stderr, "GEInitialize status=%u error=%s\n", initStatus, CurrentError().c_str());
        return 1;
    }

    ge::Graph graph("bn_training_update_static_geir");
    auto bn = ge::op::BNTrainingUpdate("bn_training_update_static");

    ge::TensorDesc xDesc(ge::Shape(kXShape), ge::FORMAT_NCHW, ge::DT_FLOAT);
    xDesc.SetOriginShape(ge::Shape(kXShape));
    xDesc.SetOriginFormat(ge::FORMAT_NCHW);
    xDesc.SetRealDimCnt(4);
    const std::vector<int64_t> channelShape = {kChannels};
    ge::TensorDesc channelDesc(ge::Shape(channelShape), ge::FORMAT_ND, ge::DT_FLOAT);
    channelDesc.SetOriginShape(ge::Shape(channelShape));
    channelDesc.SetOriginFormat(ge::FORMAT_ND);
    channelDesc.SetRealDimCnt(1);

    auto x = ge::op::Data("bn_training_update_static_x").set_attr_index(0);
    auto sum = ge::op::Data("bn_training_update_static_sum").set_attr_index(1);
    auto squareSum = ge::op::Data("bn_training_update_static_square_sum").set_attr_index(2);
    auto scale = ge::op::Data("bn_training_update_static_scale").set_attr_index(3);
    auto offset = ge::op::Data("bn_training_update_static_offset").set_attr_index(4);
    auto meanRef = ge::op::Data("bn_training_update_static_mean_ref").set_attr_index(5);
    auto varianceRef = ge::op::Data("bn_training_update_static_variance_ref").set_attr_index(6);

    std::vector<ge::Operator> graphInputs;
    for (auto* data : {&x, &sum, &squareSum, &scale, &offset, &meanRef, &varianceRef}) {
        data->update_input_desc_x(data == &x ? xDesc : channelDesc);
        data->update_output_desc_y(data == &x ? xDesc : channelDesc);
        graph.AddOp(*data);
        graphInputs.push_back(*data);
    }

    bn.set_input_x(x)
        .set_input_sum(sum)
        .set_input_square_sum(squareSum)
        .set_input_scale(scale)
        .set_input_offset(offset)
        .set_input_mean(meanRef)
        .set_input_variance(varianceRef)
        .set_attr_factor(kFactor)
        .set_attr_epsilon(kEpsilon);
    bn.update_input_desc_x(xDesc);
    bn.update_input_desc_sum(channelDesc);
    bn.update_input_desc_square_sum(channelDesc);
    bn.update_input_desc_scale(channelDesc);
    bn.update_input_desc_offset(channelDesc);
    bn.update_input_desc_mean(channelDesc);
    bn.update_input_desc_variance(channelDesc);
    bn.update_output_desc_y(xDesc);
    ge::TensorDesc outputChannelDesc(ge::Shape(channelShape), ge::FORMAT_ND, ge::DT_FLOAT);
    outputChannelDesc.SetOriginShape(ge::Shape(channelShape));
    outputChannelDesc.SetOriginFormat(ge::FORMAT_ND);
    outputChannelDesc.SetRealDimCnt(1);
    bn.update_output_desc_mean(outputChannelDesc);
    bn.update_output_desc_variance(outputChannelDesc);
    bn.update_output_desc_batch_mean(outputChannelDesc);
    bn.update_output_desc_batch_variance(outputChannelDesc);

    graph.AddOp(bn);
    graph.SetInputs(graphInputs);
    const std::vector<std::pair<ge::Operator, std::vector<size_t>>> graphOutputs = {{bn, {0U, 1U, 2U, 3U, 4U}}};
    graph.SetOutputs(graphOutputs);

    const Inputs inputs = MakeInputs();
    const Expected expected = ComputeExpected(inputs);

    {
        ge::Session session(std::map<ge::AscendString, ge::AscendString>{});
        const ge::Status addStatus = session.AddGraph(0, graph, std::map<ge::AscendString, ge::AscendString>{});
        if (addStatus != ge::SUCCESS) {
            std::fprintf(stderr, "AddGraph status=%u error=%s\n", addStatus, CurrentError().c_str());
            ge::GEFinalize();
            return 1;
        }
        std::vector<ge::Tensor> feeds = {
            MakeTensor(kXShape, ge::FORMAT_NCHW, inputs.x),
            MakeTensor(channelShape, ge::FORMAT_ND, inputs.sum),
            MakeTensor(channelShape, ge::FORMAT_ND, inputs.squareSum),
            MakeTensor(channelShape, ge::FORMAT_ND, inputs.scale),
            MakeTensor(channelShape, ge::FORMAT_ND, inputs.offset),
            MakeTensor(channelShape, ge::FORMAT_ND, inputs.meanRef),
            MakeTensor(channelShape, ge::FORMAT_ND, inputs.varianceRef),
        };
        std::vector<ge::Tensor> outputs;
        const ge::Status runStatus = session.RunGraph(0, feeds, outputs);
        if (runStatus != ge::SUCCESS) {
            std::fprintf(stderr, "RunGraph status=%u error=%s\n", runStatus, CurrentError().c_str());
            ge::GEFinalize();
            return 1;
        }
        if (outputs.size() != 5U) {
            std::fprintf(stderr, "expected 5 outputs, got %zu\n", outputs.size());
            ge::GEFinalize();
            return 1;
        }
        const bool pass = ValidateTensor(outputs[0], expected.y, kXShape, "y") &&
                          ValidateTensor(outputs[1], expected.meanOut, channelShape, "mean") &&
                          ValidateTensor(outputs[2], expected.varianceOut, channelShape, "variance") &&
                          ValidateTensor(outputs[3], expected.batchMean, channelShape, "batch_mean") &&
                          ValidateTensor(outputs[4], expected.batchVariance, channelShape, "batch_variance");
        if (!pass) {
            std::fprintf(stderr, "BNTrainingUpdate static GEIR verification not passed\n");
            ge::GEFinalize();
            return 1;
        }
        std::printf("Shape, dtype and values PASSED for [2,3,2,2]\n");
    }

    const ge::Status finalizeStatus = ge::GEFinalize();
    if (finalizeStatus != ge::SUCCESS) {
        std::fprintf(stderr, "GEFinalize status=%u\n", finalizeStatus);
        return 1;
    }
    std::printf("BNTrainingUpdate static GEIR verification PASSED\n");
    return 0;
}
