/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/*!
 * \file fused_mul_apply_keras_momentum_graph_infer.cpp
 * \brief InferDataType
 * Generated By CANNBot
 */
/*!
 * \file fused_mul_apply_keras_momentum_graph_infer.cpp
 * \brief FusedMulApplyKerasMomentum operator graph infer datatype resource
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

static constexpr size_t IN_VAR = 0;
static constexpr size_t IN_ACCUM = 1;
static constexpr size_t OUT_VAR = 0;
static constexpr size_t OUT_ACCUM = 1;

static ge::graphStatus InferDataTypeFusedMulApplyKerasMomentum(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin InferDataTypeFusedMulApplyKerasMomentum");

    // 输出 var/accum 与输入 var/accum 同 dtype（in-place）
    ge::DataType varDtype = context->GetInputDataType(IN_VAR);
    context->SetOutputDataType(OUT_VAR, varDtype);
    context->SetOutputDataType(OUT_ACCUM, context->GetInputDataType(IN_ACCUM));

    OP_LOGD(context->GetNodeName(), "End InferDataTypeFusedMulApplyKerasMomentum");
    return GRAPH_SUCCESS;
}

IMPL_OP(FusedMulApplyKerasMomentum).InferDataType(InferDataTypeFusedMulApplyKerasMomentum);

} // namespace ops
