/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#pragma once
#include "kernel_operator.h"
#include "fused_mul_apply_momentum_tiling_data.h"
#include "fused_mul_apply_momentum_struct.h"
#include <type_traits>

// ============================================================
// Kernel-side helper functions
// ============================================================

__aicore__ inline void GetCoreRange(int64_t core_id, int64_t tiles_main, int64_t cores_tail, int64_t& start,
                                    int64_t& end)
{
    if (core_id < cores_tail) {
        start = core_id * (tiles_main + 1);
        end = start + tiles_main + 1;
    } else {
        start = cores_tail * (tiles_main + 1) + (core_id - cores_tail) * tiles_main;
        end = start + tiles_main;
    }
}

__aicore__ inline int64_t GetUBSplitRange(int64_t a_o_off, int64_t a_o, int64_t a_i, int64_t a_i_tail)
{
    return (a_o_off == a_o - 1) ? a_i_tail : a_i;
}

__aicore__ inline bool FlatToEffectiveCoord(int64_t flat, const int64_t* max_bro_shape, int64_t rank,
                                            int64_t split_axis, int64_t a_i, int64_t a_o, int64_t* eff_coord)
{
    for (int64_t d = 0; d < rank; d++)
        eff_coord[d] = 0;
    int64_t a_o_off = flat % a_o;
    int64_t outer = flat / a_o;
    for (int64_t d = split_axis - 1; d >= 0; d--) {
        eff_coord[d] = outer % max_bro_shape[d];
        outer /= max_bro_shape[d];
    }
    eff_coord[split_axis] = a_o_off * a_i;
    return true;
}

__aicore__ inline int64_t CalcOffset(const int64_t* eff_coord, const int64_t* strides, int64_t rank)
{
    int64_t offset = 0;
    for (int64_t d = 0; d < rank; d++)
        offset += eff_coord[d] * strides[d];
    return offset;
}

__aicore__ inline int64_t CalcOutputTransferCount(const int64_t* normal_shape, int64_t rank, int64_t split_axis,
                                                  int64_t a_i_seg)
{
    int64_t split_elems = (normal_shape[split_axis] == 1) ? 1 : a_i_seg;
    int64_t inner_elems = 1;
    for (int64_t d = split_axis + 1; d < rank; d++)
        inner_elems *= normal_shape[d];
    return split_elems * inner_elems;
}

// ============================================================
// Kernel class
// ============================================================

template <typename T, int64_t RANK>
class FusedMulApplyMomentumKernel {
    static constexpr int64_t ND = (RANK <= kMaxNDDMA) ? RANK : kMaxNDDMA;
    static constexpr bool IS_FP16 = std::is_same<T, half>::value;

    AscendC::TPipe pipe_;
    const FusedMulApplyMomentumTilingData<RANK>* td_;
    AscendC::GlobalTensor<T> gmIn_[kMaxInputSlots];
    AscendC::GlobalTensor<T> gmOut_[kMaxOutputSlots];
    AscendC::TBuf<AscendC::TPosition::VECCALC> buf_[kPhysNodes];
    AscendC::MultiCopyParams<T, ND> nddmaParams_[kMaxInputSlots];
    int64_t nddmaOuterIters_[kMaxInputSlots];
    int64_t nddma_dims_;

public:
    __aicore__ inline void Init(GM_ADDR inputs[kMaxInputSlots], GM_ADDR outputs[kMaxOutputSlots],
                                const FusedMulApplyMomentumTilingData<RANK>* td)
    {
        td_ = td;
        for (int i = 0; i < kMaxInputSlots; i++)
            gmIn_[i].SetGlobalBuffer((__gm__ T*)inputs[i]);
        for (int i = 0; i < kMaxOutputSlots; i++)
            gmOut_[i].SetGlobalBuffer((__gm__ T*)outputs[i]);
        for (int i = 0; i < kPhysNodes; i++)
            pipe_.InitBuffer(buf_[i], td_->per_buf_bytes);

        const int64_t* dstShape = td_->max_bro_shape;
        int64_t k = td_->split.axis;
        nddma_dims_ = (RANK - k <= ND) ? (RANK - k) : ND;
        int64_t ndma_start = RANK - nddma_dims_;
        for (int inp = 0; inp < kMaxInputSlots; inp++) {
            int64_t inner = 1;
            int64_t nd = 0;
            for (int64_t d = RANK - 1; d >= ndma_start && nd < ND; d--) {
                nddmaParams_[inp].loopInfo.loopSize[nd] = (d == k) ? 0 : dstShape[d];
                nddmaParams_[inp].loopInfo.loopSrcStride[nd] = td_->input_strides[inp][d];
                nddmaParams_[inp].loopInfo.loopDstStride[nd] = inner;
                nddmaParams_[inp].loopInfo.loopLpSize[nd] = 0;
                nddmaParams_[inp].loopInfo.loopRpSize[nd] = 0;
                inner *= (d == k) ? td_->split.a_i : dstShape[d];
                nd++;
            }
            for (; nd < ND; nd++) {
                nddmaParams_[inp].loopInfo.loopSize[nd] = 1;
                nddmaParams_[inp].loopInfo.loopSrcStride[nd] = 0;
                nddmaParams_[inp].loopInfo.loopDstStride[nd] = inner;
                nddmaParams_[inp].loopInfo.loopLpSize[nd] = 0;
                nddmaParams_[inp].loopInfo.loopRpSize[nd] = 0;
            }
            nddmaOuterIters_[inp] = 1;
            for (int64_t d = k; d < ndma_start; d++)
                nddmaOuterIters_[inp] *= (d == k) ? td_->split.a_i : dstShape[d];
        }
    }

    __aicore__ inline void ProcessTile(int64_t flat, int64_t start, int64_t end, int64_t inner_count, int64_t* coord,
                                       int32_t evMTE2toV, int32_t evVtoMTE2, int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        constexpr int UB0 = 0, UB1 = 1, UB2 = 2;
        constexpr int IN_VAR = 0, IN_ACCUM = 1, IN_LR = 2, IN_X1 = 3, IN_MOM = 4, IN_X2 = 5;
        constexpr int OUT_VAR = 0, OUT_ACCUM = 1;

        int64_t a_i_seg = GetUBSplitRange(flat % td_->split.a_o, td_->split.a_o, td_->split.a_i, td_->split.a_i_tail);
        int64_t count = a_i_seg * inner_count;
        FlatToEffectiveCoord(flat, td_->max_bro_shape, RANK, td_->split.axis, td_->split.a_i, td_->split.a_o, coord);

        if (flat != start) {
            AscendC::WaitFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);
            if constexpr (IS_FP16)
                AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        }

        if (td_->use_nesterov) {
            if constexpr (IS_FP16) {
                ProcessNesterovFp16(coord, count, a_i_seg, UB0, UB1, UB2, IN_VAR, IN_ACCUM, IN_LR, IN_X1, IN_MOM, IN_X2,
                                    OUT_VAR, OUT_ACCUM, evMTE2toV, evVtoMTE2, evVtoMTE3, evMTE3toMTE2);
            } else {
                ProcessNesterov(coord, count, a_i_seg, UB0, UB1, UB2, IN_VAR, IN_ACCUM, IN_LR, IN_X1, IN_MOM, IN_X2,
                                OUT_VAR, OUT_ACCUM, evMTE2toV, evVtoMTE2, evVtoMTE3, evMTE3toMTE2);
            }
        } else {
            if constexpr (IS_FP16) {
                ProcessStandardFp16(coord, count, a_i_seg, UB0, UB1, UB2, IN_VAR, IN_ACCUM, IN_LR, IN_X1, IN_MOM, IN_X2,
                                    OUT_VAR, OUT_ACCUM, evMTE2toV, evVtoMTE2, evVtoMTE3, evMTE3toMTE2);
            } else {
                ProcessStandard(coord, count, a_i_seg, UB0, UB1, UB2, IN_VAR, IN_ACCUM, IN_LR, IN_X1, IN_MOM, IN_X2,
                                OUT_VAR, OUT_ACCUM, evMTE2toV, evVtoMTE2, evVtoMTE3, evMTE3toMTE2);
            }
        }

        if (flat != end - 1)
            AscendC::SetFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);
    }

    __aicore__ inline void Process()
    {
        int32_t evMTE2toV = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::MTE2_V));
        int32_t evVtoMTE2 = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::V_MTE2));
        int32_t evVtoMTE3 = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::V_MTE3));
        int32_t evMTE3toMTE2 = static_cast<int32_t>(GetTPipePtr()->FetchEventID(AscendC::HardEvent::MTE3_MTE2));

        int64_t start, end;
        GetCoreRange(AscendC::GetBlockIdx(), td_->multicore.tiles_main, td_->multicore.cores_tail, start, end);

        int64_t inner_count = 1;
        for (int64_t d = td_->split.axis + 1; d < RANK; d++)
            inner_count *= td_->max_bro_shape[d];

        int64_t coord[kMaxRank] = {};
        for (int64_t flat = start; flat < end; flat++) {
            ProcessTile(flat, start, end, inner_count, coord, evMTE2toV, evVtoMTE2, evVtoMTE3, evMTE3toMTE2);
        }
    }

private:
    // ============================================================
    // Standard mode (FP32)
    // ============================================================
    __aicore__ inline void ProcessStandard(const int64_t* coord, int64_t count, int64_t a_i_seg, int UB0, int UB1,
                                           int UB2, int IN_VAR, int IN_ACCUM, int IN_LR, int IN_X1, int IN_MOM,
                                           int IN_X2, int OUT_VAR, int OUT_ACCUM, int32_t evMTE2toV, int32_t evVtoMTE2,
                                           int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        // S1: grad = x1 * x2
        CopyInBrc(coord, IN_X1, UB0, a_i_seg);
        CopyInBrc(coord, IN_X2, UB1, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Mul(buf_[UB2].template Get<T>(), buf_[UB0].template Get<T>(), buf_[UB1].template Get<T>(), count);

        // S2: accum_new = accum * momentum + grad
        CopyInBrc(coord, IN_ACCUM, UB0, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        T mom_val;
        ReadScalar(coord, IN_MOM, mom_val);
        AscendC::Muls(buf_[UB0].template Get<T>(), buf_[UB0].template Get<T>(), mom_val, count);
        AscendC::Add(buf_[UB0].template Get<T>(), buf_[UB0].template Get<T>(), buf_[UB2].template Get<T>(), count);

        // S3: delta = accum_new * lr
        CopyInBrc(coord, IN_LR, UB1, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Mul(buf_[UB1].template Get<T>(), buf_[UB0].template Get<T>(), buf_[UB1].template Get<T>(), count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        // S4: var_new = var - delta
        CopyInBrc(coord, IN_VAR, UB2, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Sub(buf_[UB2].template Get<T>(), buf_[UB2].template Get<T>(), buf_[UB1].template Get<T>(), count);

        AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        CopyOutOne(coord, OUT_VAR, UB2, a_i_seg);
        CopyOutOne(coord, OUT_ACCUM, UB0, a_i_seg);
    }

    __aicore__ inline void StandardFp16ComputeGradAccumDelta(const int64_t* batch_coord, int64_t batch_count,
                                                             int64_t batch_a_i_seg, int UB0, int UB1, int UB2,
                                                             int IN_X1, int IN_ACCUM, float x2_val, float mom_val,
                                                             float lr_val, int32_t evMTE2toV, int32_t evVtoMTE2)
    {
        using FT = float;
        CopyInBrc(batch_coord, IN_X1, UB0, batch_a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Cast<FT, half>(buf_[UB2].template Get<FT>(), buf_[UB0].template Get<half>(),
                                AscendC::RoundMode::CAST_NONE, batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::Muls(buf_[UB2].template Get<FT>(), buf_[UB2].template Get<FT>(), x2_val, batch_count);

        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        CopyInBrc(batch_coord, IN_ACCUM, UB0, batch_a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Cast<FT, half>(buf_[UB1].template Get<FT>(), buf_[UB0].template Get<half>(),
                                AscendC::RoundMode::CAST_NONE, batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::Muls(buf_[UB1].template Get<FT>(), buf_[UB1].template Get<FT>(), mom_val, batch_count);
        AscendC::Add(buf_[UB1].template Get<FT>(), buf_[UB1].template Get<FT>(), buf_[UB2].template Get<FT>(),
                     batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        AscendC::Muls(buf_[UB2].template Get<FT>(), buf_[UB1].template Get<FT>(), lr_val, batch_count);
    }

    __aicore__ inline void StandardFp16UpdateVar(const int64_t* batch_coord, int64_t batch_count, int64_t batch_a_i_seg,
                                                 int UB0, int UB1, int UB2, int IN_VAR, int OUT_VAR, int32_t evMTE2toV,
                                                 int32_t evVtoMTE2, int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        using FT = float;
        AscendC::Copy(buf_[UB0].template Get<FT>(), buf_[UB2].template Get<FT>(), batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        CopyInBrc(batch_coord, IN_VAR, UB2, batch_a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        AscendC::Cast<FT, half>(buf_[UB1].template Get<FT>(), buf_[UB2].template Get<half>(),
                                AscendC::RoundMode::CAST_NONE, batch_count);
        AscendC::Sub(buf_[UB1].template Get<FT>(), buf_[UB1].template Get<FT>(), buf_[UB0].template Get<FT>(),
                     batch_count);
        AscendC::Cast<half, FT>(buf_[UB1].template Get<half>(), buf_[UB1].template Get<FT>(),
                                AscendC::RoundMode::CAST_ROUND, batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        CopyOutOne(batch_coord, OUT_VAR, UB1, batch_a_i_seg);
    }
    __aicore__ inline void ProcessStandardFp16(const int64_t* coord, int64_t count, int64_t a_i_seg, int UB0, int UB1,
                                               int UB2, int IN_VAR, int IN_ACCUM, int IN_LR, int IN_X1, int IN_MOM,
                                               int IN_X2, int OUT_VAR, int OUT_ACCUM, int32_t evMTE2toV,
                                               int32_t evVtoMTE2, int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        using FT = float;
        constexpr int64_t BATCH_SIZE = 4096;

        T x2_val_t, mom_val_t, lr_val_t;
        ReadScalar(coord, IN_X2, x2_val_t);
        ReadScalar(coord, IN_MOM, mom_val_t);
        ReadScalar(coord, IN_LR, lr_val_t);
        FT x2_val = static_cast<FT>(x2_val_t);
        FT mom_val = static_cast<FT>(mom_val_t);
        FT lr_val = static_cast<FT>(lr_val_t);

        int64_t inner_dims = 1;
        for (int64_t d = td_->split.axis + 1; d < RANK; d++)
            inner_dims *= td_->max_bro_shape[d];

        int64_t total_a_i_seg = (count + inner_dims - 1) / inner_dims;
        int64_t batch_a_i_seg_max = BATCH_SIZE / inner_dims;

        for (int64_t off = 0; off < total_a_i_seg; off += batch_a_i_seg_max) {
            int64_t bseg = (off + batch_a_i_seg_max <= total_a_i_seg) ? batch_a_i_seg_max : (total_a_i_seg - off);
            int64_t bcnt = bseg * inner_dims;

            int64_t bc[kMaxRank];
            for (int i = 0; i < kMaxRank; i++)
                bc[i] = coord[i];
            bc[td_->split.axis] += off;

            StandardFp16ComputeGradAccumDelta(bc, bcnt, bseg, UB0, UB1, UB2, IN_X1, IN_ACCUM, x2_val, mom_val, lr_val,
                                              evMTE2toV, evVtoMTE2);

            AscendC::Cast<half, FT>(buf_[UB1].template Get<half>(), buf_[UB1].template Get<FT>(),
                                    AscendC::RoundMode::CAST_ROUND, bcnt);
            AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
            CopyOutOne(bc, OUT_ACCUM, UB1, bseg);
            AscendC::SetFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);

            StandardFp16UpdateVar(bc, bcnt, bseg, UB0, UB1, UB2, IN_VAR, OUT_VAR, evMTE2toV, evVtoMTE2, evVtoMTE3,
                                  evMTE3toMTE2);
        }
    }

    // ============================================================
    // Nesterov mode (FP32)
    // ============================================================
    __aicore__ inline void ProcessNesterov(const int64_t* coord, int64_t count, int64_t a_i_seg, int UB0, int UB1,
                                           int UB2, int IN_VAR, int IN_ACCUM, int IN_LR, int IN_X1, int IN_MOM,
                                           int IN_X2, int OUT_VAR, int OUT_ACCUM, int32_t evMTE2toV, int32_t evVtoMTE2,
                                           int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        T mom_val, lr_val;
        ReadScalar(coord, IN_MOM, mom_val);
        ReadScalar(coord, IN_LR, lr_val);

        // S1: grad = x1 * x2 -> UB2
        CopyInBrc(coord, IN_X1, UB0, a_i_seg);
        CopyInBrc(coord, IN_X2, UB1, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Mul(buf_[UB2].template Get<T>(), buf_[UB0].template Get<T>(), buf_[UB1].template Get<T>(), count);

        // S2: acc_new = accum * momentum + grad -> UB1
        CopyInBrc(coord, IN_ACCUM, UB1, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Muls(buf_[UB1].template Get<T>(), buf_[UB1].template Get<T>(), mom_val, count);
        AscendC::Add(buf_[UB1].template Get<T>(), buf_[UB1].template Get<T>(), buf_[UB2].template Get<T>(), count);

        // S3: acc_m_lr = acc_new * momentum * lr -> UB0
        // FIX: Nesterov formula requires acc_new * momentum * lr, was missing * lr
        AscendC::Muls(buf_[UB0].template Get<T>(), buf_[UB1].template Get<T>(), mom_val * lr_val, count);

        // S4: grad_lr = grad * lr; delta = acc_m_lr + grad_lr
        AscendC::Muls(buf_[UB2].template Get<T>(), buf_[UB2].template Get<T>(), lr_val, count);
        AscendC::Add(buf_[UB0].template Get<T>(), buf_[UB0].template Get<T>(), buf_[UB2].template Get<T>(), count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        // S5: var_new = var - delta
        CopyInBrc(coord, IN_VAR, UB2, a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Sub(buf_[UB2].template Get<T>(), buf_[UB2].template Get<T>(), buf_[UB0].template Get<T>(), count);

        AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        CopyOutOne(coord, OUT_VAR, UB2, a_i_seg);
        CopyOutOne(coord, OUT_ACCUM, UB1, a_i_seg);
    }

    __aicore__ inline void NesterovFp16ComputeDelta(const int64_t* batch_coord, int64_t batch_count,
                                                    int64_t batch_a_i_seg, int UB0, int UB1, int UB2, int IN_X1,
                                                    int IN_ACCUM, float x2_val, float mom_val, float lr_val,
                                                    int32_t evMTE2toV, int32_t evVtoMTE2)
    {
        using FT = float;
        CopyInBrc(batch_coord, IN_X1, UB0, batch_a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Cast<FT, half>(buf_[UB2].template Get<FT>(), buf_[UB0].template Get<half>(),
                                AscendC::RoundMode::CAST_NONE, batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::Muls(buf_[UB2].template Get<FT>(), buf_[UB2].template Get<FT>(), x2_val, batch_count);

        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        CopyInBrc(batch_coord, IN_ACCUM, UB0, batch_a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::Cast<FT, half>(buf_[UB1].template Get<FT>(), buf_[UB0].template Get<half>(),
                                AscendC::RoundMode::CAST_NONE, batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::Muls(buf_[UB1].template Get<FT>(), buf_[UB1].template Get<FT>(), mom_val, batch_count);
        AscendC::Add(buf_[UB1].template Get<FT>(), buf_[UB1].template Get<FT>(), buf_[UB2].template Get<FT>(),
                     batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        AscendC::Muls(buf_[UB0].template Get<FT>(), buf_[UB1].template Get<FT>(), mom_val * lr_val, batch_count);
        AscendC::Muls(buf_[UB2].template Get<FT>(), buf_[UB2].template Get<FT>(), lr_val, batch_count);
        AscendC::Add(buf_[UB0].template Get<FT>(), buf_[UB0].template Get<FT>(), buf_[UB2].template Get<FT>(),
                     batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
    }

    __aicore__ inline void NesterovFp16UpdateVar(const int64_t* batch_coord, int64_t batch_count, int64_t batch_a_i_seg,
                                                 int UB0, int UB1, int UB2, int IN_VAR, int OUT_VAR, int32_t evMTE2toV,
                                                 int32_t evVtoMTE2, int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        using FT = float;
        AscendC::Copy(buf_[UB2].template Get<FT>(), buf_[UB0].template Get<FT>(), batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        CopyInBrc(batch_coord, IN_VAR, UB0, batch_a_i_seg);
        AscendC::SetFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::WaitFlag<AscendC::HardEvent::MTE2_V>(evMTE2toV);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE2>(evVtoMTE2);

        AscendC::Cast<FT, half>(buf_[UB1].template Get<FT>(), buf_[UB0].template Get<half>(),
                                AscendC::RoundMode::CAST_NONE, batch_count);
        AscendC::Sub(buf_[UB1].template Get<FT>(), buf_[UB1].template Get<FT>(), buf_[UB2].template Get<FT>(),
                     batch_count);
        AscendC::Cast<half, FT>(buf_[UB1].template Get<half>(), buf_[UB1].template Get<FT>(),
                                AscendC::RoundMode::CAST_ROUND, batch_count);
        AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
        CopyOutOne(batch_coord, OUT_VAR, UB1, batch_a_i_seg);
    }
    __aicore__ inline void ProcessNesterovFp16(const int64_t* coord, int64_t count, int64_t a_i_seg, int UB0, int UB1,
                                               int UB2, int IN_VAR, int IN_ACCUM, int IN_LR, int IN_X1, int IN_MOM,
                                               int IN_X2, int OUT_VAR, int OUT_ACCUM, int32_t evMTE2toV,
                                               int32_t evVtoMTE2, int32_t evVtoMTE3, int32_t evMTE3toMTE2)
    {
        using FT = float;
        constexpr int64_t BATCH_SIZE = 4096;

        T mom_val_t, lr_val_t, x2_val_t;
        ReadScalar(coord, IN_MOM, mom_val_t);
        ReadScalar(coord, IN_LR, lr_val_t);
        ReadScalar(coord, IN_X2, x2_val_t);
        FT mom_val = static_cast<FT>(mom_val_t);
        FT lr_val = static_cast<FT>(lr_val_t);
        FT x2_val = static_cast<FT>(x2_val_t);

        int64_t inner_dims = 1;
        for (int64_t d = td_->split.axis + 1; d < RANK; d++)
            inner_dims *= td_->max_bro_shape[d];

        int64_t total_a_i_seg = (count + inner_dims - 1) / inner_dims;
        int64_t batch_a_i_seg_max = BATCH_SIZE / inner_dims;

        for (int64_t off = 0; off < total_a_i_seg; off += batch_a_i_seg_max) {
            int64_t bseg = (off + batch_a_i_seg_max <= total_a_i_seg) ? batch_a_i_seg_max : (total_a_i_seg - off);
            int64_t bcnt = bseg * inner_dims;

            int64_t bc[kMaxRank];
            for (int i = 0; i < kMaxRank; i++)
                bc[i] = coord[i];
            bc[td_->split.axis] += off;

            NesterovFp16ComputeDelta(bc, bcnt, bseg, UB0, UB1, UB2, IN_X1, IN_ACCUM, x2_val, mom_val, lr_val, evMTE2toV,
                                     evVtoMTE2);

            AscendC::Cast<half, FT>(buf_[UB1].template Get<half>(), buf_[UB1].template Get<FT>(),
                                    AscendC::RoundMode::CAST_ROUND, bcnt);
            AscendC::SetFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
            AscendC::WaitFlag<AscendC::HardEvent::V_MTE3>(evVtoMTE3);
            CopyOutOne(bc, OUT_ACCUM, UB1, bseg);
            AscendC::SetFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);
            AscendC::WaitFlag<AscendC::HardEvent::MTE3_MTE2>(evMTE3toMTE2);

            NesterovFp16UpdateVar(bc, bcnt, bseg, UB0, UB1, UB2, IN_VAR, OUT_VAR, evMTE2toV, evVtoMTE2, evVtoMTE3,
                                  evMTE3toMTE2);
        }
    }

    __aicore__ inline void ReadScalar(const int64_t* coord, int inputIdx, T& val)
    {
        int64_t off = CalcOffset(coord, td_->input_strides[inputIdx], RANK);
        val = gmIn_[inputIdx][off].GetValue(0);
    }

    __aicore__ inline void CopyInBrc(const int64_t* coord, int inputIdx, int slot, int64_t a_i_seg)
    {
        int64_t k = td_->split.axis;
        int64_t off = CalcOffset(coord, td_->input_strides[inputIdx], RANK);
        const int64_t* dstShape = td_->max_bro_shape;
        int64_t ndma_start = RANK - nddma_dims_;

        auto params = nddmaParams_[inputIdx];
        int64_t k_nd = RANK - 1 - k;
        int64_t inner = 1;
        for (int64_t nd = 0; nd < ND; nd++) {
            if (nd == k_nd)
                params.loopInfo.loopSize[nd] = a_i_seg;
            params.loopInfo.loopDstStride[nd] = inner;
            inner *= params.loopInfo.loopSize[nd];
        }

        static constexpr AscendC::NdDmaConfig cfg = {false, AscendC::NdDmaConfig::unsetPad,
                                                     AscendC::NdDmaConfig::unsetPad, false};

        if constexpr (RANK <= 5) {
            AscendC::DataCopy<T, ND, cfg>(buf_[slot].template Get<T>(), gmIn_[inputIdx][off], params);
        } else {
            AscendC::LocalTensor<T> buf = buf_[slot].template Get<T>();
            int64_t elem_base = off;
            for (int64_t oi = 0; oi < nddmaOuterIters_[inputIdx]; oi++) {
                int64_t elem_adj = 0, tmp = oi;
                for (int64_t d = ndma_start - 1; d >= k; d--) {
                    int64_t sz = (d == k) ? a_i_seg : dstShape[d];
                    elem_adj += (tmp % sz) * td_->input_strides[inputIdx][d];
                    tmp /= sz;
                }
                AscendC::DataCopy<T, ND, cfg>(buf[oi * inner], gmIn_[inputIdx][elem_base + elem_adj], params);
            }
        }
    }

    __aicore__ inline void CopyOutOne(const int64_t* coord, int outputIdx, int slot, int64_t a_i_seg)
    {
        int64_t off = CalcOffset(coord, td_->output_strides[outputIdx], RANK);
        int64_t cnt = CalcOutputTransferCount(td_->output_shapes[outputIdx], RANK, td_->split.axis, a_i_seg);
        AscendC::DataCopyExtParams extParams;
        extParams.blockCount = 1;
        extParams.blockLen = static_cast<uint32_t>(cnt * sizeof(T));
        extParams.srcStride = 0;
        extParams.dstStride = 0;
        AscendC::DataCopyPad(gmOut_[outputIdx][off], buf_[slot].template Get<T>(), extParams);
    }
};
