/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file max_pool_grad_grad_with_argmax_simt.h
 * \brief SIMT kernel for max_pool_grad_grad_with_argmax operator.
 *        固定局部索引模式（include_batch_in_index=false）：
 *          batchId = idx / argmaxBatchStride
 *          gradIdx = batchId * gradBatchStride + argmax[idx]
 *          output[idx] = grad[gradIdx]
 *        Grid-Stride loop over totalElements.
 */

#ifndef MAX_POOL_GRAD_GRAD_WITH_ARGMAX_SIMT_H_
#define MAX_POOL_GRAD_GRAD_WITH_ARGMAX_SIMT_H_

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/asc_simt.h"
#include "max_pool_grad_grad_with_argmax_tiling_data.h"
#include "max_pool_grad_grad_with_argmax_tiling_key.h"

namespace NsMaxPoolGradGradWithArgmax {
using namespace AscendC;

static constexpr uint32_t THREAD_NUM = 1024;

/*!
 * \brief Local 模式 VF 函数（include_batch_in_index=false）
 *        batchId = idx / argmaxBatchStride
 *        output[idx] = grad[batchId * gradBatchStride + argmax[idx]]
 */
template <typename T, typename I>
__simt_vf__ __launch_bounds__(THREAD_NUM) inline void OpMaxPoolGradGradWithArgmaxLocalSimt(
    int64_t totalElements, int64_t gradBatchStride, int64_t argmaxBatchStride, const __gm__ T* grad,
    const __gm__ I* argmax, __gm__ T* output)
{
    const uint64_t globalThreadId = static_cast<uint64_t>(blockIdx.x) * static_cast<uint64_t>(blockDim.x) +
                                    static_cast<uint64_t>(threadIdx.x);
    const uint64_t globalThreadNum = static_cast<uint64_t>(gridDim.x) * static_cast<uint64_t>(blockDim.x);

    const uint64_t gradBatchStrideU64 = static_cast<uint64_t>(gradBatchStride);
    const uint64_t argmaxBatchStrideU64 = static_cast<uint64_t>(argmaxBatchStride);

    for (uint64_t idx = globalThreadId; idx < static_cast<uint64_t>(totalElements); idx += globalThreadNum) {
        uint64_t batchId = idx / argmaxBatchStrideU64;
        int64_t gradIdx = static_cast<int64_t>(batchId * gradBatchStrideU64 + static_cast<uint64_t>(argmax[idx]));
        output[idx] = grad[gradIdx];
    }
}

/*!
 * \brief Process 入口：Local 模式（include_batch_in_index=false）
 *        需要按 batch 维度拆索引后 gather。
 */
template <typename T, typename I>
__aicore__ inline void ProcessBatchFalse(GM_ADDR grad, GM_ADDR argmax, GM_ADDR y,
                                         const MaxPoolGradGradWithArgmaxTilingData* tilingData)
{
    int64_t totalElements = tilingData->totalElements;
    if (totalElements == 0) {
        return;
    }

    const __gm__ T* gradGm = reinterpret_cast<const __gm__ T*>(grad);
    const __gm__ I* argmaxGm = reinterpret_cast<const __gm__ I*>(argmax);
    __gm__ T* outputGm = reinterpret_cast<__gm__ T*>(y);

    asc_vf_call<OpMaxPoolGradGradWithArgmaxLocalSimt<T, I>>(dim3(THREAD_NUM), tilingData->totalElements,
                                                            tilingData->gradBatchStride, tilingData->argmaxBatchStride,
                                                            gradGm, argmaxGm, outputGm);
}

} // namespace NsMaxPoolGradGradWithArgmax
#endif // MAX_POOL_GRAD_GRAD_WITH_ARGMAX_SIMT_H_
