/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file max_pool_grad_grad_with_argmax_tiling_key.h
 * \brief Tiling key declare for max_pool_grad_grad_with_argmax operator.
 *
 * One template parameter:
 *   schMode (UINT 1-bit): 固定 LOCAL（include_batch_in_index=false，局部索引）
 *     1 = local (include_batch_in_index = false)
 *   dtype 不在 TilingKey 中枚举，由 DTYPE_ 宏自动实例化。
 */

#ifndef MAX_POOL_GRAD_GRAD_WITH_ARGMAX_TILING_KEY_H_
#define MAX_POOL_GRAD_GRAD_WITH_ARGMAX_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define MAXPOOL_GRAD_GRAD_MODE_LOCAL 1 // 固定 include_batch_in_index = false（局部索引）

ASCENDC_TPL_ARGS_DECL(MaxPoolGradGradWithArgmax,
                      ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, MAXPOOL_GRAD_GRAD_MODE_LOCAL));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                                     ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MAXPOOL_GRAD_GRAD_MODE_LOCAL),
                                     ASCENDC_TPL_TILING_STRUCT_SEL(MaxPoolGradGradWithArgmaxTilingData)));

#endif // MAX_POOL_GRAD_GRAD_WITH_ARGMAX_TILING_KEY_H_
