/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file hard_shrink.cpp
 * \brief HardShrink 算子 Kernel 入口（arch35 架构，Ascend950）
 *
 * def 驱动 dtype 模式：dtype 由 _def.cpp 的 DataType 列表经构建系统注入
 * DTYPE_INPUT_X 编译宏，kernel 入口直接使用该宏作为 IO 类型，无需 tiling_key 编码。
 *
 * 模板参数（与 hard_shrink_tiling_key.h 中 ASCENDC_TPL_ARGS_DECL 定义对应）：
 *   - BUFFER_MODE: 缓冲模式 (0=单缓冲, 1=双缓冲)
 *
 * 注：lambd 作为 Attr 通过 TilingData 传递，不作为 kernel 参数
 */

#include "arch35/hard_shrink.h"

template <int BUFFER_MODE>
__global__ __aicore__ void hard_shrink(GM_ADDR input_x, GM_ADDR output_y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(HardShrinkTilingData);
    GET_TILING_DATA_WITH_STRUCT(HardShrinkTilingData, tilingData, tiling);

    NsHardShrink::HardShrink<DTYPE_INPUT_X, BUFFER_MODE> op;
    op.Init(input_x, output_y, &tilingData);
    op.Process();
}
