/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file npu_get_float_status_tiling_data.h
 * \brief TilingData structure for npu_get_float_status
 *
 * Empty structure: no data-related tiling parameters needed.
 * - Input/output shape is fixed [8], known at compile time.
 * - BlockDim is set via context->SetBlockDim() directly.
 * - No attributes to pass.
 */

#ifndef NPU_GET_FLOAT_STATUS_TILING_DATA_H
#define NPU_GET_FLOAT_STATUS_TILING_DATA_H

struct NPUGetFloatStatusTilingData {
    // Empty structure: no data-related tiling parameters.
    // BlockDim is set via context->SetBlockDim().
    // Input/output shape is fixed [8], no splitting needed.
};

#endif // NPU_GET_FLOAT_STATUS_TILING_DATA_H
