/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * \file test_geir_dynamic_gru.cpp
 * \brief Static GE IR example for DynamicGRU (graph mode invocation).
 *
 * Builds a graph with the 7 inputs (x / w / b / cw / cb / seq_length / init_h)
 * and 5 outputs (y / output_h / r / i / n) of DynamicGRU, runs it on device
 * via a GE session and verifies all five outputs against a CPU golden that
 * mirrors the CANN V1 semantics: joint gate GEMM [x_t, h] @ w + b (w (I+H, 2H),
 * column order [r, i]), reset-before candidate n = tanh([x_t, r*h] @ cw + cb),
 * source-form update h~ = (h - n) * i + n with the freeze-style seq_length mask
 * h_t = h_prev + (h~ - h_prev) * 1[t < s[b]] (r/i/n stay unmasked), all
 * accumulated in fp32.
 *
 * dtype combination: x / w / cw = fp16, b / cb / init_h / outputs = fp32
 * (outputs anchored by b). seq_length values vary per batch (0 <= s[b] <= L)
 * to exercise the sequence-length mask semantics absorbed from RnnGenMaskV2.
 * Comparison tolerance: atol = rtol = 2e-4 (fp32 output path; kernel keeps
 * fp32 accumulation, residual differences are hardware sigmoid/tanh
 * approximation and GEMM accumulation order).
 */

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <limits>
#include <map>
#include <memory>
#include <new>
#include <string>
#include <vector>

#include "array_ops.h"
#include "ge_api.h"
#include "ge_api_types.h"
#include "ge_error_codes.h"
#include "graph.h"
#include "tensor.h"
#include "types.h"

#include "../../op_graph/dynamic_gru_proto.h"

using namespace ge;
using std::map;
using std::string;
using std::vector;

namespace {
constexpr int32_t RET_FAILED = -1;
constexpr int32_t RET_SUCCESS = 0;
constexpr float kAtol = 2.0e-4F;
constexpr float kRtol = 2.0e-4F;

// fixture 维度常量：L=序列长度, N=batch, I=输入特征维度, H=隐藏状态维度
constexpr int64_t L = 6;
constexpr int64_t N = 16;
constexpr int64_t I = 32;
constexpr int64_t H = 64;
constexpr int64_t K = I + H;  // GEMM K 维：x_t 与 h 拼接长度
constexpr int64_t B2 = 2 * H; // b 有效长度（16 对齐下界）
constexpr int64_t B1 = H;     // cb 有效长度（16 对齐下界）

string GetTime()
{
    time_t timep;
    time(&timep);
    const tm* localTime = localtime(&timep);
    if (localTime == nullptr) {
        return "1970-01-01 00:00:00,000";
    }
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S,000", localTime);
    return tmp;
}

// IEEE 754 binary16 conversion with round-to-nearest-even. All pattern values
// below are small dyadic rationals (exactly representable in fp16), so the
// golden and the device kernel observe identical input bits.
uint16_t FloatToFp16(float value)
{
    uint32_t bits = 0;
    std::memcpy(&bits, &value, sizeof(bits));
    const uint16_t sign = static_cast<uint16_t>((bits >> 16U) & 0x8000U);
    const int32_t exponent = static_cast<int32_t>((bits >> 23U) & 0xFFU) - 127;
    const uint32_t mantissa = bits & 0x7FFFFFU;
    if (exponent > 15) {
        return static_cast<uint16_t>(sign | 0x7C00U); // overflow -> +/-Inf
    }
    if (exponent >= -14) { // fp16 normal range
        uint16_t half = static_cast<uint16_t>((static_cast<uint32_t>(exponent + 15) << 10U) | (mantissa >> 13U));
        const uint32_t remainder = mantissa & 0x1FFFU;
        if ((remainder > 0x1000U) || ((remainder == 0x1000U) && ((half & 1U) != 0U))) {
            half = static_cast<uint16_t>(half + 1U);
        }
        return static_cast<uint16_t>(sign | half);
    }
    if (exponent < -25) {
        return sign; // rounds to signed zero
    }
    const uint32_t fraction = mantissa | 0x800000U;
    const int32_t shift = -(exponent + 1);
    const uint32_t remainderMask = (1ULL << static_cast<uint32_t>(shift)) - 1U;
    const uint32_t halfway = (remainderMask + 1U) >> 1U;
    uint16_t half = static_cast<uint16_t>(fraction >> static_cast<uint32_t>(shift));
    const uint32_t remainder = fraction & remainderMask;
    if ((remainder > halfway) || ((remainder == halfway) && ((half & 1U) != 0U))) {
        half = static_cast<uint16_t>(half + 1U);
    }
    return static_cast<uint16_t>(sign | half);
}

float Fp16ToFloat(uint16_t value)
{
    const float sign = ((value & 0x8000U) != 0U) ? -1.0F : 1.0F;
    const uint32_t exponent = (static_cast<uint32_t>(value) >> 10U) & 0x1FU;
    const uint32_t mantissa = static_cast<uint32_t>(value) & 0x3FFU;
    if (exponent == 0x1FU) {
        return sign * std::numeric_limits<float>::infinity();
    }
    if (exponent == 0U) {
        return sign * std::ldexp(static_cast<float>(mantissa), -24);
    }
    return sign * std::ldexp(static_cast<float>(mantissa | 0x400U), static_cast<int>(exponent) - 25);
}

float Sigmoid(float value) { return 1.0F / (1.0F + std::exp(-value)); }

ge::TensorDesc MakeTensorDesc(const vector<int64_t>& shape, ge::DataType dtype)
{
    ge::TensorDesc desc(ge::Shape(shape), ge::FORMAT_ND, dtype);
    desc.SetPlacement(ge::kPlacementHost);
    desc.SetFormat(ge::FORMAT_ND);
    desc.SetRealDimCnt(shape.size());
    return desc;
}

string ShapeToString(const vector<int64_t>& shape)
{
    string result = "[";
    for (size_t index = 0; index < shape.size(); ++index) {
        if (index != 0U) {
            result += ",";
        }
        result += std::to_string(shape[index]);
    }
    result += "]";
    return result;
}

// 确定性宿主侧输入（与动态 example 同源的小二进有理数模式，fp16 精确表示，
// 预激活有界 |z| <= ~2.5，sigmoid/tanh 不饱和）。
struct HostFeeds {
    vector<uint16_t> x;        // (L, N, I) fp16
    vector<uint16_t> w;        // (I+H, 2H) fp16
    vector<float> b;           // (2H,) fp32
    vector<uint16_t> cw;       // (I+H, H) fp16
    vector<float> cb;          // (H,) fp32
    vector<int32_t> seqLength; // (N,) int32, 0 <= s[b] <= L
    vector<float> initH;       // (H, N) fp32
};

void FillFp16Pattern(vector<uint16_t>& buffer, int64_t count, const vector<float>& pattern)
{
    buffer.resize(static_cast<size_t>(count));
    for (int64_t index = 0; index < count; ++index) {
        buffer[static_cast<size_t>(index)] = FloatToFp16(pattern[static_cast<size_t>(index) % pattern.size()]);
    }
}

void FillFp32Pattern(vector<float>& buffer, int64_t count, const vector<float>& pattern)
{
    buffer.resize(static_cast<size_t>(count));
    for (int64_t index = 0; index < count; ++index) {
        buffer[static_cast<size_t>(index)] = pattern[static_cast<size_t>(index) % pattern.size()];
    }
}

HostFeeds MakeFeeds()
{
    const vector<float> xPattern = {0.375F, -0.25F, 0.125F, -0.375F, 0.25F, -0.125F, 0.0625F, -0.0625F};
    const vector<float> wPattern = {0.25F, -0.1875F, 0.125F, -0.0625F, 0.3125F, -0.25F, 0.0625F, -0.125F};
    const vector<float> bPattern = {0.125F, -0.0625F, 0.1875F, -0.125F, 0.0625F, -0.1875F, 0.25F, -0.25F};
    const vector<float> cwPattern = {0.1875F, -0.3125F, 0.25F, -0.125F, 0.0625F, -0.25F, 0.3125F, -0.1875F};
    const vector<float> cbPattern = {0.0625F, -0.1875F, 0.125F, -0.0625F, 0.1875F, -0.125F, 0.25F, -0.25F};
    const vector<float> initHPattern = {0.125F, -0.0625F, 0.0625F, -0.125F, 0.1875F, -0.1875F};

    HostFeeds feeds;
    FillFp16Pattern(feeds.x, L * N * I, xPattern);
    FillFp16Pattern(feeds.w, K * 2 * H, wPattern);
    FillFp32Pattern(feeds.b, B2, bPattern);
    FillFp16Pattern(feeds.cw, K * H, cwPattern);
    FillFp32Pattern(feeds.cb, B1, cbPattern);
    FillFp32Pattern(feeds.initH, H * N, initHPattern);
    // 变长序列：s[b] 覆盖 0..L 全值域（0 = 全冻结，L = 定长）
    feeds.seqLength.resize(static_cast<size_t>(N));
    for (int64_t batch = 0; batch < N; ++batch) {
        feeds.seqLength[static_cast<size_t>(batch)] = static_cast<int32_t>(batch * L / (N - 1));
    }
    return feeds;
}

// CPU golden：CANN V1 语义（与动态 example / golden.py 同一公式）。
// fp16 输入无损展宽到 fp32；b/cb/init_h 本为 fp32；全部输出 fp32。
struct GoldenOutputs {
    vector<float> y;       // (L, H, N)
    vector<float> outputH; // (L, H, N)，与 y 逐元素相等
    vector<float> r;       // (L, H, N)
    vector<float> i;       // (L, H, N)
    vector<float> n;       // (L, H, N)
};

GoldenOutputs ComputeGolden(const HostFeeds& feeds)
{
    const int64_t plane = H * N; // h 布局 (H, N)
    vector<float> x(feeds.x.size());
    vector<float> w(feeds.w.size());
    vector<float> cw(feeds.cw.size());
    vector<float> h(plane);
    for (size_t index = 0; index < x.size(); ++index) {
        x[index] = Fp16ToFloat(feeds.x[index]);
    }
    for (size_t index = 0; index < w.size(); ++index) {
        w[index] = Fp16ToFloat(feeds.w[index]);
    }
    for (size_t index = 0; index < cw.size(); ++index) {
        cw[index] = Fp16ToFloat(feeds.cw[index]);
    }
    for (size_t index = 0; index < h.size(); ++index) {
        h[index] = feeds.initH[index];
    }

    GoldenOutputs out;
    out.y.resize(static_cast<size_t>(plane * L));
    out.outputH.resize(static_cast<size_t>(plane * L));
    out.r.resize(static_cast<size_t>(plane * L));
    out.i.resize(static_cast<size_t>(plane * L));
    out.n.resize(static_cast<size_t>(plane * L));

    vector<float> reset(H);
    vector<float> update(H);
    vector<float> cand(H);
    const int32_t* seq = feeds.seqLength.data();
    const float* wBase = w.data();
    const float* cwBase = cw.data();
    for (int64_t t = 0; t < L; ++t) {
        float* yPlane = out.y.data() + t * plane; // (H, N) 时间片
        float* rPlane = out.r.data() + t * plane;
        float* iPlane = out.i.data() + t * plane;
        float* nPlane = out.n.data() + t * plane;
        for (int64_t bIdx = 0; bIdx < N; ++bIdx) {
            const float* xBatch = x.data() + (t * N + bIdx) * I;
            const float* hCol = h.data() + bIdx;
            // 双门 GEMM：gates = [x_t, h] @ w + b，列序 [r, i]
            for (int64_t hidden = 0; hidden < H; ++hidden) {
                float resetAcc = 0.0F;
                float updateAcc = 0.0F;
                for (int64_t j = 0; j < K; ++j) {
                    const float a = (j < I) ? xBatch[j] : hCol[(j - I) * N];
                    resetAcc += a * wBase[j * 2 * H + hidden];
                    updateAcc += a * wBase[j * 2 * H + H + hidden];
                }
                reset[static_cast<size_t>(hidden)] = Sigmoid(resetAcc + feeds.b[static_cast<size_t>(hidden)]);
                update[static_cast<size_t>(hidden)] = Sigmoid(updateAcc + feeds.b[static_cast<size_t>(H + hidden)]);
            }
            // 候选门 GEMM（reset 前置）：n = tanh([x_t, r*h] @ cw + cb)
            for (int64_t hidden = 0; hidden < H; ++hidden) {
                float candAcc = 0.0F;
                for (int64_t j = 0; j < K; ++j) {
                    const float a = (j < I) ? xBatch[j] : reset[static_cast<size_t>(j - I)] * hCol[(j - I) * N];
                    candAcc += a * cwBase[j * H + hidden];
                }
                cand[static_cast<size_t>(hidden)] = std::tanh(candAcc + feeds.cb[static_cast<size_t>(hidden)]);
            }
            // 源码口径更新 + 冻结式掩码：h_t = h_prev + (h~ - h_prev) * 1[t < s[b]]
            const float mask = (t < static_cast<int64_t>(seq[bIdx])) ? 1.0F : 0.0F;
            for (int64_t hidden = 0; hidden < H; ++hidden) {
                const int64_t hIdx = hidden * N + bIdx;
                const float hPrev = h[static_cast<size_t>(hIdx)];
                const float hRaw = (hPrev - cand[static_cast<size_t>(hidden)]) * update[static_cast<size_t>(hidden)] +
                                   cand[static_cast<size_t>(hidden)];
                h[static_cast<size_t>(hIdx)] = hPrev + (hRaw - hPrev) * mask;
                yPlane[hIdx] = h[static_cast<size_t>(hIdx)]; // r/i/n 不受掩码影响
                rPlane[hIdx] = reset[static_cast<size_t>(hidden)];
                iPlane[hIdx] = update[static_cast<size_t>(hidden)];
                nPlane[hIdx] = cand[static_cast<size_t>(hidden)];
            }
        }
    }
    out.outputH = out.y;
    return out;
}

bool HasExpectedShape(const ge::Shape& actual, const vector<int64_t>& expected)
{
    if (actual.GetDimNum() != expected.size()) {
        return false;
    }
    for (size_t index = 0; index < expected.size(); ++index) {
        if (actual.GetDim(index) != expected[index]) {
            return false;
        }
    }
    return true;
}

bool CompareFp32Output(const ge::Tensor& output, const vector<float>& golden, const vector<int64_t>& expectedShape,
                       const string& name)
{
    const ge::TensorDesc desc = output.GetTensorDesc();
    if (!HasExpectedShape(desc.GetShape(), expectedShape)) {
        printf("output %s shape mismatch: expected %s\n", name.c_str(), ShapeToString(expectedShape).c_str());
        return false;
    }
    if (desc.GetDataType() != ge::DT_FLOAT) {
        printf("output %s dtype mismatch: expected DT_FLOAT\n", name.c_str());
        return false;
    }
    const float* actual = reinterpret_cast<const float*>(output.GetData());
    const size_t expectedBytes = golden.size() * sizeof(float);
    if (actual == nullptr || output.GetSize() != expectedBytes) {
        printf("output %s buffer mismatch: bytes=%zu expected=%zu\n", name.c_str(), output.GetSize(), expectedBytes);
        return false;
    }
    for (size_t index = 0; index < golden.size(); ++index) {
        const float error = std::fabs(actual[index] - golden[index]);
        const float tolerance = kAtol + kRtol * std::fabs(golden[index]);
        if (!std::isfinite(actual[index]) || error > tolerance) {
            printf("output %s value mismatch at %zu: actual=%f expected=%f tolerance=%f\n", name.c_str(), index,
                   actual[index], golden[index], tolerance);
            return false;
        }
    }
    return true;
}

bool VerifyOutputs(const vector<ge::Tensor>& outputs, const HostFeeds& feeds)
{
    if (outputs.size() != 5U) {
        printf("expected exactly 5 outputs, got %zu\n", outputs.size());
        return false;
    }
    const GoldenOutputs golden = ComputeGolden(feeds);
    const vector<int64_t> outShape = {L, H, N};
    return CompareFp32Output(outputs[0], golden.y, outShape, "y") &&
           CompareFp32Output(outputs[1], golden.outputH, outShape, "output_h") &&
           CompareFp32Output(outputs[2], golden.r, outShape, "r") &&
           CompareFp32Output(outputs[3], golden.i, outShape, "i") &&
           CompareFp32Output(outputs[4], golden.n, outShape, "n");
}
} // namespace

int32_t CreateOppInGraph(vector<Tensor>& input, vector<std::unique_ptr<uint8_t[]>>& inputHolder,
                         vector<Operator>& inputs, vector<Operator>& outputs, Graph& graph)
{
    auto gru = op::DynamicGRU("dynamic_gru_1");
    const vector<int64_t> xShape = {L, N, I};      // time_major：(L, N, I)
    const vector<int64_t> wShape = {I + H, 2 * H}; // (I+H, 2H)，列序 [r, i]
    const vector<int64_t> bShape = {2 * H};        // B2 = 2H，16 对齐
    const vector<int64_t> cwShape = {I + H, H};    // (I+H, H)
    const vector<int64_t> cbShape = {H};           // B1 = H，16 对齐
    const vector<int64_t> seqShape = {N};          // (N,) int32
    const vector<int64_t> initHShape = {H, N};     // (H, N)

    const HostFeeds feeds = MakeFeeds();

    auto addFp16Input = [&](const string& name, uint32_t index, const vector<int64_t>& shape,
                            const vector<uint16_t>& data) -> int32_t {
        const size_t dataSize = data.size() * sizeof(uint16_t);
        std::unique_ptr<uint8_t[]> buffer(new (std::nothrow) uint8_t[dataSize]);
        if (buffer == nullptr) {
            return RET_FAILED;
        }
        std::memcpy(buffer.get(), data.data(), dataSize);
        const ge::TensorDesc desc = MakeTensorDesc(shape, ge::DT_FLOAT16);
        Tensor tensor(desc, buffer.get(), dataSize);
        inputHolder.emplace_back(std::move(buffer));
        input.push_back(tensor);
        auto dataOp = op::Data(name.c_str()).set_attr_index(index);
        dataOp.update_input_desc_x(desc);
        dataOp.update_output_desc_y(desc);
        graph.AddOp(dataOp);
        inputs.push_back(dataOp);
        return RET_SUCCESS;
    };
    auto addFp32Input = [&](const string& name, uint32_t index, const vector<int64_t>& shape,
                            const vector<float>& data) -> int32_t {
        const size_t dataSize = data.size() * sizeof(float);
        std::unique_ptr<uint8_t[]> buffer(new (std::nothrow) uint8_t[dataSize]);
        if (buffer == nullptr) {
            return RET_FAILED;
        }
        std::memcpy(buffer.get(), data.data(), dataSize);
        const ge::TensorDesc desc = MakeTensorDesc(shape, ge::DT_FLOAT);
        Tensor tensor(desc, buffer.get(), dataSize);
        inputHolder.emplace_back(std::move(buffer));
        input.push_back(tensor);
        auto dataOp = op::Data(name.c_str()).set_attr_index(index);
        dataOp.update_input_desc_x(desc);
        dataOp.update_output_desc_y(desc);
        graph.AddOp(dataOp);
        inputs.push_back(dataOp);
        return RET_SUCCESS;
    };

    if (addFp16Input("data_x", 0U, xShape, feeds.x) != RET_SUCCESS ||
        addFp16Input("data_w", 1U, wShape, feeds.w) != RET_SUCCESS ||
        addFp32Input("data_b", 2U, bShape, feeds.b) != RET_SUCCESS ||
        addFp16Input("data_cw", 3U, cwShape, feeds.cw) != RET_SUCCESS ||
        addFp32Input("data_cb", 4U, cbShape, feeds.cb) != RET_SUCCESS) {
        return RET_FAILED;
    }
    {
        // seq_length：int32，(N,)
        const size_t dataSize = feeds.seqLength.size() * sizeof(int32_t);
        std::unique_ptr<uint8_t[]> buffer(new (std::nothrow) uint8_t[dataSize]);
        if (buffer == nullptr) {
            return RET_FAILED;
        }
        std::memcpy(buffer.get(), feeds.seqLength.data(), dataSize);
        const ge::TensorDesc desc = MakeTensorDesc(seqShape, ge::DT_INT32);
        Tensor tensor(desc, buffer.get(), dataSize);
        inputHolder.emplace_back(std::move(buffer));
        input.push_back(tensor);
        auto dataOp = op::Data("data_seq_length").set_attr_index(5U);
        dataOp.update_input_desc_x(desc);
        dataOp.update_output_desc_y(desc);
        graph.AddOp(dataOp);
        inputs.push_back(dataOp);
    }
    if (addFp32Input("data_init_h", 6U, initHShape, feeds.initH) != RET_SUCCESS) {
        return RET_FAILED;
    }

    gru.set_input_x(inputs[0]);
    gru.set_input_w(inputs[1]);
    gru.set_input_b(inputs[2]);
    gru.set_input_cw(inputs[3]);
    gru.set_input_cb(inputs[4]);
    gru.set_input_seq_length(inputs[5]);
    gru.set_input_init_h(inputs[6]);
    // 属性保持 proto 默认值（唯一支持取值）：direction=UNIDIRECTIONAL、
    // cell_depth=1、keep_prob=1.0、cell_clip=-1.0、num_proj=0、
    // time_major=true、activation=tanh、is_training=true。

    const vector<int64_t> outShape = {L, H, N};
    const TensorDesc yDesc = MakeTensorDesc(outShape, ge::DT_FLOAT);
    gru.update_output_desc_y(yDesc);
    gru.update_output_desc_output_h(yDesc);
    gru.update_output_desc_r(yDesc);
    gru.update_output_desc_i(yDesc);
    gru.update_output_desc_n(yDesc);
    outputs.push_back(gru);
    return RET_SUCCESS;
}

int main(int argc, char* argv[])
{
    (void)argc;
    (void)argv;
    Graph graph("tc_ge_irrun_dynamic_gru");
    vector<Tensor> input;
    vector<std::unique_ptr<uint8_t[]>> inputHolder;

    printf("%s - INFO - [XIR]: Start to initialize ge\n", GetTime().c_str());
    map<AscendString, AscendString> globalOptions = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    if (ge::GEInitialize(globalOptions) != ge::SUCCESS) {
        printf("%s - INFO - [XIR]: Initialize ge did not pass\n", GetTime().c_str());
        return RET_FAILED;
    }

    vector<Operator> inputs;
    vector<Operator> outputs;
    if (CreateOppInGraph(input, inputHolder, inputs, outputs, graph) != RET_SUCCESS) {
        printf("%s - INFO - [XIR]: Create graph did not pass\n", GetTime().c_str());
        GEFinalize();
        return RET_FAILED;
    }
    graph.SetInputs(inputs).SetOutputs(outputs);

    map<AscendString, AscendString> buildOptions;
    Session* session = new (std::nothrow) Session(buildOptions);
    if (session == nullptr) {
        printf("%s - INFO - [XIR]: Create session did not pass\n", GetTime().c_str());
        GEFinalize();
        return RET_FAILED;
    }

    uint32_t graphId = 0;
    map<AscendString, AscendString> graphOptions;
    if (session->AddGraph(graphId, graph, graphOptions) != ge::SUCCESS) {
        printf("%s - INFO - [XIR]: Add graph did not pass\n", GetTime().c_str());
        delete session;
        GEFinalize();
        return RET_FAILED;
    }

    vector<Tensor> output;
    if (session->RunGraph(graphId, input, output) != ge::SUCCESS) {
        printf("%s - INFO - [XIR]: Run graph did not pass\n", GetTime().c_str());
        delete session;
        GEFinalize();
        return RET_FAILED;
    }
    printf("%s - INFO - [XIR]: Session run ir compute graph success\n", GetTime().c_str());

    // 数值核验：重建确定性输入，CPU golden 与 NPU 输出逐元素比对（5 个
    // (L, H, N) fp32 输出，Shape + dtype + 数值）。
    const HostFeeds feeds = MakeFeeds();
    if (!VerifyOutputs(output, feeds)) {
        printf("%s - INFO - [XIR]: Output verification did not pass\n", GetTime().c_str());
        delete session;
        GEFinalize();
        return RET_FAILED;
    }
    const vector<int64_t> xShape = {L, N, I};
    const vector<int64_t> wShape = {I + H, 2 * H};
    const vector<int64_t> bShape = {2 * H};
    const vector<int64_t> cwShape = {I + H, H};
    const vector<int64_t> cbShape = {H};
    const vector<int64_t> seqShape = {N};
    const vector<int64_t> initHShape = {H, N};
    string shapeGroup = "[" + ShapeToString(xShape) + "," + ShapeToString(wShape) + "," + ShapeToString(bShape) + "," +
                        ShapeToString(cwShape) + "," + ShapeToString(cbShape) + "," + ShapeToString(seqShape) + "," +
                        ShapeToString(initHShape) + "]";
    printf("Shape, dtype and values PASSED for %s\n", shapeGroup.c_str());
    printf("%s - INFO - [XIR]: DynamicGRU static GEIR verification PASSED\n", GetTime().c_str());

    delete session;
    GEFinalize();
    return RET_SUCCESS;
}
