/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_geir_fused_mul_apply_momentum_extern.cpp
 * \brief GEIR example for FusedMulApplyMomentumExtern operator
 */

#include <iostream>
#include <fstream>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <string>
#include <map>
#include "assert.h"
#include "graph.h"
#include "types.h"
#include "tensor.h"
#include "ge_error_codes.h"
#include "ge_api_types.h"
#include "ge_api.h"
#include "array_ops.h"
#include "ge_ir_build.h"
#include "../../op_graph/fused_mul_apply_momentum_extern_proto.h"

#define FAILED -1
#define SUCCESS 0

using namespace ge;
using std::map;
using std::string;
using std::vector;

#define ADD_INPUT(intputIndex, intputName, intputDtype, inputShape)                                                 \
    vector<int64_t> placeholder##intputIndex##_shape = inputShape;                                                  \
    auto placeholder##intputIndex = op::Data(string("placeholder_") + #intputName).set_attr_index(0);               \
    TensorDesc placeholder##intputIndex##_desc = TensorDesc(ge::Shape(placeholder##intputIndex##_shape), FORMAT_ND, \
                                                            intputDtype);                                           \
    placeholder##intputIndex##_desc.SetPlacement(ge::kPlacementHost);                                               \
    placeholder##intputIndex##_desc.SetFormat(FORMAT_ND);                                                           \
    Tensor tensor_placeholder##intputIndex;                                                                         \
    ret = GenOnesDataFloat32(placeholder##intputIndex##_shape, tensor_placeholder##intputIndex,                     \
                             placeholder##intputIndex##_desc, 1.0f);                                                \
    if (ret != SUCCESS) {                                                                                           \
        return FAILED;                                                                                              \
    }                                                                                                               \
    placeholder##intputIndex.update_input_desc_x(placeholder##intputIndex##_desc);                                  \
    placeholder##intputIndex.update_output_desc_y(placeholder##intputIndex##_desc);                                 \
    input.push_back(tensor_placeholder##intputIndex);                                                               \
    graph.AddOp(placeholder##intputIndex);                                                                          \
    fusedMom.set_input_##intputName(placeholder##intputIndex);                                                      \
    inputs.push_back(placeholder##intputIndex)

#define ADD_OUTPUT(outputIndex, outputName, outputDtype, outputShape)                                        \
    TensorDesc outputName##outputIndex##_desc_ = TensorDesc(ge::Shape(outputShape), FORMAT_ND, outputDtype); \
    fusedMom.update_output_desc_##outputName(outputName##outputIndex##_desc_)

uint32_t GetDataTypeSize(DataType dt)
{
    if (dt == ge::DT_FLOAT) {
        return 4;
    } else if (dt == ge::DT_FLOAT16 || dt == ge::DT_BF16) {
        return 2;
    }
    return 4;
}

int32_t GenOnesDataFloat32(vector<int64_t> shapes, Tensor& input_tensor, TensorDesc& input_tensor_desc, float value)
{
    input_tensor_desc.SetRealDimCnt(shapes.size());
    size_t size = 1;
    for (uint32_t i = 0; i < shapes.size(); i++) {
        size *= shapes[i];
    }
    uint32_t data_len = size * 4;
    float* pData = new (std::nothrow) float[size];
    if (pData == nullptr) {
        return FAILED;
    }
    for (size_t i = 0; i < size; ++i) {
        pData[i] = value;
    }
    input_tensor = Tensor(input_tensor_desc, reinterpret_cast<uint8_t*>(pData), data_len);
    return SUCCESS;
}

// FusedMulApplyMomentumExtern：7 输入（var/accum/lr/x1/momentum/x2/var_copy）+ 3 输出（var/var_copy/accum，
// inplace 复用输入名）+ 2 属性（use_nesterov/use_locking）。var 恒 FP32；var_copy 恒 FP16。
int CreateOppInGraph(std::vector<ge::Tensor>& input, std::vector<Operator>& inputs, std::vector<Operator>& outputs,
                     Graph& graph)
{
    Status ret = SUCCESS;
    auto fusedMom = op::FusedMulApplyMomentumExtern("fusedMulApplyMomentumExtern1");
    std::vector<int64_t> xShape = {8};
    std::vector<int64_t> scalarShape = {1};

    ADD_INPUT(1, var, DT_FLOAT, xShape);           // 主权重 var 恒 FP32
    ADD_INPUT(2, accum, DT_FLOAT, xShape);         // 动量缓冲（FP32 通路）
    ADD_INPUT(3, lr, DT_FLOAT, scalarShape);       // 学习率标量
    ADD_INPUT(4, x1, DT_FLOAT, xShape);            // 梯度分量
    ADD_INPUT(5, momentum, DT_FLOAT, scalarShape); // 动量系数标量
    ADD_INPUT(6, x2, DT_FLOAT, scalarShape);       // LossScale 倒数缩放标量
    ADD_INPUT(7, var_copy, DT_FLOAT16, xShape);    // 低精度副本 恒 FP16

    fusedMom.set_attr_use_nesterov(false);
    fusedMom.set_attr_use_locking(false);

    ADD_OUTPUT(1, var, DT_FLOAT, xShape);        // var'      inplace 复用 var
    ADD_OUTPUT(2, var_copy, DT_FLOAT16, xShape); // var_copy' inplace 复用 var_copy
    ADD_OUTPUT(3, accum, DT_FLOAT, xShape);      // accum'    inplace 复用 accum

    outputs.push_back(fusedMom);
    return SUCCESS;
}

int main(int argc, char* argv[])
{
    Graph graph("fused_mul_apply_momentum_extern_graph");
    std::vector<ge::Tensor> input;

    std::map<AscendString, AscendString> global_options = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    Status ret = ge::GEInitialize(global_options);
    if (ret != SUCCESS) {
        std::cerr << "[ERROR] GEInitialize failed" << std::endl;
        return FAILED;
    }

    std::vector<Operator> inputs{};
    std::vector<Operator> outputs{};

    ret = CreateOppInGraph(input, inputs, outputs, graph);
    if (ret != SUCCESS) {
        std::cerr << "[ERROR] CreateOppInGraph failed" << std::endl;
        GEFinalize();
        return FAILED;
    }

    if (!inputs.empty() && !outputs.empty()) {
        graph.SetInputs(inputs).SetOutputs(outputs);
    }

    std::map<AscendString, AscendString> build_options;
    Session* session = new Session(build_options);
    if (session == nullptr) {
        std::cerr << "[ERROR] Create session failed" << std::endl;
        GEFinalize();
        return FAILED;
    }

    std::map<AscendString, AscendString> graph_options;
    uint32_t graph_id = 0;
    ret = session->AddGraph(graph_id, graph, graph_options);
    if (ret != SUCCESS) {
        std::cerr << "[ERROR] AddGraph failed" << std::endl;
        delete session;
        GEFinalize();
        return FAILED;
    }

    std::vector<ge::Tensor> output;
    ret = session->RunGraph(graph_id, input, output);
    if (ret != SUCCESS) {
        std::cerr << "[ERROR] RunGraph failed" << std::endl;
        delete session;
        GEFinalize();
        return FAILED;
    }

    std::cout << "=== GEIR Run PASS ===" << std::endl;
    for (size_t i = 0; i < output.size(); i++) {
        int64_t shapeSize = output[i].GetTensorDesc().GetShape().GetShapeSize();
        std::cout << "output " << i << " shape size = " << shapeSize << std::endl;
    }

    delete session;
    GEFinalize();
    return SUCCESS;
}
