/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file acts_ulq_input_grad_tiling_arch35.cpp
 * \brief ActsULQInputGrad Host 侧 Tiling（arch35 / DAV_3510，DESIGN.md §3.4/§3.10）
 *
 * 1D 展平多核 + UB 双切分：
 *   - 核数按多输入 GM 读写总足迹「求和」口径（DESIGN.md §3.4 权威声明）
 *   - blockFormer 对齐 512 元素；ubFormer 按 256B 对齐
 *   - UB 大小以 GetCoreMemSize 运行时查询，禁止硬编码
 *   - extraSize=8192B 预留（系统/框架 + 双缓冲对齐余量）
 *   - v2.0：4 dtype 组合 K1-K4（yGrad∈{fp16,fp32} × mask∈{bool, 同 yGrad 浮点}）
 *   - cast 中间寄存器驻留（穿刺 K3 实证），不占 UB TBuf；bufferDivisor 仅计队列足迹
 *   - UB 切分按真实最坏 32 B/elem（K4 全 fp32）统一上界，各 Key 按自身 bufferDivisor 反算
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/acts_ulq_input_grad_tiling_data.h"
#include "../../op_kernel/arch35/acts_ulq_input_grad_tiling_key.h"

namespace optiling {

using Ops::Base::CeilAlign;
using Ops::Base::CeilDiv;
using Ops::Base::FloorAlign;
using Ops::Base::FloorDiv;

// 常量（DESIGN.md §3.4 / elewise/tiling.md）
constexpr int64_t MIN_TILING_BITS = 32768; // 每核至少 4KB（bits）
constexpr int64_t ELEM_ALIGN_FACTOR = 512; // 多核切分元素对齐因子
constexpr int64_t ALIGN_256 = 256;         // UB 对齐字节数
constexpr int64_t BITS_PER_BYTE = 8;
constexpr int64_t BUFFER_NUM_DOUBLE = 2; // 双缓冲
constexpr int64_t EXTRA_SIZE = 8192;     // UB 预留（DESIGN.md §3.10）
constexpr size_t WORKSPACE_NUM = 1;
constexpr uint32_t WS_SYS_SIZE = 0U;

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& inShape)
{
    if (inShape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return inShape;
}

// 获取平台信息：ubSize / vector 核数（纯 vector 算子，禁止硬编码）
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// 三输入 + 输出 shape 完全一致校验（无广播，spec shape_mismatch），输出元素总数
static ge::graphStatus GetShapeAndCheck(gert::TilingContext* context, int64_t* totalIdx)
{
    auto inYGrad = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inYGrad);
    auto shapeYGrad = EnsureNotScalar(inYGrad->GetStorageShape());
    auto inMinMask = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, inMinMask);
    auto shapeMinMask = EnsureNotScalar(inMinMask->GetStorageShape());
    auto inMaxMask = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, inMaxMask);
    auto shapeMaxMask = EnsureNotScalar(inMaxMask->GetStorageShape());
    auto outXGrad = context->GetOutputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, outXGrad);
    auto shapeXGrad = EnsureNotScalar(outXGrad->GetStorageShape());

    OP_CHECK_IF(shapeYGrad.GetShapeSize() != shapeMinMask.GetShapeSize() ||
                    shapeYGrad.GetShapeSize() != shapeMaxMask.GetShapeSize() ||
                    shapeYGrad.GetShapeSize() != shapeXGrad.GetShapeSize(),
                OP_LOGE(context,
                        "ActsULQInputGrad: input/output shape size mismatch: y_grad=%ld, min_mask=%ld, "
                        "max_mask=%ld, x_grad=%ld",
                        shapeYGrad.GetShapeSize(), shapeMinMask.GetShapeSize(), shapeMaxMask.GetShapeSize(),
                        shapeXGrad.GetShapeSize()),
                return ge::GRAPH_FAILED);

    *totalIdx = shapeYGrad.GetShapeSize();
    return ge::GRAPH_SUCCESS;
}

// dtype 组合校验（v2.0 4 组：(fp16,bool)(fp16,fp16)(fp32,bool)(fp32,fp32)），输出 y_grad / mask dtype
static ge::graphStatus CheckDtypeCombination(gert::TilingContext* context, ge::DataType* yGradDtype,
                                             ge::DataType* maskDtype)
{
    auto yGradDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, yGradDesc);
    auto minMaskDesc = context->GetInputDesc(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, minMaskDesc);
    auto maxMaskDesc = context->GetInputDesc(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, maxMaskDesc);
    *yGradDtype = yGradDesc->GetDataType();
    *maskDtype = minMaskDesc->GetDataType();

    // 两掩码 dtype 必须一致
    OP_CHECK_IF(minMaskDesc->GetDataType() != maxMaskDesc->GetDataType(),
                OP_LOGE(context, "ActsULQInputGrad: two masks dtype mismatch: min=%d, max=%d",
                        static_cast<int>(minMaskDesc->GetDataType()), static_cast<int>(maxMaskDesc->GetDataType())),
                return ge::GRAPH_FAILED);

    // y_grad dtype 支持集：fp16 / fp32
    OP_CHECK_IF(*yGradDtype != ge::DT_FLOAT16 && *yGradDtype != ge::DT_FLOAT,
                OP_LOGE(context, "ActsULQInputGrad: y_grad dtype not supported: %d (need fp16/fp32)",
                        static_cast<int>(*yGradDtype)),
                return ge::GRAPH_FAILED);

    // mask dtype 支持集：bool / fp16 / fp32
    OP_CHECK_IF(*maskDtype != ge::DT_BOOL && *maskDtype != ge::DT_FLOAT16 && *maskDtype != ge::DT_FLOAT,
                OP_LOGE(context, "ActsULQInputGrad: mask dtype not supported: %d (need bool/fp16/fp32)",
                        static_cast<int>(*maskDtype)),
                return ge::GRAPH_FAILED);

    // v2.0：mask 浮点须与 y_grad 同 dtype（混合浮点组合已移除）；mask 为 bool 时豁免。
    // 合法组合仅 4 组：(fp16,bool)(fp16,fp16)(fp32,bool)(fp32,fp32)。
    OP_CHECK_IF(*maskDtype != ge::DT_BOOL && *maskDtype != *yGradDtype,
                OP_LOGE(context,
                        "ActsULQInputGrad: float mask dtype (%d) must match y_grad dtype (%d) or be bool "
                        "(mixed float combos removed in v2.0)",
                        static_cast<int>(*maskDtype), static_cast<int>(*yGradDtype)),
                return ge::GRAPH_FAILED);

    // x_grad dtype 必须与 y_grad 一致（same_as_first_input）
    auto xGradDesc = context->GetOutputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, xGradDesc);
    OP_CHECK_IF(xGradDesc->GetDataType() != *yGradDtype,
                OP_LOGE(context, "ActsULQInputGrad: x_grad dtype (%d) must match y_grad dtype (%d)",
                        static_cast<int>(xGradDesc->GetDataType()), static_cast<int>(*yGradDtype)),
                return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

// 获取 shape / dtype，并做三输入 shape 一致 + dtype 组合校验（DESIGN.md §3.4 校验）
static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* totalIdx, ge::DataType* yGradDtype,
                                         ge::DataType* maskDtype)
{
    OP_CHECK_IF(GetShapeAndCheck(context, totalIdx) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetShapeAndCheck error"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(CheckDtypeCombination(context, yGradDtype, maskDtype) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "CheckDtypeCombination error"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// 即使 workspace=0 也必须声明 slot，否则运行时不分配 workspace 指针
static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

// 多核切分 + UB 双切分核心计算（totalIdx>0 已保证），填充 TilingData 并设 BlockDim
static ge::graphStatus CalcTilingData(gert::TilingContext* context, ActsULQInputGradTilingData* tiling,
                                      int64_t totalIdx, uint64_t ubSize, int64_t availableCoreNum, int64_t yGradBytes,
                                      int64_t maskBytes)
{
    tiling->dim0 = totalIdx;

    // 多核切分：求和口径每元素 GM 读写总足迹（y_grad 读 + 两 mask 读 + x_grad 写）
    // elemBitsPerCore = (2*sizeof(yGrad) + 2*sizeof(mask)) * 8
    int64_t elemBitsPerCore = (2 * yGradBytes + 2 * maskBytes) * BITS_PER_BYTE;
    int64_t coreNum = CeilDiv(totalIdx * elemBitsPerCore, MIN_TILING_BITS);
    coreNum = (coreNum < availableCoreNum) ? coreNum : availableCoreNum;
    if (coreNum < 1) {
        coreNum = 1;
    }
    tiling->coreNum = static_cast<int32_t>(coreNum);

    // blockFormer：每核基础元素数，对齐 512 元素
    tiling->blockFormer = CeilAlign(CeilDiv(totalIdx, coreNum), ELEM_ALIGN_FACTOR);
    tiling->blockNum = CeilDiv(totalIdx, tiling->blockFormer);
    int64_t usedCoreNum = tiling->blockNum;

    // UB 切分：cast 中间寄存器驻留（穿刺 K3 实证），不占 UB TBuf，故 Kcast=0。
    // bufferDivisor（bits）= bufferNum*(2*yGradBytes + 2*maskBytes)*8（仅队列足迹）。
    // 真实最坏 = K4 全 fp32 → 2*(2*4+2*4)*8 = 256 bits/elem（32 B/elem）。
    int64_t bufferDivisorBits = BUFFER_NUM_DOUBLE * (2 * yGradBytes + 2 * maskBytes) * BITS_PER_BYTE;
    int64_t maxElemNum = (static_cast<int64_t>(ubSize) - EXTRA_SIZE) * BITS_PER_BYTE / bufferDivisorBits;
    // alignFactor：按该 Key 最细 dtype 保证各 buffer 256B 对齐（含 bool/int8→256、fp16→128、fp32→64）
    int64_t minDtypeBytes = (yGradBytes < maskBytes) ? yGradBytes : maskBytes;
    int64_t alignFactor = ALIGN_256 / minDtypeBytes;
    tiling->ubFormer = FloorAlign(maxElemNum, alignFactor);
    OP_CHECK_IF(tiling->ubFormer <= 0, OP_LOGE(context, "ubFormer computed as 0"), return ge::GRAPH_FAILED);

    // former/tail 循环次数（区分首/尾 block）
    tiling->ubLoopOfFormerBlock = CeilDiv(tiling->blockFormer, tiling->ubFormer);
    tiling->ubTailOfFormerBlock = tiling->blockFormer - (tiling->ubLoopOfFormerBlock - 1) * tiling->ubFormer;

    int64_t blockTail = totalIdx - (tiling->blockNum - 1) * tiling->blockFormer;
    tiling->ubLoopOfTailBlock = CeilDiv(blockTail, tiling->ubFormer);
    tiling->ubTailOfTailBlock = blockTail - (tiling->ubLoopOfTailBlock - 1) * tiling->ubFormer;

    context->SetBlockDim(usedCoreNum);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ActsULQInputGradTilingFunc(gert::TilingContext* context)
{
    // 1、平台信息
    uint64_t ubSize = 0;
    int64_t availableCoreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, &ubSize, &availableCoreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // 2、shape / dtype
    int64_t totalIdx;
    ge::DataType yGradDtype;
    ge::DataType maskDtype;
    OP_CHECK_IF(GetShapeAttrsInfo(context, &totalIdx, &yGradDtype, &maskDtype) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    // 3、workspace
    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    // 4、TilingData 清零
    ActsULQInputGradTilingData* tiling = context->GetTilingData<ActsULQInputGradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(ActsULQInputGradTilingData), 0, sizeof(ActsULQInputGradTilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    // 空 Tensor 短路（dim0=0），避免除零 / 非法搬运（spec §5.3）
    // TilingKey 仅 BUFFER_MODE 维度（dtype 由 def 驱动的 DTYPE_* 宏承担）。
    if (totalIdx == 0) {
        // ubFormer 必须设为正数：kernel Process 计算 loopCount=(blockLength_+ubFormer_-1)/ubFormer_，
        // 若 ubFormer_=0（memset 清零）则除零崩溃。设 ubFormer=1 时 blockLength_=0 → loopCount=0，
        // 循环不执行，安全返回（kernel 侧另有 blockLength_==0 提前返回双保险）。
        tiling->dim0 = 0;
        tiling->ubFormer = 1;
        context->SetBlockDim(1);
        ASCENDC_TPL_SEL_PARAM(context, 0); // BUFFER_MODE=0（空 Tensor 无实际计算）
        return ge::GRAPH_SUCCESS;
    }

    // 5、多核 / UB 切分核心计算
    // dtype 字节宽（bool 以 1B 计；fp16=2B、fp32=4B）
    int64_t yGradBytes = static_cast<int64_t>(ge::GetSizeByDataType(yGradDtype));
    int64_t maskBytes = static_cast<int64_t>(ge::GetSizeByDataType(maskDtype));
    OP_CHECK_IF(
        CalcTilingData(context, tiling, totalIdx, ubSize, availableCoreNum, yGradBytes, maskBytes) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "CalcTilingData error"), return ge::GRAPH_FAILED);

    // 6、TilingKey（模板参数选择，禁止 TILING_KEY_IS 宏）
    // 参数顺序与 tiling_key.h ASCENDC_TPL_ARGS_DECL 一致：仅 BUFFER_MODE
    // （dtype 维度由 def 驱动的 DTYPE_* 宏承担，tiling_key 不再编码 dtype）。
    uint32_t bufferMode = 1; // 双缓冲流水
    ASCENDC_TPL_SEL_PARAM(context, bufferMode);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForActsULQInputGrad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct ActsULQInputGradCompileInfo {}; // 必须定义，入图场景依赖

IMPL_OP_OPTILING(ActsULQInputGrad)
    .Tiling(ActsULQInputGradTilingFunc)
    .TilingParse<ActsULQInputGradCompileInfo>(TilingParseForActsULQInputGrad);

} // namespace optiling
