/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 */
/*!
 * \file inplace_apply_ada_max_tiling_host_arch35.h
 * \brief InplaceApplyAdaMax 纯函数 tiling 接口头文件（arch35）
 */

#ifndef INPLACE_APPLY_ADA_MAX_TILING_HOST_ARCH35_H
#define INPLACE_APPLY_ADA_MAX_TILING_HOST_ARCH35_H

#include <cstdint>
#include "graph/types.h"
#include "../../op_kernel/arch35/inplace_apply_ada_max_tiling_data.h"

namespace optiling {

struct CommonTilingInputs {
    ge::DataType dtype;
    int64_t N;
    int64_t coreNumAiv;
    int64_t ubBytes;
};

struct CommonTilingOutputs {
    int64_t perBufBytes;
    int64_t perBufElems;
    int64_t P;
    int64_t ubUsedBytes;
    int32_t tilingKey;
    int64_t alignElem;
    bool isAlign;
    int64_t totalTiles;
};

void ComputeCommonQuantities(int64_t ubBytes, int64_t P, CommonTilingOutputs& out);

int32_t ChooseTilingKey(ge::DataType dtype, int64_t N);

void ComputeCommonTiling(const CommonTilingInputs& in, CommonTilingOutputs& out);

void FindSplitAxis(const int64_t* maxBroShape, int64_t rank, int64_t perBufElems, SplitResult& split);

void MultiCoreSplit(const int64_t* maxBroShape, const SplitResult& split, int64_t coreNumAiv,
                    MultiCoreResult& multicore);

struct BranchInputs {
    const int64_t* maxBroShape;
    int64_t rank;
    int64_t N;
    int64_t perBufElems;
    int64_t coreNumAiv;
    int64_t alignElem;
};

void ComputeBranchTiling(int32_t tilingKey, const BranchInputs& in, SplitResult& split, MultiCoreResult& multicore);

} // namespace optiling

#endif // INPLACE_APPLY_ADA_MAX_TILING_HOST_ARCH35_H
