/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <array>
#include <climits>
#include <string>
#include "log/log.h"
#include "register/op_impl_registry.h"
#include "util/shape_util.h"

namespace ops {
namespace {
constexpr size_t KSIZE_ATTR = 0;
constexpr size_t STRIDES_ATTR = 1;
constexpr size_t PADS_ATTR = 2;
constexpr size_t DATA_FORMAT_ATTR = 3;
constexpr size_t RANK_5 = 5;
constexpr size_t INPUT_NUM = 3;
constexpr size_t Y_IDX = 0;
constexpr int64_t UNKNOWN_DIM = -1;

constexpr size_t SPATIAL_DIM_NUM = 3;
constexpr size_t PADS_NUM = 6;
constexpr const char* INPUT_NAMES[INPUT_NUM] = {"orig_x", "orig_y", "grads"};
bool CheckedMul(int64_t a, int64_t b, int64_t& value)
{
    if (a < 0 || b < 0 || (a != 0 && b > INT64_MAX / a))
        return false;
    value = a * b;
    return true;
}

bool CheckedAdd(int64_t a, int64_t b, int64_t& value)
{
    if ((b > 0 && a > INT64_MAX - b) || (b < 0 && a < INT64_MIN - b))
        return false;
    value = a + b;
    return true;
}

ge::graphStatus ParseSpatial(gert::InferShapeContext* context, size_t index, const char* attrName,
                             std::array<int64_t, SPATIAL_DIM_NUM>& values)
{
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    auto vector = attrs->GetAttrPointer<gert::ContinuousVector>(index);
    OP_CHECK_NULL_WITH_CONTEXT(context, vector);
    const size_t size = vector->GetSize();
    OP_CHECK_IF(
        size != 1 && size != 3 && size != 5,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), attrName, std::to_string(size).c_str(), "1, 3 or 5"),
        return ge::GRAPH_FAILED);
    auto data = static_cast<const int64_t*>(vector->GetData());
    OP_CHECK_NULL_WITH_CONTEXT(context, data);
    if (size == 1) {
        values = {data[0], data[0], data[0]};
    } else if (size == 3) {
        values = {data[0], data[1], data[2]};
    } else {
        OP_CHECK_IF(data[0] != 1 || data[4] != 1,
                    OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), attrName, "N/C values are not 1",
                                                           "N and C axes must not be pooled"),
                    return ge::GRAPH_FAILED);
        values = {data[1], data[2], data[3]};
    }
    OP_CHECK_IF(values[0] <= 0 || values[1] <= 0 || values[2] <= 0,
                OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), attrName,
                                                       "one or more spatial values are non-positive",
                                                       "spatial values must be positive"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus ValidateAttrs(gert::InferShapeContext* context, std::array<int64_t, SPATIAL_DIM_NUM>& kernel,
                              std::array<int64_t, SPATIAL_DIM_NUM>& stride, bool& same)
{
    if (ParseSpatial(context, KSIZE_ATTR, "ksize", kernel) != ge::GRAPH_SUCCESS ||
        ParseSpatial(context, STRIDES_ATTR, "strides", stride) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    auto pads = attrs->GetAttrPointer<gert::ContinuousVector>(PADS_ATTR);
    OP_CHECK_NULL_WITH_CONTEXT(context, pads);
    OP_CHECK_IF(
        pads->GetSize() != PADS_NUM,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "pads", std::to_string(pads->GetSize()).c_str(), "6"),
        return ge::GRAPH_FAILED);
    auto padData = static_cast<const int64_t*>(pads->GetData());
    OP_CHECK_NULL_WITH_CONTEXT(context, padData);
    same = false;
    for (size_t i = 0; i < PADS_NUM; ++i) {
        OP_CHECK_IF(
            padData[i] < 0,
            OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "pads", std::to_string(padData[i]).c_str(),
                                                  "all pads values must be non-negative"),
            return ge::GRAPH_FAILED);
        same = same || padData[i] != 0;
    }
    const char* format = attrs->GetAttrPointer<char>(DATA_FORMAT_ATTR);
    OP_CHECK_NULL_WITH_CONTEXT(context, format);
    OP_CHECK_IF(std::string(format) != "NDHWC",
                OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), "data_format", format, "NDHWC"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus ValidateDtypeAndFormat(gert::InferShapeContext* context)
{
    for (size_t i = 0; i < INPUT_NUM; ++i) {
        auto desc = context->GetInputDesc(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, desc);
        OP_CHECK_IF(desc->GetDataType() != ge::DT_FLOAT16,
                    OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), INPUT_NAMES[i],
                                              std::to_string(desc->GetDataType()).c_str(), "DT_FLOAT16"),
                    return ge::GRAPH_FAILED);
        OP_CHECK_IF(desc->GetOriginFormat() != ge::FORMAT_ND,
                    OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), INPUT_NAMES[i],
                                               std::to_string(desc->GetOriginFormat()).c_str(), "FORMAT_ND"),
                    return ge::GRAPH_FAILED);
        OP_CHECK_IF(
            desc->GetFormat().GetStorageFormat() != ge::FORMAT_ND,
            OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), INPUT_NAMES[i],
                                       std::to_string(desc->GetFormat().GetStorageFormat()).c_str(), "FORMAT_ND"),
            return ge::GRAPH_FAILED);
    }
    auto outputDesc = context->GetOutputDesc(Y_IDX);
    OP_CHECK_NULL_WITH_CONTEXT(context, outputDesc);
    OP_CHECK_IF(outputDesc->GetOriginFormat() != ge::FORMAT_ND,
                OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), "y",
                                           std::to_string(outputDesc->GetOriginFormat()).c_str(), "FORMAT_ND"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(
        outputDesc->GetFormat().GetStorageFormat() != ge::FORMAT_ND,
        OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), "y",
                                   std::to_string(outputDesc->GetFormat().GetStorageFormat()).c_str(), "FORMAT_ND"),
        return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus ValidateWindowBounds(gert::InferShapeContext* context, int64_t output, int64_t kernel, int64_t stride,
                                     int64_t padBefore)
{
    int64_t lastStart = 0;
    int64_t lastEnd = 0;
    int64_t firstEnd = 0;
    OP_CHECK_IF(
        !CheckedMul(output - 1, stride, lastStart) || !CheckedAdd(lastStart, -padBefore, lastStart) ||
            !CheckedAdd(lastStart, kernel - 1, lastEnd) || !CheckedAdd(-padBefore, kernel - 1, firstEnd),
        OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), "shape, ksize, strides",
                                               "pool window endpoint overflow", "pool window endpoint exceeds int64"),
        return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus InferPoolDim(gert::InferShapeContext* context, int64_t input, int64_t kernel, int64_t stride, bool same,
                             int64_t& output)
{
    if (input == UNKNOWN_DIM) {
        output = UNKNOWN_DIM;
        return ge::GRAPH_SUCCESS;
    }
    OP_CHECK_IF(
        input <= 0,
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "orig_x shape", std::to_string(input).c_str(),
                                              "input spatial dimensions must be positive"),
        return ge::GRAPH_FAILED);
    if (same) {
        output = input / stride + static_cast<int64_t>(input % stride != 0);
        int64_t end = 0;
        OP_CHECK_IF(!CheckedMul(output - 1, stride, end) || !CheckedAdd(end, kernel, end),
                    OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), "orig_x shape, ksize, strides",
                                                           "SAME padding expression overflow",
                                                           "padding calculation exceeds int64"),
                    return ge::GRAPH_FAILED);
        const int64_t totalPad = end > input ? end - input : 0;
        return ValidateWindowBounds(context, output, kernel, stride, totalPad / 2);
    }
    OP_CHECK_IF(kernel > input,
                OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), "ksize, orig_x shape",
                                                       "kernel exceeds input", "VALID kernel must fit input"),
                return ge::GRAPH_FAILED);
    const int64_t span = input - kernel + 1;
    output = span / stride + static_cast<int64_t>(span % stride != 0);
    return ValidateWindowBounds(context, output, kernel, stride, 0);
}

ge::graphStatus ValidateKnownShape(gert::InferShapeContext* context, const gert::Shape& shape, const char* name)
{
    if (Ops::Base::IsUnknownRank(shape)) {
        return ge::GRAPH_SUCCESS;
    }
    OP_CHECK_IF(
        shape.GetDimNum() != RANK_5,
        OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), name, std::to_string(shape.GetDimNum()).c_str(), "5"),
        return ge::GRAPH_FAILED);
    int64_t product = 1;
    bool fullyKnown = true;
    for (size_t i = 0; i < RANK_5; ++i) {
        const int64_t dim = shape.GetDim(i);
        OP_CHECK_IF(dim != UNKNOWN_DIM && dim <= 0,
                    OP_LOGE_FOR_INVALID_SHAPE_WITH_REASON(context->GetNodeName(), name,
                                                          "contains a non-positive known dimension",
                                                          "known dimensions must be positive"),
                    return ge::GRAPH_FAILED);
        if (dim == UNKNOWN_DIM) {
            fullyKnown = false;
            continue;
        }
        OP_CHECK_IF(!CheckedMul(product, dim, product),
                    OP_LOGE_FOR_INVALID_SHAPE_WITH_REASON(context->GetNodeName(), name, "shape product overflow",
                                                          "shape product exceeds int64"),
                    return ge::GRAPH_FAILED);
    }
    if (!fullyKnown) {
        return ge::GRAPH_SUCCESS;
    }
    int64_t offset = shape.GetDim(0) - 1;
    for (size_t i = 1; i < RANK_5; ++i) {
        OP_CHECK_IF(!CheckedMul(offset, shape.GetDim(i), offset) || !CheckedAdd(offset, shape.GetDim(i) - 1, offset),
                    OP_LOGE_FOR_INVALID_SHAPE_WITH_REASON(context->GetNodeName(), name, "linear offset overflow",
                                                          "linear offset upper bound exceeds int64"),
                    return ge::GRAPH_FAILED);
    }
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus ValidateXAndGrads(gert::InferShapeContext* context, const gert::Shape& x, const gert::Shape& grads)
{
    if (Ops::Base::IsUnknownRank(x) || Ops::Base::IsUnknownRank(grads)) {
        return ge::GRAPH_SUCCESS;
    }
    for (size_t i = 0; i < RANK_5; ++i) {
        const int64_t xd = x.GetDim(i);
        const int64_t gd = grads.GetDim(i);
        OP_CHECK_IF(xd != UNKNOWN_DIM && gd != UNKNOWN_DIM && xd != gd,
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "orig_x, grads",
                                                           "shapes are different", "orig_x and grads must match"),
                    return ge::GRAPH_FAILED);
    }
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus ValidatePoolShape(gert::InferShapeContext* context, const gert::Shape& x, const gert::Shape& origY,
                                  const std::array<int64_t, SPATIAL_DIM_NUM>& kernel,
                                  const std::array<int64_t, SPATIAL_DIM_NUM>& stride, bool same)
{
    if (Ops::Base::IsUnknownRank(x)) {
        return ge::GRAPH_SUCCESS;
    }
    int64_t expected[SPATIAL_DIM_NUM] = {};
    for (size_t i = 0; i < SPATIAL_DIM_NUM; ++i) {
        if (InferPoolDim(context, x.GetDim(i + 1), kernel[i], stride[i], same, expected[i]) != ge::GRAPH_SUCCESS) {
            return ge::GRAPH_FAILED;
        }
    }
    if (Ops::Base::IsUnknownRank(origY)) {
        return ge::GRAPH_SUCCESS;
    }
    OP_CHECK_IF(x.GetDim(0) != UNKNOWN_DIM && origY.GetDim(0) != UNKNOWN_DIM && x.GetDim(0) != origY.GetDim(0),
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "orig_x, orig_y",
                                                       "batch dimensions are different",
                                                       "orig_x and orig_y batch dimensions must match"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(x.GetDim(4) != UNKNOWN_DIM && origY.GetDim(4) != UNKNOWN_DIM && x.GetDim(4) != origY.GetDim(4),
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "orig_x, orig_y",
                                                       "channel dimensions are different",
                                                       "orig_x and orig_y channel dimensions must match"),
                return ge::GRAPH_FAILED);
    for (size_t i = 0; i < SPATIAL_DIM_NUM; ++i) {
        OP_CHECK_IF(
            expected[i] != UNKNOWN_DIM && origY.GetDim(i + 1) != UNKNOWN_DIM && expected[i] != origY.GetDim(i + 1),
            OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "orig_x, orig_y",
                                                   "orig_y spatial shape differs from inferred output",
                                                   "orig_y spatial shape must match the pooling output"),
            return ge::GRAPH_FAILED);
    }
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus ValidateShapes(gert::InferShapeContext* context, const std::array<int64_t, SPATIAL_DIM_NUM>& kernel,
                               const std::array<int64_t, SPATIAL_DIM_NUM>& stride, bool same, gert::Shape* yShape)
{
    const gert::Shape* x = context->GetInputShape(0);
    const gert::Shape* origY = context->GetInputShape(1);
    const gert::Shape* grads = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, x);
    OP_CHECK_NULL_WITH_CONTEXT(context, origY);
    OP_CHECK_NULL_WITH_CONTEXT(context, grads);
    if (ValidateKnownShape(context, *x, "orig_x") != ge::GRAPH_SUCCESS ||
        ValidateKnownShape(context, *origY, "orig_y") != ge::GRAPH_SUCCESS ||
        ValidateKnownShape(context, *grads, "grads") != ge::GRAPH_SUCCESS ||
        ValidateXAndGrads(context, *x, *grads) != ge::GRAPH_SUCCESS ||
        ValidatePoolShape(context, *x, *origY, kernel, stride, same) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    if (Ops::Base::IsUnknownRank(*origY)) {
        Ops::Base::SetUnknownRank(*yShape);
    } else {
        *yShape = *origY;
    }
    return ge::GRAPH_SUCCESS;
}
} // namespace

ge::graphStatus InferShapeForMaxPool3DGradGrad(gert::InferShapeContext* context)
{
    OP_CHECK_IF(context == nullptr, OP_LOGE("MaxPool3DGradGrad", "context is null"), return ge::GRAPH_FAILED);
    std::array<int64_t, SPATIAL_DIM_NUM> kernel = {}, stride = {};
    bool same = false;
    if (ValidateDtypeAndFormat(context) != ge::GRAPH_SUCCESS ||
        ValidateAttrs(context, kernel, stride, same) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    gert::Shape* yShape = context->GetOutputShape(Y_IDX);
    OP_CHECK_NULL_WITH_CONTEXT(context, yShape);
    return ValidateShapes(context, kernel, stride, same, yShape);
}

IMPL_OP_INFERSHAPE(MaxPool3DGradGrad).InferShape(InferShapeForMaxPool3DGradGrad);
} // namespace ops
