/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#include <gtest/gtest.h>
#include <iostream>
#include "infershape_test_util.h"
#include "ut_op_common.h"
#include "../../../op_graph/fused_mul_apply_momentum_proto.h"

class FusedMulApplyMomentumInferShape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "FusedMulApplyMomentum SetUp" << std::endl; }
    static void TearDownTestCase() { std::cout << "FusedMulApplyMomentum TearDown" << std::endl; }
};

TEST_F(FusedMulApplyMomentumInferShape, infershape_case_0)
{
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl("FusedMulApplyMomentum"), nullptr);
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("FusedMulApplyMomentum")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);

    gert::StorageShape varShape = {{256, 16}, {256, 16}};
    gert::StorageShape accumShape = {{256, 16}, {256, 16}};
    gert::StorageShape lrShape = {{1}, {1}};
    gert::StorageShape x1Shape = {{256, 16}, {256, 16}};
    gert::StorageShape momentumShape = {{1}, {1}};
    gert::StorageShape x2Shape = {{1}, {1}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(6, 2)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1})
                      .InputShapes({&varShape, &accumShape, &lrShape, &x1Shape, &momentumShape, &x2Shape})
                      .OutputShapes({&varShape, &accumShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);
}

TEST_F(FusedMulApplyMomentumInferShape, infershape_rank_6)
{
    auto inferShapeFunc = gert::OpImplRegistry::GetInstance().GetOpImpl("FusedMulApplyMomentum")->infer_shape;
    ASSERT_NE(inferShapeFunc, nullptr);

    gert::StorageShape tensorShape = {{2, 2, 2, 2, 2, 2}, {2, 2, 2, 2, 2, 2}};
    gert::StorageShape scalarShape = {{1}, {1}};

    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(6, 2)
                      .IrInstanceNum({1, 1, 1, 1, 1, 1})
                      .InputShapes({&tensorShape, &tensorShape, &scalarShape, &tensorShape, &scalarShape, &scalarShape})
                      .OutputShapes({&tensorShape, &tensorShape})
                      .Build();

    ASSERT_EQ(inferShapeFunc(holder.GetContext<gert::InferShapeContext>()), ge::GRAPH_SUCCESS);
}
