/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software; you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/* Dynamic-shape / dynamic-rank GEIR verification for BlockLstmGrad.
 *
 * Both scenarios share one GE Session. Each scenario adds one graph and runs
 * it three times with distinct concrete shapes; every run checks all eight
 * outputs' shape, dtype and values against an in-process double-precision
 * backward golden. use_peephole=false, gate_order="ifco" (w columns
 * [i | f | g | o], each H wide; rows [0,I) hit x, rows [I,I+H) hit h).
 *
 * Rank note: the BlockLstmGrad contract fixes input ranks (x [T,B,I] rank 3,
 * cs_prev/h_prev [B,H] rank 2, w [I+H,4H] rank 2, vectors rank 1, the seven
 * gate/grad tensors [T,B,H] rank 3; block_lstm_grad_infershape.cpp rejects any
 * other KNOWN rank). The unknown-rank (-2) scenario therefore varies T/B/I/H
 * with contract ranks, same as the forward's dynamic example.
 */

#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "array_ops.h"
#include "ge_api.h"
#include "ge_api_types.h"
#include "ge_error_codes.h"
#include "ge_ir_build.h"
#include "graph.h"
#include "tensor.h"
#include "types.h"

#include "../../op_graph/block_lstm_grad_proto.h"

namespace {

constexpr int kSuccess = 0;
constexpr int kFailed = -1;
/* The backward chain sums T*B products into w_grad/b_grad; the fp32 kernel
 * against the double golden keeps ~1e-4 relative error, so 1e-3 leaves margin
 * for the largest case without hiding real breakage. */
constexpr float kAtol = 1.0e-3F;
constexpr float kRtol = 1.0e-3F;

using ShapeVector = std::vector<int64_t>;
using ShapeList = std::vector<ShapeVector>;

struct Rng {
    unsigned int seed = 42U;
    float Next()
    {
        seed = seed * 1664525U + 1013904223U;
        return (seed >> 8) / 16777216.0F - 0.5F;
    }
};

/* Feed order: slm, x, cs_prev, h_prev, w, wci, wcf, wco, b,
 *              i, cs, f, o, ci, co, h, cs_grad, h_grad. */
struct CaseData {
    ShapeList shapes;
    std::vector<int64_t> slm;
    std::vector<float> x;
    std::vector<float> csPrev;
    std::vector<float> hPrev;
    std::vector<float> w;
    std::vector<float> wci;
    std::vector<float> wcf;
    std::vector<float> wco;
    std::vector<float> b;
    std::vector<float> gi;
    std::vector<float> gcs;
    std::vector<float> gf;
    std::vector<float> go;
    std::vector<float> gci;
    std::vector<float> gco;
    std::vector<float> gh;
    std::vector<float> csGrad;
    std::vector<float> hGrad;
};

std::string ShapeListToJson(const ShapeList& shapes)
{
    std::string text = "[";
    for (size_t outer = 0; outer < shapes.size(); ++outer) {
        if (outer != 0U) {
            text += ",";
        }
        text += "[";
        for (size_t inner = 0; inner < shapes[outer].size(); ++inner) {
            if (inner != 0U) {
                text += ",";
            }
            text += std::to_string(shapes[outer][inner]);
        }
        text += "]";
    }
    text += "]";
    return text;
}

std::vector<float> RandomVector(int64_t count, Rng& rng, float scale)
{
    std::vector<float> data(static_cast<size_t>(count));
    for (int64_t index = 0; index < count; ++index) {
        data[static_cast<size_t>(index)] = scale * rng.Next();
    }
    return data;
}

/* Gate tensors stay inside (0,1) / (-1,1) so the derivative factors
 * (g*(1-g), 1-tanh^2) are well conditioned; cs uses tanh-range values
 * because co = tanh(cs) must be finite. */
std::vector<float> SigmoidRange(int64_t count, Rng& rng)
{
    std::vector<float> data(static_cast<size_t>(count));
    for (int64_t index = 0; index < count; ++index) {
        data[static_cast<size_t>(index)] = 0.5F + 0.4F * rng.Next();
    }
    return data;
}

std::vector<float> TanhRange(int64_t count, Rng& rng)
{
    std::vector<float> data(static_cast<size_t>(count));
    for (int64_t index = 0; index < count; ++index) {
        data[static_cast<size_t>(index)] = 0.8F * rng.Next();
    }
    return data;
}

CaseData MakeCase(int t, int b, int i, int h)
{
    CaseData data;
    Rng rng;
    data.shapes = {{1},       {t, b, i}, {b, h},    {b, h},    {i + h, 4 * h}, {h},
                   {h},       {h},       {4 * h},   {t, b, h}, {t, b, h},      {t, b, h},
                   {t, b, h}, {t, b, h}, {t, b, h}, {t, b, h}, {t, b, h},      {t, b, h}};
    data.slm = {t};
    data.x = RandomVector((int64_t)t * b * i, rng, 1.0F);
    data.csPrev = TanhRange((int64_t)b * h, rng);
    data.hPrev = TanhRange((int64_t)b * h, rng);
    data.w = RandomVector((int64_t)(i + h) * 4 * h, rng, 1.0F);
    data.wci = RandomVector(h, rng, 0.1F);
    data.wcf = RandomVector(h, rng, 0.1F);
    data.wco = RandomVector(h, rng, 0.1F);
    data.b = RandomVector(4 * static_cast<int64_t>(h), rng, 0.1F);
    data.gi = SigmoidRange((int64_t)t * b * h, rng);
    data.gcs = TanhRange((int64_t)t * b * h, rng);
    data.gf = SigmoidRange((int64_t)t * b * h, rng);
    data.go = SigmoidRange((int64_t)t * b * h, rng);
    data.gci = TanhRange((int64_t)t * b * h, rng);
    data.gco = TanhRange((int64_t)t * b * h, rng);
    data.gh = TanhRange((int64_t)t * b * h, rng);
    data.csGrad = RandomVector((int64_t)t * b * h, rng, 1.0F);
    data.hGrad = RandomVector((int64_t)t * b * h, rng, 1.0F);
    return data;
}

/* The eight grads in output order. */
struct BackwardGolden {
    std::vector<double> xGrad;
    std::vector<double> csPrevGrad;
    std::vector<double> hPrevGrad;
    std::vector<double> wGrad;
    std::vector<double> wciGrad;
    std::vector<double> wcfGrad;
    std::vector<double> wcoGrad;
    std::vector<double> bGrad;
};

/* Standard LSTM BPTT over the PROVIDED gate values (the op is a pure backward:
 * it never recomputes the forward). Reverse sweep, per batch, carrying dcs and
 * dh across timesteps; the t=0 carries land in cs_prev_grad / h_prev_grad. */
BackwardGolden ComputeBackwardGolden(int t, int b, int i, int h, const CaseData& d)
{
    BackwardGolden out;
    const size_t plane = static_cast<size_t>(b) * h;
    const size_t xPlane = static_cast<size_t>(b) * i;
    out.xGrad.assign(static_cast<size_t>(t) * xPlane, 0.0);
    out.csPrevGrad.assign(plane, 0.0);
    out.hPrevGrad.assign(plane, 0.0);
    out.wGrad.assign(static_cast<size_t>(i + h) * 4 * h, 0.0);
    out.wciGrad.assign(h, 0.0);
    out.wcfGrad.assign(h, 0.0);
    out.wcoGrad.assign(h, 0.0);
    out.bGrad.assign(static_cast<size_t>(4) * h, 0.0);

    std::vector<double> carryCs(plane, 0.0);
    std::vector<double> carryH(plane, 0.0);
    for (int tt = t - 1; tt >= 0; --tt) {
        for (int bb = 0; bb < b; ++bb) {
            const size_t goff = (static_cast<size_t>(tt) * b + bb) * h;
            const float* iv = &d.gi[goff];
            const float* fv = &d.gf[goff];
            const float* gv = &d.gci[goff];
            const float* ov = &d.go[goff];
            const float* cov = &d.gco[goff];
            /* dh at tt = h_grad[tt] + feedback from step tt+1. */
            std::vector<double> dh(h);
            for (int j = 0; j < h; ++j) {
                dh[static_cast<size_t>(j)] = d.hGrad[goff + j] + carryH[static_cast<size_t>(bb) * h + j];
            }
            /* dct = dh*o*(1-co^2) + cs_grad + carry. */
            std::vector<double> dct(h);
            for (int j = 0; j < h; ++j) {
                const double co = cov[j];
                dct[static_cast<size_t>(j)] = dh[static_cast<size_t>(j)] * ov[j] * (1.0 - co * co) +
                                              d.csGrad[goff + j] + carryCs[static_cast<size_t>(bb) * h + j];
            }
            /* cs_{t-1} and h_{t-1} for this (t,b). */
            const float* csPrevRow = (tt == 0) ? &d.csPrev[static_cast<size_t>(bb) * h] :
                                                 &d.gcs[(static_cast<size_t>(tt - 1) * b + bb) * h];
            const float* hPrevRow = (tt == 0) ? &d.hPrev[static_cast<size_t>(bb) * h] :
                                                &d.gh[(static_cast<size_t>(tt - 1) * b + bb) * h];
            /* Pre-activation grads. */
            std::vector<double> di(h), df(h), dg(h), do_(h);
            for (int j = 0; j < h; ++j) {
                di[static_cast<size_t>(j)] = dct[j] * gv[j] * iv[j] * (1.0 - iv[j]);
                df[static_cast<size_t>(j)] = dct[j] * csPrevRow[j] * fv[j] * (1.0 - fv[j]);
                dg[static_cast<size_t>(j)] = dct[j] * iv[j] * (1.0 - gv[j] * gv[j]);
                do_[static_cast<size_t>(j)] = dh[j] * cov[j] * ov[j] * (1.0 - ov[j]);
            }
            const double* dgate[4] = {di.data(), df.data(), dg.data(), do_.data()};
            /* x-side rows: dx and dW. */
            const float* xRow = &d.x[(static_cast<size_t>(tt) * b + bb) * i];
            for (int j = 0; j < i; ++j) {
                double acc = 0.0;
                for (int g = 0; g < 4; ++g) {
                    const float* wRow = &d.w[static_cast<size_t>(j) * 4 * h + static_cast<size_t>(g) * h];
                    double wRowSum = 0.0;
                    for (int c = 0; c < h; ++c) {
                        wRowSum += dgate[g][c] * wRow[c];
                        out.wGrad[static_cast<size_t>(j) * 4 * h + static_cast<size_t>(g) * h + c] += xRow[j] *
                                                                                                      dgate[g][c];
                    }
                    acc += wRowSum;
                }
                out.xGrad[(static_cast<size_t>(tt) * b + bb) * i + j] = acc;
            }
            /* h-side rows: dW and the dh feedback (carry to t-1). */
            std::vector<double> dhPrev(h, 0.0);
            for (int j = 0; j < h; ++j) {
                for (int g = 0; g < 4; ++g) {
                    const float* wRow = &d.w[static_cast<size_t>(i + j) * 4 * h + static_cast<size_t>(g) * h];
                    for (int c = 0; c < h; ++c) {
                        dhPrev[j] += dgate[g][c] * wRow[c];
                        out.wGrad[static_cast<size_t>(i + j) * 4 * h + static_cast<size_t>(g) * h + c] += hPrevRow[j] *
                                                                                                          dgate[g][c];
                    }
                }
            }
            /* b grad and the carries. */
            for (int c = 0; c < h; ++c) {
                out.bGrad[static_cast<size_t>(c)] += di[c];
                out.bGrad[static_cast<size_t>(h + c)] += df[c];
                out.bGrad[static_cast<size_t>(2 * h + c)] += dg[c];
                out.bGrad[static_cast<size_t>(3 * h + c)] += do_[c];
                carryCs[static_cast<size_t>(bb) * h + c] = dct[c] * fv[c];
                carryH[static_cast<size_t>(bb) * h + c] = dhPrev[c];
            }
            if (tt == 0) {
                for (int c = 0; c < h; ++c) {
                    out.csPrevGrad[static_cast<size_t>(bb) * h + c] = carryCs[static_cast<size_t>(bb) * h + c];
                    out.hPrevGrad[static_cast<size_t>(bb) * h + c] = carryH[static_cast<size_t>(bb) * h + c];
                }
            }
        }
    }
    return out;
}

ge::TensorDesc MakeDesc(const ShapeVector& shape, ge::DataType dtype, bool hostPlacement)
{
    ge::TensorDesc desc(ge::Shape(shape), ge::FORMAT_ND, dtype);
    if (hostPlacement) {
        desc.SetPlacement(ge::kPlacementHost);
    }
    desc.SetFormat(ge::FORMAT_ND);
    desc.SetRealDimCnt(static_cast<uint32_t>(shape.size()));
    return desc;
}

ge::Tensor MakeFeed(const ShapeVector& shape, const void* data, size_t bytes, ge::DataType dtype)
{
    return ge::Tensor(MakeDesc(shape, dtype, true), reinterpret_cast<uint8_t*>(const_cast<void*>(data)),
                      static_cast<uint32_t>(bytes));
}

bool CheckTensor(const ge::Tensor& tensor, const ShapeVector& shape, const std::vector<double>& golden,
                 const char* name)
{
    const ge::TensorDesc& desc = tensor.GetTensorDesc();
    const ge::Shape& actual = desc.GetShape();
    if (actual.GetDimNum() != shape.size()) {
        std::cout << name << " rank mismatch: " << actual.GetDimNum() << " vs " << shape.size() << std::endl;
        return false;
    }
    for (size_t index = 0; index < shape.size(); ++index) {
        if (actual.GetDim(index) != shape[index]) {
            std::cout << name << " dim[" << index << "] mismatch: " << actual.GetDim(index) << " vs " << shape[index]
                      << std::endl;
            return false;
        }
    }
    if (desc.GetDataType() != ge::DT_FLOAT) {
        std::cout << name << " dtype mismatch: " << desc.GetDataType() << std::endl;
        return false;
    }
    if (tensor.GetSize() != golden.size() * sizeof(float)) {
        std::cout << name << " byte size mismatch" << std::endl;
        return false;
    }
    const float* values = reinterpret_cast<const float*>(tensor.GetData());
    for (size_t index = 0; index < golden.size(); ++index) {
        const float error = std::fabs(values[index] - static_cast<float>(golden[index]));
        const float tolerance = kAtol + kRtol * static_cast<float>(std::fabs(golden[index]));
        if (!std::isfinite(values[index]) || error > tolerance) {
            std::cout << name << " value mismatch at " << index << ": " << values[index] << " vs " << golden[index]
                      << " (tol " << tolerance << ")" << std::endl;
            return false;
        }
    }
    return true;
}

/* Declared shapes per scenario, in feed order (slm, x, cs_prev, h_prev, w,
 * wci, wcf, wco, b, i, cs, f, o, ci, co, h, cs_grad, h_grad). */
ShapeList DeclaredShapes(const std::string& scenario)
{
    if (scenario == "unknown_rank_minus_2") {
        /* x declared as exact [-2]; remaining inputs unknown dims. */
        return {{1},          {-2},         {-1, -1},     {-1, -1},     {-1, -1},     {-1},
                {-1},         {-1},         {-1},         {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
                {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}};
    }
    return {{1},          {-1, -1, -1}, {-1, -1},     {-1, -1},     {-1, -1},     {-1},
            {-1},         {-1},         {-1},         {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
            {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}};
}

int RunScenario(ge::Session& session, uint32_t graphId, const std::string& scenario, const std::vector<CaseData>& cases)
{
    const ShapeList declared = DeclaredShapes(scenario);
    std::cout << "Scenario " << scenario << ", declared shape " << ShapeListToJson(declared) << std::endl;

    const std::string prefix = "block_lstm_grad_" + scenario;
    ge::Graph graph((prefix + "_graph").c_str());

    auto slmData = ge::op::Data((prefix + "_slm").c_str());
    slmData.set_attr_index(0);
    slmData.update_input_desc_x(MakeDesc(declared[0], ge::DT_INT64, false));
    slmData.update_output_desc_y(MakeDesc(declared[0], ge::DT_INT64, false));
    graph.AddOp(slmData);

    const char* names[17] = {"x",  "cs_prev", "h_prev", "w",  "wci", "wcf", "wco",     "b",     "i",
                             "cs", "f",       "o",      "ci", "co",  "h",   "cs_grad", "h_grad"};
    std::vector<ge::op::Data> dataOps;
    for (int index = 0; index < 17; ++index) {
        ge::op::Data op((prefix + "_" + names[index]).c_str());
        op.set_attr_index(index + 1);
        const ge::TensorDesc desc = MakeDesc(declared[index + 1], ge::DT_FLOAT, false);
        op.update_input_desc_x(desc);
        op.update_output_desc_y(desc);
        graph.AddOp(op);
        dataOps.push_back(op);
    }

    auto grad = ge::op::BlockLstmGrad(prefix.c_str());
    grad.set_input_seq_len_max(slmData);
    grad.set_input_x(dataOps[0]);
    grad.set_input_cs_prev(dataOps[1]);
    grad.set_input_h_prev(dataOps[2]);
    grad.set_input_w(dataOps[3]);
    grad.set_input_wci(dataOps[4]);
    grad.set_input_wcf(dataOps[5]);
    grad.set_input_wco(dataOps[6]);
    grad.set_input_b(dataOps[7]);
    grad.set_input_i(dataOps[8]);
    grad.set_input_cs(dataOps[9]);
    grad.set_input_f(dataOps[10]);
    grad.set_input_o(dataOps[11]);
    grad.set_input_ci(dataOps[12]);
    grad.set_input_co(dataOps[13]);
    grad.set_input_h(dataOps[14]);
    grad.set_input_cs_grad(dataOps[15]);
    grad.set_input_h_grad(dataOps[16]);
    grad.set_attr_use_peephole(false);
    grad.set_attr_gate_order("ifco");
    const ge::TensorDesc out3 = MakeDesc({-1, -1, -1}, ge::DT_FLOAT, false);
    const ge::TensorDesc out2 = MakeDesc({-1, -1}, ge::DT_FLOAT, false);
    const ge::TensorDesc out1 = MakeDesc({-1}, ge::DT_FLOAT, false);
    grad.update_output_desc_x_grad(out3);
    grad.update_output_desc_cs_prev_grad(out2);
    grad.update_output_desc_h_prev_grad(out2);
    grad.update_output_desc_w_grad(out2);
    grad.update_output_desc_wci_grad(out1);
    grad.update_output_desc_wcf_grad(out1);
    grad.update_output_desc_wco_grad(out1);
    grad.update_output_desc_b_grad(out1);
    graph.AddOp(grad);

    std::vector<ge::Operator> inputOps;
    inputOps.push_back(slmData);
    for (auto& op : dataOps) {
        inputOps.push_back(op);
    }
    graph.SetInputs(inputOps).SetOutputs({grad});

    std::map<ge::AscendString, ge::AscendString> options;
    ge::Status status = session.AddGraph(graphId, graph, options);
    if (status != kSuccess) {
        std::cout << "AddGraph failed for " << scenario << ": " << ge::GEGetErrorMsgV2().GetString() << std::endl;
        return kFailed;
    }

    size_t passed = 0U;
    for (const CaseData& data : cases) {
        std::cout << "Run concrete shape " << ShapeListToJson(data.shapes) << std::endl;
        const int t = static_cast<int>(data.shapes[1][0]);
        const int b = static_cast<int>(data.shapes[1][1]);
        const int i = static_cast<int>(data.shapes[1][2]);
        const int h = static_cast<int>(data.shapes[2][1]);
        const BackwardGolden golden = ComputeBackwardGolden(t, b, i, h, data);

        std::vector<ge::Tensor> feeds;
        feeds.push_back(MakeFeed(data.shapes[0], data.slm.data(), data.slm.size() * sizeof(int64_t), ge::DT_INT64));
        feeds.push_back(MakeFeed(data.shapes[1], data.x.data(), data.x.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[2], data.csPrev.data(), data.csPrev.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[3], data.hPrev.data(), data.hPrev.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[4], data.w.data(), data.w.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[5], data.wci.data(), data.wci.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[6], data.wcf.data(), data.wcf.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[7], data.wco.data(), data.wco.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[8], data.b.data(), data.b.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[9], data.gi.data(), data.gi.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[10], data.gcs.data(), data.gcs.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[11], data.gf.data(), data.gf.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[12], data.go.data(), data.go.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[13], data.gci.data(), data.gci.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[14], data.gco.data(), data.gco.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[15], data.gh.data(), data.gh.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(
            MakeFeed(data.shapes[16], data.csGrad.data(), data.csGrad.size() * sizeof(float), ge::DT_FLOAT));
        feeds.push_back(MakeFeed(data.shapes[17], data.hGrad.data(), data.hGrad.size() * sizeof(float), ge::DT_FLOAT));

        std::vector<ge::Tensor> outputs;
        status = session.RunGraph(graphId, feeds, outputs);
        if (status != kSuccess) {
            std::cout << "RunGraph failed for " << scenario << ": " << ge::GEGetErrorMsgV2().GetString() << std::endl;
            continue;
        }
        if (outputs.size() != 8U) {
            std::cout << "output count mismatch: " << outputs.size() << std::endl;
            continue;
        }
        const ShapeVector shape3 = {t, b, i};
        const ShapeVector shape2 = {b, h};
        const ShapeVector shapeW = {i + h, 4 * h};
        const ShapeVector shape1 = {h};
        const ShapeVector shapeB4 = {4 * h};
        bool ok = true;
        ok = ok && CheckTensor(outputs[0], shape3, golden.xGrad, "x_grad");
        ok = ok && CheckTensor(outputs[1], shape2, golden.csPrevGrad, "cs_prev_grad");
        ok = ok && CheckTensor(outputs[2], shape2, golden.hPrevGrad, "h_prev_grad");
        ok = ok && CheckTensor(outputs[3], shapeW, golden.wGrad, "w_grad");
        ok = ok && CheckTensor(outputs[4], shape1, golden.wciGrad, "wci_grad");
        ok = ok && CheckTensor(outputs[5], shape1, golden.wcfGrad, "wcf_grad");
        ok = ok && CheckTensor(outputs[6], shape1, golden.wcoGrad, "wco_grad");
        ok = ok && CheckTensor(outputs[7], shapeB4, golden.bGrad, "b_grad");
        if (!ok) {
            continue;
        }
        ++passed;
        std::cout << "Shape, dtype and values PASSED for " << ShapeListToJson(data.shapes) << std::endl;
    }

    std::cout << "Scenario " << scenario << " summary: " << passed << "/" << cases.size() << " passed" << std::endl;
    return passed == cases.size() ? kSuccess : kFailed;
}

} // namespace

int main()
{
    std::map<ge::AscendString, ge::AscendString> globalOptions = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    ge::Status status = ge::GEInitialize(globalOptions);
    if (status != kSuccess) {
        std::cout << "GEInitialize failed: " << ge::GEGetErrorMsgV2().GetString() << std::endl;
        return kFailed;
    }

    std::map<ge::AscendString, ge::AscendString> buildOptions;
    ge::Session* session = new (std::nothrow) ge::Session(buildOptions);
    if (session == nullptr) {
        std::cout << "Session create failed" << std::endl;
        (void)ge::GEFinalize();
        return kFailed;
    }

    const std::vector<CaseData> dimCases = {MakeCase(2, 4, 16, 32), MakeCase(4, 8, 8, 64), MakeCase(3, 4, 24, 48)};
    const std::vector<CaseData> rankCases = {MakeCase(2, 4, 16, 32), MakeCase(4, 8, 8, 64), MakeCase(3, 4, 24, 48)};

    const int dimResult = RunScenario(*session, 0U, "unknown_dim_minus_1", dimCases);
    const int rankResult = RunScenario(*session, 1U, "unknown_rank_minus_2", rankCases);

    delete session;
    status = ge::GEFinalize();
    if (status != kSuccess) {
        std::cout << "GEFinalize failed" << std::endl;
        return kFailed;
    }
    if (dimResult != kSuccess || rankResult != kSuccess) {
        std::cout << "BlockLstmGrad dynamic GEIR verification did not pass all scenarios" << std::endl;
        return kFailed;
    }

    std::cout << "BlockLstmGrad dynamic GEIR verification PASSED (-1 and -2)" << std::endl;
    return kSuccess;
}
