/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file apply_gradient_descent_tiling_def.h
 * \brief Kernel-UT tiling struct for apply_gradient_descent.
 *        Uses the SAME include guard as op_kernel/apply_gradient_descent_tiling_data.h so
 *        that the kernel's own include of that header becomes a no-op when this header is
 *        force-included by the kernel-UT build (single, conflict-free struct definition).
 */

#ifndef APPLY_GRADIENT_DESCENT_TILING_DATA_H
#define APPLY_GRADIENT_DESCENT_TILING_DATA_H

#include <cstdint>

struct ApplyGradientDescentTilingData {
    uint64_t totalDataCount;
    uint64_t tileDataCount;
    uint64_t blocksPerCore;
    uint32_t needCoreNum;
    uint32_t blockElems;
    uint32_t remCoreNum;
    uint32_t reserved;
};

// In the normal AscendC build GET_TILING_DATA_WITH_STRUCT is code-generated by the tbe
// compile flow. In the CPU-twin kernel UT no such generation happens, so we provide it here:
// the tiling GM buffer is filled by the test as the raw plain struct, so we copy it out
// directly. Guarded so it never clashes with the generated definition elsewhere.
#ifndef GET_TILING_DATA_WITH_STRUCT
#define GET_TILING_DATA_WITH_STRUCT(tiling_struct, tiling_data, tiling_arg) \
    tiling_struct tiling_data = *reinterpret_cast<__gm__ const tiling_struct*>(tiling_arg)
#endif

#endif // APPLY_GRADIENT_DESCENT_TILING_DATA_H
