/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file smooth_l1_loss_grad.cpp
 * \brief SmoothL1LossGrad 算子 Kernel 入口（arch35 / DAV_3510 架构）
 *
 * 一芯片一算子一入口：arch35 的唯一 __global__ 入口。核函数参数顺序固定：
 *   输入 predict → label → dout → 输出 gradient → workspace → tiling（workspaceSize=0）。
 *
 * 输入 dtype 由编译系统自动注入的 DTYPE_PREDICT 宏指定，按 dtype 各编译一份 kernel。
 * KernelSmoothL1LossGrad<T> 按 T 参数化，单一模板实例覆盖全 3 dtype。
 */

#include "arch35/smooth_l1_loss_grad.h"

extern "C" __global__ __aicore__ void smooth_l1_loss_grad(GM_ADDR predict, GM_ADDR label, GM_ADDR dout, GM_ADDR gradient,
                                               GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(SmoothL1LossGradTilingData);
    GET_TILING_DATA_WITH_STRUCT(SmoothL1LossGradTilingData, tilingData, tiling);
    // 核守卫：冗余核（GetBlockIdx >= blockNum，含空 Tensor blockNum=0）
    // 直接 return，不进入 Init/Process，避免冗余核分配 UB Buffer / 设置 GM 偏移。
    if (AscendC::GetBlockIdx() >= tilingData.blockNum) {
        return;
    }
    NsSmoothL1LossGrad::KernelSmoothL1LossGrad<DTYPE_PREDICT> op;
    op.Init(predict, label, dout, gradient, &tilingData);
    op.Process();
}
